### DISCUSSION TITLE
Agent node in workflow run status fails.

### DISCUSSION THREAD

**Discussion by detongz** [langgenius/dify#12764] [General]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Content

Error:
> Failed to transform agent message: PluginInvokeError: {"args":{},"error_type":"ValidationError","message":"1 validation error for ReActParams\nmodel.entity\n Input should be a valid dictionary or instance of AIModelEntity [type=model_type, input_value=None, input_type=NoneType]\n For further information visit https://errors.pydantic.dev/2.8/v/model_type"}

Version: 1.0.0-beta.1

DSL:
```yaml

app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: 所以升级了能少些多少代码？
  use_icon_as_answer_icon: false
dependencies: []
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: agent
      id: 1736927660700-source-1736927668620-target
      source: '1736927660700'
      sourceHandle: source
      target: '1736927668620'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: agent
        targetType: end
      id: 1736927668620-source-1736931768699-target
      source: '1736927668620'
      sourceHandle: source
      target: '1736931768699'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables:
        - label: input
          max_length: 48
          options: []
          required: true
          type: text-input
          variable: input
      height: 88
      id: '1736927660700'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        agent_parameters:
          instruction:
            type: constant
            value: 你能判断用户输入的情绪，根据提问的时间推荐菜谱
          model:
            type: constant
            value:
              mode: chat
              model: Doubao-pro-32k-240828
              model_type: llm
              provider: langgenius/volcengine_maas/volcengine_maas
              type: model-selector
          query:
            type: constant
            value: '{{#1736927660700.input#}}'
          tools:
            type: constant
            value:
            - enabled: true
              extra:
                description: ''
              parameters:
                model: langgenius/tongyi/tongyi#tts-1
                text: ''
                voice#langgenius/tongyi/tongyi#tts-1: sambert-zhinan-v1
              provider_name: audio
              tool_name: tts
        agent_strategy_label: ReAct
        agent_strategy_name: ReAct
        agent_strategy_provider_name: langgenius/agent/agent
        desc: ''
        output_schema: null
        plugin_unique_identifier: langgenius/agent:0.0.3@56b71fdb9e8e799632c4f7329bc67b77d060f361900753f02e1ca232fcbce1ee
        selected: false
        title: Agent
        type: agent
      height: 196
      id: '1736927668620'
      position:
        x: 383
        y: 282
      positionAbsolute:
        x: 383
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1736927668620'
          - text
          variable: text
        selected: false
        title: End
        type: end
      height: 88
      id: '1736931768699'
      position:
        x: 686
        y: 282
      positionAbsolute:
        x: 686
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    viewport:
      x: -197.79392492306692
      y: 53.00339937089083
      zoom: 1.1856828826828067

```
