### DISCUSSION TITLE
General Discussion: if I already have a redis docker service running, how do I modify the compose file to reuse it

### DISCUSSION THREAD

**Discussion by qiulang** [langgenius/dify#16010] [General]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Content

I already have a redis docker service running, so when starting dify I want dify to reuse that redis.

I know I can set `external: true`  to tell docker to reuse the existing Redis service, but do I need to change volumes setting ?

And in .env file I need to change REDIS_PASSWORD too.

So has anyone done that before?

**Comment by qiulang** [comment]
The other easy I can I think of is do not reuse the existing one and add `ports:` property to redis service, say 6380 port on the host, but can this work ?

```
  redis:
    image: redis:6-alpine
    restart: always
    port:
        - 6380:6379
    environment:
      REDISCLI_AUTH: ${REDIS_PASSWORD:-difyai123456}
```
