### DISCUSSION TITLE
message_end event message was chunked

### DISCUSSION THREAD

**Discussion by khanhnd0408** [langgenius/dify#16286] [Help]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Content

My chat flow responded with the last event, message_end, to the client, but the client failed to parse the JSON string response. I printed out the failed JSON string and found that it was chunked, which caused the client to fail to load it. Since it's the last event, there are no further events after that. Does anyone have the same issue?
![image](https://github.com/user-attachments/assets/495c0c91-9537-4343-bcc1-e554db22a5ac)

My DSL:
```yaml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: CustomerChatBot
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/bedrock:0.0.5@56ef70ec6ada6c6e5456ca7fb3230546d571d19626743be77e53cf6a0a5c2040
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/cohere:0.0.5@c5fca2d9b249603dc829cc1e087060ee648b121225a38c24a47913d3c6aa9031
kind: app
version: 0.1.5
workflow:
  conversation_variables:
  - description: ''
    id: bd31e2f9-337f-4234-8aac-3a6a0c9eecc0
    name: history
    selector:
    - conversation
    - history
    value: []
    value_type: array[object]
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        sourceType: llm
        targetType: answer
      id: llm-answer
      selected: false
      source: llm
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
    - data:
        isInIteration: false
        sourceType: llm
        targetType: code
      id: llm-source-1741752992695-target
      selected: false
      source: llm
      sourceHandle: source
      target: '1741752992695'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: assigner
      id: 1741752992695-source-1741752820931-target
      selected: false
      source: '1741752992695'
      sourceHandle: source
      target: '1741752820931'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1741749237349-source-1741753557800-target
      selected: false
      source: '1741749237349'
      sourceHandle: source
      target: '1741753557800'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: knowledge-retrieval
        targetType: llm
      id: 1741749333601-source-llm-target
      selected: false
      source: '1741749333601'
      sourceHandle: source
      target: llm
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: code
      id: 1741753557800-source-1742201551826-target
      source: '1741753557800'
      sourceHandle: source
      target: '1742201551826'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: knowledge-retrieval
      id: 1742201551826-source-1741749333601-target
      source: '1742201551826'
      sourceHandle: source
      target: '1741749333601'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables: []
      height: 54
      id: '1741749237349'
      position:
        x: -772.2277440498872
        y: 434
      positionAbsolute:
        x: -772.2277440498872
        y: 434
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - '1741749333601'
          - result
        desc: ''
        memory:
          query_prompt_template: '{{#sys.query#}}'
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: true
            size: 20
        model:
          completion_params: {}
          mode: chat
          name: us.anthropic.claude-3-7-sonnet-20250219-v1:0
          provider: langgenius/bedrock/bedrock
        prompt_template:
        - edition_type: basic
          id: a56de345-8955-4989-ba22-f59e16dae310
          role: system
          text: 'You are customer support, your responsibility are:

            - Answer customer question base on what you retrieve at <context></context>.

            - If the <context></context> field is empty, just said that you do not
            have enough information to answer, do not generate things that you do
            not know or <context></context> field does not have.

            - Answer within ethical standards.

            - Reject all question about self harm

            - Provide information correctly with translated answer to user original
            languages.


            <histories>

            {{#1741753557800.result#}}

            </histories>


            <context>

            {{#context#}}

            </context>'
        selected: true
        title: CoachingLLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 90
      id: llm
      position:
        x: 169.12773715077446
        y: 434
      positionAbsolute:
        x: 169.12773715077446
        y: 434
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#llm.text#}}'
        desc: ''
        selected: false
        title: Answer
        type: answer
        variables: []
      height: 102
      id: answer
      position:
        x: 519.3129105809651
        y: 434
      positionAbsolute:
        x: 519.3129105809651
        y: 434
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        dataset_ids:
        - 3ab3526f-799b-43c4-ae93-eefcd81a020f
        desc: ''
        multiple_retrieval_config:
          reranking_enable: true
          reranking_mode: reranking_model
          reranking_model:
            model: rerank-multilingual-v3.0
            provider: langgenius/cohere/cohere
          score_threshold: null
          top_k: 3
        query_variable_selector:
        - '1742201551826'
        - result
        retrieval_mode: multiple
        selected: false
        title: Knowledge Retrieval
        type: knowledge-retrieval
      height: 92
      id: '1741749333601'
      position:
        x: -162.7995323752092
        y: 434
      positionAbsolute:
        x: -162.7995323752092
        y: 434
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        items:
        - input_type: variable
          operation: append
          value:
          - '1741752992695'
          - result
          variable_selector:
          - conversation
          - history
          write_mode: over-write
        selected: false
        title: WriteHistory
        type: assigner
        version: '2'
      height: 88
      id: '1741752820931'
      position:
        x: 823.0339924886807
        y: 574.1706830521503
      positionAbsolute:
        x: 823.0339924886807
        y: 574.1706830521503
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(arg1: str, arg2: str) -> dict:\n    return {\n        \"\
          result\": {\n            \"user\": arg1,\n            \"assistant\": arg2\n\
          \        },\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: object
        selected: false
        title: ConvertToStore
        type: code
        variables:
        - value_selector:
          - sys
          - query
          variable: arg1
        - value_selector:
          - llm
          - text
          variable: arg2
      height: 54
      id: '1741752992695'
      position:
        x: 519.3129105809651
        y: 574.1706830521503
      positionAbsolute:
        x: 519.3129105809651
        y: 574.1706830521503
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "import json\n\ndef main(history: list) -> dict:\n    conversation =\
          \ \"\\n\".join([f\"User: {item['user']}\\nAssistant: {item['assistant']}\"\
          \ for item in history[9::-1]])\n    return {\n        \"result\": conversation\n\
          \    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: ReadConversationHistory
        type: code
        variables:
        - value_selector:
          - conversation
          - history
          variable: history
      height: 54
      id: '1741753557800'
      position:
        x: -478.7108778667624
        y: 434
      positionAbsolute:
        x: -478.7108778667624
        y: 434
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(arg1: str) -> dict:\n    question = f\"{arg1}<|>{{}}\"\n\
          \    return {\n        \"result\": question\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: Code 3
        type: code
        variables:
        - value_selector:
          - sys
          - query
          variable: arg1
      height: 54
      id: '1742201551826'
      position:
        x: -323.7563794750972
        y: 269.29139847926575
      positionAbsolute:
        x: -323.7563794750972
        y: 269.29139847926575
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 141.9076545149079
      y: -123.55576967843979
      zoom: 0.9066287950810187
```
