### DISCUSSION TITLE
Help How can I embed dify.app into my web app, and modifying a src path

### DISCUSSION THREAD

**Discussion by moluzhui** [langgenius/dify#17066] [Help]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I currently want to embed the dify application into the mobile H5 page via iframe, but due to network issues, I have to use a subpath to access it, such as , rewrite src as `http://my.com/proxy/dify/chatbot/abcdefg` as follows
```
<iframe
 src="http://my.com/chatbot/abcdefg"
 style="width: 100%; height: 100%; min-height: 700px"
 frameborder="0"
 allow="microphone">
</iframe>
```

I then tried to intercept the application's request with nginx and remove the *additional paths(proxy/dify)*.  However, an error is `default backend-404`. 

I know there is a high probability of an error because I did not change the src etc inside the iframe.  But I don't know any other way to achieve, looking forward to your help

### 2. Additional context or comments
In my local test, it is normal to request without adding subroutes, but in the simulation of online scenarios, adding subroutes is abnormal

nginx by ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /\$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/preserve-host: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: proxy
spec:
  rules:
    - host: my.com
      http:
        paths:
          - path: /proxy/dify/(.*)
            backend:
              serviceName: dify
              servicePort: 80
```

_No response_
