### DISCUSSION TITLE
Help: For the plugin SDK, there's an issue where the file path input using for is automatically escaped.

### DISCUSSION THREAD

**Discussion by ntmaster84** [langgenius/dify#18464] [Help]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

For the plugin SDK, there's an issue where the file path input using form is automatically escaped.

When entering a path like D:\Key\noenc_rsa.p8, the plugin ends up receiving a double-escaped string like 'D:\\\\Key\\\\noenc_rsa.p8'.

How can this be resolved?

The environment is Windows, and Docker Desktop is used for installation.

Development is done in a Windows environment using IntelliJ IDEA, and the plugin is built using the cmd with the package command.

Interestingly, when running in debug mode within IntelliJ IDEA, everything works as expected. However, after packaging and installing the plugin, the issue with double escaping occurs.

![error](https://github.com/user-attachments/assets/d57b030d-df7d-4bb6-88e2-a6d18dd1a143)

```python
######my_tool.py############
from collections.abc import Generator
from typing import Any

from dify_plugin import Tool
from dify_plugin.entities.tool import ToolInvokeMessage
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import serialization

class BsSqlTool(Tool):
    def _invoke(self, tool_parameters: dict[str, Any]) -> Generator[ToolInvokeMessage]:
        key_path = tool_parameters.get("key_path")
        with open( key_path,"rb") as key:
            p_key = serialization.load_pem_private_key(
                key.read(),
                password=None,
                backend=default_backend()
            )

        pkb = p_key.private_bytes(
            encoding=serialization.Encoding.DER,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption())


        yield self.create_json_message({
            "result": "Hello, world!"
        })
```

```yaml
identity:
  name: bs_sql
  author: bskim
  label:
    en_US: bs_sql
description:
  human:
    en_US: bskim
  llm: bskim

parameters:
  - name: query
    type: string
    required: false
    label:
      en_US: Query string
    human_description:
      en_US: SQL Query
    llm_description: SQKL Query
    form: llm

  - name: postgres_uri
    type: string
    required: false
    label:
      en_US: postgres_uri
    human_description:
      en_US: postgres_uri
    llm_description: postgres_uri
    form: llm

  - name: key_path
    type: string
    required: false
    label:
      en_US: key_path
    human_description:
      en_US: key_path
    llm_description: key_path
    form: llm

  - name: db
    type: select
    required: false
    label:
      en_US: Database
    human_description:
      en_US: Choese the database.
    form: form
    default: postgres
    options:
      - value: postgres
        label:
          en_US: Postgres
      - value: snowflake
        label:
          en_US: Snowflake
extra:
  python:
    source: tools/bs_sql.py
```
