### DISCUSSION TITLE
Host using proxy and use docker deploy Dify

### DISCUSSION THREAD

**Discussion by pzookloop** [langgenius/dify#18575] [Help] [answered]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.2.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

hi, everyone, please help me:
My operation system is Ubuntu 24.04 and Docker Compose version is v2.34.0, Dify version is 1.2.0. 
I deploy ollama and dify with docker and expected Dify to be able to access the models in Ollama.
I deployed it according to the following steps:
1. In all Dify services that do not require a proxy, I exclude the proxy by setting the http_proxy & https_proxy environment variable to an empty string.
2. start Dify with docker compose up -d
3. This is my ollama deployment file:

```
services:
  ollama:
    image: ollama/ollama
    runtime: nvidia
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```

5.start ollama with docker compose up -d

finally, when i want to add model from local docker ollama in Dify web page
![01](https://github.com/user-attachments/assets/04f5aad8-79c4-47d4-aca2-f8c3b3415b37)
I get an error: An error occurred during credentials validation: HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://192.168.2.122:11434/api/chat (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f17f1d17dd0>: Failed to establish a new connection: [Errno 111] Connection refused')))

Here are the methods I have tried:
1. Unset the system proxy environment variables (HTTP_PROXY and HTTPS_PROXY) on the Dify host machine before running Docker Compose.        result fail
2. add extarct_host with http://host.docker.internal:11434 but host is ubuntu not support it
3. use network mode: host in Dify service, but get error with network

Please someone can give me some help, please

### ✔️ Expected Behavior

I expected it can access Model from ollama.

### ❌ Actual Behavior

An error occurred during credentials validation: HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://192.168.2.122:11434/api/chat (Caused by ProxyError('Unable to connect to proxy', NewConnectionError(': Failed to establish a new connection: Connection refused')))
