### DISCUSSION TITLE
Variable not found for unknown reason

### DISCUSSION THREAD

**Discussion by deathemperor** [langgenius/dify#19097] [Help]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Not sure what do I misconfigured? I'm using cloud

![CleanShot 2025-04-29 at 17 59 31](https://github.com/user-attachments/assets/62cfe79a-1120-4a06-824b-62b99cfed8ed)

### 2. Additional context or comments

DSL file

```yaml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: '1'
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/gemini:0.1.5@012c9e0467a11910db974e0436348e93a376fdc96381946a3db2c56708377381
kind: app
version: 0.2.0
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInLoop: false
        sourceType: start
        targetType: document-extractor
      id: 1745919839281-source-1745921910883-target
      source: '1745919839281'
      sourceHandle: source
      target: '1745921910883'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: document-extractor
        targetType: llm
      id: 1745921910883-source-1745919846382-target
      source: '1745921910883'
      sourceHandle: source
      target: '1745919846382'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables:
        - allowed_file_extensions: []
          allowed_file_types:
          - image
          - document
          allowed_file_upload_methods:
          - local_file
          - remote_url
          label: f
          max_length: 5
          options: []
          required: true
          type: file
          variable: f
      height: 89
      id: '1745919839281'
      position:
        x: -184
        y: 304
      positionAbsolute:
        x: -184
        y: 304
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        context:
          enabled: true
          variable_selector:
          - '1745921910883'
          - text
        desc: ''
        model:
          completion_params: {}
          mode: chat
          name: gemini-2.5-flash-preview-04-17
          provider: langgenius/gemini/google
        prompt_config:
          jinja2_variables:
          - value_selector: []
            variable: ''
        prompt_template:
        - edition_type: basic
          id: 0c4df013-4b99-4e5e-a35e-ed4968996c3c
          role: system
          text: summarize {{#1745921910883.text#}}{{#context#}}
        - id: 8c04ceb6-d776-435a-bda5-9740b879bcc6
          role: user
          text: summarize {{#1745921910883.text#}}
        selected: true
        structured_output:
          schema:
            additionalProperties: false
            properties:
              properties:
                additionalProperties: false
                properties:
                  diagnosis:
                    additionalProperties: false
                    properties:
                      type:
                        type: string
                    required:
                    - type
                    type: object
                  drugs:
                    additionalProperties: false
                    properties:
                      items:
                        additionalProperties: false
                        properties:
                          properties:
                            additionalProperties: false
                            properties:
                              afternoon:
                                additionalProperties: false
                                properties:
                                  type:
                                    type: string
                                required:
                                - type
                                type: object
                              dosage:
                                additionalProperties: false
                                properties:
                                  type:
                                    type: string
                                required:
                                - type
                                type: object
                              evening:
                                additionalProperties: false
                                properties:
                                  type:
                                    type: string
                                required:
                                - type
                                type: object
                              morning:
                                additionalProperties: false
                                properties:
                                  type:
                                    type: string
                                required:
                                - type
                                type: object
                              name:
                                additionalProperties: false
                                properties:
                                  type:
                                    type: string
                                required:
                                - type
                                type: object
                            required:
                            - name
                            - dosage
                            - morning
                            - afternoon
                            - evening
                            type: object
                          type:
                            type: string
                        required:
                        - type
                        - properties
                        type: object
                      type:
                        type: string
                    required:
                    - type
                    - items
                    type: object
                  patient_name:
                    additionalProperties: false
                    properties:
                      type:
                        type: string
                    required:
                    - type
                    type: object
                required:
                - patient_name
                - diagnosis
                - drugs
                type: object
              type:
                type: string
            required:
            - type
            - properties
            type: object
        structured_output_enabled: false
        title: LLM
        type: llm
        variables: []
        vision:
          configs:
            detail: high
            variable_selector:
            - '1745919839281'
            - f
          enabled: false
      height: 89
      id: '1745919846382'
      position:
        x: 721
        y: 358
      positionAbsolute:
        x: 721
        y: 358
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        desc: ''
        is_array_file: false
        selected: false
        title: Doc Extractor
        type: document-extractor
        variable_selector:
        - '1745919839281'
        - f
      height: 91
      id: '1745921910883'
      position:
        x: 340.5
        y: 358
      positionAbsolute:
        x: 340.5
        y: 358
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    viewport:
      x: 385.5
      y: 375
      zoom: 1
```
