### DISCUSSION TITLE
[1.4.0] Proxy Agent Configuration - Document Operate Record

### DISCUSSION THREAD

**Discussion by H4ngZz** [langgenius/dify#19991] [Help]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

# Version
1.4.0

# Type
local docker compose start

# Significance
record what did i configuration proxy agent on dify (because of many errors occurred)

i use local linux(CentOS 7.2) machine to deployment the latest version dify (1.4.0)
my machine can not request any public(global) network
so that i need configuration my proxy(linux system http/https proxy)
then i found it not work on docker(dify)

Here is what I configured

## env
PATH -> /dify/docker/.env
global environment(required)
1. SSRF_PROXY_HTTP_URL
2. SSRF_PROXY_HTTPS_URL
3. SANDBOX_HTTP_PROXY
4. SANDBOX_HTTPS_PROXY

## plugin_daemon
```
  # plugin daemon
  plugin_daemon:
    image: langgenius/dify-plugin-daemon:0.0.10-local
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      # Use the shared environment variables.
      <<: *shared-api-worker-env
      DB_DATABASE: ${DB_PLUGIN_DATABASE:-dify_plugin}
      HTTP_PROXY: ${SSRF_PROXY_HTTP_URL:-http://xxxxxx:3128}
      HTTPS_PROXY: ${SSRF_PROXY_HTTPS_URL:-http://xxxxxx:3128}
      PIP_HTTP_PROXY: ${SSRF_PROXY_HTTP_URL:-http://1xxxxxx:3128}
      PIP_HTTPS_PROXY: ${SSRF_PROXY_HTTPS_URL:-http://xxxxxx:3128}
      PIP_MIRROR_URL: ${PIP_MIRROR_URL:-https://pypi.tuna.tsinghua.edu.cn/simple}
      ...
    ports:
      - "${EXPOSE_PLUGIN_DEBUGGING_PORT:-5003}:${PLUGIN_DEBUGGING_PORT:-5003}"
    volumes:
      - /data01/infra/pip-packages # i install some local whl dependencies first(just like pydantic_core / setuptools)
      - ./volumes/plugin_daemon:/app/storage
      - ./pip.conf:/etc/pip.conf
```

## pip.conf
```
[global]
proxy = http://xxxxxx:3128
timeout = 120
retries = 5
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
trusted-host = pypi.tuna.tsinghua.edu.cn
```

## other
ln -s /your_path/python3.12/python /usr/bin/python
if u configured any content, please use `docker-compose down` then `docker-compose up -d`, not restart single services(it may does not work)

## cause errors
just record cause errors, it has been resolved
1. [ERROR]PluginDaemonInternalServerError: failed to get plugin declaration
2. [ERROR]init environment failed: failed to install dependencies: exit status 2, output: error: Failed to fetch: `https://pypi.tuna.tsinghua.edu.cn/simple/dify-plugin/`
3. [PANIC]failed to init dify plugin db: failed to connect to `host=db user=postgres database=postgres`: hostname resolving error (lookup db on 127.0.0.11:53: read udp 127.0.0.1:40984->127.0.0.11:53: i/o timeout)
4. [ERROR]init environment failed: failed to install dependencies: signal: killed, output: init process exited due to no activity for 120 seconds, retrying
5. [api] Operation not permitted

## refer
1. https://github.com/langgenius/dify/issues/886
2. https://github.com/langgenius/dify-plugin-daemon/pull/59
3. https://github.com/langgenius/dify/issues/19797
