### DISCUSSION TITLE
Work_flow_code_node: Failed to resolve 'resapiuat.hkbn.com.hk' ([Errno -2] Name or service not known)")) error: exit status 255

### DISCUSSION THREAD

**Discussion by minglong-huang** [langgenius/dify#20031] [Help]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.1.3

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

I have set up a series of changes, as follows
1、 
docker-compose.yaml :   
```
    sandbox:
      image: langgenius/dify-sandbox:0.2.11
      restart: always
      environment:
        # The DifySandbox configurations
        # Make sure you are changing this key for your deployment with a strong key.
        # You can generate a strong key using `openssl rand -base64 42`.
        API_KEY: ${SANDBOX_API_KEY:-dify-sandbox}
        GIN_MODE: ${SANDBOX_GIN_MODE:-release}
        WORKER_TIMEOUT: ${SANDBOX_WORKER_TIMEOUT:-15}
        ENABLE_NETWORK: ${SANDBOX_ENABLE_NETWORK:-true}
          #HTTP_PROXY: ${SANDBOX_HTTP_PROXY:-http://ssrf_proxy:3128}
          # HTTPS_PROXY: ${SANDBOX_HTTPS_PROXY:-http://ssrf_proxy:3128}
        SANDBOX_PORT: ${SANDBOX_PORT:-8194}
      volumes:
        - ./volumes/sandbox/dependencies:/dependencies
        - ./volumes/sandbox/conf:/conf
      healthcheck:
        test: [ 'CMD', 'curl', '-f', 'http://localhost:8194/health' ]
      networks:
        - ssrf_proxy_network
        - dify_external_network
        - default
networks:
  # create a network between sandbox, api and ssrf_proxy, and can not access outside.
  ssrf_proxy_network:
    driver: bridge
    internal: true
  milvus:
    driver: bridge
  opensearch-net:
    driver: bridge
    internal: true
  dify_external_network:
    external: true  # 引用外部已存在的网络
```
2、dify/docker/ssrf_proxy/squid.conf.template 
Just change acl allowed_domains dstdomain ,add .business.osapps.xx.com 
```
acl localnet src 0.0.0.1-0.255.255.255  # RFC 1122 "this" network (LAN)
acl localnet src 10.0.0.0/8             # RFC 1918 local private network (LAN)
acl localnet src 100.64.0.0/10          # RFC 6598 shared address space (CGN)
acl localnet src 169.254.0.0/16         # RFC 3927 link-local (directly plugged) machines
acl localnet src 172.16.0.0/12          # RFC 1918 local private network (LAN)
acl localnet src 192.168.0.0/16         # RFC 1918 local private network (LAN)
acl localnet src fc00::/7               # RFC 4193 local private network range
acl localnet src fe80::/10              # RFC 4291 link-local (directly plugged) machines
acl SSL_ports port 443
# acl SSL_ports port 1025-65535   # Enable the configuration to resolve this issue: https://github.com/langgenius/dify/issues/12792
acl Safe_ports port 80          # http
acl Safe_ports port 21          # ftp
acl Safe_ports port 443         # https
acl Safe_ports port 70          # gopher
acl Safe_ports port 210         # wais
acl Safe_ports port 1025-65535  # unregistered ports
acl Safe_ports port 280         # http-mgmt
acl Safe_ports port 488         # gss-http
acl Safe_ports port 591         # filemaker
acl Safe_ports port 777         # multiling http
acl CONNECT method CONNECT
acl allowed_domains dstdomain .marketplace.dify.ai .business.osapps.xx.com
http_access allow allowed_domains
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow localhost manager
http_access deny manager
http_access allow localhost
include /etc/squid/conf.d/*.conf
http_access deny all

################################## Proxy Server ################################
http_port ${HTTP_PORT}
coredump_dir ${COREDUMP_DIR}
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern \/(Packages|Sources)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
refresh_pattern \/Release(|\.gpg)$ 0 0% 0 refresh-ims
refresh_pattern \/InRelease$ 0 0% 0 refresh-ims
refresh_pattern \/(Translation-.*)(|\.bz2|\.gz|\.xz)$ 0 0% 0 refresh-ims
refresh_pattern .               0       20%     4320

```

when I run the code in workflow ,it report Failed to resolve 'resapiuat.hkbn.com.hk' ([Errno -2] Name or service not known)")) error: exit status 255
I guarantee that my previous operation was feasible, but I don't know what changes have caused the current error and inability to resolve DNS
```
import requests
def main() -> dict:
    response = requests.get(
    "https://business.osapps.xx.com/callmenu-api/healthy/version",
    verify = '/dependencies/certs/fullchain.crt'
    )

    return {
        "result": response.status_code,
    }
```
In the dify-sandbox-container, the system can successfully curl the target URL. Similarly, the same functionality is also available in the dify-ssrf-container.

**Comment by dosubot** [comment]
I found a similar resolved issue related to DNS resolution errors in the Dify platform. The solution involved several steps to ensure proper configuration and connectivity:

1. **Service Definition**: Verify that all services are correctly defined in your `docker-compose.yaml`.

2. **Network Configuration**: Ensure that the networks are correctly set up and that the services are connected to the appropriate networks.

3. **DNS Resolution**: Check Docker's DNS resolution by running a container and trying to ping the problematic domain from within it.

4. **Environment Variables**: Ensure that environment variables related to proxies are correctly set in your configuration files.

5. **Inspect Docker Network**: Use the command `docker network inspect <network_name>` to verify that the services are listed and connected properly.

6. **Restart Docker**: Restart Docker and your containers to apply any changes.

7. **Check Docker DNS Configuration**: Ensure that Docker's DNS settings are correctly configured.

8. **Test with Container**: Run a temporary container in the same network and try to ping the domain to check connectivity.

Additionally, if you have modified the Squid configuration in the `ssrf_proxy` container, ensure that the changes are correctly applied and that the configuration allows access to the necessary domains and ports <sup>[[1]](https://github.com/langgenius/dify/issues/20005)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/3bbcbf4f-ad21-472a-bcdb-7f18477abd79?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/3bbcbf4f-ad21-472a-bcdb-7f18477abd79?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/3bbcbf4f-ad21-472a-bcdb-7f18477abd79?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/3bbcbf4f-ad21-472a-bcdb-7f18477abd79?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/3bbcbf4f-ad21-472a-bcdb-7f18477abd79?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/3bbcbf4f-ad21-472a-bcdb-7f18477abd79?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/3bbcbf4f-ad21-472a-bcdb-7f18477abd79?feedback_type=other)</sup>

**Comment by minglong-huang** [comment]
I found that as long as the IP address of the SSRF container is added to the request, the request can be successful again. 
The code is as follows:
```
import requests
def main() -> dict:
    proxy = {
        "http": "http://172.18.0.3:3128",  # HTTP 请求的代理
        "https": "http://172.18.0.3:3128"  # HTTPS 请求的代理
    }

    response = requests.get(
        "https://business.osapps.xx.com/callmenu-api/healthy/version",
            verify = '/dependencies/certs/fullchain.crt',
            proxies=proxy
            )

    return {
        "result": response.status_code,
    }
```
So why do I need to add a proxy IP in the code? I set it in docker-compose.yaml, right
Even if I restore docker-compose.yaml to the following state, it still won't work


```
  sandbox:
    image: langgenius/dify-sandbox:0.2.11
    restart: always
    environment:
      # The DifySandbox configurations
      # Make sure you are changing this key for your deployment with a strong key.
      # You can generate a strong key using `openssl rand -base64 42`.
      API_KEY: ${SANDBOX_API_KEY:-dify-sandbox}
      GIN_MODE: ${SANDBOX_GIN_MODE:-release}
      WORKER_TIMEOUT: ${SANDBOX_WORKER_TIMEOUT:-15}
      ENABLE_NETWORK: ${SANDBOX_ENABLE_NETWORK:-true}
      HTTP_PROXY: ${SANDBOX_HTTP_PROXY:-http://ssrf_proxy:3128}
      HTTPS_PROXY: ${SANDBOX_HTTPS_PROXY:-http://ssrf_proxy:3128}
      SANDBOX_PORT: ${SANDBOX_PORT:-8194}
    volumes:
      - ./volumes/sandbox/dependencies:/dependencies
      - ./volumes/sandbox/conf:/conf
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8194/health' ]
    networks:
      - ssrf_proxy_network

```

So,Why can I perform DNS resolution on docker-ssrf_proxy-1 in the sandbox container content, but there will be an error message in the code node of the workflow, and the DNS cannot resolve docker-ssrf_proxy-1? @dosu @crazywoola
