### DISCUSSION TITLE
How to skip or fix SSL cert verification error

### DISCUSSION THREAD

**Discussion by qianfeiqianlan** [langgenius/dify#4600] [General]
when i save openai provider with **API Base**(openai_api_base,base_url), got connection error, message is following

`httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)`

i try to use openai SDK test my setting, got correct result
```
from openai import OpenAI

client = OpenAI(
    api_key="sk-xxxxxxxxxxx",
    base_url="https://open-api.xxx.xx/v1")

stream = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Say this is a test"}],
    stream=True,
)
for chunk in stream:
    if chunk.choices[0].delta.content is not None:
        print(chunk.choices[0].delta.content, end="")
```

at logs found some init logic, but dont know how to update this logic
<img width="1933" alt="image" src="https://github.com/langgenius/dify/assets/12892568/7721bc50-25af-4e6c-8d17-968fbc16f61e">
 

1. version 0.6.8
2. deploy on k8s with helm
3. cert was request by certbot
4. https://open-api.xxx.xx was proxy by nginx

related issue 
1. https://github.com/langgenius/dify/issues/2637
2. https://github.com/langgenius/dify/issues/4114

**Comment by qianfeiqianlan** [comment]
**add some custom openai http client config was correct?**

i use some magic logic to resolve this issue

1. docker exec pod
2. vim `core/model_runtime/model_providers/openai/_common.py` file
3. use a custom http client `httpx.Client(verify=False)`
4. commit image and replace old dify api image

<img width="1469" alt="image" src="https://github.com/langgenius/dify/assets/12892568/7c5119c1-d6b8-4bcb-a7d9-6c8e016441b4">

**Comment by LeoQuote** [comment]
install the root certificate inside container, after that everything should be fine.

your changes doesn’t follow the security best practices, you could be attacked by DNS spoofing.

**Comment by valckmir** [comment]
Hi guys and all future readers,

Before providing my solutions I woud like to emphasise, that using certificates issued by **verified CA authorities** should be always your solution ([Let's Encrypt](https://letsencrypt.org/getting-started/) certs are free). However if you find yourself in a situation when you have no other option than using a self-signed CA, here is my story:

I got the same error when my custom tool used self-signed certificate. The problem here is that Dify uses `httpx` for making requests. The `httpx` uses `certifi` to verify certificates. And here the fun begins.

The `certifi` maintains its own registry of verified certification authorities, therefore installing your CA certificate in your Dify environement/container, e.g. with copying your CA to the host machine and runnign the `update-ca-certificates`command, will **not** help.

The only workaround that made Dify trust my CA was to build my own image with copy of my CA certificate appended to the end of the CA bundle used by certifi.

This is how I did it:

```dockerfile
FROM langgenius/dify-api:0.6.8

COPY ./certs/my_awesome_CA.crt /usr/local/share/ca-certificates/

RUN update-ca-certificates  # add to system CAs, probably not needed but can be useful
RUN cat /usr/local/share/ca-certificates/my_awesome_CA.crt >> /usr/local/lib/python3.10/site-packages/certifi/cacert.pem

WORKDIR /app/api

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
```

Check what CA bundle certifi on your machine uses:

```python
import certifi

certifi.where()
``` 

**Do not use this in a production environment. I repeat, use a certificate issued by verified certification authority whenever possible!**

**Reply by mbbyn** [reply]
Tried this and works perfectly, thank you very much.

**Reply by javiergonzales06** [reply]
Hi. I tried this methodology. But It still thrown same error which is [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate. Could you help me?

**Reply by zolgear** [reply]
To address SSL inspection and support for certificates issued by an intranet certification authority, the following steps are taken:  

1. Create an `ex_ca.pem` file containing the root and intermediate CA certificates.  
2. Prepare an override file for the Docker Compose configuration to mount the certificate and specify it in environment variables used by `httpx`.  

Example `docker-compose.override.yaml` file:  

```yaml
services:
  api:
    environment:
      # SSL Inspection
      SSL_CERT_FILE: /usr/local/share/ca-certificates/extra/ex_ca.pem
      REQUESTS_CA_BUNDLE: /usr/local/share/ca-certificates/extra/ex_ca.pem
      # Unstructured.io Telemetry disabled
      DO_NOT_TRACK: true
      SCARF_NO_ANALYTICS: true
    volumes:
      - ../certs/ex_ca.pem:/usr/local/share/ca-certificates/extra/ex_ca.pem

  worker:
    environment:
      # SSL Inspection
      SSL_CERT_FILE: /usr/local/share/ca-certificates/extra/ex_ca.pem
      REQUESTS_CA_BUNDLE: /usr/local/share/ca-certificates/extra/ex_ca.pem
      # Unstructured.io Telemetry disabled
      DO_NOT_TRACK: true
      SCARF_NO_ANALYTICS: true
    volumes:
      - ../certs/ex_ca.pem:/usr/local/share/ca-certificates/extra/ex_ca.pem
```

This configuration makes it easier to keep up with upgrades.

**Comment by K1K1K1Zhang** [comment]
Hi, 

Is there anyone still dealing with this error? 

I came up with it a few days ago, and my dify version is 0.6.11. 

The error is on the http request node instead of the LLM node. 

I tried to fix the problem by adding the line in dify/api/workflow/nodes/http_request/http_executor.py by adding the argument 'verify', to ignore the SSL verification for httpx: 

```python

    def _do_http_request(self, headers: dict[str, Any]) -> httpx.Response:
        """
            do http request depending on api bundle
        """
        kwargs = {
            'url': self.server_url,
            'headers': headers,
            'params': self.params,
            'timeout': (self.timeout.connect, self.timeout.read, self.timeout.write),
            'follow_redirects': True,
            'verify': False  # Disable SSL verification for httpx
        }

        if self.method in ('get', 'head', 'options'):
            response = getattr(ssrf_proxy, self.method)(**kwargs)
        elif self.method in ('post', 'put', 'delete', 'patch'):
            response = getattr(ssrf_proxy, self.method)(data=self.body, files=self.files, **kwargs)
        else:
            raise ValueError(f'Invalid http method {self.method}')
        return response
```

But that didn't work.

**Reply by HappyClint** [reply]
I did this too， and it‘s did’t work.

**Comment by resline** [comment]
Resolution that worked for me.

### Steps to Resolve:

1. **Copy your SSL certificate**: 
   - Copy `my_cert.crt` to the `./docker/volumes/app/ssl_certs` directory.

2. **Modify the `docker-compose.yaml` file**:

    ```yaml
    services:
      # API service
      api:
        image: langgenius/dify-api:0.6.12-fix1
        restart: always
        environment:
          # Use the shared environment variables.
          <<: *shared-api-worker-env
          # Startup mode, 'api' starts the API server.
          MODE: api
        depends_on:
          - db
          - redis
        volumes:
          # Mount the storage directory to the container, for storing user files.
          - ./volumes/app/storage:/app/api/storage
          
          # Added line to mount the SSL certificate
          - ./volumes/app/ssl_certs/my_cert.crt:/usr/local/share/ca-certificates/my_cert.crt
          
        entrypoint: 
          # Append certificates to certifi's CA bundle
          - /bin/bash
          - -c 
          - |
            cat /usr/local/share/ca-certificates/my_cert.crt >> /app/api/.venv/lib/python3.10/site-packages/certifi/cacert.pem
            /entrypoint.sh
          
        networks:
          - ssrf_proxy_network
          - default    
    ```

### Key Additions:
- **Mount the SSL Certificate**:

    ```yaml
    volumes:
      # Added line to mount the SSL certificate
      - ./volumes/app/ssl_certs/my_cert.crt:/usr/local/share/ca-certificates/my_cert.crt
    ```

- **Update the `entrypoint`** to append the SSL certificate to the Certifi's CA bundle:

    ```yaml
    entrypoint: 
      # Added lines to append certificate
      - /bin/bash
      - -c 
      - |
        cat /usr/local/share/ca-certificates/my_cert.crt >> /app/api/.venv/lib/python3.10/site-packages/certifi/cacert.pem
        /entrypoint.sh
    ```

### Additional Information:
Dify has switched from `pip` to `poetry` for dependency management. This change has affected the path where Certifi's CA bundle is stored compared to previous versions. Ensure you use the correct path (`/app/api/.venv/lib/python3.10/site-packages/certifi/cacert.pem`) as shown above.

By following these steps, you should be able to resolve the SSL certificate issue effectively. Feel free to reach out if you have any further questions or need additional assistance.

---

**Reply by tjroamer** [reply]
This solution worked for me. Many thanks!

**Reply by FelixYangFromChina** [reply]
unfortunately, it's not working for me, any hint ? thank you in advance.

**Comment by happy-dogsss** [comment]
## Another way is to directly modify the requests library (not recommended for production environments).
image：docker-plugin_daemon-1
vim `/app/storage/cwd/langgenius/openai/.venv/lib/python3.12/site-packages/requests/sessions.py` file
![image](https://github.com/user-attachments/assets/8a9c10e0-f235-49b5-b208-539d91422771)
set `self.verify` to `False`
it can be work

**Reply by tatianass** [reply]
This is also a problem that I faced and I tried all the solutions that I found online, nothing worked. The strange thing is that it would work on some environments and others not, so I went library by library to see what was the differences between the ones working and not. The cause was `urllib3`, I had to change versions:
```bash
 - urllib3==2.3.0
 + urllib3==1.26.16
```

**Reply by FelixYangFromChina** [reply]
I followed above solutions, but it didn't work, could you share me details ? thank you

**Reply by happy-dogsss** [reply]
it’s change

**Comment by lartikzhong-lb** [comment]
![image](https://github.com/user-attachments/assets/10c63d80-ea99-42c2-9581-d929da57e9ea)
Sometimes it's really frustrating. The certificate in the plugin also needs to be replaced separately. I hope you don't fall into this trap.

**Reply by colamiya** [reply]
Reboot Dify can take effect. This idea solved the problem that troubled me for two days, thanks for sharing!

**Reply by Thunderinmoonlight** [reply]
It's really frustrating. When I added the secret key to the pom of the plugin, an error named ssl.SSLError: [X509] PEM lib (_ssl.c:4146) was reported.

**Reply by zolgear** [reply]
This is the method I use when deploying with Docker.

I make the virtual environment created during plugin installation use the host's certificates.

I mount the certificates into the container and install them, and I also pass the --native-tls parameter using the PIP_EXTRA_ARGS option.

```yaml
  plugin_daemon:
    environment:
      SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
      REQUESTS_CA_BUNDLE: /usr/local/share/ca-certificates/extra/ex_ca.pem
      #PIP_VERBOSE: true
      PIP_EXTRA_ARGS: "pip-system-certs --native-tls"
    volumes:
      - ../my-certs/ex_ca.pem:/usr/local/share/ca-certificates/ex_ca.crt
      - ../my-certs/ex_ca.pem:/usr/local/share/ca-certificates/extra/ex_ca.pem
    entrypoint: /bin/bash
    command:
      - "-c"
      - |
        update-ca-certificates && exec /app/entrypoint.sh
```

refs: <https://github.com/langgenius/dify-plugin-daemon/issues/121>
