### DISCUSSION TITLE
A question about SearXNG Extension

### DISCUSSION THREAD

**Discussion by momowuhao** [langgenius/dify#4645] [General]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I want have a free web search engine, I used the tool SearXNG search in the dify and deployed the SearXNG search engine locally.After selecting the bing search engine in SearXNG, I can use it in the web page normally. But I can't receive the reply from SearXNG search engine from dify extension.And when I select the option of image I can receive the reply, but when I select the option of web page and news I can't receive the reply, please help me to check this problem,Thank you very much!
![屏幕截图 2024-05-24 155654](https://github.com/langgenius/dify/assets/81690063/cab67b97-197d-4976-851d-76051572e181)
![屏幕截图 2024-05-24 155725](https://github.com/langgenius/dify/assets/81690063/83906cfa-ddda-41f0-bb02-a0011af9c6bd)
![屏幕截图 2024-05-24 155740](https://github.com/langgenius/dify/assets/81690063/76a406c6-a5b3-4076-895f-d28014cc16c9)

### ✔️ Expected Behavior

Receive the response from the SearXNG tool.

### ❌ Actual Behavior

I can not recevie the response from the searxng tool when i select the news and web option

**Comment by dosubot** [comment]
@139qaz6 Hello there! I'm here to help you with any bugs, questions, or contributions you have regarding the SearXNG Extension. Let's get to the bottom of this together.


The issue might be due to the default output format settings in SearXNG. By default, SearXNG outputs in HTML format, and you need to activate the JSON format for it to work correctly with Dify. Ensure that your `settings.yml` file includes the JSON format as shown below:

```yaml
# remove format to deny access, use lower case.
# formats: [html, csv, json, rss]
formats:
  - html
  - json    # <-- add this line 
```

Without this configuration, SearXNG may not return the expected results for "web page" or "news" queries, while the "image" option might still work due to different handling or fallback mechanisms. Additionally, ensure that you have correctly integrated SearXNG with Dify by following these steps:

1. **Install SearXNG using Docker:**
   ```sh
   docker run --rm \
              -d -p 8080:8080 \
              -v "${PWD}/searxng:/etc/searxng" \
              -e "BASE_URL=http://0.0.0.0:8080/" \
              -e "INSTANCE_NAME=searxng" \
              searxng/searxng
   ```

2. **Modify `settings.yml` to activate JSON format:**
   ```yaml
   # remove format to deny access, use lower case.
   # formats: [html, csv, json, rss]
   formats:
     - html
     - json    # <-- add this line
   ```

3. **Integrate SearXNG with Dify:**
   In Dify, go to `Tools > SearXNG > Authenticate` and fill in the access URL, for example: `http://x.x.x.x:8080`.

Additionally, ensure that the search type mappings in Dify's SearXNG integration are correctly set up. The `SearXNGSearchTool` class in Dify uses specific mappings for different search types:

```python
SEARCH_TYPE = {
    "page": "general",
    "news": "news",
    "image": "images",
    # "video": "videos",
    # "file": "files"
}
```

Make sure that the search type you are querying matches these mappings. For example, "web page" should map to "general" and "news" should map to "news". This ensures that the correct category is queried in SearXNG.

Also, verify that the `search_type` parameter in Dify's SearXNG tool configuration is correctly set. According to the Dify configuration, the `search_type` parameter should be one of "Page", "News", or "Image":

```yaml
parameters:
  - name: search_type
    type: select
    required: true
    label:
      en_US: search type
      zh_Hans: 搜索类型
      pt_BR: search type
    human_description:
      en_US: search type for page, news or image.
      zh_Hans: 选择搜索的类型：网页，新闻，图片。
      pt_BR: search type for page, news or image.
    default: Page
    options:
      - value: Page
        label:
          en_US: Page
          zh_Hans: 网页
          pt_BR: Page
      - value: News
        label:
          en_US: News
          zh_Hans: 新闻
          pt_BR: News
      - value: Image
        label:
          en_US: Image
          zh_Hans: 图片
          pt_BR: Image
```

Following these steps should resolve the issue and allow you to receive responses for "web page" and "news" queries <sup>[[1]](https://github.com/langgenius/dify-docs/blob/main/en/tutorials/tool-configuration/searxng.md)</sup><sup>[[2]](https://github.com/langgenius/dify-docs/blob/main/zh_CN/guides/tools/tool-configuration/searxng.md)</sup><sup>[[3]](https://github.com/langgenius/dify/blob/main/api/core/tools/provider/builtin/searxng/tools/searxng_search.py)</sup><sup>[[4]](https://github.com/langgenius/dify/blob/main/api/core/tools/provider/builtin/searxng/tools/searxng_search.yaml)</sup>.



<details open>
<summary>

#### Details
</summary>

**About Dosu**
This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.

Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
</details>

*To continue the conversation, mention @dosu.*
