### DISCUSSION TITLE
Run into "[Errno -2] Name or service not known" error in HTTP node or Customzed Tool

### DISCUSSION THREAD

**Discussion by huangfup** [langgenius/dify#4802] [Help] [answered]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.8

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I want to leverage HTTP node or customzed tool to fetch some data fom my local DB, so I developed Flask service for this, and I can access corresponding API via its swagger UI, but when I use it in HTTP node or customzed tool, [Errno -2] Name or service not known always occurs
<img width="1319" alt="Screenshot 2024-05-22 at 16 35 34" src="https://github.com/langgenius/dify/assets/16588370/3d8b27f6-62c0-4667-a880-a865d8c8144d">
<img width="1522" alt="Screenshot 2024-05-22 at 16 38 24" src="https://github.com/langgenius/dify/assets/16588370/2ac4b2ac-f1b6-4d53-afa8-6ddcd7cc3bbe">

### ✔️ Expected Behavior

I expect HTTP node or customzed tool to return data via my service so that those can be used in successor node

### ❌ Actual Behavior

Run into "[Errno -2] Name or service not known" error in HTTP node or Customzed Tool

**Comment by dosubot** [comment]
To resolve the "[Errno -2] Name or service not known" error when using an HTTP node or a customized tool to fetch data from your local database in a self-hosted Dify 0.6.8 deployment, ensure that the service names used in your configuration match the actual service names defined in your `docker-compose.middleware.yaml` file.

From your `docker-compose.middleware.yaml` file, the database service is named `db`. Therefore, you should use `db` as the hostname when connecting to the database from other services. For example, if you are using a PostgreSQL connection string, it should look like this:

```
postgresql://postgres:difyai123456@db:5432/dify
```

Additionally, verify that your environment variables in the `api/config.py` file are correctly set. The `DB_HOST` should be set to `db` as shown in the `DEFAULTS` dictionary:

```py
DEFAULTS = {
    'DB_USERNAME': 'postgres',
    'DB_PASSWORD': '',
    'DB_HOST': 'db',
    'DB_PORT': '5432',
    'DB_DATABASE': 'dify',
    ...
}
```

If you are using a different service name or hostname, update it to `db` to match the service name defined in the `docker-compose.middleware.yaml` file.



<details>
<summary>

#### Details
</summary>

**Sources**
- [Unable to make http request either in http node or custom tool and return [Errno -3] ](https://github.com/langgenius/dify/issues/4423)
- [docker/docker-compose.yaml](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml)
- [api/config.py](https://github.com/langgenius/dify/blob/main/api/config.py)
- [api/.env.example](https://github.com/langgenius/dify/blob/main/api/.env.example)
- [docker/docker-compose.middleware.yaml](https://github.com/langgenius/dify/blob/main/docker/docker-compose.middleware.yaml)

<br/>

**About Dosu**
This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.

Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
</details>

*To continue the conversation, mention @dosu.*

**Comment by huangfup** [comment]
@dosubot I feel you misunderstanding my question, I want to use HTTP Node to access the Flask service developed by myself instead of middleware of Dify

**Comment by dosubot** [comment]
To resolve the "[Errno -2] Name or service not known" error when using an HTTP node to access your Flask service, follow these steps:

1. **Check Docker Compose Service Names**: Ensure the service name in your connection matches the service name defined in your `docker-compose.yml` file. For example, if your Flask service is defined as `flask-service`, use `http://flask-service:5000` to connect to it.

2. **Verify Container Status**: Ensure all containers are running by executing:
    ```bash
    docker compose ps
    ```

3. **Example Docker Compose Configuration**:
    ```yaml
    version: '3'
    services:
      flask-service:
        image: your-flask-image
        ports:
          - "5000:5000"
      api:
        image: langgenius/dify-api:0.6.8
        environment:
          MODE: api
          LOG_LEVEL: INFO
          SECRET_KEY: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
          DB_HOST: db
          REDIS_HOST: redis
          CELERY_BROKER_URL: redis://:difyai123456@redis:6379/1
        depends_on:
          - flask-service
        ports:
          - "80:80"
      db:
        image: postgres:15-alpine
        environment:
          POSTGRES_PASSWORD: difyai123456
          POSTGRES_DB: dify
        volumes:
          - ./volumes/db/data:/var/lib/postgresql/data
      redis:
        image: redis:6-alpine
        command: redis-server --requirepass difyai123456
        volumes:
          - ./volumes/redis/data:/data
    ```

4. **Connecting to Flask Service**: Use the service name defined in the Docker Compose file to connect to the Flask service. For example:
    ```python
    import requests

    response = requests.get('http://flask-service:5000/your-endpoint')
    print(response.text)
    ```

5. **Ensure Flask App Configuration**: Make sure your Flask app is properly configured to handle requests. For example, in your `api/app.py` file:
    ```python
    from flask import Flask, Response, request
    import os

    class DifyApp(Flask):
        pass

    def create_app() -> Flask:
        app = DifyApp(__name__)
        app.config.from_object(Config())
        app.secret_key = app.config['SECRET_KEY']
        initialize_extensions(app)
        register_blueprints(app)
        register_commands(app)
        return app

    def initialize_extensions(app):
        ext_compress.init_app(app)
        ext_code_based_extension.init()
        ext_database.init_app(app)
        ext_migrate.init(app, db)
        ext_redis.init_app(app)
        ext_storage.init_app(app)
        ext_celery.init_app(app)
        ext_login.init_app(app)
        ext_mail.init_app(app)
        ext_hosting_provider.init_app(app)
        ext_sentry.init_app(app)

    app = create_app()
    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=5001)
    ```

6. **Ensure Proper Entrypoint Configuration**: Make sure your entrypoint script is correctly set up to run the Flask app. For example, in your `api/docker/entrypoint.sh` file:
    ```sh
    #!/bin/bash

    set -e

    if [[ "${MIGRATION_ENABLED}" == "true" ]]; then
      echo "Running migrations"
      flask db upgrade
    fi

    if [[ "${MODE}" == "worker" ]]; then
      celery -A app.celery worker -P ${CELERY_WORKER_CLASS:-gevent} -c ${CELERY_WORKER_AMOUNT:-1} --loglevel INFO \
        -Q ${CELERY_QUEUES:-dataset,generation,mail}
    elif [[ "${MODE}" == "beat" ]]; then
      celery -A app.celery beat --loglevel INFO
    else
      if [[ "${DEBUG}" == "true" ]]; then
        flask run --host=${DIFY_BIND_ADDRESS:-0.0.0.0} --port=${DIFY_PORT:-5001} --debug
      else
        gunicorn \
          --bind "${DIFY_BIND_ADDRESS:-0.0.0.0}:${DIFY_PORT:-5001}" \
          --workers ${SERVER_WORKER_AMOUNT:-1} \
          --worker-class ${SERVER_WORKER_CLASS:-gevent} \
          --timeout ${GUNICORN_TIMEOUT:-200} \
          --preload \
          app:app
      }
    fi
    ```

7. **Environment Variables Configuration**: Ensure the necessary environment variables are correctly set in your Docker Compose file or environment configuration. For example:
    ```yaml
    environment:
      MODE: api
      LOG_LEVEL: INFO
      SECRET_KEY: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
      DB_HOST: db
      REDIS_HOST: redis
      CELERY_BROKER_URL: redis://:difyai123456@redis:6379/1
      DIFY_BIND_ADDRESS: 0.0.0.0
      DIFY_PORT: 5001
    ```

By ensuring the service names are correctly referenced, all containers are running, your Flask app is properly configured, the entrypoint script is correctly set up, and the necessary environment variables are set, you should be able to resolve the "[Errno -2] Name or service not known" error and connect to your Flask service successfully.



<details>
<summary>

#### Details
</summary>

**Sources**
- [API KEY](https://github.com/langgenius/dify/issues/4321)
- [Unable to make http request either in http node or custom tool and return [Errno -3] ](https://github.com/langgenius/dify/issues/4423)
- [Workflow run code tool error: operation not permitted](https://github.com/langgenius/dify/issues/3331)
- [en/getting-started/install-self-hosted/docker-compose.md](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/docker-compose.md)
- [api/app.py](https://github.com/langgenius/dify/blob/main/api/app.py)
- [docker/docker-compose.yaml](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml)
- [api/docker/entrypoint.sh](https://github.com/langgenius/dify/blob/main/api/docker/entrypoint.sh)
- [en/getting-started/install-self-hosted/environments.md](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/environments.md)

<br/>

**About Dosu**
This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.

Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
</details>

*To continue the conversation, mention @dosu.*

**Comment by takatost** [comment]
This error is because the URL domain you filled in cannot be resolved, please check the DNS configuration.

**Comment by huangfup** [comment]
> This error is because the URL domain you filled in cannot be resolved, please check the DNS configuration.

@takatost thanks for your reply, I have no idea how to configh DNS for this, I ask gpt about this, it told me to make sure all services in docker container in the same network, so I checked docker-compose.yaml under docker folder of Dify, found DIfy related services are in default and ssrf_proxy_network, does this mean I need start up my service in such networks?

If you can explain in details about how to resolve this issue, appreciate a lot!

**Comment by crazywoola** [comment]
<img width="141" alt="image" src="https://github.com/langgenius/dify/assets/100913391/a2371cd2-868e-4d72-b914-8d7a348dc468">
This one you marked I think you are missing the http or https ?

**Comment by zhagnzhenfei** [comment]
应该是这个ssrf_proxy容器的原因，你可以在api，web两个服务里面把这一段注释掉
      # SSRF Proxy server
      SSRF_PROXY_HTTP_URL: 'http://ssrf_proxy:3128'
      SSRF_PROXY_HTTPS_URL: 'http://ssrf_proxy:3128'
然后确保你在容器内能解析域名就可以了

**Comment by Sunzz1996** [comment]
### After update the latest version of dify (0.6.8) and when I used HTTP custom modules, I encountered the same problem：
### [Errno -2] Name or service not known 
![image](https://github.com/langgenius/dify/assets/42266693/10af291a-f397-45e4-b1a2-eaf74e07d1d0)
The HTTP module config is:
![image](https://github.com/langgenius/dify/assets/42266693/87b02e5f-da9a-4ca9-a4e6-a7923ecb1642)

### The previous version of dify (0.6.4) is working for HTTP custom modules, i.e. no error in all process.
### I have confirmed the HTTP service is working:
```
# LAN IP 
curl http://10.252.224.19:8111/api/dify/receive
{"detail":"Method Not Allowed"}
```

**Comment by tony-wuhongtao** [comment]
> 应该是这个ssrf_proxy容器的原因，你可以在api，web两个服务里面把这一段注释掉 # SSRF Proxy server SSRF_PROXY_HTTP_URL: 'http://ssrf_proxy:3128' SSRF_PROXY_HTTPS_URL: 'http://ssrf_proxy:3128' 然后确保你在容器内能解析域名就可以了

问题解决
最新版0.6.9
只需要注释掉api里面的这段代码
问题解决
感谢！

**Comment by crazywoola** [comment, marked as answer]
TL;DR Just leave these two blank will solve this problem.

```yaml
api:
  environment:
    # SSRF Proxy server
    SSRF_PROXY_HTTP_URL: ''
    SSRF_PROXY_HTTPS_URL: '' 
```

Ref: [Why is SSRF_PROXY Needed?](https://docs.dify.ai/getting-started/install-self-hosted/install-faq#id-16.-why-is-ssrf_proxy-needed)
