### DISCUSSION TITLE
google search工具无法使用

### DISCUSSION THREAD

**Discussion by xmxoxo** [langgenius/dify#5614] [Help] [answered]
版本：DIFY 0.6.11，
简单做了一个LLM+google search的工作流，发现google search工具里无法设置语言，没办法设置成中文； 
尝试着在LLM里输出英文，但是LLM里的输出会自带引号，导致google search没有返回。

以下是工作流导出的YML文件内容：
```
app:
  description: DEMO
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: workflow
  name: "\u627E\u8D44\u6599"
workflow:
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: llm
      id: 1719371766206-source-1719372029969-target
      source: '1719371766206'
      sourceHandle: source
      target: '1719372029969'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: llm
        targetType: tool
      id: 1719372029969-source-1719372007836-target
      source: '1719372029969'
      sourceHandle: source
      target: '1719372007836'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: tool
        targetType: end
      id: 1719372007836-source-1719372374879-target
      source: '1719372007836'
      sourceHandle: source
      target: '1719372374879'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: "\u5F00\u59CB"
        type: start
        variables:
        - label: query
          max_length: 200
          options: []
          required: true
          type: paragraph
          variable: query
      height: 90
      id: '1719371766206'
      position:
        x: 104
        y: 88
      positionAbsolute:
        x: 104
        y: 88
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        provider_id: google
        provider_name: google
        provider_type: builtin
        selected: false
        title: "\u8C37\u6B4C\u641C\u7D22"
        tool_configurations:
          result_type: link
        tool_label: "\u8C37\u6B4C\u641C\u7D22"
        tool_name: google_search
        tool_parameters:
          query:
            type: mixed
            value: '{{#1719372029969.text#}}'
        type: tool
      height: 90
      id: '1719372007836'
      position:
        x: 696
        y: 88
      positionAbsolute:
        x: 696
        y: 88
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - '1719371766206'
          - query
        desc: ''
        model:
          completion_params:
            temperature: 0.7
          mode: completion
          name: qwen-turbo
          provider: tongyi
        prompt_template:
          edition_type: basic
          text: "\n# \u6307\u4EE4\uFF1A \u8BF7\u5206\u6790\u7528\u6237\u7684\u610F\
            \u56FE\uFF0C\u751F\u6210\u7528\u4E8E\u89E3\u51B3\u7528\u6237\u95EE\u9898\
            \u6240\u9700\u8981\u7684\u8BED\u53E5\uFF0C\u4EE5\u4FBF\u4E8E\u540E\u7EED\
            \u5230\u641C\u7D22\u5F15\u64CE\u4E2D\u8FDB\u884C\u641C\u7D22\n# \u8F93\
            \u51FA\uFF1A\u4E0D\u9700\u8981\u5176\u5B83\u89E3\u91CA\uFF0C\u53EA\u9700\
            \u8981\u8F93\u51FA\u6700\u7EC8\u8981\u641C\u7D22\u7684\u6587\u672C\uFF1B\
            \n\u8BF7\u7528\u82F1\u6587\u8F93\u51FA\u6587\u672C\u5185\u5BB9\uFF1B\u8F93\
            \u51FA\u5185\u5BB9\u7684\u5934\u5C3E\u4E0D\u8981\u5E26\u5F15\u53F7\uFF1B\
            \nHuman:{{#1719371766206.query#}}\nAssistant:"
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 98
      id: '1719372029969'
      position:
        x: 392
        y: 88
      positionAbsolute:
        x: 392
        y: 88
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1719371766206'
          - query
          variable: query
        - value_selector:
          - '1719372007836'
          - text
          variable: result
        selected: false
        title: "\u7ED3\u675F"
        type: end
      height: 116
      id: '1719372374879'
      position:
        x: 1007
        y: 88
      positionAbsolute:
        x: 1007
        y: 88
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -110
      y: 311.5
      zoom: 1.0000000000000002
```

**Comment by xmxoxo** [comment, marked as answer]
以下是工作流导出的YML文件内容：
```
app:
  description: DEMO
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: workflow
  name: "\u627E\u8D44\u6599"
workflow:
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: llm
      id: 1719371766206-source-1719372029969-target
      source: '1719371766206'
      sourceHandle: source
      target: '1719372029969'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: llm
        targetType: tool
      id: 1719372029969-source-1719372007836-target
      source: '1719372029969'
      sourceHandle: source
      target: '1719372007836'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: tool
        targetType: end
      id: 1719372007836-source-1719372374879-target
      source: '1719372007836'
      sourceHandle: source
      target: '1719372374879'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: "\u5F00\u59CB"
        type: start
        variables:
        - label: query
          max_length: 200
          options: []
          required: true
          type: paragraph
          variable: query
      height: 90
      id: '1719371766206'
      position:
        x: 104
        y: 88
      positionAbsolute:
        x: 104
        y: 88
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        provider_id: google
        provider_name: google
        provider_type: builtin
        selected: false
        title: "\u8C37\u6B4C\u641C\u7D22"
        tool_configurations:
          result_type: link
        tool_label: "\u8C37\u6B4C\u641C\u7D22"
        tool_name: google_search
        tool_parameters:
          query:
            type: mixed
            value: '{{#1719372029969.text#}}'
        type: tool
      height: 90
      id: '1719372007836'
      position:
        x: 696
        y: 88
      positionAbsolute:
        x: 696
        y: 88
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - '1719371766206'
          - query
        desc: ''
        model:
          completion_params:
            temperature: 0.7
          mode: completion
          name: qwen-turbo
          provider: tongyi
        prompt_template:
          edition_type: basic
          text: "\n# \u6307\u4EE4\uFF1A \u8BF7\u5206\u6790\u7528\u6237\u7684\u610F\
            \u56FE\uFF0C\u751F\u6210\u7528\u4E8E\u89E3\u51B3\u7528\u6237\u95EE\u9898\
            \u6240\u9700\u8981\u7684\u8BED\u53E5\uFF0C\u4EE5\u4FBF\u4E8E\u540E\u7EED\
            \u5230\u641C\u7D22\u5F15\u64CE\u4E2D\u8FDB\u884C\u641C\u7D22\n# \u8F93\
            \u51FA\uFF1A\u4E0D\u9700\u8981\u5176\u5B83\u89E3\u91CA\uFF0C\u53EA\u9700\
            \u8981\u8F93\u51FA\u6700\u7EC8\u8981\u641C\u7D22\u7684\u6587\u672C\uFF1B\
            \n\u8BF7\u7528\u82F1\u6587\u8F93\u51FA\u6587\u672C\u5185\u5BB9\uFF1B\u8F93\
            \u51FA\u5185\u5BB9\u7684\u5934\u5C3E\u4E0D\u8981\u5E26\u5F15\u53F7\uFF1B\
            \nHuman:{{#1719371766206.query#}}\nAssistant:"
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 98
      id: '1719372029969'
      position:
        x: 392
        y: 88
      positionAbsolute:
        x: 392
        y: 88
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1719371766206'
          - query
          variable: query
        - value_selector:
          - '1719372007836'
          - text
          variable: result
        selected: false
        title: "\u7ED3\u675F"
        type: end
      height: 116
      id: '1719372374879'
      position:
        x: 1007
        y: 88
      positionAbsolute:
        x: 1007
        y: 88
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -110
      y: 311.5
      zoom: 1.0000000000000002
```
