### DISCUSSION TITLE
Implement qdrnt. dify 0.6.12

### DISCUSSION THREAD

**Discussion by koryakovda** [langgenius/dify#5883] [Help]
Hello, I am trying to change my VECTOR_STORE from Weaviate to Qdrant on my Windows.

1)In the previous version, it worked fine when I changed the VECTOR_STORE parameter in docker-compose.yaml. However, in the new version, the VECTOR_STORE parameter has been moved to the .env file.

I am using the 'docker compose up -d' command to start Docker with Dify. 

Before running docker compose up -d, I changed the VECTOR_STORE in the .env file (line 244) to VECTOR_STORE=qdrant, but I can't access the Qdrant UI at http://localhost:6333/dashboard.

2)I also tried running Qdrant in a separate Docker container:

fceedcc16930   qdrant/qdrant   "./entrypoint.sh"   3 hours ago   Up About an hour   0.0.0.0:6333-6334->6333-6334/tcp   elastic_driscoll

and changed (line 251) in the .env file:
The Qdrant endpoint URL. Only available when VECTOR_STORE is `qdrant`.
QDRANT_URL=http://localhost:6333/ and http://host.docker.internal:6333

This didn't help.

3)I also tried running Qdrant in the cloud and changed:

(line 251) # The Qdrant endpoint URL. Only available when VECTOR_STORE is `qdrant`.
QDRANT_URL=https://1722***fe3.us-east4-0.gcp.cloud.qdrant.io:6333
(line 254) # The Qdrant API key.
QDRANT_API_KEY=dgeq*****Fev

This didn't help either.

What do I need to change to make it work for all of these methods?

Thank you!

**Comment by dosubot** [comment]
Hello, @koryakovda! I'm here to help you with your Dify issue. I can assist with bug fixes, answer questions, and guide you through becoming a contributor. Let's tackle this problem together!


To successfully change your VECTOR_STORE from Weaviate to Qdrant on your Windows machine using Dify version 0.6.12, follow these steps:

1. **Modify the `.env` file**:
   Update the environment variable in the `.env` file to use Qdrant:
   ```plaintext
   VECTOR_STORE=qdrant
   ```

2. **Modify the `docker-compose.yaml` file**:
   Update the environment variable in the `docker-compose.yaml` file for both the `api` and `worker` services:
   ```yaml
   environment:
     VECTOR_STORE: qdrant
   ```

3. **Configure Qdrant-specific settings**:
   Ensure that the Qdrant-specific settings are correctly configured in the `docker-compose.yaml` file:
   ```yaml
   qdrant:
     image: langgenius/qdrant:v1.7.3
     restart: always
     volumes:
       - ./volumes/qdrant:/qdrant/storage
     environment:
       QDRANT_API_KEY: 'difyai123456'
     ports:
       - "6333:6333"
       - "6334:6334"
   ```

4. **Update Qdrant settings in the `.env` file**:
   Ensure that the Qdrant-specific environment variables are set in the `.env` file:
   ```plaintext
   QDRANT_URL=http://qdrant:6333
   QDRANT_API_KEY=difyai123456
   QDRANT_CLIENT_TIMEOUT=20
   QDRANT_GRPC_ENABLED=false
   QDRANT_GRPC_PORT=6334
   ```

5. **Run the migration command**:
   Execute the following command in your terminal or Docker container to migrate the data:
   ```sh
   flask vdb-migrate
   ```
   Or, if using Docker:
   ```sh
   docker exec -it docker-api-1 flask vdb-migrate
   ```

Additionally, ensure that the necessary ports (6333 and 6334) are not blocked by your Windows firewall or any other network security settings. You may need to create firewall rules to allow traffic on these ports <sup>[[1]](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/install-faq.md)</sup><sup>[[2]](https://github.com/langgenius/dify-docs/blob/main/zh_CN/learn-more/faq/install-faq.md)</sup><sup>[[3]](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml)</sup><sup>[[4]](https://github.com/langgenius/dify/blob/main/docker-legacy/docker-compose.qdrant.yaml)</sup><sup>[[5]](https://github.com/langgenius/dify/blob/main/docker/.env.example)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by koryakovda** [reply]
Hello,

1)I have modified the .env file:
![image](https://github.com/langgenius/dify/assets/63857069/11687bfe-bdcc-43a8-a83a-6456c52b4b65)
2)I have modified the docker-compose.yaml file (it has changed in the new version):
![image](https://github.com/langgenius/dify/assets/63857069/6bd1f11e-ae65-40d1-83de-eb9457d80104)
3) Configured Qdrant-specific settings (they have changed in the new version):
![image](https://github.com/langgenius/dify/assets/63857069/dacbd2d1-5b05-412a-acec-0d71b36b7edc)
4) Updated Qdrant settings in the .env file:
![image](https://github.com/langgenius/dify/assets/63857069/db96af31-1c03-484b-a5bb-7ad2519a0310)
5) After all these steps, I started Docker with the command docker compose up -d.

However, I still couldn't get access to the Qdrant UI at http://localhost:6333/dashboard.
![image](https://github.com/langgenius/dify/assets/63857069/5106fbfd-c7ad-4f74-8157-4a876d1e5549)

**Reply by dosubot** [reply]
To successfully access the Qdrant UI at `http://localhost:6333/dashboard` after following the steps you mentioned, ensure the following:

1. **Verify Qdrant Container Status**:
   Ensure that the Qdrant container is running without issues. You can check the status using:
   ```sh
   docker ps
   ```
   Look for the Qdrant container and ensure it is up and running.

2. **Check Qdrant Logs**:
   Inspect the logs of the Qdrant container to identify any potential issues:
   ```sh
   docker logs <qdrant_container_id>
   ```
   Replace `<qdrant_container_id>` with the actual container ID of the Qdrant service.

3. **Firewall and Network Settings**:
   Ensure that your Windows firewall or any other network security software is not blocking port 6333. You can follow these steps to allow traffic on port 6333:
   - Open Windows Firewall settings (`Win + R`, type `firewall.cpl`, and press `Enter`).
   - Click on "Advanced settings" and create a new inbound rule to allow TCP traffic on port 6333.

4. **Health Check Endpoint**:
   Use the Qdrant health check endpoint to verify that the service is running correctly. You can do this by running the following Python script:
   ```python
   from qdrant_client import QdrantClient

   client = QdrantClient(url="http://localhost:6333")

   try:
       collections_response = client.get_collections()
       print("Qdrant service is running correctly.")
   except Exception as e:
       print(f"Qdrant service health check failed: {e}")
   ```

5. **Docker Network Configuration**:
   Ensure that the Docker network configuration allows communication between containers and the host. You can inspect the network settings using:
   ```sh
   docker network inspect bridge
   ```

By following these steps, you should be able to diagnose and resolve the issue preventing access to the Qdrant UI <sup>[[1]](https://github.com/langgenius/dify/blob/main/docker-legacy/docker-compose.qdrant.yaml)</sup><sup>[[2]](https://github.com/langgenius/dify/blob/main/api/core/rag/datasource/vdb/qdrant/qdrant_vector.py)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Comment by koryakovda** [comment]
1) Verify Qdrant Container Status:
is ok, its up
81f03f619e6e   langgenius/qdrant:v1.7.3          "./entrypoint.sh"        About an hour ago   Up About an hour             6333-6334/tcp                              docker-qdrant-1
2) Check Qdrant Logs:
Seems ok.

According to logs I am obtaining 2 POST reguests to qdrnt database when testing RAG chatbot with Rerank model:

-2024-07-02T14:06:35.595389Z  INFO actix_web::middleware::logger: 172.25.0.8 "POST /collections/Vector_index_a6a954ed_8089_4b93_a51e_7bad75a9208a_Node/points/scroll HTTP/1.1" 200 6558 "-" "python-httpx/0.27.0" 0.034362
-2024-07-02T14:06:36.706689Z  INFO actix_web::middleware::logger: 172.25.0.8 "POST /collections/Vector_index_a6a954ed_8089_4b93_a51e_7bad75a9208a_Node/points/search HTTP/1.1" 200 18724 "-" "python-httpx/0.27.0" 0.019699

and one POST request when deliting knowlage:
-2024-07-02T14:09:59.912764Z  INFO actix_web::middleware::logger: 172.25.0.7 "POST /collections/Vector_index_a6a954ed_8089_4b93_a51e_7bad75a9208a_Node/points/delete?wait=true HTTP/1.1" 200 92 "-" "python-httpx/0.27.0" 0.229652

3) Firewall and Network Settings:
Ok. Not blocking port 6333

4)Health Check Endpoint:
Faild.

"Qdrant service health check failed: [WinError 10061] No connection could be made because the target machine actively refused it"

5) Docker Network Configuration:
The Qdrant container is in the docker_default network as it is supposed to be when you use the docker compose up -d command.

@dosu doesent helps

**Reply by dosubot** [reply]
Since the Qdrant service health check failed with the error "[WinError 10061] No connection could be made because the target machine actively refused it," it indicates that the Qdrant service is not accessible from your host machine. Here are some additional steps to troubleshoot and resolve this issue:

1. **Check Port Mapping in Docker Compose**:
   Ensure that the ports are correctly mapped in your `docker-compose.yaml` file. The Qdrant service should have the following port mappings:
   ```yaml
   services:
     qdrant:
       image: langgenius/qdrant:v1.7.3
       restart: always
       ports:
         - "6333:6333"
         - "6334:6334"
       environment:
         QDRANT_API_KEY: ${QDRANT_API_KEY:-difyai123456}
       volumes:
         - ./volumes/qdrant:/qdrant/storage
   ```

2. **Restart Docker Services**:
   Sometimes, restarting the Docker services can resolve connectivity issues. Run the following commands to restart the services:
   ```sh
   docker-compose down
   docker-compose up -d
   ```

3. **Check Docker Network Configuration**:
   Ensure that the Docker network allows communication between the host and the container. You can try creating a new Docker network and attaching the Qdrant container to it:
   ```sh
   docker network create qdrant_network
   docker network connect qdrant_network docker-qdrant-1
   ```

4. **Access Qdrant from Another Container**:
   Try accessing the Qdrant service from another container to verify if the issue is specific to the host machine. You can use a temporary container to test this:
   ```sh
   docker run -it --network qdrant_network --rm python:3.9 bash
   ```
   Inside the container, run the following Python script to check the Qdrant service:
   ```python
   from qdrant_client import QdrantClient

   client = QdrantClient(url="http://qdrant:6333")

   try:
       collections_response = client.get_collections()
       print("Qdrant service is running correctly.")
   except Exception as e:
       print(f"Qdrant service health check failed: {e}")
   ```

5. **Inspect Qdrant Container Logs**:
   Double-check the Qdrant container logs for any errors or warnings that might indicate why the service is not accessible:
   ```sh
   docker logs docker-qdrant-1
   ```

By following these steps, you should be able to identify and resolve the issue preventing access to the Qdrant UI and service.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by koryakovda** [reply]
How can I connect my https://cloud.qdrant.io/ cluster to Dify, which I run using the docker-compose up -d command?

**Reply by dosubot** [reply]
To connect your Qdrant Cloud cluster to Dify, which you run using the `docker-compose up -d` command, follow these steps:

1. **Update the `.env` File**:
   Ensure that the `.env` file contains the correct Qdrant Cloud endpoint and API key:
   ```plaintext
   VECTOR_STORE=qdrant
   QDRANT_URL=https://your-qdrant-cluster-url.qdrant.io
   QDRANT_API_KEY=your-qdrant-api-key
   QDRANT_CLIENT_TIMEOUT=20
   QDRANT_GRPC_ENABLED=false
   QDRANT_GRPC_PORT=6334
   ```

2. **Modify the `docker-compose.yaml` File**:
   Ensure that the `docker-compose.yaml` file for both the `api` and `worker` services includes the necessary environment variables:
   ```yaml
   services:
     api:
       environment:
         VECTOR_STORE: qdrant
         QDRANT_URL: ${QDRANT_URL}
         QDRANT_API_KEY: ${QDRANT_API_KEY}
         QDRANT_CLIENT_TIMEOUT: ${QDRANT_CLIENT_TIMEOUT}
         QDRANT_GRPC_ENABLED: ${QDRANT_GRPC_ENABLED}
         QDRANT_GRPC_PORT: ${QDRANT_GRPC_PORT}
     worker:
       environment:
         VECTOR_STORE: qdrant
         QDRANT_URL: ${QDRANT_URL}
         QDRANT_API_KEY: ${QDRANT_API_KEY}
         QDRANT_CLIENT_TIMEOUT: ${QDRANT_CLIENT_TIMEOUT}
         QDRANT_GRPC_ENABLED: ${QDRANT_GRPC_ENABLED}
         QDRANT_GRPC_PORT: ${QDRANT_GRPC_PORT}
   ```

3. **Restart Docker Services**:
   Restart the Docker services to apply the changes:
   ```sh
   docker-compose down
   docker-compose up -d
   ```

4. **Verify Connectivity**:
   Use a Python script to verify the connection to your Qdrant Cloud cluster:
   ```python
   from qdrant_client import QdrantClient

   client = QdrantClient(url="https://your-qdrant-cluster-url.qdrant.io", api_key="your-qdrant-api-key")

   try:
       collections_response = client.get_collections()
       print("Qdrant service is running correctly.")
   except Exception as e:
       print(f"Qdrant service health check failed: {e}")
   ```

By following these steps, you should be able to connect your Qdrant Cloud cluster to Dify successfully <sup>[[1]](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/install-faq.md)</sup><sup>[[2]](https://github.com/langgenius/dify/blob/main/api/.env.example)</sup><sup>[[3]](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by koryakovda** [reply]
1 Done
2 Done
3 Done
4 Done. Got 'Qdrant service is running correctly.'
But it still doesn't work. I've tried to create 'knowledge' but got an error.
![image](https://github.com/langgenius/dify/assets/63857069/0811a57c-e549-4637-a869-789e75cd5591)

**Reply by dosubot** [reply]
To resolve the "403 Forbidden" error when creating knowledge in Dify after connecting your Qdrant Cloud cluster, ensure that the `QDRANT_API_KEY` environment variable is correctly set and has the necessary permissions to operate on all knowledge bases. Here are the steps to verify and correct this:

1. **Verify `QDRANT_API_KEY` Permissions**:
   Ensure that the API key you are using has the necessary permissions to interact with Dify's knowledge creation feature. The API key must have permissions to operate on all knowledge bases.

2. **Check `docker-compose.yaml` Configuration**:
   Ensure that the `docker-compose.yaml` file includes the correct environment variables for both the `api` and `worker` services:
   ```yaml
   services:
     api:
       environment:
         VECTOR_STORE: qdrant
         QDRANT_URL: ${QDRANT_URL}
         QDRANT_API_KEY: ${QDRANT_API_KEY}
         QDRANT_CLIENT_TIMEOUT: ${QDRANT_CLIENT_TIMEOUT}
         QDRANT_GRPC_ENABLED: ${QDRANT_GRPC_ENABLED}
         QDRANT_GRPC_PORT: ${QDRANT_GRPC_PORT}
     worker:
       environment:
         VECTOR_STORE: qdrant
         QDRANT_URL: ${QDRANT_URL}
         QDRANT_API_KEY: ${QDRANT_API_KEY}
         QDRANT_CLIENT_TIMEOUT: ${QDRANT_CLIENT_TIMEOUT}
         QDRANT_GRPC_ENABLED: ${QDRANT_GRPC_ENABLED}
         QDRANT_GRPC_PORT: ${QDRANT_GRPC_PORT}
   ```

3. **Enable Debug Mode**:
   Enable detailed logging and debugging information to get more insights into the error. Update your `.env` file with the following settings:
   ```plaintext
   LOG_LEVEL=DEBUG
   DEBUG=true
   FLASK_DEBUG=true
   ```

4. **Restart Docker Services**:
   Restart the Docker services to apply the changes:
   ```sh
   docker-compose down
   docker-compose up -d
   ```

5. **Check Logs for Detailed Error Information**:
   After enabling debug mode, check the logs for more detailed information about the "403 Forbidden" error:
   ```sh
   docker logs <api_container_id>
   ```

By ensuring the API key has the correct permissions and enabling detailed logging, you should be able to diagnose and resolve the "403 Forbidden" error <sup>[[1]](https://github.com/langgenius/dify/blob/main/docker-legacy/docker-compose.qdrant.yaml)</sup><sup>[[2]](https://github.com/langgenius/dify-docs/blob/main/zh_CN/features/datasets/maintain-dataset-via-api.md)</sup><sup>[[3]](https://github.com/langgenius/dify/blob/main/docker/.env.example)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
