### DISCUSSION TITLE
How to pass variables to chatflow from chatbot

### DISCUSSION THREAD

**Discussion by fabiofurlano** [langgenius/dify#5992] [General]
Hello everyone,
I am trying to pass the variables to the workflows. It's fine when it's one, but when there are more, it's a bit of a mess. I was wondering if there is a better way.

**Comment by dosubot** [comment]
Ciao @fabiofurlano! 👋 I'm here to help you with any bugs, questions, or contributions while waiting for a human maintainer.


To efficiently pass multiple variables to workflows in your chatbot, you can follow these steps:

1. **Define Execution Start Variables**: Start by defining the necessary input variables for your workflow. For example, you can define an input variable `sys.query` for a chatbot.

2. **Node Input Variables**: Each node in the workflow should have its input variables defined. For instance, if you have a question classifier node, you can define its input variable as `sys.query`.

3. **Reference Upstream Variables**: When referencing variables within nodes, ensure that you only reference variables from upstream nodes in the process.

4. **Unique Node Names**: To avoid variable name conflicts, ensure that each node has a unique name.

5. **System-Fixed Output Variables**: Note that the output variables of nodes are generally system-fixed and cannot be edited.

Here is an example of how you might define and pass variables in a workflow:

```yaml
# Define start variables
start_node:
  input_variables:
    - sys.query
    - sys.user_id

# Define a question classifier node
question_classifier_node:
  input_variables:
    - sys.query
  output_variables:
    - classified_question

# Define another node that uses the output of the question classifier
response_generator_node:
  input_variables:
    - classified_question
  output_variables:
    - response
```

Additionally, you can use the `WorkflowVariablesConfigManager` class to convert workflow start variables to a list of `VariableEntity` objects. This is done by finding the start node and iterating over the user input form to append each variable to the list:

```py
from core.app.app_config.entities import VariableEntity
from models.workflow import Workflow

class WorkflowVariablesConfigManager:
    @classmethod
    def convert(cls, workflow: Workflow) -> list[VariableEntity]:
        """
        Convert workflow start variables to variables

        :param workflow: workflow instance
        """
        variables = []

        # find start node
        user_input_form = workflow.user_input_form()

        # variables
        for variable in user_input_form:
            variables.append(VariableEntity(**variable))

        return variables
```

By following these steps, you can efficiently pass multiple variables through your workflow, ensuring smooth and complex processing logic <sup>[[1]](https://github.com/langgenius/dify-docs/blob/main/en/guides/workflow/key-concept.md)</sup><sup>[[2]](https://github.com/langgenius/dify/blob/main/api/core/app/app_config/workflow_ui_based_app/variables/manager.py)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
