### DISCUSSION TITLE
How to  activate to code block in comminity ver

### DISCUSSION THREAD

**Discussion by potofo** [langgenius/dify#5993] [General]
The Code Extension page of the Dify manual states that the Sandbox Service is suppressed in Local Deployment.

It says that the Sandbox Service can be started with the following command, but it doesn't work.

Please let me know what to pay attention to in the startup procedure and how to run it, including docker-compose -f docker-compose.yaml up -d.

The current steps are as follows:
1) Starting Dify 
   docker-compose -f docker-compose.yaml up -d
2) Starting Sandbox Service & miscellaneous Service
   docker-compose -f docker-compose.middleware.yaml up -d

```
docker-compose -f docker-compose.middleware.yaml up -d
```

Manual
  [Workflow]->[Node Description]->[Code Extention]
  https://docs.dify.ai/guides/workflow/node/code

**Comment by dosubot** [comment]
To successfully run the Sandbox Service in the community version of Dify, follow these steps:

1. **Ensure Docker and Docker Compose are installed** on your system.

2. **Save the provided YAML configuration** for the Sandbox Service to a file named `docker-compose.middleware.yaml`:

```yaml
# The DifySandbox
sandbox:
  image: langgenius/dify-sandbox:0.2.1
  restart: always
  environment:
    API_KEY: ${API_KEY:-dify-sandbox}
    GIN_MODE: ${GIN_MODE:-release}
    WORKER_TIMEOUT: ${WORKER_TIMEOUT:-15}
    ENABLE_NETWORK: ${ENABLE_NETWORK:-true}
    HTTP_PROXY: ${HTTP_PROXY:-http://ssrf_proxy:3128}
    HTTPS_PROXY: ${HTTPS_PROXY:-http://ssrf_proxy:3128}
    SANDBOX_PORT: ${SANDBOX_PORT:-8194}
  volumes:
    - ./volumes/sandbox/dependencies:/dependencies
  networks:
    - ssrf_proxy_network
```

3. **Ensure the `ssrf_proxy` service is properly configured** and running. Here is the configuration for the `ssrf_proxy` service:

```yaml
# ssrf_proxy server
ssrf_proxy:
  image: ubuntu/squid:latest
  restart: always
  volumes:
    - ./ssrf_proxy/squid.conf.template:/etc/squid/squid.conf.template
    - ./ssrf_proxy/docker-entrypoint.sh:/docker-entrypoint.sh
  entrypoint: ["sh", "-c", "chmod +x /docker-entrypoint.sh && /docker-entrypoint.sh"]
  environment:
    HTTP_PORT: ${HTTP_PORT:-3128}
    COREDUMP_DIR: ${COREDUMP_DIR:-/var/spool/squid}
    REVERSE_PROXY_PORT: ${REVERSE_PROXY_PORT:-8194}
    SANDBOX_HOST: ${SANDBOX_HOST:-sandbox}
    SANDBOX_PORT: ${SANDBOX_PORT:-8194}
  networks:
    - ssrf_proxy_network
    - default
```

4. **Start Dify** using the following command:

```sh
docker-compose -f docker-compose.yaml up -d
```

5. **Start the Sandbox Service and other necessary services** using the following command:

```sh
docker-compose -f docker-compose.middleware.yaml up -d
```

Make sure to adjust the environment variables and paths according to your specific deployment needs <sup>[[1]](https://github.com/langgenius/dify/blob/main/docker-legacy/docker-compose.middleware.yaml)</sup><sup>[[2]](https://github.com/langgenius/dify/blob/main/docker/docker-compose.middleware.yaml)</sup><sup>[[3]](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
