### DISCUSSION TITLE
add 3rd party model from aliyun to dify

### DISCUSSION THREAD

**Discussion by jay-jjwu** [langgenius/dify#6005] [General]
did anyone try to add 3rd party models to dify? 
i did try to add yaml confogi file to integrate chatglm form aliyun to dify, but the log shows only qwen models are currently supported as below:
//*********
ERROR [Dummy-2] [base_app_generate_response_converter.py:128] - Not support model: chatglm3-6b, currently only support qwen models.

so the 3rd party models are not supported?

**Comment by dosubot** [comment]
Hey @jay-jjwu! 👋 I'm here to assist you with any bugs, questions, or contributions you have. Let's squash those bugs together!


You can integrate the ChatGLM model into Dify. Dify supports ZHIPU (ChatGLM) as a provider for both System Inference Models and Embedding Models. Additionally, Dify can connect to locally deployed Xinference models, which include support for ChatGLM.

To deploy Xinference locally and integrate it with Dify, follow these steps:

1. Install Xinference via PyPI:
    ```bash
    $ pip install "xinference[all]"
    ```

2. Start Xinference locally:
    ```bash
    $ xinference-local
    2023-08-20 19:21:05,265 xinference   10148 INFO     Xinference successfully started. Endpoint: http://127.0.0.1:9997
    2023-08-20 19:21:05,266 xinference.core.supervisor 10148 INFO     Worker 127.0.0.1:37822 has been added successfully
    2023-08-20 19:21:05,267 xinference.deploy.worker 10148 INFO     Xinference worker successfully started.
    ```

3. Create and deploy the model by visiting `http://127.0.0.1:9997`, selecting the model and specification you need to deploy.

4. Obtain the model UID from the `Running Models` page.

5. Connect the deployed model in Dify by navigating to `Settings > Model Providers > Xinference` and entering:
    - Model name: `chatglm`
    - Server URL: `http://<Machine_IP>:9997` (Replace with your machine IP address)
    - Model UID: (Copy the model UID from the `Running Models` page)

Click "Save" to use the model in the Dify application.

For more detailed information, you can refer to the [Xinference documentation](https://github.com/xorbitsai/inference) <sup>[[1]](https://github.com/langgenius/dify-docs/blob/main/en/guides/model-configuration/README.md)</sup><sup>[[2]](https://github.com/langgenius/dify-docs/blob/main/jp/guides/model-configuration/xinference.md)</sup><sup>[[3]](https://github.com/langgenius/dify-docs/blob/main/en/guides/model-configuration/xinference.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by jay-jjwu** [reply]
but this is not my aimming, i dont have enough hardware to run models in xinference locally, that's why i'm looking for integrate 3rd party modeling like chatglm or llama3 from aliyun.
is there any solution to this senario?

**Reply by dosubot** [reply]
Yes, you can integrate third-party models like ChatGLM or LLaMA3 from Aliyun into Dify without running them locally. You need to obtain the API key from the model provider's official website and set it in Dify's `Settings > Model Provider`.

For specific integration methods, you can refer to the documentation for each provider:
- [Hugging Face](https://docs.dify.ai/advanced/model-configuration/hugging-face)
- [Replicate](https://docs.dify.ai/advanced/model-configuration/replicate)
- [Xinference](https://docs.dify.ai/advanced/model-configuration/xinference)
- [OpenLLM](https://docs.dify.ai/advanced/model-configuration/openllm) <sup>[[1]](https://github.com/langgenius/dify-docs/blob/main/en/guides/model-configuration/README.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by jay-jjwu** [reply]
yes, but all above you mentioned are local models. Ii already have an api-key from aliyun, is it possible to connect model like llama3 via aliyun provider channel?

**Reply by dosubot** [reply]
Yes, it is possible to connect the LLaMA3 model from Aliyun to Dify using the Aliyun provider channel with an API key. You need to configure the `tongyi.yaml` file to use the API key from AliCloud. Here is an example configuration:

```yaml
provider: tongyi
label:
  zh_Hans: 通义千问
  en_US: TONGYI
icon_small:
  en_US: icon_s_en.png
icon_large:
  zh_Hans: icon_l_zh.png
  en_US: icon_l_en.png
background: "#EFF1FE"
help:
  title:
    en_US: Get your API key from AliCloud
    zh_Hans: 从阿里云获取 API Key
  url:
    en_US: https://dashscope.console.aliyun.com/api-key_management
supported_model_types:
  - llm
  - tts
  - text-embedding
configurate_methods:
  - predefined-model
provider_credential_schema:
  credential_form_schemas:
    - variable: dashscope_api_key
      label:
        en_US: API Key
      type: secret-input
      required: true
      placeholder:
        zh_Hans: 在此输入您的 API Key
        en_US: Enter your API Key
```

You need to obtain the API key from AliCloud and enter it in the required field to connect the model <sup>[[1]](https://github.com/langgenius/dify/blob/main/api/core/model_runtime/model_providers/tongyi/tongyi.yaml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
