### DISCUSSION TITLE
Looking for guide to self-host/deploy Dify on GCP.

### DISCUSSION THREAD

**Discussion by ajaman190** [langgenius/dify#6344] [Help]
Hi everyone,

I am looking to deploy Dify on Google Cloud Platform (GCP) for use by my team. After some research, I found that we can deploy Dify services on GCP as follows:

1. Cloud Run or GKE: For services such as api, worker, web, sandbox, ssrfproxy, and nginx (or alternatively, using GCP load balancer).
2. Cloud SQL: For PostgreSQL database and pgvector.
3. Memorystore: For Redis.

I attempted to deploy Dify services on Cloud Run using Terraform taking reference from Docker Compose but encountered issues that prevented a successful deployment.

Could anyone provide a detailed guide or best practices for correctly deploying Dify on GCP? Any help would be greatly appreciated.

Thanks in advance!

**Comment by dosubot** [comment]
Hey @ajaman190! 👋 I'm here to help you out with your Dify deployment on GCP. I'm a bot that can assist with bug fixes, answering questions, and becoming a contributor.


To deploy Dify on Google Cloud Platform (GCP), you can follow these steps and best practices:

### Prerequisites
1. **GCP Project**: Ensure you have a GCP project set up.
2. **Cloud SQL**: Set up a PostgreSQL instance.
3. **Memorystore**: Set up a Redis instance.
4. **Docker**: Ensure Docker is installed on your local machine.

### Step-by-Step Guide

#### 1. Start Middleware Services
Start the required middleware services (PostgreSQL, Redis, and Weaviate) using Docker Compose:
```bash
cd docker
cp middleware.env.example middleware.env
docker compose -f docker-compose.middleware.yaml up -d
```

#### 2. Set Up Python Environment
Create a Python 3.10 environment (recommended to use Anaconda):
```bash
conda create --name dify python=3.10
conda activate dify
```

#### 3. Configure API Service
Navigate to the "api" directory and set up the environment:
```bash
cd api
cp .env.example .env
openssl rand -base64 42 | sed -i 's/SECRET_KEY=.*/SECRET_KEY=<your_value>/' .env
pip install -r requirements.txt
flask db upgrade
flask run --host 0.0.0.0 --port=5001 --debug
```

#### 4. Configure Worker Service
Start the worker service for local async processing if needed:
```bash
celery -A app.celery worker -P gevent -c 1 -Q dataset,generation,mail --loglevel INFO
```

#### 5. Deploy Web Service
Navigate to the "web" directory, install dependencies, and start the service:
```bash
cd web
npm install
cp .env.example .env.local
# Modify .env.local as needed
npm run build
npm run start
```

### Cloud Run Deployment

#### Environment Variables
Set the following environment variables for Cloud SQL and Memorystore:

**Database Configuration (Cloud SQL)**
```bash
DB_USERNAME=<your-db-username>
DB_PASSWORD=<your-db-password>
DB_HOST=<your-cloud-sql-instance-ip>
DB_PORT=5432
DB_DATABASE=<your-database-name>
SQLALCHEMY_POOL_SIZE=30
SQLALCHEMY_POOL_RECYCLE=3600
SQLALCHEMY_ECHO=false
```

**Redis Configuration (Memorystore)**
```bash
REDIS_HOST=<your-memorystore-instance-ip>
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=<your-redis-password>
REDIS_USE_SSL=false
```

**Celery Configuration**
```bash
CELERY_BROKER_URL=redis://:<redis_password>@<redis_host>:<redis_port>/1
BROKER_USE_SSL=false
```

**Enable Migrations**
```bash
MIGRATION_ENABLED='true'
```

### Best Practices for Scaling

#### Cloud Run
Configure autoscaling based on request count or CPU utilization for each service. Example for the `api` service:
```yaml
api:
  image: langgenius/dify-api:0.6.12
  concurrency: 80
  autoscaling:
    max-instances: 10
  environment:
    SERVER_WORKER_AMOUNT: 4
```

#### GKE
Use Horizontal Pod Autoscaler (HPA) based on CPU or memory utilization. Example for the `api` service:
```yaml
api:
  image: langgenius/dify-api:0.6.12
  env:
    - name: SERVER_WORKER_AMOUNT
      value: "4"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
  hpa:
    minReplicas: 1
    maxReplicas: 10
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
```

These steps and configurations should help you deploy Dify on GCP effectively. For more detailed information, you can refer to the Dify documentation and the Docker Compose setup <sup>[[1]](https://github.com/langgenius/dify/blob/main/api/README.md)</sup><sup>[[2]](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/local-source-code.md)</sup><sup>[[3]](https://github.com/langgenius/dify-docs/blob/main/zh_CN/getting-started/install-self-hosted/environments.md)</sup><sup>[[4]](https://github.com/langgenius/dify/blob/main/docker-legacy/docker-compose.yaml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
