### DISCUSSION TITLE
How to use the Embedding Model and rerank model deployed with docker in dify

### DISCUSSION THREAD

**Discussion by MdcGIt** [langgenius/dify#6362] [General]
How to use the Embedding Model and rerank model deployed with docker in dify？

I deployed the m3e model and bge-reranker model using docker. How to integrate them into dify?

**Comment by dosubot** [comment]
Hey @MdcGIt! I'm here to help you with any questions or issues you have. I'm a bot designed to assist with bug fixes, answering questions, and guiding you on how to contribute. Let me know how I can assist you!


To integrate the `m3e` model and `bge-reranker` model, which you deployed using Docker, into Dify, follow these steps:

1. **Deploy LocalAI:**
   - Clone the LocalAI repository and navigate to the specified directory:
     ```bash
     $ git clone https://github.com/go-skynet/LocalAI
     $ cd LocalAI/examples/langchain-chroma
     ```
   - Download example LLM and Embedding models:
     ```bash
     $ wget https://huggingface.co/skeskinen/ggml/resolve/main/all-MiniLM-L6-v2/ggml-model-q4_0.bin -O models/bert
     $ wget https://gpt4all.io/models/ggml-gpt4all-j.bin -O models/ggml-gpt4all-j
     ```
   - Configure the `.env` file:
     ```shell
     $ mv .env.example .env
     ```
   - Start LocalAI:
     ```bash
     $ docker-compose up -d --build
     $ docker logs -f langchain-chroma-api-1
     ```
   - Ensure the LocalAI request API endpoint is available at `http://127.0.0.1:8080`.

2. **Integrate Models into Dify:**
   - Go to `Settings > Model Providers > LocalAI` in Dify.
   - For the `ggml-gpt4all-j` model:
     - Model Type: Text Generation
     - Model Name: `gpt-3.5-turbo`
     - Server URL: `http://127.0.0.1:8080` (or the host domain if Dify is deployed via Docker)
   - For the `all-MiniLM-L6-v2` model:
     - Model Type: Embeddings
     - Model Name: `text-embedding-ada-002`
     - Server URL: `http://127.0.0.1:8080` (or the host domain if Dify is deployed via Docker)
   - Click "Save" to use the models in the application.

3. **Configure the Rerank Model:**
   - Go to the "Model Provider" section in Dify.
   - Ensure the `bge-reranker` model is properly set up and accessible.

4. **Set the Rerank Model in the Dataset:**
   - Navigate to "Dataset -> Create Dataset -> Retrieval Settings".
   - Add the Rerank settings by specifying the `bge-reranker` model.
   - You can also change the Rerank configuration in the settings of an already created dataset.

5. **Enable Multi-Path Recall Mode:**
   - Go to "Prompt Orchestration -> Context -> Settings".
   - Set the recall mode to Multi-Path Recall and enable the Rerank model.

Here is a summary of the steps in code format:

```yaml
# Step 1: Configure the Rerank Model
model_provider:
  - name: "Local Rerank Model"
    type: "bge-reranker"
    endpoint: "http://localhost:your_reranker_port"

# Step 2: Set the Rerank Model in the Dataset
dataset:
  - name: "Your Dataset"
    retrieval_settings:
      rerank_model: "bge-reranker"
      top_k: 10
      score_threshold: 0.5

# Step 3: Enable Multi-Path Recall Mode
prompt_orchestration:
  context:
    settings:
      recall_mode: "Multi-Path Recall"
      rerank_model: "bge-reranker"
```

Ensure that your `m3e` model is also properly integrated and accessible within your application context settings.

By following these steps, you can effectively integrate the `m3e` and `bge-reranker` models into Dify, ensuring a robust and efficient knowledge base application <sup>[[1]](https://github.com/langgenius/dify-docs/blob/main/en/guides/knowledge-base/integrate-knowledge-within-application.md)</sup><sup>[[2]](https://github.com/langgenius/dify-docs/blob/main/zh_CN/guides/knowledge-base/integrate_knowledge_within_application.md)</sup><sup>[[3]](https://github.com/langgenius/dify/blob/main/api/tests/integration_tests/model_runtime/localai/test_rerank.py)</sup><sup>[[4]](https://github.com/langgenius/dify-docs/blob/main/en/guides/model-configuration/localai.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
