### DISCUSSION TITLE
Vector database connection error

### DISCUSSION THREAD

**Discussion by yourengod** [langgenius/dify#7142] [Help]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

latest

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

Follow this address "https://docs.dify.ai/v/zh-hans/getting-started/install-self-hosted/local-source-code" to install. When creating a knowledge base, an error is reported after submitting the file: [2024-08-09 07:38:43,041: INFO/MainProcess] Vector database connection error; the vector database used is bge-m3. 

### ✔️ Expected Behavior

What should I do?

### ❌ Actual Behavior

What should I do?

**Comment by dosubot** [comment]
To resolve the vector database connection error when creating a knowledge base with the bge-m3 database in your self-hosted Dify setup, follow these steps:

1. **Modify Environment Variables:**
   Ensure that the environment variables are correctly set for the bge-m3 vector database. Update the `.env` file or `docker-compose.yaml` file with the following settings:

   ```env
   VECTOR_STORE=milvus
   MILVUS_HOST=your-milvus-host
   MILVUS_PORT=your-milvus-port
   MILVUS_USER=your-milvus-username
   MILVUS_PASSWORD=your-milvus-password
   MILVUS_SECURE=false
   ```

   Replace `your-milvus-host`, `your-milvus-port`, `your-milvus-username`, and `your-milvus-password` with the actual values for your Milvus instance.

2. **Run the Migration Command:**
   Execute the following command in your terminal or Docker container to migrate the data in the vector database:

   ```bash
   flask vdb-migrate
   ```

   Or if you are using Docker:

   ```bash
   docker exec -it docker-api-1 flask vdb-migrate
   ```

3. **Check the Health of the Vector Database:**
   Ensure that the vector database service is running and healthy. For example, if you are using Docker Compose, you can check the health status defined in the `docker-compose.yaml` file:

   ```yaml
   healthcheck:
     test: [ "CMD", "pg_isready" ]
     interval: 1s
     timeout: 3s
     retries: 30
   ```

   Here is an example configuration for the vector database service in `docker-compose.yaml`:

   ```yaml
   services:
     pgvector:
       image: pgvector/pgvector:pg16
       restart: always
       environment:
         PGUSER: postgres
         POSTGRES_PASSWORD: difyai123456
         POSTGRES_DB: dify
         PGDATA: /var/lib/postgresql/data/pgdata
       volumes:
         - ./volumes/pgvector/data:/var/lib/postgresql/data
       ports:
         - "5433:5432"
       healthcheck:
         test: [ "CMD", "pg_isready" ]
         interval: 1s
         timeout: 3s
         retries: 30
   ```

By following these steps, you should be able to resolve the vector database connection error and ensure that the bge-m3 vector database is correctly configured and accessible from the Dify application <sup>[[1]](https://github.com/langgenius/dify-docs/blob/main/en/getting-started/install-self-hosted/install-faq.md)</sup><sup>[[2]](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml)</sup><sup>[[3]](https://github.com/langgenius/dify/blob/main/docker-legacy/docker-compose.pgvector.yaml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
