### DISCUSSION TITLE
tools development problems

### DISCUSSION THREAD

**Discussion by janglichao** [langgenius/dify#8212] [Help]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

when I follow the “Quick Tool Integration” doc to created my tools，it just cannot find my tools in tools list，can you guys help  me ？

**Comment by dosubot** [comment]
Hello @janglichao! I'm here to help you with any bugs, questions, or contributions. Let's work together to resolve the issue you're facing.


I found 2 similar unsolved discussions that might be relevant to your issue:
1. [Why this not work](https://github.com/langgenius/dify/discussions/8006) which was last updated on 2024-09-05.
2. [Dify API Extension application issue?](https://github.com/langgenius/dify/discussions/3621) which was last updated on 2024-04-19.

If you cannot find your tools in the tools list after following the “Quick Tool Integration” documentation, it is likely because you missed one or more of the following steps:

1. **Ensure the YAML files are correctly named and placed**:
   - The `google.yaml` file should be placed under `core/tools/provider/builtin/google/`.
   - The `google_search.yaml` file should be placed under `core/tools/provider/builtin/google/tools/`.

2. **Check the `identity` fields**:
   - Ensure that the `identity` fields in both `google.yaml` and `google_search.yaml` are correctly filled out and match the required format.

3. **Verify the icon placement**:
   - The icon specified in the `google.yaml` file should be placed in the `_assets` folder of the `google` module.

4. **Credential configuration**:
   - If your tool requires credentials, ensure that the `credentials_for_provider` field is correctly configured in the `google.yaml` file.

5. **Provider and tool logic implementation**:
   - Ensure that the `GoogleSearchTool` class and the `GoogleProvider` class are correctly implemented and placed in the appropriate directories.

Here is a checklist to verify:

- `core/tools/provider/builtin/google/google.yaml`:
  ```yaml
  identity:
    author: Dify
    name: google
    label:
      en_US: Google
      zh_Hans: Google
    description:
      en_US: Google
      zh_Hans: Google
    icon: icon.svg
  credentials_for_provider:
    serpapi_api_key:
      type: secret-input
      required: true
      label:
        en_US: SerpApi API key
        zh_Hans: SerpApi API key
      placeholder:
        en_US: Please input your SerpApi API key
        zh_Hans: 请输入你的 SerpApi API key
      help:
        en_US: Get your SerpApi API key from SerpApi
        zh_Hans: 从 SerpApi 获取您的 SerpApi API key
      url: https://serpapi.com/manage-api-key
  ```

- `core/tools/provider/builtin/google/tools/google_search.yaml`:
  ```yaml
  identity:
    name: google_search
    author: Dify
    label:
      en_US: GoogleSearch
      zh_Hans: 谷歌搜索
  description:
    human:
      en_US: A tool for performing a Google SERP search and extracting snippets and webpages. Input should be a search query.
      zh_Hans: 一个用于执行 Google SERP 搜索并提取片段和网页的工具。输入应该是一个搜索查询。
    llm: A tool for performing a Google SERP search and extracting snippets and webpages. Input should be a search query.
  parameters:
    - name: query
      type: string
      required: true
      label:
        en_US: Query string
        zh_Hans: 查询语句
      human_description:
        en_US: used for searching
        zh_Hans: 用于搜索网页内容
      llm_description: key words for searching
      form: llm
    - name: result_type
      type: select
      required: true
      options:
        - value: text
          label:
            en_US: text
            zh_Hans: 文本
        - value: link
          label:
            en_US: link
            zh_Hans: 链接
      default: link
      label:
        en_US: Result type
        zh_Hans: 结果类型
      human_description:
        en_US: used for selecting the result type, text or link
        zh_Hans: 用于选择结果类型，使用文本还是链接进行展示
      form: form
  ```

- Ensure the icon is placed at `core/tools/provider/builtin/google/_assets/icon.svg`.

- Implement the `GoogleSearchTool` and `GoogleProvider` classes as described in the documentation.

If all these steps are correctly followed, your tools should appear in the tools list <sup>[[1]](https://github.com/langgenius/dify-docs/blob/main/en/guides/tools/quick-tool-integration.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
