### DISCUSSION TITLE
Sandbox service start

### DISCUSSION THREAD

**Discussion by muckthaa-ss** [langgenius/dify#8520] [Help]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

In my local server i update all the necessary url for code execution in env file but how sandbox service is running in 8194 port how to start the sandbox service in specific Ip and port and verify 

### ✔️ Expected Behavior

code Execution in workflow to get proper output

### ❌ Actual Behavior

timeout error

**Comment by dosubot** [comment]
I found a similar closed issue that might help you. The issue was about the sandbox service listening on a random port instead of the specified 8194 port when deployed on Kubernetes. The suggested solution was to use a "Headless service" and set the `SANDBOX_PORT` environment variable. You can find the detailed solution [here](https://github.com/langgenius/dify/issues/3532) <sup>[[1]](https://github.com/langgenius/dify/issues/3532)</sup>.

To start the sandbox service on a specific IP and port and verify it, you can modify the `docker-compose.yaml` file as follows:

1. **Modify the `docker-compose.yaml` file:**
   Update the `sandbox` service configuration to expose the desired port and bind it to a specific IP address. For example, if you want to bind the sandbox service to IP `192.168.1.100` and port `8200`, you can modify the `ports` section as follows:

   ```yaml
   sandbox:
     image: langgenius/dify-sandbox:0.2.1
     restart: always
     environment:
       API_KEY: dify-sandbox
       GIN_MODE: 'release'
       WORKER_TIMEOUT: 15
       ENABLE_NETWORK: 'true'
       HTTP_PROXY: 'http://ssrf_proxy:3128'
       HTTPS_PROXY: 'http://ssrf_proxy:3128'
       SANDBOX_PORT: 8200
     volumes:
       - ./volumes/sandbox/dependencies:/dependencies
     networks:
       - ssrf_proxy_network
     ports:
       - "192.168.1.100:8200:8200"
   ```

2. **Verify the sandbox service:**
   After modifying the `docker-compose.yaml` file, restart the Docker services to apply the changes:

   ```sh
   docker-compose down
   docker-compose up -d
   ```

3. **Check if the sandbox service is running on the specified IP and port:**
   You can verify if the sandbox service is running on the specified IP and port by using `curl` or any other HTTP client:

   ```sh
   curl http://192.168.1.100:8200
   ```

   If the service is running correctly, you should receive a response from the sandbox service <sup>[[2]](https://github.com/langgenius/dify/blob/main/docker-legacy/docker-compose.yaml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
