### ISSUE TITLE
Upgrade to version 0.10.2 failed

### ISSUE THREAD

**Issue by murtaza-motorwala** [langgenius/dify#10263]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

[web-1.txt](https://github.com/user-attachments/files/17621614/web-1.txt)

Please see attached log. All the containers came up and running but the docker-web-1 has errors. I get a 502 Bad gateway when I try to access the console. 

### ✔️ Expected Behavior

It should load the homepage at localhost:3000

### ❌ Actual Behavior

I get a 502 Bad gateway when I try to access the console.

**Comment by damadorPL** [comment]
2024-11-04 21:01:02 Error: ENOSPC: no space left on device, mkdir   - you server is full ?

**Comment by crazywoola** [comment]
This logs is pretty straightforward, you are running out of the disk spaces.

**Comment by nadilas** [comment]
@murtaza-motorwala Adding volumes to the web container in the docker-compose file solved it for me:

```
  # Frontend web application.
  web:
    image: langgenius/dify-web:0.15.3
    restart: always
    environment:
      CONSOLE_API_URL: ${CONSOLE_API_URL:-}
      APP_API_URL: ${APP_API_URL:-}
      SENTRY_DSN: ${WEB_SENTRY_DSN:-}
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED:-0}
      TEXT_GENERATION_TIMEOUT_MS: ${TEXT_GENERATION_TIMEOUT_MS:-60000}
      CSP_WHITELIST: ${CSP_WHITELIST:-}
      TOP_K_MAX_VALUE: ${TOP_K_MAX_VALUE:-}
      INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH: ${INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH:-}
    volumes:
      - ./volumes/web/.pm2:/.pm2/
```
