### ISSUE TITLE
parallel iteration bug report

### ISSUE THREAD

**Issue by 143230** [langgenius/dify#10572]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

when running http request in a iteration parallel, it got error:Reached maximum retries (3) for URL https://www.runoob.com/test/demo_form.php

this is the log:
2024-11-12 03:39:27,387.387 WARNING [ThreadPoolExecutor-101_1] [ssrf_proxy.py:54] - Request to URL https://www.runoob.com/test/demo_form.php failed on attempt 2: [Errno 9] File descriptor was closed in another greenlet

this is the yaml config:

```
app:
  description: 测试替换根据主题检索关联资讯
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: 报告生成工作流_20241112_cuixuan
  use_icon_as_answer_icon: false
kind: app
version: 0.1.3
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: code
        targetType: iteration
      id: 1730346539705-source-1731381770656-target
      selected: false
      source: '1730346539705'
      sourceHandle: source
      target: '1731381770656'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: iteration
        targetType: end
      id: 1731381770656-source-1731381793827-target
      selected: false
      source: '1731381770656'
      sourceHandle: source
      target: '1731381793827'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1730169413286-source-1731381870748-target
      selected: false
      source: '1730169413286'
      sourceHandle: source
      target: '1731381870748'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: code
      id: 1731381870748-source-1730346539705-target
      selected: false
      source: '1731381870748'
      sourceHandle: source
      target: '1730346539705'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: true
        iteration_id: '1731381770656'
        sourceType: iteration-start
        targetType: http-request
      id: 1731381770656start-source-1731382677649-target
      source: 1731381770656start
      sourceHandle: source
      target: '1731382677649'
      targetHandle: target
      type: custom
      zIndex: 1002
    nodes:
    - data:
        desc: 输入主题和大纲(可选)
        selected: false
        title: 开始
        type: start
        variables:
        - label: 是否预定义大纲
          max_length: 48
          options:
          - 预定义(人工输入大纲)
          - 自定义(系统生成大纲)
          required: true
          type: select
          variable: has_outline
        - label: 主题报告大纲
          max_length: null
          options: []
          required: false
          type: paragraph
          variable: outline
        - label: 是否进行元搜索
          max_length: 48
          options:
          - 是
          - 否
          required: true
          type: select
          variable: is_meta_search
        - label: 初始主题
          max_length: null
          options: []
          required: true
          type: text-input
          variable: initial_topic
      height: 196
      id: '1730169413286'
      position:
        x: 30
        y: 297.5
      positionAbsolute:
        x: 30
        y: 297.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        author: admin
        desc: ''
        height: 88
        selected: false
        showAuthor: false
        text: '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"转换格式，并与原关键词检索相关内容合并","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'
        theme: blue
        title: ''
        type: ''
        width: 240
      height: 88
      id: '1730271773207'
      position:
        x: 9025.60295847669
        y: 370.18897048412254
      positionAbsolute:
        x: 9025.60295847669
        y: 370.18897048412254
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom-note
      width: 240
    - data:
        author: admin
        desc: ''
        height: 88
        selected: false
        showAuthor: false
        text: '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"转换格式，并与原关键词搜索的相关内容合并","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1,"textFormat":0}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}'
        theme: blue
        title: ' (1)'
        type: ''
        width: 240
      height: 88
      id: '17302727232850'
      position:
        x: 9017.592958164108
        y: 775.395527452795
      positionAbsolute:
        x: 9017.592958164108
        y: 775.395527452795
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom-note
      width: 240
    - data:
        code: "def main(trans_topic_str: str, initial_topic: str) -> dict:\n    trans_topic_str\
          \ = trans_topic_str.strip()\n    trans_topics = trans_topic_str.split(\"\
          \\n\")\n    # 使用 lambda 表达式筛选非空行\n    trans_topics = list(filter(lambda\
          \ topic: topic.strip()!= \"\", trans_topics))\n    # 对筛选后的列表中的每个元素进行去除空格操作\n\
          \    return {\n        \"topics\": list(map(lambda topic: topic.strip(),\
          \ trans_topics))[:9] + [initial_topic]\n    }"
        code_language: python3
        desc: 提取扩写的主题列表，与原始主题合并处理
        outputs:
          topics:
            children: null
            type: array[string]
        selected: false
        title: 提取并合并主题列表
        type: code
        variables:
        - value_selector:
          - '1730169413286'
          - initial_topic
          variable: initial_topic
        - value_selector:
          - '1731381870748'
          - trans_topic_str
          variable: trans_topic_str
      height: 98
      id: '1730346539705'
      position:
        x: 619.3051178149508
        y: 297.5
      positionAbsolute:
        x: 619.3051178149508
        y: 297.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        error_handle_mode: terminated
        height: 198
        is_parallel: true
        iterator_selector:
        - '1730346539705'
        - topics
        output_selector:
        - '1731382677649'
        - body
        output_type: array[string]
        parallel_nums: 9
        selected: false
        start_node_id: 1731381770656start
        title: 迭代
        type: iteration
        width: 388
      height: 198
      id: '1731381770656'
      position:
        x: 922.4922968503834
        y: 297.5
      positionAbsolute:
        x: 922.4922968503834
        y: 297.5
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 388
      zIndex: 1
    - data:
        desc: ''
        isInIteration: true
        selected: false
        title: ''
        type: iteration-start
      draggable: false
      height: 48
      id: 1731381770656start
      parentId: '1731381770656'
      position:
        x: 24
        y: 68
      positionAbsolute:
        x: 946.4922968503834
        y: 365.5
      selectable: false
      sourcePosition: right
      targetPosition: left
      type: custom-iteration-start
      width: 44
      zIndex: 1002
    - data:
        authorization:
          config: null
          type: no-auth
        body:
          data: []
          type: none
        desc: ''
        headers: ''
        isInIteration: true
        iteration_id: '1731381770656'
        method: post
        params: ''
        selected: false
        timeout:
          max_connect_timeout: 0
          max_read_timeout: 0
          max_write_timeout: 0
        title: HTTP 请求
        type: http-request
        url: https://www.runoob.com/test/demo_form.php
        variables: []
      height: 110
      id: '1731382677649'
      parentId: '1731381770656'
      position:
        x: 128
        y: 68
      positionAbsolute:
        x: 1050.4922968503834
        y: 365.5
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1731381770656'
          - output
          variable: test
        selected: false
        title: 结束
        type: end
      height: 90
      id: '1731381793827'
      position:
        x: 1388.3743580708651
        y: 297.5
      positionAbsolute:
        x: 1388.3743580708651
        y: 297.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(arg1: str) -> dict:\n    return {\n        \"trans_topic_str\"\
          : \"OpenAI高管离职原因分析\\nReasons Behind OpenAI Executive Departures\\nOpenAI高管离职对公司未来发展的影响\\\
          nImpact of OpenAI Executive Departure on Future Development\\nOpenAI高管离职对员工士气的影响\\\
          nEffect of OpenAI Executive Departure on Employee Morale\\nOpenAI高管离职对投资者信心的影响\\\
          nImpact of OpenAI Executive Departure on Investor Confidence\\nOpenAI高管离职对竞争对手的影响\\\
          nEffect of OpenAI Executive Departure on Competitors\\nOpenAI高管离职后的新动向\\\
          nNew Directions for Departed OpenAI Executives\\nOpenAI高管离职与公司治理结构的关系\\\
          nRelationship Between OpenAI Executive Departure and Corporate Governance\\\
          nOpenAI高管离职对中国市场的影响\\nImpact of OpenAI Executive Departure on the Chinese\
          \ Market\\nOpenAI高管离职对国际业务布局的影响\\nImpact of OpenAI Executive Departure on\
          \ International Business Strategy\"\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          trans_topic_str:
            children: null
            type: string
        selected: false
        title: 代码执行 2
        type: code
        variables:
        - value_selector:
          - '1730169413286'
          - initial_topic
          variable: arg1
      height: 54
      id: '1731381870748'
      position:
        x: 334
        y: 297.5
      positionAbsolute:
        x: 334
        y: 297.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -280.60174690457256
      y: 82.19270013409931
      zoom: 1.230283227908955
```

### ✔️ Expected Behavior

expected got http result

### ❌ Actual Behavior

wrong:  Reached maximum retries (3) for URL https://www.runoob.com/test/demo_form.php
