### ISSUE TITLE
Tool Integration Not Reflecting in UI

### ISSUE THREAD

**Issue by ibrahimcal** [langgenius/dify#10788]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Created a new tool directory structure:
```
core/tools/provider/builtin/weather/
├── _assets/
│   └── icon.svg
├── weather.yaml
├── weather.py
├── tools/
│   ├── get_current_weather.yaml
│   └── get_current_weather.py
```

2. Created provider configuration (`weather.yaml`):
```yaml
identity:
  author: User
  name: weather
  label:
    en_US: WeatherAPI.com
  description:
    en_US: Get real-time weather data using WeatherAPI.com
  icon: icon.svg

credentials_for_provider:
  api_key:
    type: secret-input
    required: true
    # ... credential configuration
```

3. Created tool configuration (`tools/get_current_weather.yaml`):
```yaml
identity:
  name: get_current_weather
  author: User
  label:
    en_US: Get Current Weather
  description:
    human:
      en_US: Get the current weather in a given location

parameters:
  - name: location
    type: string
    required: true
    # ... parameter configuration
  - name: unit
    type: select
    required: false
    options:
      - value: celsius
      - value: fahrenheit
    # ... parameter configuration
```

4. Added implementation files:
   - Created `weather.py` with `WeatherProvider` class
   - Created `get_current_weather.py` with `GetCurrentWeatherTool` class
   - Added appropriate icon in `_assets` folder

5. Restarted the Dify API container

### ✔️ Expected Behavior

- The new Weather tool should appear in the Tools UI
- Should be able to configure the API key
- Should be able to use the tool in conversations

## Additional Notes
- Followed the documentation at https://docs.dify.ai/guides/tools/quick-tool-integration
- Verified all file permissions and directory structure
- Checked docker logs for any relevant errors

### ❌ Actual Behavior

- Changes are not reflected in the Tools UI
- Cannot find the added files when checking inside the docker-api container

## Questions
1. Are there additional steps needed beyond those in the documentation?
2. Is there a specific location where custom tools should be placed in the Docker container?
3. Is there a required build/compilation step that's missing from the documentation?
