### ISSUE TITLE
Add Pixtral Large (Mistral AI)

### ISSUE THREAD

**Issue by Asterovim** [langgenius/dify#10896]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

I would like to use the new Pixtral Large (Mistral AI) with Dify : https://mistral.ai/fr/news/pixtral-large/

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.

**Comment by Asterovim** [comment]
api/core/model_runtime/model_providers/mistralai/llm/pixtral-latest.yaml
`model: pixtral-latest
label:
  zh_Hans: pixtral-latest
  en_US: pixtral-latest
model_type: llm
features:
  - agent-thought
  - vision
model_properties:
  mode: chat
  context_size: 128000
parameter_rules:
  - name: temperature
    use_template: temperature
    default: 0.7
    min: 0
    max: 1
  - name: top_p
    use_template: top_p
    default: 1
    min: 0
    max: 1
  - name: max_tokens
    use_template: max_tokens
    default: 1024
    min: 1
    max: 128000
  - name: safe_prompt
    default: false
    type: boolean
    help:
      en_US: Whether to inject a safety prompt before all conversations.
      zh_Hans: 是否开启提示词审查
    label:
      en_US: SafePrompt
      zh_Hans: 提示词审查
  - name: random_seed
    type: int
    help:
      en_US: The seed to use for random sampling. If set, different calls will generate deterministic results.
      zh_Hans: 当开启随机数种子以后，你可以通过指定一个固定的种子来使得回答结果更加稳定
    label:
      en_US: RandomSeed
      zh_Hans: 随机数种子
    default: 0
    min: 0
    max: 2147483647
pricing:
  input: '0.008'
  output: '0.024'
  unit: '0.001'
  currency: USD
`
api/core/model_runtime/model_providers/mistralai/llm/pixtral-latest.yaml
`model: pixtral-large-2411
label:
  zh_Hans: pixtral-large-2411
  en_US: pixtral-large-2411
model_type: llm
features:
  - agent-thought
  - vision
  - document
model_properties:
  mode: chat
  context_size: 128000
parameter_rules:
  - name: temperature
    use_template: temperature
    default: 0.7
    min: 0
    max: 1
  - name: top_p
    use_template: top_p
    default: 1
    min: 0
    max: 1
  - name: max_tokens
    use_template: max_tokens
    default: 1024
    min: 1
    max: 128000
  - name: safe_prompt
    default: false
    type: boolean
    help:
      en_US: Whether to inject a safety prompt before all conversations.
      zh_Hans: 是否开启提示词审查
    label:
      en_US: SafePrompt
      zh_Hans: 提示词审查
  - name: random_seed
    type: int
    help:
      en_US: The seed to use for random sampling. If set, different calls will generate deterministic results.
      zh_Hans: 当开启随机数种子以后，你可以通过指定一个固定的种子来使得回答结果更加稳定
    label:
      en_US: RandomSeed
      zh_Hans: 随机数种子
    default: 0
    min: 0
    max: 2147483647
pricing:
  input: '0.008'
  output: '0.024'
  unit: '0.001'
  currency: USD
`
api/core/model_runtime/model_providers/mistralai/llm/_position.yaml
`- pixtral-latest
- pixtral-large-2411
- pixtral-12b-2409
- codestral-latest
- mistral-embed
- open-mistral-nemo
- open-codestral-mamba
- open-mistral-7b
- open-mixtral-8x7b
- open-mixtral-8x22b
- mistral-small-latest
- mistral-medium-latest
- mistral-large-latest
`

The model work's ! Could  you please add this ?

**Comment by Asterovim** [comment]
The model work's with this files ! Could  you please add this ?

api/core/model_runtime/model_providers/mistralai/llm/_position.yaml
```
- pixtral-latest
- pixtral-large-2411
- pixtral-12b-2409
- codestral-latest
- mistral-embed
- open-mistral-nemo
- open-codestral-mamba
- open-mistral-7b
- open-mixtral-8x7b
- open-mixtral-8x22b
- mistral-small-latest
- mistral-medium-latest
- mistral-large-latest
```
api/core/model_runtime/model_providers/mistralai/llm/pixtral-large-2411.yaml
```
model: pixtral-large-2411
label:
  zh_Hans: pixtral-large-2411
  en_US: pixtral-large-2411
model_type: llm
features:
  - agent-thought
  - vision
model_properties:
  mode: chat
  context_size: 128000
parameter_rules:
  - name: temperature
    use_template: temperature
    default: 0.7
    min: 0
    max: 1
  - name: top_p
    use_template: top_p
    default: 1
    min: 0
    max: 1
  - name: max_tokens
    use_template: max_tokens
    default: 1024
    min: 1
    max: 128000
  - name: safe_prompt
    default: false
    type: boolean
    help:
      en_US: Whether to inject a safety prompt before all conversations.
      zh_Hans: 是否开启提示词审查
    label:
      en_US: SafePrompt
      zh_Hans: 提示词审查
  - name: random_seed
    type: int
    help:
      en_US: The seed to use for random sampling. If set, different calls will generate deterministic results.
      zh_Hans: 当开启随机数种子以后，你可以通过指定一个固定的种子来使得回答结果更加稳定
    label:
      en_US: RandomSeed
      zh_Hans: 随机数种子
    default: 0
    min: 0
    max: 2147483647
pricing:
  input: '0.008'
  output: '0.024'
  unit: '0.001'
  currency: USD

```
api/core/model_runtime/model_providers/mistralai/llm/pixtral-latest.yaml
```
model: pixtral-latest
label:
  zh_Hans: pixtral-latest
  en_US: pixtral-latest
model_type: llm
features:
  - agent-thought
  - vision
model_properties:
  mode: chat
  context_size: 128000
parameter_rules:
  - name: temperature
    use_template: temperature
    default: 0.7
    min: 0
    max: 1
  - name: top_p
    use_template: top_p
    default: 1
    min: 0
    max: 1
  - name: max_tokens
    use_template: max_tokens
    default: 1024
    min: 1
    max: 128000
  - name: safe_prompt
    default: false
    type: boolean
    help:
      en_US: Whether to inject a safety prompt before all conversations.
      zh_Hans: 是否开启提示词审查
    label:
      en_US: SafePrompt
      zh_Hans: 提示词审查
  - name: random_seed
    type: int
    help:
      en_US: The seed to use for random sampling. If set, different calls will generate deterministic results.
      zh_Hans: 当开启随机数种子以后，你可以通过指定一个固定的种子来使得回答结果更加稳定
    label:
      en_US: RandomSeed
      zh_Hans: 随机数种子
    default: 0
    min: 0
    max: 2147483647
pricing:
  input: '0.008'
  output: '0.024'
  unit: '0.001'
  currency: USD

```
