### ISSUE TITLE
Ineffective Redis health check implementation

### ISSUE THREAD

**Issue by shisaru292** [langgenius/dify#10898]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

The need for health check implementation was raised in issue #7961, followed by a code PR in #7962. However, the current Redis health check implementation proves to be ineffective.

When `redis-server` is started with the `--requirepass` parameter, `redis-cli `performs health checks without authentication, resulting in NOAUTH errors. Notably, unlike OOM and similar errors, NOAUTH errors return with exit code 0, causing health checks to incorrectly pass.

Current healthcheck settings in `docker-compose.middleware.yaml`:
```
  redis:
    image: redis:6-alpine
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-difyai123456}
    volumes:
      # Mount the redis data directory to the container.
      - ${REDIS_HOST_VOLUME:-./volumes/redis/data}:/data
    # Set the redis password when startup redis server.
    command: redis-server --requirepass ${REDIS_PASSWORD:-difyai123456}
    ports:
      - "${EXPOSE_REDIS_PORT:-6379}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
```

This can also be verified through docker inspect logs.
```bash
$ docker inspect --format='{{json .State.Health}}' docker-redis-1 | jq
{
  "Status": "healthy",
  "FailingStreak": 0,
  "Log": [
    {
      "Start": "2024-11-20T11:36:17.229030135+08:00",
      "End": "2024-11-20T11:36:17.327432313+08:00",
      "ExitCode": 0,
      "Output": "NOAUTH Authentication required.\n\n"
    },
    ...
  ]
}
```

This further prevents the detection of issues that would only be discoverable after a successful connection, such as OOM , server load problems.

### ✔️ Expected Behavior

The redis-cli ping command should be properly executed and validated.
