### ISSUE TITLE
知识库文件总数超出限制100？如何解决

### ISSUE THREAD

**Issue by facematter** [langgenius/dify#1103]
1.限制100是可以修改的吗？出于什么理由？会降低回复速率吗？
2.如果不能修改，那有没有好一点的文本整理方案。

**Comment by Ps7ch3** [comment]
> Hello @crazywoola - WHERE do I set this env var? Using the docker install ..

@knowsnotmuch  Just add environment variables in your docker-compose.yaml

```
❯ head docker-compose.yaml
version: '3.1'
services:
  # API service
  api:
    image: langgenius/dify-api:0.3.30
    restart: always
    environment:
      TENANT_DOCUMENT_COUNT: 1000
```
