### ISSUE TITLE
Node Limit Error: "Maximum limit per branch is 50 nodes" when Publishing (2)

### ISSUE THREAD

**Issue by WarriorMama777** [langgenius/dify#11381]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hi, Dosu!
There is an issue with the same name, Node Limit Error: "Maximum limit per branch is 50 nodes" when Publishing, but it has not been resolved yet, so please reply.

### Issue Description
When attempting to publish my application in Dify, I encountered an error message stating "Maximum limit per branch is 50 nodes". This prevents me from publishing the application successfully.

### Environment
- Deployment Method: Docker (Local deployment)
- Installation Type: Self-hosted
- DifyVersion: Version 0.10.1

### Current workflow
The current workflow is relatively large and complex.
![](https://i.imgur.com/F8a0WPV.jpeg)

### Expected Behavior
Being able to publish the application without encountering the node limit error.

### Current Behavior
Receiving an error message about node limit (50 nodes per branch), which blocks the publishing process.

### What I've Tried
In previous cases with other limitations, I was able to modify restrictions by editing the `docker-compose.yaml` file (such as adjusting `TEMPLATE_TRANSFORM_MAX_LENGTH`). However, I cannot find any configuration option related to this node limit restriction.

### Additional Information
- This issue occurred during the publishing step
- Using local Docker deployment setup
- Already checked docker-compose configuration options

### Questions
1. Is this a known limitation for self-hosted deployments?
2. Are there any workarounds or solutions to handle more than 50 nodes?
3. Is this limit configurable in the settings or through environment variables?
4. If configurable, which specific setting should be modified in the docker-compose file?

Any assistance or clarification would be greatly appreciated.

____

# Additional Information

> To work around this issue in a self-hosted Dify setup using Docker, you can manually adjust the node limit by modifying the MAX_TREE_DEPTH in the web/app/components/workflow/constants.ts file. The default value is set to 50, but you can increase it to accommodate more complex workflows.

I confirmed that the relevant entry exists in dify\web\app\components\workflow\constants.ts.
I made the following change:
`export const MAX_TREE_DEPTH = 50`
↓
`export const MAX_TREE_DEPTH = 200`

After that, I tried the following Docker operations, but I'm still getting the error "Maximum limit per branch is 50 nodes", suggesting that the modification to constants.ts hasn't been reflected.
```
docker compose down
docker compose up -d
```
How can I make these changes take effect?

**Comment by WarriorMama777** [comment]
@dosu
Thank you Dosu.
Please do not close the issue as I want to see if the error is resolved.

**Comment by WarriorMama777** [comment]
@dosu
docker compose build
When I run it, I get the following: What should I do?
```
docker compose build
time="2024-12-05T15:34:29+09:00" level=warning msg="The \"CERTBOT_EMAIL\" variable is not set. Defaulting to a blank string."
time="2024-12-05T15:34:29+09:00" level=warning msg="The \"CERTBOT_DOMAIN\" variable is not set. Defaulting to a blank string."
```

**Comment by clickflow1** [comment]
> I found a similar unsolved discussion titled "Node Limit Error: 'Maximum limit per branch is 50 nodes' when Publishing" [[1]](https://github.com/langgenius/dify/discussions/11363).
> 
> To address the issue you're facing, ensure that after modifying the `MAX_TREE_DEPTH` in `web/app/components/workflow/constants.ts`, you rebuild the Docker image to apply the changes. Here are the steps you should follow:
> 
> 1. **Rebuild the Docker Image**: After making changes to the source code, you need to rebuild the Docker image to ensure the changes are included. You can do this by running:
>    ```shell
>    docker compose build
>    ```
> 2. **Restart the Docker Containers**: Once the image is rebuilt, restart the containers to apply the changes:
>    ```shell
>    docker compose down
>    docker compose up -d
>    ```
> 
> These steps should help ensure that your changes to `MAX_TREE_DEPTH` are reflected in the running application. If the issue persists, double-check that the file path and the changes are correct, and ensure there are no caching mechanisms interfering with the update.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

Didn't work for me, any other solutions?

**Comment by clickflow1** [comment]
> I found a similar unsolved discussion titled "Node Limit Error: 'Maximum limit per branch is 50 nodes' when Publishing" [[1]](https://github.com/langgenius/dify/discussions/11363).
> 
> To address the issue you're facing, ensure that after modifying the `MAX_TREE_DEPTH` in `web/app/components/workflow/constants.ts`, you rebuild the Docker image to apply the changes. Here are the steps you should follow:
> 
> 1. **Rebuild the Docker Image**: After making changes to the source code, you need to rebuild the Docker image to ensure the changes are included. You can do this by running:
>    ```shell
>    docker compose build
>    ```
> 2. **Restart the Docker Containers**: Once the image is rebuilt, restart the containers to apply the changes:
>    ```shell
>    docker compose down
>    docker compose up -d
>    ```
> 
> These steps should help ensure that your changes to `MAX_TREE_DEPTH` are reflected in the running application. If the issue persists, double-check that the file path and the changes are correct, and ensure there are no caching mechanisms interfering with the update.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

@dosu Didn't work for me, any other solutions?

**Comment by WarriorMama777** [comment]
After some time has passed, I've been investigating by interacting with Dosu on NotebookLM and forked Dify repositories, and as a result, I managed to get Dify working by circumventing the restrictions. Below, I'll show you methods for circumventing/mitigating various restrictions, including Issue titles, for your reference.

# Maximum limit per branch is 50 nodes
You can manually adjust the node limit by modifying MAX_TREE_DEPTH in the web/app/components/workflow/constants.ts file. While the default value is set to 50, you can increase this value to accommodate more complex workflows. After modifying constants.ts, you'll need to rebuild the frontend application and create a new Docker image to reflect these changes. In the docker-compose.yaml file, the web section specifies using a fixed Docker image langgenius/dify-web:0.13.1 to launch the frontend application. Here's how to instruct docker-compose to use your rebuilt frontend instead of the fixed image:

1. First, modify the web service configuration as follows:

```yaml
  # Frontend web application.
  web:
      build:
        context: ../web  # Path to directory containing Dockerfile
        dockerfile: Dockerfile  # Name of the Dockerfile to use
      restart: always
      environment:
        CONSOLE_API_URL: ${CONSOLE_API_URL:-}
        APP_API_URL: ${APP_API_URL:-}
        SENTRY_DSN: ${WEB_SENTRY_DSN:-}
        NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED:-0}
        TEXT_GENERATION_TIMEOUT_MS: ${TEXT_GENERATION_TIMEOUT_MS:-60000}
        CSP_WHITELIST: ${CSP_WHITELIST:-}
```

Key changes:
- Removed `image: langgenius/dify-web:0.13.2`
- Added `build` section specifying local build configuration

2. Steps to apply changes:
※Execute these commands in the directory containing docker-compose.yml
```bash
# 1. First, stop existing containers
docker-compose down

# 2. Rebuild web container
docker-compose build web

# 3. Start all services
docker-compose up -d
```

# Parallel nesting layer limit of 3 layers
I encountered a similar limitation with "Parallel nesting layer limit of 3 layers," so I'll document it here.

In dify\web\app\components\workflow\constants.ts
After changing this limit restriction and running `docker-compose build web`, it can run without restrictions.
```ts
export const PARALLEL_DEPTH_LIMIT = 3
```
↓
```ts
export const PARALLEL_DEPTH_LIMIT = 6
```

# Exceeds 3 layers of parallel
I also encountered another similar limit restriction: "Exceeds 3 layers of parallel."

Around Dify version v0.14, this value became configurable through
WORKFLOW_PARALLEL_DEPTH_LIMIT=3
in the .env file, but I'll document the removal method for previous versions as well.

Here are the complete steps to relax Dify's "Exceeds 3 layers of parallel" restriction:

1. First, edit `api/core/workflow/graph_engine/entities/graph.py`:
```python
        # Check if it exceeds N layers of parallel
        for parallel in parallel_mapping.values():
            if parallel.parent_parallel_id:
                cls._check_exceed_parallel_limit(
                    parallel_mapping=parallel_mapping,
                    level_limit=5,  # Changed from 3 to 5 (adjustable as needed)
                    parent_parallel_id=parallel.parent_parallel_id
                )
```

2. Modify the `api` and `worker` services in `docker/docker-compose.yaml` as follows:
```yaml
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    restart: always
    environment:
      <<: *shared-api-worker-env
      MODE: api
    depends_on:
      - db
      - redis
    volumes:
      - ./volumes/app/storage:/app/api/storage
    networks:
      - ssrf_proxy_network
      - default

  worker:
    build:
      context: ../api
      dockerfile: Dockerfile
    restart: always
    environment:
      <<: *shared-api-worker-env
      MODE: worker
    depends_on:
      - db
      - redis
    volumes:
      - ./volumes/app/storage:/app/api/storage
    networks:
      - ssrf_proxy_network
      - default
```

3. Execute the following commands in order to apply the changes:
```bash
# Navigate to dify/docker directory
cd dify/docker

# Stop existing containers
docker-compose down

# Build new images (without using cache)
docker-compose build --no-cache api worker

# Start containers
docker-compose up -d
```

Important notes:
- It's recommended to create a backup before proceeding
- Keep a backup of the original `docker-compose.yaml` for safety
- Data in database and Redis is preserved in `volumes` directory even after `docker-compose down`
- This modification changes a limitation intentionally set by Dify developers, so there might be unexpected consequences

Following these steps, you can run Dify with the parallel layer limit changed from 3 to 5 (or your specified value).

**Comment by WarriorMama777** [comment]
After some time has passed, I've been investigating by interacting with Dosu on NotebookLM and forked Dify repositories, and as a result, I managed to get Dify working by circumventing the restrictions. Below, I'll show you methods for circumventing/mitigating various restrictions, including Issue titles, for your reference.

# Maximum limit per branch is 50 nodes
You can manually adjust the node limit by modifying MAX_TREE_DEPTH in the web/app/components/workflow/constants.ts file. While the default value is set to 50, you can increase this value to accommodate more complex workflows. After modifying constants.ts, you'll need to rebuild the frontend application and create a new Docker image to reflect these changes. In the docker-compose.yaml file, the web section specifies using a fixed Docker image langgenius/dify-web:0.13.1 to launch the frontend application. Here's how to instruct docker-compose to use your rebuilt frontend instead of the fixed image:

1. First, modify the web service configuration as follows:

```yaml
  # Frontend web application.
  web:
      build:
        context: ../web  # Path to directory containing Dockerfile
        dockerfile: Dockerfile  # Name of the Dockerfile to use
      restart: always
      environment:
        CONSOLE_API_URL: ${CONSOLE_API_URL:-}
        APP_API_URL: ${APP_API_URL:-}
        SENTRY_DSN: ${WEB_SENTRY_DSN:-}
        NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED:-0}
        TEXT_GENERATION_TIMEOUT_MS: ${TEXT_GENERATION_TIMEOUT_MS:-60000}
        CSP_WHITELIST: ${CSP_WHITELIST:-}
```

Key changes:
- Removed `image: langgenius/dify-web:0.13.2`
- Added `build` section specifying local build configuration

2. Steps to apply changes:
※Execute these commands in the directory containing docker-compose.yml
```bash
# 1. First, stop existing containers
docker-compose down

# 2. Rebuild web container
docker-compose build web

# 3. Start all services
docker-compose up -d
```

# Parallel nesting layer limit of 3 layers
I encountered a similar limitation with "Parallel nesting layer limit of 3 layers," so I'll document it here.

In dify\web\app\components\workflow\constants.ts
After changing this limit restriction and running `docker-compose build web`, it can run without restrictions.
```ts
export const PARALLEL_DEPTH_LIMIT = 3
```
↓
```ts
export const PARALLEL_DEPTH_LIMIT = 6
```

# Exceeds 3 layers of parallel
I also encountered another similar limit restriction: "Exceeds 3 layers of parallel."

Around Dify version v0.14, this value became configurable through
WORKFLOW_PARALLEL_DEPTH_LIMIT=3
in the .env file, but I'll document the removal method for previous versions as well.

Here are the complete steps to relax Dify's "Exceeds 3 layers of parallel" restriction:

1. First, edit `api/core/workflow/graph_engine/entities/graph.py`:
```python
        # Check if it exceeds N layers of parallel
        for parallel in parallel_mapping.values():
            if parallel.parent_parallel_id:
                cls._check_exceed_parallel_limit(
                    parallel_mapping=parallel_mapping,
                    level_limit=5,  # Changed from 3 to 5 (adjustable as needed)
                    parent_parallel_id=parallel.parent_parallel_id
                )
```

2. Modify the `api` and `worker` services in `docker/docker-compose.yaml` as follows:
```yaml
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    restart: always
    environment:
      <<: *shared-api-worker-env
      MODE: api
    depends_on:
      - db
      - redis
    volumes:
      - ./volumes/app/storage:/app/api/storage
    networks:
      - ssrf_proxy_network
      - default

  worker:
    build:
      context: ../api
      dockerfile: Dockerfile
    restart: always
    environment:
      <<: *shared-api-worker-env
      MODE: worker
    depends_on:
      - db
      - redis
    volumes:
      - ./volumes/app/storage:/app/api/storage
    networks:
      - ssrf_proxy_network
      - default
```

3. Execute the following commands in order to apply the changes:
```bash
# Navigate to dify/docker directory
cd dify/docker

# Stop existing containers
docker-compose down

# Build new images (without using cache)
docker-compose build --no-cache api worker

# Start containers
docker-compose up -d
```

Important notes:
- It's recommended to create a backup before proceeding
- Keep a backup of the original `docker-compose.yaml` for safety
- Data in database and Redis is preserved in `volumes` directory even after `docker-compose down`
- This modification changes a limitation intentionally set by Dify developers, so there might be unexpected consequences

Following these steps, you can run Dify with the parallel layer limit changed from 3 to 5 (or your specified value).
