### ISSUE TITLE
The openrouter's openai model all reports errors, such as o1 preview, gpt-4o,   Choosing the calude model is normal

### ISSUE THREAD

**Issue by lichao4Java** [langgenius/dify#11629]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.13.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/59c28c7f-9029-4058-877d-f71c0cb15d04)

### ✔️ Expected Behavior

o1 preview, gpt-4o,   calude model is normal

### ❌ Actual Behavior

The openrouter's openai model all reports errors, such as o1 preview, gpt-4o,   Choosing the calude model is normal

**Comment by yihong0618** [comment]
> ### Self Checks
> * [x]  This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
> * [x]  I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
> * [x]  I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
> * [x]  [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
> * [x]  Please do not modify this template :) and fill in all the required fields.
> 
> ### Dify version
> 0.13.0
> 
> ### Cloud or Self Hosted
> Self Hosted (Docker)
> 
> ### Steps to reproduce
> ![image](https://private-user-images.githubusercontent.com/13230226/395442142-59c28c7f-9029-4058-877d-f71c0cb15d04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNjkyNzMsIm5iZiI6MTczNDA2ODk3MywicGF0aCI6Ii8xMzIzMDIyNi8zOTU0NDIxNDItNTljMjhjN2YtOTAyOS00MDU4LTg3N2QtZjcxYzBjYjE1ZDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA1NDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYmViMWVjZjE2MzNlNDIxYjQ0Y2UyYzEyMjk1YzI4Zjc4MzExNWY3Y2FiNTU2ODJiZGEwZjQ0OTdhZmU5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JumUa5iZNwQj6jIFhAPDSraB-ppsEVpPrSTRX8uDP1I)
> 
> ### ✔️ Expected Behavior
> o1 preview, gpt-4o, calude model is normal
> 
> ### ❌ Actual Behavior
> The openrouter's openai model all reports errors, such as o1 preview, gpt-4o, Choosing the calude model is normal

can you provide your dsl thanks.

**Comment by lichao4Java** [comment]
> > ### 自我检查
> > 
> > * [x]   这仅用于错误报告，如果您想提问，请前往[讨论](https://github.com/langgenius/dify/discussions/categories/general)。
> > * [x]   我已经搜索了现有[问题](https://github.com/langgenius/dify/issues)，包括已关闭的问题。
> > * [x]   我确认我使用英语提交此报告（我已阅读并同意[语言政策](https://github.com/langgenius/dify/issues/1542)）。
> > * [x]   [对于中国用户]请务必使用英文提交Issue，否则会被关闭。谢谢！:)
> > * [x]   请不要修改此模板:)并填写所有必填字段。
> > 
> > ### 区分版本
> > 0.13.0
> > ### 云或自托管
> > 自托管（Docker）
> > ### 重现步骤
> > ![图像](https://private-user-images.githubusercontent.com/13230226/395442142-59c28c7f-9029-4058-877d-f71c0cb15d04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNjkyNzMsIm5iZiI6MTczNDA2ODk3MywicGF0aCI6Ii8xMzIzMDIyNi8zOTU0NDIxNDItNTljMjhjN2YtOTAyOS00MDU4LTg3N2QtZjcxYzBjYjE1ZDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA1NDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxYmViMWVjZjE2MzNlNDIxYjQ0Y2UyYzEyMjk1YzI4Zjc4MzExNWY3Y2FiNTU2ODJiZGEwZjQ0OTdhZmU5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JumUa5iZNwQj6jIFhAPDSraB-ppsEVpPrSTRX8uDP1I)
> > ### ✔️ 预期行为
> > o1预览，gpt-4o，calude模型正常
> > ### ❌ 实际行为
> > openrouter的openai型号全部报错，比如o1 preview，gpt-4o，选择calude型号就正常了
> 
> 你能提供你的 dsl 吗，谢谢。



DSL :


```yml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: chat
  name: 测试2
  use_icon_as_answer_icon: false
kind: app
model_config:
  agent_mode:
    enabled: false
    max_iteration: 5
    strategy: react
    tools: []
  annotation_reply:
    enabled: false
  chat_prompt_config: {}
  completion_prompt_config: {}
  dataset_configs:
    datasets:
      datasets: []
    reranking_enable: true
    retrieval_model: multiple
    top_k: 4
  dataset_query_variable: ''
  external_data_tools: []
  file_upload:
    allowed_file_extensions:
    - .JPG
    - .JPEG
    - .PNG
    - .GIF
    - .WEBP
    - .SVG
    - .MP4
    - .MOV
    - .MPEG
    - .MPGA
    allowed_file_types: []
    allowed_file_upload_methods:
    - remote_url
    - local_file
    enabled: false
    image:
      detail: high
      enabled: false
      number_limits: 3
      transfer_methods:
      - remote_url
      - local_file
    number_limits: 3
  model:
    completion_params:
      stop: []
    mode: chat
    name: openai/o1-preview
    provider: openrouter
  more_like_this:
    enabled: false
  opening_statement: ''
  pre_prompt: ''
  prompt_type: simple
  retriever_resource:
    enabled: true
  sensitive_word_avoidance:
    configs: []
    enabled: false
    type: ''
  speech_to_text:
    enabled: false
  suggested_questions: []
  suggested_questions_after_answer:
    enabled: false
  text_to_speech:
    enabled: false
    language: ''
    voice: ''
  user_input_form: []
version: 0.1.4

```
