### ISSUE TITLE
Environment variable not being read correctly

### ISSUE THREAD

**Issue by Hsnico** [langgenius/dify#12245]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.14.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I defined an environment variable test, but using {{ test }} in the template transform module outputs None. However, clicking "Preview" correctly outputs the environment variable. The issue can also be reproduced when imported into cloud.dify.ai. 

![20241231_101011](https://github.com/user-attachments/assets/7fa163ed-d33f-4b32-bd89-ba5b347e43cb)

![20241231_100813](https://github.com/user-attachments/assets/fe5ce163-1774-4e91-8174-520ece066284)

Below is my DSL file:
``` yaml
app:
  description: ''
  icon: scream
  icon_background: '#FBE8FF'
  mode: advanced-chat
  name: env 测试
  use_icon_as_answer_icon: false
kind: app
version: 0.1.4
workflow:
  conversation_variables: []
  environment_variables:
  - description: ''
    id: ccc16253-c3d3-4b61-8f8c-e4fc438f5736
    name: test
    selector:
    - env
    - test
    value: 0.2
    value_type: number
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 300
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: template-transform
      id: 1726016536373-source-1735608577569-target
      source: '1726016536373'
      sourceHandle: source
      target: '1735608577569'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: template-transform
        targetType: answer
      id: 1735608577569-source-1735608998560-target
      source: '1735608577569'
      sourceHandle: source
      target: '1735608998560'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables: []
      height: 53
      id: '1726016536373'
      position:
        x: 75.960028937022
        y: 390.5
      positionAbsolute:
        x: 75.960028937022
        y: 390.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        selected: false
        template: '{{ test }}'
        title: 模板转换
        type: template-transform
        variables:
        - value_selector:
          - env
          - test
          variable: test
      height: 53
      id: '1735608577569'
      position:
        x: 379.3007823245152
        y: 390.5
      positionAbsolute:
        x: 379.3007823245152
        y: 390.5
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#1735608577569.output#}}'
        desc: ''
        selected: false
        title: 直接回复
        type: answer
        variables: []
      height: 102
      id: '1735608998560'
      position:
        x: 683.3007823245152
        y: 390.5
      positionAbsolute:
        x: 683.3007823245152
        y: 390.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -34.16463674531542
      y: 43.11802507751344
      zoom: 0.8185322195299809
```

### ✔️ Expected Behavior

output `0.2`

### ❌ Actual Behavior

output `None`
