### ISSUE TITLE
Restore a workflow breaks its environment variables of "secret" type

### ISSUE THREAD

**Issue by JokerQyou** [langgenius/dify#12255]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Import this test workflow:

```yaml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: debug
  use_icon_as_answer_icon: false
kind: app
version: 0.1.2
workflow:
  conversation_variables: []
  environment_variables:
  - description: ''
    id: 9ff0fefe-d87a-444e-bbe7-92bd249afbc7
    name: test1
    value: '1234567890'
    value_type: secret
  features:
    file_upload: {}
    opening_statement: ''
    sensitive_word_avoidance:
      enabled: false
    suggested_questions: []
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1735620845790-source-1735620851338-target
      source: '1735620845790'
      sourceHandle: source
      target: '1735620851338'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: end
      id: 1735620851338-source-1735620972591-target
      source: '1735620851338'
      sourceHandle: source
      target: '1735620972591'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables: []
      height: 54
      id: '1735620845790'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(test1: str) -> dict:\n    return {\n        \"result\":\
          \ 'Yes, env var secret matches expected value' if test1 == '1234567890'\
          \ else 'No, env var secret does not match',\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: Code
        type: code
        variables:
        - value_selector:
          - env
          - test1
          variable: test1
      height: 54
      id: '1735620851338'
      position:
        x: 384
        y: 282
      positionAbsolute:
        x: 384
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1735620851338'
          - result
          variable: result
        selected: false
        title: End
        type: end
      height: 90
      id: '1735620972591'
      position:
        x: 688
        y: 282
      positionAbsolute:
        x: 688
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 668
      y: 28
      zoom: 1

```

You can see the `test1` secret is valued `1234567890` in DSL.
Publish this workflow.
Run this workflow, it should say "Yes, ....".

Then make an edit, for example, in the code node add a space at the last line.
Then click on the expand icon of "Publish" button, find "Restore" dropdown button, click it and confirm restore.

After restoring the workflow (thus reverting the last edit), publish the workflow again.
Run this workflow again, it now says "No, ...".

This is because the environment variable `test1` which is of `secret` type has changed its value when restoring the workflow to last revision. It seems that the restoration used a redacted version of the secret, changing its value from `1234567890` to `123456********90`.

### ✔️ Expected Behavior

Either of the two:

- The serect value should not change.
- The secret value should be cleared, and the user should be prompted a confirmation before restoring, and list what was cleared after having restored.

### ❌ Actual Behavior

The secret changed without any notice. This would break the workflow unexpectedly, since "secret" types are mostly used to authenticated against remote APIs.
