### ISSUE TITLE
DuckDuckGo Search Issue

### ISSUE THREAD

**Issue by KitteeRusty** [langgenius/dify#12307]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.14.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Run the DuckDuckGo test module

### ✔️ Expected Behavior

It was expect to return a normal result

### ❌ Actual Behavior

It returned to errors depending on the input
<img width="428" alt="截屏2025-01-02 17 51 15" src="https://github.com/user-attachments/assets/edf76049-16ff-40b8-a69e-765aa12ab0d8" />
<img width="414" alt="截屏2025-01-02 17 51 41" src="https://github.com/user-attachments/assets/aceff9cd-080a-4911-a244-1647be28e389" />

**Comment by byrocuy** [comment]
Hi, is there any update? I am trying to use DuckDuckGo, but I am still encountering errors.

- Sometime the error is: `Failed to invoke tool: _text_extract_json() keywords='<query>' ValueError: subsection not found`,
- Sometime it hit rate limit: `Failed to invoke tool: https://links.duckduckgo.com/d.js?q=what+is+LLM&kl=wt-wt&l=wt-wt&p=&s=0&df=&vqd=4-221686711487517880756078907173797270879&bing_market=wt-WT&ex=-1 202 Ratelimit`

![image](https://github.com/user-attachments/assets/761ada2e-9c51-4b44-9e06-6b734a789b63)
![image](https://github.com/user-attachments/assets/e798104c-d305-4ec8-be63-0636b6984ae2)

**Comment by Bae-ChangHyun** [comment]
I found solution
```bash
docker exec -it docker-api-1 /bin/bash
cd /app/api/.venv/lib/python3.12/site-packages
pip install duckduckgo-search==7.2.1
```
and restart `docker-api-1` container, it works fine

It was because of the duckducko version.

**Comment by zifeiYv** [comment]
It seems that the [version of duckduckgo-search](https://github.com/langgenius/dify/blob/main/api/pyproject.toml#L118) needs to be updated. 

7.2.1 works fine, at least. @GarfieldDai

**Comment by Hi-king** [comment]
Version 7.2.1 works fine for me as well!

As a workaround, I overridden the ENTRYPOINT and CMD instructions to update duckduckgo_search before running:

```yaml
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh"]
          args: ["-c", "poetry run pip install \"duckduckgo_search>=7.1\" && bash /entrypoint.sh"]
```

(I'm using k8s)
