### ISSUE TITLE
The Japanese PDF gets garbled when registering it as knowledge.

### ISSUE THREAD

**Issue by jin413413** [langgenius/dify#12457]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.15.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Ver. 0.15.0, Japanese PDF files display garbled text when registered as knowledge and previewed. In 0.14.2, the same files did not have garbled text when registered as knowledge. However, some Japanese PDFs do not display garbled text, so the cause is unknown.
![スクリーンショット 2025-01-07 232900](https://github.com/user-attachments/assets/d928db62-84ca-47fb-8347-4dcb6ff9a401)

### ✔️ Expected Behavior

Please ensure that the text is displayed correctly without any garbling.

**Comment by crazywoola** [comment]
Can you provide some example PDF files for testing?

**Comment by jin413413** [comment]
Although version 0.15.0 could read many Japanese PDF files, the PDF files on this specific site appear as gibberish when previewed in the knowledge feature.

https://www.nta.go.jp/publication/pamph/gensen/0024001-021.pdf

**Comment by XiaoBa-Yu** [comment]
It may be a language problem
![image](https://github.com/user-attachments/assets/28ff7fcc-8d65-4fd0-9328-4e41ccc26d15)
![image](https://github.com/user-attachments/assets/879560d4-a9ce-4f29-a098-4b2cb7539697)

**Comment by iwaim** [comment]
This problem also occurs in "Doc Extractor" block. I confirmed that it does not occur if I change back to "pypdfium2 ver.4.30.0".

![Image](https://github.com/user-attachments/assets/8cc68bd1-2da4-4e10-9e53-ddeed042a542)

sample file: https://www.nta.go.jp/publication/pamph/gensen/0024001-021.pdf
Dify version: 0.15.3 with Self Hosted (Docker)

**Comment by iwaim** [comment]
sample DSL file.

```yaml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: Japanese_PDF
  use_icon_as_answer_icon: false
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: document-extractor
      id: 1739520066113-source-1739520083193-target
      source: '1739520066113'
      sourceHandle: source
      target: '1739520083193'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: document-extractor
        targetType: end
      id: 1739520083193-source-1739520115807-target
      source: '1739520083193'
      sourceHandle: source
      target: '1739520115807'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 開始
        type: start
        variables:
        - allowed_file_extensions: []
          allowed_file_types:
          - document
          allowed_file_upload_methods:
          - local_file
          label: f
          max_length: 48
          options: []
          required: true
          type: file
          variable: f
      height: 90
      id: '1739520066113'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        is_array_file: false
        selected: false
        title: テキスト抽出ツール
        type: document-extractor
        variable_selector:
        - '1739520066113'
        - f
      height: 92
      id: '1739520083193'
      position:
        x: 80
        y: 415
      positionAbsolute:
        x: 80
        y: 415
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1739520083193'
          - text
          variable: text
        selected: false
        title: 終了
        type: end
      height: 90
      id: '1739520115807'
      position:
        x: 80
        y: 543
      positionAbsolute:
        x: 80
        y: 543
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 364
      y: -224.5
      zoom: 1
```
