### ISSUE TITLE
Value error, When using tool_choice, tools must be set.

### ISSUE THREAD

**Issue by MiyazonoKaori** [langgenius/dify#12485]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.15.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Agent cannot call tools. Except for the first conversation, it seems that the tools parameter was not included in the subsequent conversations. Model error: Value error, When using tool_choice, tools must be set.

**Comment by crazywoola** [comment]
Can you share the DSL or the screenshot of the configuration page, we need to indicate which model is used.

**Comment by MiyazonoKaori** [comment]
model: Qwen2.5-72B-Instruct 
deploy: vllm 0.6.6.post1  with --enable-auto-tool-choice --tool-call-parser hermes.
dify model config：Function calling: Tool Call, Stream function calling: not support (If set support,  will get an error regarding comma separators)

In addition, gpt-4o not have the comma separators error, but get the same error: Value error, When using tool_choice, tools must be set.

**Comment by Nduy2k** [comment]
I encountered the same issue. In version 0.14, my VLLM model worked with the streaming tool call, but in version 0.15, I am experiencing the same error.

**Comment by yihong0618** [comment]
can you provide dsl?
thank you very much

**Comment by MiyazonoKaori** [comment]
```

app:
  description: 查询NSKG全量安全知识
  icon: world_map
  icon_background: '#FFEAD5'
  mode: agent-chat
  name: 漏洞情报融合分析智能体
  use_icon_as_answer_icon: true
kind: app
model_config:
  agent_mode:
    enabled: true
    max_iteration: 5
    prompt: null
    strategy: function_call
    tools:
    - enabled: true
      isDeleted: false
      notAuthor: false
      provider_id: 992a1885-2958-4282-a4e9-21150b48e577
      provider_name: 网络搜索
      provider_type: api
      tool_label: search_network
      tool_name: search_network
      tool_parameters:
        query: ''
    - enabled: true
      isDeleted: false
      notAuthor: false
      provider_id: 3d0373af-01c1-40db-a06c-e6f44b972aea
      provider_name: url_content_fetch
      provider_type: api
      tool_label: FetchURLContent
      tool_name: FetchURLContent
      tool_parameters:
        query: ''
    - enabled: true
      isDeleted: false
      notAuthor: false
      provider_id: 3503e1f8-b08c-442c-b5df-b165a6dc2d4c
      provider_name: 攻击者查询查询
      provider_type: api
      tool_label: search_threator
      tool_name: search_threator
      tool_parameters:
        query: ''
    - enabled: true
      isDeleted: false
      notAuthor: false
      provider_id: 77a99652-ec0d-47ae-a98a-1aa8dda578e7
      provider_name: ATTCK信息查询
      provider_type: api
      tool_label: search_attck
      tool_name: search_attck
      tool_parameters:
        query: ''
    - enabled: true
      isDeleted: false
      notAuthor: false
      provider_id: 59b6447c-4bd5-4ba6-b2ee-4898c05b9a07
      provider_name: ip威胁信息查询
      provider_type: api
      tool_label: apiv2objectsip-details_get
      tool_name: apiv2objectsip-details_get
      tool_parameters:
        X-Ns-Nti-Key: ''
        query: ''
        type: ''
    - enabled: true
      isDeleted: false
      notAuthor: false
      provider_id: 1935184d-d82f-4e4c-86b1-54d14dcedc7e
      provider_name: 域名威胁信息查询
      provider_type: api
      tool_label: apiv2objectsdomain-details_get
      tool_name: apiv2objectsdomain-details_get
      tool_parameters:
        X-Ns-Nti-Key: ''
        query: ''
        type: ''
    - enabled: true
      isDeleted: false
      notAuthor: false
      provider_id: f4c1e006-ab22-4161-96a7-2bccfd74433a
      provider_name: 恶意样本威胁信息查询
      provider_type: api
      tool_label: apiv2objectssample-details_get
      tool_name: apiv2objectssample-details_get
      tool_parameters:
        X-Ns-Nti-Key: ''
        query: ''
        type: ''
    - enabled: true
      isDeleted: false
      notAuthor: false
      provider_id: 97fc3fe8-3004-4dd3-9918-8957c25e3d70
      provider_name: 漏洞检测规则
      provider_type: api
      tool_label: search_vuln_rule
      tool_name: search_vuln_rule
      tool_parameters:
        query: ''
    - enabled: true
      isDeleted: false
      notAuthor: false
      provider_id: 2db0e18e-6b4b-4951-92b6-9f7b0241b1ab
      provider_name: 漏洞POC查询
      provider_type: api
      tool_label: search_vuln_poc
      tool_name: search_vuln_poc
      tool_parameters:
        cves: ''
        fingers: ''
    - enabled: false
      isDeleted: false
      notAuthor: false
      provider_id: 6526284e-7561-439e-aef3-e7aa553c50c6
      provider_name: nscert查询工具
      provider_type: api
      tool_label: search_kg_nscert
      tool_name: search_kg_nscert
      tool_parameters:
        query: ''
  annotation_reply:
    enabled: false
  chat_prompt_config: {}
  completion_prompt_config: {}
  dataset_configs:
    datasets:
      datasets:
      - dataset:
          enabled: true
          id: 5292356a-b719-4ca6-9861-88190350edf1
    reranking_enable: true
    reranking_mode: weighted_score
    retrieval_model: multiple
    top_k: 4
    weights:
      keyword_setting:
        keyword_weight: 0
      vector_setting:
        embedding_model_name: bce-embedding-base-v1
        embedding_provider_name: openai_api_compatible
        vector_weight: 1
  dataset_query_variable: ''
  external_data_tools: []
  file_upload:
    allowed_file_extensions:
    - .JPG
    - .JPEG
    - .PNG
    - .GIF
    - .WEBP
    - .SVG
    allowed_file_types:
    - image
    allowed_file_upload_methods:
    - remote_url
    - local_file
    enabled: false
    image:
      detail: high
      enabled: false
      number_limits: 3
      transfer_methods:
      - remote_url
      - local_file
    number_limits: 3
  model:
    completion_params:
      stop: []
    mode: chat
    name: Qwen2.5-72B-Instruct
    provider: openai_api_compatible
  more_like_this:
    enabled: false
  opening_statement: ''
  pre_prompt: "You are a helpful assistant.\n\
    你需要专业、全面的完成网络安全知识查询。\n\
    \n请将答案整理成markdown格式输出。"
  prompt_type: simple
  retriever_resource:
    enabled: true
  sensitive_word_avoidance:
    configs: []
    enabled: false
    type: ''
  speech_to_text:
    enabled: false
  suggested_questions: []
  suggested_questions_after_answer:
    enabled: true
  text_to_speech:
    enabled: false
    language: ''
    voice: ''
  user_input_form: []
version: 0.1.5


```
