### ISSUE TITLE
Workflow with Parallel Nodes causes exception due to topology graph parsing issues.

### ISSUE THREAD

**Issue by Ecohnoch** [langgenius/dify#12536]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.11.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

This bug occurs in a topology graph containing parallel nodes. As shown in the image, there are three parallel paths after the start node, but two of them converge prematurely at a single node. 
![image](https://github.com/user-attachments/assets/ecf6cffb-922e-4232-b0af-56b03d4e1bdf)

In actual execution, all three paths run in parallel, causing the prematurely converged node to be executed an extra time. Additionally, it consistently fails to correctly retrieve the values from Node A and Node B. This issue may be caused by having three paths at the start of the parallel section, but only two at the end, leading to abnormal execution behavior.

dsl: 
```yaml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: Test
  use_icon_as_answer_icon: false
kind: app
version: 0.1.3
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1736400777889-source-1736400781647-target
      source: '1736400777889'
      sourceHandle: source
      target: '1736400781647'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1736400777889-source-1736400785587-target
      source: '1736400777889'
      sourceHandle: source
      target: '1736400785587'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: code
      id: 1736400781647-source-1736400802024-target
      source: '1736400781647'
      sourceHandle: source
      target: '1736400802024'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: end
      id: 1736400802024-source-1736400809991-target
      source: '1736400802024'
      sourceHandle: source
      target: '1736400809991'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1736400777889-source-1736401334800-target
      source: '1736400777889'
      sourceHandle: source
      target: '1736401334800'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: end
      id: 1736401334800-source-1736400809991-target
      source: '1736401334800'
      sourceHandle: source
      target: '1736400809991'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: code
      id: 1736400785587-source-1736400802024-target
      source: '1736400785587'
      sourceHandle: source
      target: '1736400802024'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables: []
      height: 52
      id: '1736400777889'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        code: "\ndef main() -> dict:\n    return {\n        \"result\": \"A\",\n \
          \   }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: A
        type: code
        variables: []
      height: 52
      id: '1736400781647'
      position:
        x: 464.61358013386484
        y: 282
      positionAbsolute:
        x: 464.61358013386484
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        code: "\ndef main() -> dict:\n    return {\n        \"result\": \"B\",\n \
          \   }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: B
        type: code
        variables: []
      height: 52
      id: '1736400785587'
      position:
        x: 464.61358013386484
        y: 448.2348109412576
      positionAbsolute:
        x: 464.61358013386484
        y: 448.2348109412576
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        code: "\ndef main(arg1: str, arg2: str) -> dict:\n    return {\n        \"\
          result\": arg1 + arg2,\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: AB
        type: code
        variables:
        - value_selector:
          - '1736400781647'
          - result
          variable: arg1
        - value_selector:
          - '1736400785587'
          - result
          variable: arg2
      height: 52
      id: '1736400802024'
      position:
        x: 1023
        y: 436
      positionAbsolute:
        x: 1023
        y: 436
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1736401334800'
          - result
          variable: result1
        - value_selector:
          - '1736400802024'
          - result
          variable: result2
        selected: false
        title: 结束
        type: end
      height: 114
      id: '1736400809991'
      position:
        x: 1386
        y: 548
      positionAbsolute:
        x: 1386
        y: 548
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        code: "\ndef main() -> dict:\n    return {\n        \"result\": \"C\",\n \
          \   }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: C
        type: code
        variables: []
      height: 52
      id: '1736401334800'
      position:
        x: 464.61358013386484
        y: 603.214390116543
      positionAbsolute:
        x: 464.61358013386484
        y: 603.214390116543
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    viewport:
      x: 163.07251004687714
      y: 10.689820569381595
      zoom: 0.7474246308022043
```

### ✔️ Expected Behavior

Perhaps it could detect this topological structure in the graph and insert an independent parallel node before Node A and Node B, ending the parallel section at the AB node.

Now execution chain:
   start -> A -> AB -> end
   start -> B -> AB -> end
   start -> C -> end

Expected:
   start -> parallel (A+B) -> AB -> end
   start -> C -> end

### ❌ Actual Behavior

Currently, three paths are created, causing Node AB to be executed repeatedly. Moreover, Node AB executes without waiting for Node A and Node B to complete.
