### ISSUE TITLE
The LLM node following multiple consecutive IF-ELSE nodes cannot perform streaming output normally.

### ISSUE THREAD

**Issue by berg-wang** [langgenius/dify#13264]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.15.2,0.14.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

In the chatflow, input p1=1,p2=2 to reproduce the bug

![Image](https://github.com/user-attachments/assets/b6e0654c-0ba9-4c5d-9f6a-8f4cd3e77658)

The code of the DSL file is as follows
```yaml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: 聊天助手
  use_icon_as_answer_icon: false
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 10
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: if-else
      id: 1736473141049-source-1736500039341-target
      selected: false
      source: '1736473141049'
      sourceHandle: source
      target: '1736500039341'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: llm
        targetType: answer
      id: llm-source-1736905725300-target
      source: llm
      sourceHandle: source
      target: '1736905725300'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: if-else
      id: 1736500039341-true-1736912452686-target
      source: '1736500039341'
      sourceHandle: 'true'
      target: '1736912452686'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: llm
      id: 1736912452686-false-llm-target
      source: '1736912452686'
      sourceHandle: 'false'
      target: llm
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: answer
      id: 1736912452686-true-1736500282728-target
      source: '1736912452686'
      sourceHandle: 'true'
      target: '1736500282728'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: llm
      id: 1736500039341-false-llm-target
      selected: false
      source: '1736500039341'
      sourceHandle: 'false'
      target: llm
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - label: p1
          max_length: 48
          options:
          - rag
          - coding
          required: true
          type: number
          variable: p1
        - label: p2
          max_length: 48
          options: []
          required: true
          type: number
          variable: p2
      height: 116
      id: '1736473141049'
      position:
        x: -168.62450458982806
        y: -116.76570389946635
      positionAbsolute:
        x: -168.62450458982806
        y: -116.76570389946635
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - sys
          - query
        desc: ''
        memory:
          query_prompt_template: '{{#sys.query#}}'
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: true
            size: 10
        model:
          completion_params:
            temperature: 0.1
          mode: chat
          name: qwen2.5-instruct-7b
          provider: xinference
        prompt_template:
        - id: 297c5dcb-fcaa-4fcc-8f5e-a958a38cdd33
          role: system
          text: '{{#context#}}'
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 98
      id: llm
      position:
        x: 901.7295665243596
        y: -50.052447015913074
      positionAbsolute:
        x: 901.7295665243596
        y: -50.052447015913074
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: '='
            id: 67f95487-2a09-4819-a7cd-8689ee4478a9
            value: '1'
            varType: number
            variable_selector:
            - '1736473141049'
            - p1
          id: 'true'
          logical_operator: and
        desc: ''
        selected: false
        title: 条件分支
        type: if-else
      height: 126
      id: '1736500039341'
      position:
        x: 177.47424548618807
        y: -124.68275136410372
      positionAbsolute:
        x: 177.47424548618807
        y: -124.68275136410372
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: p1={{#1736473141049.p1#}},p2={{#1736473141049.p2#}}
        desc: ''
        selected: false
        title: 直接回复 2
        type: answer
        variables: []
      height: 122
      id: '1736500282728'
      position:
        x: 901.7295665243596
        y: -259.7791887951555
      positionAbsolute:
        x: 901.7295665243596
        y: -259.7791887951555
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#llm.text#}}'
        desc: ''
        selected: false
        title: 直接回复 4
        type: answer
        variables: []
      height: 103
      id: '1736905725300'
      position:
        x: 1266.2290315905668
        y: -50.052447015913074
      positionAbsolute:
        x: 1266.2290315905668
        y: -50.052447015913074
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: '='
            id: e356acb3-6154-4f45-9e7f-af42f39e353b
            value: '1'
            varType: number
            variable_selector:
            - '1736473141049'
            - p2
          id: 'true'
          logical_operator: and
        desc: ''
        selected: false
        title: 条件分支 3
        type: if-else
      height: 126
      id: '1736912452686'
      position:
        x: 521.2606128153778
        y: -268.81052581580366
      positionAbsolute:
        x: 521.2606128153778
        y: -268.81052581580366
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 404.110405425826
      y: 482.0449711931172
      zoom: 0.6597539553864473
```

### ✔️ Expected Behavior

 the Direct-Reply node can handle streaming data responses.

### ❌ Actual Behavior

 the Direct-Reply node is unable to handle streaming data responses.

**Comment by crazywoola** [comment]
I can not reproduce this bug.

**Comment by boHam-wang** [comment]
https://github.com/langgenius/dify/pull/12105 cannot fix my issue.

**Comment by Wasim-yang** [comment]
+1

**Comment by ITMeow** [comment]
In the llm node after the http request node, none of them can achieve stream output

![Image](https://github.com/user-attachments/assets/d44d6551-3dae-403f-9148-531a01059dae)

**Comment by ITMeow** [comment]
In the llm node after the http request node, none of them can achieve stream output

![Image](https://github.com/user-attachments/assets/a628d796-d353-40e4-a7a6-1b1763b6f4ae)

**Comment by lasthash** [comment]
> In the llm node after the http request node, none of them can achieve stream output
> 
> ![Image](https://github.com/user-attachments/assets/a628d796-d353-40e4-a7a6-1b1763b6f4ae)

after selecting the default value for the exception mode configuration in the HTTP request node, I encountered the same issue

**Comment by Kain-90** [comment]
<img width="1050" alt="Image" src="https://github.com/user-attachments/assets/76dfe2ee-aace-4275-91f5-5d31c58ef5e0" />

I have found the simplest example to reproduce this issue.

dify version: 0.15.3(self-hosted)

```yaml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: '1'
  use_icon_as_answer_icon: false
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .doc
      - .docx
      allowed_file_types:
      - custom
      allowed_file_upload_methods:
      - remote_url
      - local_file
      enabled: true
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 1
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: if-else
      id: 1739251774129-source-1740729243446-target
      selected: false
      source: '1739251774129'
      sourceHandle: source
      target: '1740729243446'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: llm
        targetType: answer
      id: 1740729249423-source-answer-target
      source: '1740729249423'
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: llm
      id: 1740729243446-true-1740729249423-target
      source: '1740729243446'
      sourceHandle: 'true'
      target: '1740729249423'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: llm
      id: 1740993386020-true-1740729249423-target
      source: '1740993386020'
      sourceHandle: 'true'
      target: '1740729249423'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: start
        targetType: if-else
      id: 1739251774129-source-1740993386020-target
      source: '1739251774129'
      sourceHandle: source
      target: '1740993386020'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables: []
      height: 54
      id: '1739251774129'
      position:
        x: 30
        y: 263
      positionAbsolute:
        x: 30
        y: 263
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#1740729249423.text#}}'
        desc: ''
        selected: false
        title: Answer
        type: answer
        variables: []
      height: 103
      id: answer
      position:
        x: 1246
        y: 263
      positionAbsolute:
        x: 1246
        y: 263
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: empty
            id: 3add315b-8fa0-468f-b8bd-7521175862e6
            value: ''
            varType: string
            variable_selector:
            - sys
            - query
          id: 'true'
          logical_operator: and
        desc: ''
        selected: false
        title: IF-ELSE
        type: if-else
      height: 126
      id: '1740729243446'
      position:
        x: 399.42857142857144
        y: 163
      positionAbsolute:
        x: 399.42857142857144
        y: 163
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: qwen-turbo
          provider: tongyi
        prompt_template:
        - id: 1a79a159-bec1-4051-a7e4-a549acef2e68
          role: system
          text: you're a helpful assistant!
        - id: a1eab112-e2ed-44b8-a129-f3b601945b3c
          role: user
          text: '{{#sys.query#}}'
        selected: true
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 98
      id: '1740729249423'
      position:
        x: 942
        y: 263
      positionAbsolute:
        x: 942
        y: 263
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: not empty
            id: ca1524c8-64c4-42d1-9c8c-aad54afc4f02
            value: ''
            varType: string
            variable_selector:
            - sys
            - user_id
          id: 'true'
          logical_operator: and
        desc: ''
        selected: false
        title: IF-ELSE
        type: if-else
      height: 126
      id: '1740993386020'
      position:
        x: 399.42857142857144
        y: 363.4285714285714
      positionAbsolute:
        x: 399.42857142857144
        y: 363.4285714285714
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 6.810069538623679
      y: 176.66501435412357
      zoom: 0.6999251370153812
```
