### ISSUE TITLE
Support Stream template transform in workflow OR Support end node template feature.

### ISSUE THREAD

**Issue by wellCh4n** [langgenius/dify#13443]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Merge two LLM outputs into one.

Now I have only two options
1. use a TemplateTransformNode after the two LLM nodes. the problem with this is that I have to wait for the two streams to output before I can get the result in the workflow.
2. select two LLM nodes as output variables in the end node. The problem with this is that when I call through the API, only the content of the first LLM node is output one by one Token, while the second one is all Token output.

Is it possible for we to add streaming rendering feature to Workflow similar to AnswerNode in Chat?

### 2. Additional context or comments

Minimal DSL

```yaml
app:
  description: aaa
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: '111'
  use_icon_as_answer_icon: false
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: llm
      id: 1737010767476-false-1736485205249-target
      source: '1737010767476'
      sourceHandle: 'false'
      target: '1736485205249'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: start
        targetType: if-else
      id: 1736484874578-source-1737010767476-target
      source: '1736484874578'
      sourceHandle: source
      target: '1737010767476'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: llm
      id: 1737010767476-true-17370109704300-target
      source: '1737010767476'
      sourceHandle: 'true'
      target: '17370109704300'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: llm
        targetType: end
      id: 17370109704300-source-1736485017880-target
      source: '17370109704300'
      sourceHandle: source
      target: '1736485017880'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: llm
        targetType: template-transform
      id: 1736485205249-source-1737011099693-target
      source: '1736485205249'
      sourceHandle: source
      target: '1737011099693'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: template-transform
        targetType: end
      id: 1737011099693-source-1738919183633-target
      source: '1737011099693'
      sourceHandle: source
      target: '1738919183633'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: llm
      id: 1737010767476-true-1738997272166-target
      source: '1737010767476'
      sourceHandle: 'true'
      target: '1738997272166'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: llm
        targetType: end
      id: 1738997272166-source-1736485017880-target
      source: '1738997272166'
      sourceHandle: source
      target: '1736485017880'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - label: input
          max_length: 1024
          options: []
          required: true
          type: paragraph
          variable: input
        - label: way
          max_length: 48
          options: []
          required: true
          type: text-input
          variable: way
      height: 116
      id: '1736484874578'
      position:
        x: 3.445748363722487
        y: 198.27401163657362
      positionAbsolute:
        x: 3.445748363722487
        y: 198.27401163657362
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '17370109704300'
          - text
          variable: text
        - value_selector:
          - '1738997272166'
          - text
          variable: text1
        selected: false
        title: 结束
        type: end
      height: 116
      id: '1736485017880'
      position:
        x: 1253.8723756336342
        y: 110.79941631292118
      positionAbsolute:
        x: 1253.8723756336342
        y: 110.79941631292118
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: gpt-4o-mini
          provider: openai
        prompt_template:
        - id: e6d7b742-5b19-439d-9ece-1921fddf2396
          role: system
          text: Summarize user input.
        - id: a107c8e3-04eb-45f8-bda3-ec82b1092ed1
          role: user
          text: '{{#1736484874578.input#}}'
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 98
      id: '1736485205249'
      position:
        x: 639.3738938171914
        y: 449.9862080736
      positionAbsolute:
        x: 639.3738938171914
        y: 449.9862080736
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: contains
            id: d65b4e01-f926-4384-b1a9-2ca8e25aa1e8
            value: '1'
            varType: string
            variable_selector:
            - '1736484874578'
            - way
          id: 'true'
          logical_operator: and
        desc: ''
        selected: false
        title: 条件分支
        type: if-else
      height: 126
      id: '1737010767476'
      position:
        x: 337.6050283646107
        y: 198.27401163657362
      positionAbsolute:
        x: 337.6050283646107
        y: 198.27401163657362
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: gpt-4o-mini
          provider: openai
        prompt_template:
        - id: e6d7b742-5b19-439d-9ece-1921fddf2396
          role: system
          text: Summarize user input.
        - id: a107c8e3-04eb-45f8-bda3-ec82b1092ed1
          role: user
          text: '{{#1736484874578.input#}}'
        selected: false
        title: LLM (1)
        type: llm
        variables: []
        vision:
          enabled: false
      height: 98
      id: '17370109704300'
      position:
        x: 671.0175339717991
        y: 19.656725480628467
      positionAbsolute:
        x: 671.0175339717991
        y: 19.656725480628467
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        selected: false
        template: '{{ arg1 }}


          > Foo'
        title: 模板转换
        type: template-transform
        variables:
        - value_selector:
          - '1736485205249'
          - text
          variable: arg1
      height: 54
      id: '1737011099693'
      position:
        x: 952.0394504702425
        y: 449.9862080736
      positionAbsolute:
        x: 952.0394504702425
        y: 449.9862080736
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1737011099693'
          - output
          variable: output
        selected: false
        title: 结束 2
        type: end
      height: 90
      id: '1738919183633'
      position:
        x: 1244.2101464006525
        y: 449.9862080736
      positionAbsolute:
        x: 1244.2101464006525
        y: 449.9862080736
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: gpt-4o-mini
          provider: openai
        prompt_template:
        - id: e4025745-a405-478b-af5f-73526299f64d
          role: system
          text: Talk something you like.
        selected: false
        title: LLM 3
        type: llm
        variables: []
        vision:
          enabled: false
      height: 98
      id: '1738997272166'
      position:
        x: 661.3711767365428
        y: 170.4772143625691
      positionAbsolute:
        x: 661.3711767365428
        y: 170.4772143625691
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -419.15644967253667
      y: 263.00613459763645
      zoom: 0.518330378821731

```

### 3. Can you help us with this feature?

- [x] I am interested in contributing to this feature.
