### ISSUE TITLE
LLM Stuck at Question Classifier Node

### ISSUE THREAD

**Issue by khoi03** [langgenius/dify#13628]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.15.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After running a parallel chatflow, it gets stuck at the Question Classifier node, as shown in the video. However, if I remove the connection between the Variable Assigner and the If/Else node, the issue disappears, and the chatflow works as expected.

https://github.com/user-attachments/assets/fad184ec-2fd1-40d1-b98b-f4bbb93749fe

### ✔️ Expected Behavior

Streaming Response

### ❌ Actual Behavior

Stuck

**Comment by crazywoola** [comment]
Can you provide the DSL?
It seems the `class_name` is not found in the workflow.

**Comment by khoi03** [comment]
> Can you provide the DSL? It seems the `class_name` is not found in the workflow.

Yes, it could not find the `class_name` because Question Classifier stuck.

Here is the DSL:
```
app:
  description: ''
  icon: face_with_monocle
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: 'Question Classifier + Knowledge + Chatbot '
  use_icon_as_answer_icon: false
kind: app
version: 0.1.5
workflow:
  conversation_variables:
  - description: ''
    id: 23cbf5d2-3674-42f2-b281-6580c992b8f3
    name: trigger
    selector:
    - conversation
    - trigger
    value: ''
    value_type: string
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        sourceType: question-classifier
        targetType: answer
      id: 1711528709608-1711528775142
      selected: false
      source: '1711528709608'
      sourceHandle: '1711528737066'
      target: '1711528775142'
      targetHandle: target
      type: custom
    - data:
        sourceType: llm
        targetType: answer
      id: 1711528802931-1711528833796
      selected: false
      source: '1711528802931'
      sourceHandle: source
      target: '1711528833796'
      targetHandle: target
      type: custom
    - data:
        sourceType: llm
        targetType: answer
      id: 1711528815414-1711528835179
      selected: false
      source: '1711528815414'
      sourceHandle: source
      target: '1711528835179'
      targetHandle: target
      type: custom
    - data:
        isInIteration: false
        sourceType: question-classifier
        targetType: if-else
      id: 1711528709608-1711528736036-1737652760352-target
      selected: false
      source: '1711528709608'
      sourceHandle: '1711528736036'
      target: '1737652760352'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: llm
      id: 1737652760352-true-1711528802931-target
      selected: false
      source: '1737652760352'
      sourceHandle: 'true'
      target: '1711528802931'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: llm
      id: 1737652760352-74e0f2ea-687b-402a-abe1-e090420a87d3-1711528815414-target
      selected: false
      source: '1737652760352'
      sourceHandle: 74e0f2ea-687b-402a-abe1-e090420a87d3
      target: '1711528815414'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: question-classifier
        targetType: if-else
      id: 1711528709608-1711528736549-1737652760352-target
      selected: false
      source: '1711528709608'
      sourceHandle: '1711528736549'
      target: '1737652760352'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1711528708197-source-1739392509255-target
      selected: false
      source: '1711528708197'
      sourceHandle: source
      target: '1739392509255'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: assigner
      id: 1739392509255-source-1739392996723-target
      selected: false
      source: '1739392509255'
      sourceHandle: source
      target: '1739392996723'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: start
        targetType: question-classifier
      id: 1711528708197-source-1711528709608-target
      selected: false
      source: '1711528708197'
      sourceHandle: source
      target: '1711528709608'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: assigner
        targetType: if-else
      id: 1739392996723-source-1737652760352-target
      source: '1739392996723'
      sourceHandle: source
      target: '1737652760352'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: Define the initial parameters for launching a workflow
        selected: false
        title: Start
        type: start
        variables: []
      height: 97
      id: '1711528708197'
      position:
        x: -401.1880537992373
        y: 920.8963689066167
      positionAbsolute:
        x: -401.1880537992373
        y: 920.8963689066167
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        classes:
        - id: '1711528736036'
          name: Question related to after sales
        - id: '1711528736549'
          name: Questions about how to use products
        - id: '1711528737066'
          name: Other questions
        desc: 'Define the classification conditions of user questions, LLM can define
          how the conversation progresses based on the classification description. '
        instructions: ''
        model:
          completion_params:
            frequency_penalty: 0
            max_tokens: 512
            presence_penalty: 0
            temperature: 0.7
            top_p: 1
          mode: chat
          name: gpt-4o-mini
          provider: openai
        query_variable_selector:
        - '1711528708197'
        - sys.query
        selected: false
        title: Question Classifier
        topics: []
        type: question-classifier
      height: 287
      id: '1711528709608'
      position:
        x: 307.8025930365004
        y: 1064.862953129812
      positionAbsolute:
        x: 307.8025930365004
        y: 1064.862953129812
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: "Sorry, I can't help you with these questions. \n{{#conversation.trigger#}}"
        desc: ''
        selected: false
        title: Answer
        type: answer
        variables: []
      height: 119
      id: '1711528775142'
      position:
        x: 746.5168787507857
        y: 1295.1486674155265
      positionAbsolute:
        x: 746.5168787507857
        y: 1295.1486674155265
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - sys
          - query
        desc: ''
        memory:
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: false
            size: 50
        model:
          completion_params:
            frequency_penalty: 0
            max_tokens: 512
            presence_penalty: 0
            temperature: 0.7
            top_p: 1
          mode: chat
          name: gpt-4o-mini
          provider: openai
        prompt_template:
        - id: 4b5848f8-723b-4036-8296-2037c9213b61
          role: system
          text: 'Use the following context as your learned knowledge, inside <context></context>
            XML tags.

            <context>

            {{#context#}}

            </context>

            When answer to user:

            - If you don''t know, just say that you don''t know.

            - If you don''t know when you are not sure, ask for clarification.

            Avoid mentioning that you obtained the information from the context.

            And answer according to the language of the user''s question.'
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      dragging: false
      height: 97
      id: '1711528802931'
      position:
        x: 1005.2311644650717
        y: 914.0058102726694
      positionAbsolute:
        x: 1005.2311644650717
        y: 914.0058102726694
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - sys
          - query
        desc: ''
        memory:
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: false
            size: 50
        model:
          completion_params:
            frequency_penalty: 0
            max_tokens: 512
            presence_penalty: 0
            temperature: 0.7
            top_p: 1
          mode: chat
          name: gpt-4o-mini
          provider: openai
        prompt_template:
        - id: 5099476a-9768-43dd-b257-4272495d77a1
          role: system
          text: 'Use the following context as your learned knowledge, inside <context></context>
            XML tags.

            <context>

            {{#context#}}

            </context>

            When answer to user:

            - If you don''t know, just say that you don''t know.

            - If you don''t know when you are not sure, ask for clarification.

            Avoid mentioning that you obtained the information from the context.

            And answer according to the language of the user''s question.'
        selected: false
        title: 'LLM '
        type: llm
        variables: []
        vision:
          enabled: false
      dragging: false
      height: 97
      id: '1711528815414'
      position:
        x: 1012.3740216079286
        y: 1113.8629531298125
      positionAbsolute:
        x: 1012.3740216079286
        y: 1113.8629531298125
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#1711528802931.text#}}

          {{#conversation.trigger#}}'
        desc: ''
        selected: false
        title: Answer 2
        type: answer
        variables:
        - value_selector:
          - '1711528802931'
          - text
          variable: text
      dragging: false
      height: 103
      id: '1711528833796'
      position:
        x: 1452.5168787507855
        y: 926.8629531298125
      positionAbsolute:
        x: 1452.5168787507855
        y: 926.8629531298125
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#1711528815414.text#}}

          {{#conversation.trigger#}}'
        desc: ''
        selected: false
        title: Answer 3
        type: answer
        variables:
        - value_selector:
          - '1711528815414'
          - text
          variable: text
      dragging: false
      height: 103
      id: '1711528835179'
      position:
        x: 1446.8025930365002
        y: 1125.291524558384
      positionAbsolute:
        x: 1446.8025930365002
        y: 1125.291524558384
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: contains
            id: bcac9a89-feed-4155-8008-51debe266ac9
            value: Question related to after sales
            varType: string
            variable_selector:
            - '1711528709608'
            - class_name
          - comparison_operator: contains
            id: 96659dcf-c40e-426a-9979-7b0c7a7ca5b5
            value: class 1
            varType: string
            variable_selector:
            - conversation
            - trigger
          id: 'true'
          logical_operator: or
        - case_id: 74e0f2ea-687b-402a-abe1-e090420a87d3
          conditions:
          - comparison_operator: contains
            id: 2e4e0d89-f64b-4e44-9081-a7703ac822a3
            value: Questions about how to use products
            varType: string
            variable_selector:
            - '1711528709608'
            - class_name
          - comparison_operator: contains
            id: b9f01277-0f13-4ab1-a52e-b1811703f612
            value: class 2
            varType: string
            variable_selector:
            - conversation
            - trigger
          id: 74e0f2ea-687b-402a-abe1-e090420a87d3
          logical_operator: or
        desc: ''
        selected: false
        title: IF/ELSE
        type: if-else
      height: 225
      id: '1737652760352'
      position:
        x: 730.8025930365004
        y: 962.0058102726691
      positionAbsolute:
        x: 730.8025930365004
        y: 962.0058102726691
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "import random\n\ndef main() -> dict:\n\n    options = [\"class 1\"\
          , \"class 2\"]\n    trigger = random.choice(options)\n    return {\n   \
          \     \"trigger\": trigger,\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          trigger:
            children: null
            type: string
        selected: false
        title: Code
        type: code
        variables: []
      height: 53
      id: '1739392509255'
      position:
        x: 141.76317578252332
        y: 689.2323719415472
      positionAbsolute:
        x: 141.76317578252332
        y: 689.2323719415472
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        items:
        - input_type: variable
          operation: over-write
          value:
          - '1739392509255'
          - trigger
          variable_selector:
          - conversation
          - trigger
          write_mode: over-write
        selected: false
        title: Variable Assigner
        type: assigner
        version: '2'
      height: 87
      id: '1739392996723'
      position:
        x: 426.1944740013613
        y: 689.2323719415472
      positionAbsolute:
        x: 426.1944740013613
        y: 689.2323719415472
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 323.13000268076655
      y: -118.80038269780306
      zoom: 0.48570563626138646

```
