### ISSUE TITLE
Abnormalities in multi-round LLM conversations

### ISSUE THREAD

**Issue by love01211** [langgenius/dify#13846]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

v0.15.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Using vllm to launch the Deepseek-7b model,“Model Provider” - > "ADD MORE MODEL PROVIDER" -> localAI ,Then configure the workflow to upload the file, and then have multiple rounds of conversations，But use "ADD MORE MODEL PROVIDER" -> ollama，Normal operation。

### ✔️ Expected Behavior

Normal operation

### ❌ Actual Behavior

“User message content must be str”
![Image](https://github.com/user-attachments/assets/f119e9f7-870f-4487-bd93-7af63775bc36)

DSL：
```
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: 上传文件读取
  use_icon_as_answer_icon: false
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions: []
      allowed_file_types:
      - document
      allowed_file_upload_methods:
      - local_file
      enabled: true
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 1
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        sourceType: llm
        targetType: answer
      id: llm-answer
      source: llm
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
    - data:
        isInIteration: false
        sourceType: start
        targetType: document-extractor
      id: 1738899393364-source-1738922032713-target
      source: '1738899393364'
      sourceHandle: source
      target: '1738922032713'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: document-extractor
        targetType: llm
      id: 1738922032713-source-llm-target
      source: '1738922032713'
      sourceHandle: source
      target: llm
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables: []
      height: 53
      id: '1738899393364'
      position:
        x: 30
        y: 251
      positionAbsolute:
        x: 30
        y: 251
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - '1738922032713'
          - text
        desc: ''
        memory:
          query_prompt_template: '{{#sys.query#}}'
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: false
            size: 10
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: DeepSeek-R1-Distill-Qwen-7B
          provider: localai
        prompt_template:
        - id: 4a6623cd-78ba-4a4d-9478-589528dca75c
          role: system
          text: 你是一个文件助手，根据用户需要，结合文件内容回答用户，文件内容在<files>{{#context#}}</files>
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 97
      id: llm
      position:
        x: 638
        y: 251
      positionAbsolute:
        x: 638
        y: 251
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#llm.text#}}'
        desc: ''
        selected: false
        title: 直接回复
        type: answer
        variables: []
      height: 102
      id: answer
      position:
        x: 942
        y: 251
      positionAbsolute:
        x: 942
        y: 251
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        is_array_file: true
        selected: false
        title: 文档提取器
        type: document-extractor
        variable_selector:
        - sys
        - files
      height: 91
      id: '1738922032713'
      position:
        x: 332.57142857142856
        y: 251
      positionAbsolute:
        x: 332.57142857142856
        y: 251
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 77.86710032646181
      y: 174.9890744049676
      zoom: 0.6093853943072869
```
