### ISSUE TITLE
The format of dify's response to the DeepSeek-R1-Distill-Llama-70B model is incorrect. Multiple thinking... collapse tags are displayed.

### ISSUE THREAD

**Issue by majestichou** [langgenius/dify#13858]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.15.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Download the DeepSeek-R1-Distillation-Llama-70B model and delete `<think>\\n` at the end of the chat template in tokenizer_config.json. Use vllm docker images to start the model
2. Create the following applications by DSL:
```
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: deepseek-qwen-llama-70b
  use_icon_as_answer_icon: false
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        sourceType: start
        targetType: llm
      id: 1739773269234-llm
      source: '1739773269234'
      sourceHandle: source
      target: llm
      targetHandle: target
      type: custom
    - data:
        sourceType: llm
        targetType: answer
      id: llm-answer
      source: llm
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables: []
      height: 54
      id: '1739773269234'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        memory:
          query_prompt_template: '{{#sys.query#}}'
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: true
            size: 10
        model:
          completion_params:
            max_tokens: 4096
            temperature: 0.6
            top_p: 0.8
          mode: chat
          name: /data/models/DeepSeek-R1-Distill-Llama-70B
          provider: openai_api_compatible
        prompt_template:
        - id: ace60b14-ea7c-4239-a9d2-ed0c8ef15506
          role: system
          text: ''
        selected: true
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 98
      id: llm
      position:
        x: 380
        y: 282
      positionAbsolute:
        x: 380
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#llm.text#}}'
        desc: ''
        selected: false
        title: 直接回复
        type: answer
        variables: []
      height: 103
      id: answer
      position:
        x: 680
        y: 282
      positionAbsolute:
        x: 680
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -150
      y: 115
      zoom: 1
```
3. Create a new conversation, ask a question: "帮我写一个单例模式". The answer of AI is as follows:
```
<details style="color:gray;background-color: #f8f8f8;padding: 8px;border-radius: 4px;" open> <summary> Thinking... </summary>
嗯，用户让我帮他写一个单例模式。那我得先想想单例模式是什么。单例模式就是保证一个类只有一个实例，并且提供一个全局访问点。常见的实现方式有几种，比如</details><details style="color:gray;background-color: #f8f8f8;padding: 8px;border-radius: 4px;" open> <summary> Thinking... </summary>懒汉式和</details><details style="color:gray;background-color: #f8f8f8;padding: 8px;border-radius: 4px;" open> <summary> Thinking... </summary>饿汉式，还有双重检查锁机制。

首先，我应该考虑用户的需求是什么。他可能需要一个基本的单例模式，或者有特定的使用场景？比如是在多线程环境下使用，可能需要考虑线程安全的问题。所以，我应该提供一个线程安全的版本，这样更稳</details><details style="color:gray;background-color: #f8f8f8;padding: 8px;border-radius: 4px;" open> <summary> Thinking... </summary>妥。

然后，我应该解释一下单例模式的基本概念和用途，这样用户能理解为什么要用单例模式。比如，它常用于数据库连接池、日志管理等只需要一个实例的情况。

接下来，我应该给出具体的代码示例。考虑到线程安全，我应该使用双重检查锁机制，这样在多线程环境下也能安全地获取单例。代码应该清</details><details style="color:gray;background-color: #f8f8f8;padding: 8px;border-radius: 4px;" open> <summary> Thinking... </summary>晰明了，包括私有构造方法，静态实例变量，以及公共的获取实例方法。

另外，我应该举一个简单的例子，比如一个记录用户数的类，这样用户能更直观地理解单例模式的应用。这样用户在实际使用中也能更容易地应用这个模式。

最后，我应该总结一下这种实现方式的优点，比如线程安全、高效性，以及它适用的场景。这样用户在选择使用时会更加明确。

总的来说，我需要提供一个全面但简洁的解释，包括概念、代码示例和用途，确保用户能够理解和应用单例模式。
</details>

单例模式（Singleton Pattern）是一种常用的设计模式，用于确保一个类在整个应用程序中只有一个实例，并且提供一个全局访问点。以下是单例模式的实现方式：

### 单例模式的实现

#### 1. 懒汉式（非线程安全）
```python
class Singleton:
    _instance = None  # 单例实例

    def __new__(cls, *args, **kwargs):
        if not cls._instance:
            cls._instance = super(Singleton, cls).__new__(cls, *args, **kwargs)
        return cls._instance
```

#### 2. 饿汉式（线程安全）
```python
class Singleton:
    _instance = None  # 单例实例

    def __init__(self):
        if Singleton._instance is None:
            Singleton._instance = self

    @classmethod
    def get_instance(cls):
        if cls._instance is None:
            cls._instance = Singleton()
        return cls._instance
```

#### 3. 双重检查锁机制（线程安全）
```python
import threading

class Singleton:
    _instance = None  # 单例实例
    _lock = threading.Lock()  # 锁

    def __new__(cls, *args, **kwargs):
        if not cls._instance:
            with cls._lock:
                if not cls._instance:
                    cls._instance = super(Singleton, cls).__new__(cls, *args, **kwargs)
        return cls._instance
```

### 说明

1. **懒汉式**：在第一次调用时创建实例，适用于单线程环境，但在多线程环境下可能会出现多个实例。
2. **饿汉式**：在类加载时就创建实例，适用于多线程环境，但可能会浪费资源。
3. **双重检查锁机制**：在多线程环境下安全地创建单例，性能较高。

### 使用示例

```python
# 创建单例类
class Logger(Singleton):
    def __init__(self):
        self.users = []

    def add_user(self, user):
        self.users.append(user)

    def get_users(self):
        return self.users

# 获取单例实例
logger1 = Logger()
logger2 = Logger()

# 添加用户
logger1.add_user("Alice")
logger2.add_user("Bob")

# 获取用户列表
print(logger1.get_users())  # 输出：['Alice', 'Bob']
print(logger2.get_users())  # 输出：['Alice', 'Bob']
```

### 总结

单例模式确保了一个类只有一个实例，并且提供了一个全局访问点。常用的实现方式包括懒汉式、饿汉式和双重检查锁机制。根据具体需求选择合适的实现方式，以确保在多线程环境下的线程安全和性能。
```

**The format of dify's response to the DeepSeek-R1-Distill-Llama-70B model is incorrect. Multiple thinking... collapse tags are displayed.**

5. What's more, the dialogue summary is gone. Only "New Conversation" is displayed on the left of the window.


### ✔️ Expected Behavior

1. The format of dify's response to the DeepSeek-R1-Distill-Llama-70B model is correct. Only one thinking... collapse tags are displayed.
2. The dialogue summary is ok rather than only "New Conversation" is displayed on the left of the window.

### ❌ Actual Behavior

The format of dify's response to the DeepSeek-R1-Distill-Llama-70B model is incorrect. Multiple thinking... collapse tags are displayed.
And the dialogue summary is gone. Only "New Conversation" is displayed on the left of the window.
