### ISSUE TITLE
arm docker chat error: Instance <App at 0x7f62402c30> is not bound to a Session; attribute refresh operation cannot proceed

### ISSUE THREAD

**Issue by 2576834738** [langgenius/dify#14224]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.15.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When using Chat in the ARM environment, I encountered an error. I added some parameters in docker-compose. Only when these parameters were added could the sandbox start up; otherwise, it kept reporting errors. I'm not sure if this has any impact on the Chat error. 

1. sandbox error

```
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x7fbcd87240 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: g 0: unknown pc 0x7fbcd87240
stack: frame={sp:0x7fd705a5e0, fp:0x0} stack=[0x7fd685bac8,0x7fd705aae0)
0x0000007fd705a4e0:  0x0000000000000000  0x00000000021af958 
0x0000007fd705a4f0:  0x0000007fbcefc640  0x0000007fd705a940 
0x0000007fd705a500:  0x000000000270e000  0x00000000027260a0 
0x0000007fd705a510:  0x0000007fd705a550  0x0000007fd705a580 
0x0000007fd705a520:  0x0000000000000000  0x0000007fbcf026f8 
0x0000007fd705a530:  0x0000007fbceaf198  0x0000007fbcf01000 
0x0000007fd705a540:  0x0000000000000002  0x0000000000000001 
0x0000007fd705a550:  0x0000007fd705a590  0x0000007fbcd4cda8 
0x0000007fd705a560:  0x0000007fd705a5f8  0x0000000002177f70 
0x0000007fd705a570:  0x0000007fd705a700  0x0000000000679694 
0x0000007fd705a580:  0x0000007fbcd15c98  0x0000007fbcefb170 
0x0000007fd705a590:  0x0000007fbceb2590  0x000000000000002e 
0x0000007fd705a5a0:  0x0000007fd705a700  0x00000000027260a0 
0x0000007fd705a5b0:  0x0000007fd705a860  0x0000007fd705a860 
0x0000007fd705a5c0:  0x0000007fd705a720  0x0000007fbced0884 
0x0000007fd705a5d0:  0x0000007fbceb1630  0x0000000002177f70 
0x0000007fd705a5e0: <0x00000000027632f0  0x80dea6c26c033c00 
0x0000007fd705a5f0:  0x0000007fd705a630  0x0000007fbcd367a0 
0x0000007fd705a600:  0x0000000000000006  0x0000007fbcefbf00 
0x0000007fd705a610:  0x0000007fbceb1a50  0x0000000000000001 
0x0000007fd705a620:  0x0000007fbcd21950  0x5f64616572687470 
0x0000007fd705a630:  0x0000007fd705a6f0  0x0000007fbcd21a48 
0x0000007fd705a640:  0x0000007fbceb1000  0x0000000000000000 
0x0000007fd705a650:  0x0000000000000020  0x00000000ffffffff 
0x0000007fd705a660:  0x0000007fd705a6a8  0x0000007fd705a656 
0x0000007fd705a670:  0x00000000fbad2887  0x0000000000000000 
0x0000007fd705a680:  0x000000000000000a  0x0000007fbceb2590 
0x0000007fd705a690:  0x2525252525252525  0x2525252525252525 
0x0000007fd705a6a0:  0x25203a64656c6961  0x0000000000000073 
0x0000007fd705a6b0:  0x00000000f0000000  0x0000000000000000 
0x0000007fd705a6c0:  0xff00000000000000  0xffffffffffffff00 
0x0000007fd705a6d0:  0xfffffff0f0000000  0x0000000000000000 
runtime: g 0: unknown pc 0x7fbcd87240
stack: frame={sp:0x7fd705a5e0, fp:0x0} stack=[0x7fd685bac8,0x7fd705aae0)
0x0000007fd705a4e0:  0x0000000000000000  0x00000000021af958 
0x0000007fd705a4f0:  0x0000007fbcefc640  0x0000007fd705a940 
0x0000007fd705a500:  0x000000000270e000  0x00000000027260a0 
0x0000007fd705a510:  0x0000007fd705a550  0x0000007fd705a580 
0x0000007fd705a520:  0x0000000000000000  0x0000007fbcf026f8 
0x0000007fd705a530:  0x0000007fbceaf198  0x0000007fbcf01000 
0x0000007fd705a540:  0x0000000000000002  0x0000000000000001 
0x0000007fd705a550:  0x0000007fd705a590  0x0000007fbcd4cda8 
0x0000007fd705a560:  0x0000007fd705a5f8  0x0000000002177f70 
0x0000007fd705a570:  0x0000007fd705a700  0x0000000000679694 
0x0000007fd705a580:  0x0000007fbcd15c98  0x0000007fbcefb170 
0x0000007fd705a590:  0x0000007fbceb2590  0x000000000000002e 
0x0000007fd705a5a0:  0x0000007fd705a700  0x00000000027260a0 
0x0000007fd705a5b0:  0x0000007fd705a860  0x0000007fd705a860 
0x0000007fd705a5c0:  0x0000007fd705a720  0x0000007fbced0884 
0x0000007fd705a5d0:  0x0000007fbceb1630  0x0000000002177f70 
0x0000007fd705a5e0: <0x00000000027632f0  0x80dea6c26c033c00 
0x0000007fd705a5f0:  0x0000007fd705a630  0x0000007fbcd367a0 
0x0000007fd705a600:  0x0000000000000006  0x0000007fbcefbf00 
0x0000007fd705a610:  0x0000007fbceb1a50  0x0000000000000001 
0x0000007fd705a620:  0x0000007fbcd21950  0x5f64616572687470 
0x0000007fd705a630:  0x0000007fd705a6f0  0x0000007fbcd21a48 
0x0000007fd705a640:  0x0000007fbceb1000  0x0000000000000000 
0x0000007fd705a650:  0x0000000000000020  0x00000000ffffffff 
0x0000007fd705a660:  0x0000007fd705a6a8  0x0000007fd705a656 
0x0000007fd705a670:  0x00000000fbad2887  0x0000000000000000 
0x0000007fd705a680:  0x000000000000000a  0x0000007fbceb2590 
0x0000007fd705a690:  0x2525252525252525  0x2525252525252525 
0x0000007fd705a6a0:  0x25203a64656c6961  0x0000000000000073 
0x0000007fd705a6b0:  0x00000000f0000000  0x0000000000000000 
0x0000007fd705a6c0:  0xff00000000000000  0xffffffffffffff00 
0x0000007fd705a6d0:  0xfffffff0f0000000  0x0000000000000000 

goroutine 1 [running]:
runtime.systemstack_switch()
        /opt/hostedtoolcache/go/1.20.6/arm64/src/runtime/asm_arm64.s:200 +0x8 fp=0x400004e770 sp=0x400004e760 pc=0x73608
runtime.main()
        /opt/hostedtoolcache/go/1.20.6/arm64/src/runtime/proc.go:170 +0x6c fp=0x400004e7d0 sp=0x400004e770 pc=0x4704c
runtime.goexit()
        /opt/hostedtoolcache/go/1.20.6/arm64/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400004e7d0 sp=0x400004e7d0 pc=0x75bd4

r0      0x0
r1      0x1
r2      0x6
r3      0x7fbcefbf00
r4      0x7fbcf00b30
r5      0x1
r6      0x20
r7      0xffffffff
r8      0x83
r9      0x0
r10     0x7fbcd15c98
r11     0x0
r12     0x7fbcf02350
r13     0x7fd705a9e0
r14     0x3d
r15     0x3c47b5
r16     0x0
r17     0x0
r18     0x1ad000
r19     0x1
r20     0x7fbcefbf00
r21     0x6
r22     0x1
r23     0x0
r24     0x0
r25     0x0
r26     0x7fd705a940
r27     0x270e000
r28     0x27260a0
r29     0x7fd705a5f0
lr      0x7fbcd8722c
sp      0x7fd705a5e0
pc      0x7fbcd87240
fault   0x0
```

2. docker-compose

```
sandbox:
    image: langgenius/dify-sandbox:0.2.10
    restart: always
    ulimits:
      nproc:
        soft: 1000000
        hard: 1000000
    security_opt:
      - seccomp:unconfined
    environment:
      # The DifySandbox configurations
      # Make sure you are changing this key for your deployment with a strong key.
      # You can generate a strong key using `openssl rand -base64 42`.
      API_KEY: ${SANDBOX_API_KEY:-dify-sandbox}
      GIN_MODE: ${SANDBOX_GIN_MODE:-release}
      WORKER_TIMEOUT: ${SANDBOX_WORKER_TIMEOUT:-15}
      ENABLE_NETWORK: ${SANDBOX_ENABLE_NETWORK:-true}
      HTTP_PROXY: ${SANDBOX_HTTP_PROXY:-http://ssrf_proxy:3128}
      HTTPS_PROXY: ${SANDBOX_HTTPS_PROXY:-http://ssrf_proxy:3128}
      SANDBOX_PORT: ${SANDBOX_PORT:-8194}
    volumes:
      - ./volumes/sandbox/dependencies:/dependencies
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8194/health' ]
    networks:
      - ssrf_proxy_network
```

3. chat error
```
2025-02-24 02:18:11.334 ERROR [Thread-15 (_generate_worker)] [app_generator.py:243] - Unknown Error when generating
Traceback (most recent call last):
  File "/app/api/core/app/apps/chat/app_generator.py", line 223, in _generate_worker
    runner.run(
  File "/app/api/core/app/apps/chat/app_runner.py", line 176, in run
    prompt_messages, stop = self.organize_prompt_messages(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/app/apps/base_app_runner.py", line 162, in organize_prompt_messages
    app_mode=AppMode.value_of(app_record.mode),
                              ^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 566, in __get__
    return self.impl.get(state, dict_)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1086, in get
    value = self._fire_loader_callables(state, key, passive)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/attributes.py", line 1116, in _fire_loader_callables
    return state._load_expired(state, passive)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/state.py", line 803, in _load_expired
    self.manager.expired_attribute_loader(self, toload, passive)
  File "/app/api/.venv/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 1603, in load_scalar_attributes
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Instance <App at 0x7f62402c30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
2025-02-24 02:18:11.349 ERROR [Dummy-16] [base_app_generate_response_converter.py:123] - Instance <App at 0x7f62402c30> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/20/bhk3)
```

### ✔️ Expected Behavior

fix error

### ❌ Actual Behavior

error happend
