### ISSUE TITLE
社区版 1.0.0 本地部署后无法配置模型秘钥

### ISSUE THREAD

**Issue by dukun1224** [langgenius/dify#14603]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.0.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

<img width="720" alt="Image" src="https://github.com/user-attachments/assets/80704a28-19cc-4229-ac70-6943684bbb68" />

报错：Uncaught (in promise) TimeoutError: Request timed out: POST http://localhost/console/api/workspaces/current/model-providers/langgenius/tongyi/tongyi
    at 3451-f3b01e497296e6f6.js:1:4366

无法配置模型apikey，导致整个流程无法使用

**Comment by YunFenLei** [comment]
@dosu 我也遇到这个问题，新安装绑定了域名，但是提示500错误，如下图：

![Image](https://github.com/user-attachments/assets/77f3c36a-aebe-4910-a596-c3487b9dcf4f)

同时，设置里面不能正常加载出模型供应商，点击市场的话地址是127...本地地址如下图：

![Image](https://github.com/user-attachments/assets/39776fec-371a-4253-b30e-9fbdf576b618)

**Comment by AreChen** [comment]
> [@dosu](https://github.com/dosu) 我也遇到这个问题，新安装绑定了域名，但是提示500错误，如下图：
> 
> ![Image](https://github.com/user-attachments/assets/77f3c36a-aebe-4910-a596-c3487b9dcf4f)
> 
> 同时，设置里面不能正常加载出模型供应商，点击市场的话地址是127...本地地址如下图：
> 
> ![Image](https://github.com/user-attachments/assets/39776fec-371a-4253-b30e-9fbdf576b618)

你这个应该是没做插件迁移安装

**Comment by YunFenLei** [comment]
@AreChen 我这个是全新安装，不存在插件迁移吧？

**Comment by xuesd** [comment]
The issue of not finding the plugin can be checked to see if there is an. env. local file in the web folder

**Comment by YunFenLei** [comment]
@xuesd 我删除镜像重新安装看看，反正是学习测试。

**Comment by xuesd** [comment]
Docker deployment method, please check if cp. env. example. env has been executed in the Docker folder

**Comment by crazyFeng** [comment]
same problem， 重启后正常了

**Comment by YunFenLei** [comment]
@crazyFeng 重启docker 还是dify容器~

**Comment by crazyFeng** [comment]
@YunFenLei  
steps:
1. docker compose stop
2. docker compose up -d

**Comment by YunFenLei** [comment]
@crazyFeng 重装，重启都未能解决这个问题，感谢解答，等官方看看吧！

**Comment by xuesd** [comment]
@YunFenLei 检查是否存在.env文件

**Comment by YunFenLei** [comment]
@xuesd 

![Image](https://github.com/user-attachments/assets/08777e70-41cc-4e42-ad05-d2d29dc46aef)

**Comment by dukun1224** [comment]
api日志：

2025-03-01 16:33:52 2025-03-01 08:33:52.226 ERROR [Dummy-13] [app.py:875] - Exception on /console/api/workspaces/current/model-providers/langgenius/tongyi/tongyi [POST]
2025-03-01 16:33:52 Traceback (most recent call last):
2025-03-01 16:33:52   File "/app/api/.venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
2025-03-01 16:33:52     rv = self.dispatch_request()
2025-03-01 16:33:52          ^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 16:33:52   File "/app/api/.venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
2025-03-01 16:33:52     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
2025-03-01 16:33:52            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 16:33:52   File "/app/api/.venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 489, in wrapper
2025-03-01 16:33:52     resp = resource(*args, **kwargs)
2025-03-01 16:33:52            ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 16:33:52   File "/app/api/.venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
2025-03-01 16:33:52     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
2025-03-01 16:33:52            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 16:33:52   File "/app/api/.venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
2025-03-01 16:33:52     resp = meth(*args, **kwargs)
2025-03-01 16:33:52            ^^^^^^^^^^^^^^^^^^^^^
2025-03-01 16:33:52   File "/app/api/controllers/console/wraps.py", line 147, in decorated
2025-03-01 16:33:52     return view(*args, **kwargs)
2025-03-01 16:33:52            ^^^^^^^^^^^^^^^^^^^^^
2025-03-01 16:33:52   File "/app/api/libs/login.py", line 94, in decorated_view
2025-03-01 16:33:52     return current_app.ensure_sync(func)(*args, **kwargs)
2025-03-01 16:33:52            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 16:33:52   File "/app/api/controllers/console/wraps.py", line 27, in decorated
2025-03-01 16:33:52     return view(*args, **kwargs)
2025-03-01 16:33:52            ^^^^^^^^^^^^^^^^^^^^^
2025-03-01 16:33:52   File "/app/api/controllers/console/workspace/model_providers.py", line 102, in post
2025-03-01 16:33:52     model_provider_service.save_provider_credentials(
2025-03-01 16:33:52   File "/app/api/services/model_provider_service.py", line 145, in save_provider_credentials
2025-03-01 16:33:52     provider_configuration.add_or_update_custom_credentials(credentials)
2025-03-01 16:33:52   File "/app/api/core/entities/provider_configuration.py", line 248, in add_or_update_custom_credentials
2025-03-01 16:33:52     provider_record, credentials = self.custom_credentials_validate(credentials)
2025-03-01 16:33:52                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 16:33:52   File "/app/api/core/entities/provider_configuration.py", line 231, in custom_credentials_validate
2025-03-01 16:33:52     credentials = model_provider_factory.provider_credentials_validate(
2025-03-01 16:33:52                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-03-01 16:33:52   File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 155, in provider_credentials_validate
2025-03-01 16:33:52     self.plugin_model_manager.validate_provider_credentials(
2025-03-01 16:33:52   File "/app/api/core/plugin/manager/model.py", line 97, in validate_provider_credentials
2025-03-01 16:33:52     for resp in response:
2025-03-01 16:33:52                 ^^^^^^^^
2025-03-01 16:33:52   File "/app/api/core/plugin/manager/base.py", line 189, in _request_with_plugin_daemon_response_stream
2025-03-01 16:33:52     self._handle_plugin_daemon_error(error.error_type, error.message)
2025-03-01 16:33:52   File "/app/api/core/plugin/manager/base.py", line 223, in _handle_plugin_daemon_error
2025-03-01 16:33:52     raise PluginDaemonInternalServerError(description=message)
2025-03-01 16:33:52 core.plugin.manager.exc.PluginDaemonInternalServerError: PluginDaemonInternalServerError: killed by timeout

**Comment by hjqcn** [comment]
昨天安装了1.0.0，好垃圾，
1是原来旧版的数据没了，
2模型做为插件安装两次才装上，安装上插件之后是模型死活都添加不上

**Comment by ft4710403** [comment]
me too

**Comment by maruilav** [comment]
me too

**Comment by dukun1224** [comment]
大家都遇到模型秘钥不可以配置的问题了吗

**Comment by 52learn** [comment]
me too .   that is a serious issue , pls resolve it as soon as possible!!! 
`
2025-03-01 00:00:33.961 ERROR [Dummy-11] [app.py:875] - Exception on /console/api/workspaces/current/model-providers/langgenius/tongyi/tongyi/models [POST]
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/controllers/console/wraps.py", line 147, in decorated
    return view(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/libs/login.py", line 94, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/controllers/console/wraps.py", line 27, in decorated
    return view(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/controllers/console/workspace/models.py", line 154, in post
    model_provider_service.save_model_credentials(
  File "/app/api/services/model_provider_service.py", line 237, in save_model_credentials
    provider_configuration.add_or_update_custom_model_credentials(
  File "/app/api/core/entities/provider_configuration.py", line 406, in add_or_update_custom_model_credentials
    provider_model_record, credentials = self.custom_model_credentials_validate(model_type, model, credentials)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/entities/provider_configuration.py", line 386, in custom_model_credentials_validate
    credentials = model_provider_factory.model_credentials_validate(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 190, in model_credentials_validate
    self.plugin_model_manager.validate_model_credentials(
  File "/app/api/core/plugin/manager/model.py", line 137, in validate_model_credentials
    for resp in response:
                ^^^^^^^^
  File "/app/api/core/plugin/manager/base.py", line 189, in _request_with_plugin_daemon_response_stream
    self._handle_plugin_daemon_error(error.error_type, error.message)
  File "/app/api/core/plugin/manager/base.py", line 223, in _handle_plugin_daemon_error
    raise PluginDaemonInternalServerError(description=message)
core.plugin.manager.exc.PluginDaemonInternalServerError: PluginDaemonInternalServerError: killed by timeout
`

**Comment by 52learn** [comment]
Too many people have encountered the same problem, why hasn't there been any progress yet!!!  we are all waiting for it online!!!!

**Comment by martin666888** [comment]
Is version 1.0.0 not yet ready?

**Comment by AreChen** [comment]
```
  # Frontend web application.
  web:
    image: langgenius/dify-web:1.0.0
    restart: always
    environment:
      CONSOLE_API_URL: ${CONSOLE_API_URL:-}
      APP_API_URL: ${APP_API_URL:-}
      SENTRY_DSN: ${WEB_SENTRY_DSN:-}
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED:-0}
      TEXT_GENERATION_TIMEOUT_MS: ${TEXT_GENERATION_TIMEOUT_MS:-60000}
      CSP_WHITELIST: ${CSP_WHITELIST:-}
      MARKETPLACE_API_URL: ${MARKETPLACE_API_URL:-https://marketplace.dify.ai}
      MARKETPLACE_URL: ${MARKETPLACE_URL:-https://marketplace.dify.ai}
      TOP_K_MAX_VALUE: ${TOP_K_MAX_VALUE:-}
      INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH: ${INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH:-}
      PM2_INSTANCES: ${PM2_INSTANCES:-2}
      # example: http://udify.app/api
      NEXT_PUBLIC_PUBLIC_API_PREFIX: https://your.domin.com/api
      # The API PREFIX for MARKETPLACE
      NEXT_PUBLIC_MARKETPLACE_API_PREFIX: https://marketplace.dify.ai/api/v1
      # The URL for MARKETPLACE
      NEXT_PUBLIC_MARKETPLACE_URL_PREFIX: https://marketplace.dify.ai
```

docker compose里更新以下这些环境参数试试
Try updating these environment variables in docker compose.

**Comment by YunFenLei** [comment]
> > 昨天安装了1.0.0，好垃圾， 1是原来旧版的数据没了， 2模型做为插件安装两次才装上，安装上插件之后是模型死活都添加不上
> 
> 模型插件安装的很慢，没有进度显示，所以点了两次等了很久才行。 模型Key设置时要打开5003端口，否则就是设置不上去， 两大坑

我是安装都没装好哈哈，这个1.0太草率拉！

**Comment by xuesd** [comment]
@YunFenLei 你可以添加模型了吗？

**Comment by dukun1224** [comment]
> > 昨天安装了1.0.0，好垃圾， 1是原来旧版的数据没了， 2模型做为插件安装两次才装上，安装上插件之后是模型死活都添加不上
> 
> 模型插件安装的很慢，没有进度显示，所以点了两次等了很久才行。 模型Key设置时要打开5003端口，否则就是设置不上去， 两大坑

你可以添加模型秘钥了吗？你是windows 部署的还是？

**Comment by xuesd** [comment]
不论是本地的ollama还是阿里云的通义千问api，我都还添加不了。windows和Ubuntu我都部署了

**Comment by xuesd** [comment]
这几天已经部署好多次了，都是这个问题。一开始没人问过这个问题我就已经遇到了。我还怀疑是我自己的问题，重新部署了好几次
I have deployed it many times in the past few days, and it has always been this issue. At the beginning, no one asked me this question, but I already encountered it. I still suspected it was my own fault and redeployed several times

**Comment by 52learn** [comment]
> 5003

你好，dify相关容器如图所示：

![Image](https://github.com/user-attachments/assets/a0451675-f37b-4878-bac7-bba396aa1126)

也打开了5003端口，还是存在一样问题

**Comment by YunFenLei** [comment]
> > 5003
> 
> 你好，dify相关容器如图所示：
> 
> ![Image](https://github.com/user-attachments/assets/a0451675-f37b-4878-bac7-bba396aa1126)
> 
> 也打开了5003端口，还是存在一样问题

感觉这是官方的bug 不是我们的问题嘿嘿！

**Comment by 51302890** [comment]
安装了1.0.0用不了，又从新安装0.15.3，也不行了，很无语

**Comment by ganjiayi** [comment]
绝对是个大坑，玛德！验证API Key怎么走的是本地的URL啊？

**Comment by cwjcharles** [comment]
我也是这个问题   dify更新到1.0后，火山模型无法使用，添加模式的时候，提示internal server error，之前是正常的，而且我重新添加了其他模型也是正常的，用兼容 openai 的接口添加火山模型反而是正常的

**Comment by JasonkayZK** [comment]
Same issue here, any solution?

**Comment by zorn-zhao** [comment]
1、docker compose 方式本地部署dify 1.0版本 模型的api key 添加不上
2、安装模型插件时打开代理安装的很快，但不开代理安装不上，下载模型插件到本地，从本地安装，不成功

**Comment by YunFenLei** [comment]
> 1、docker compose 方式本地部署dify 1.0版本 模型的api key 添加不上 2、安装模型插件时打开代理安装的很快，但不开代理安装不上，下载模型插件到本地，从本地安装，不成功

周末，等他们上班吧，估计在处理商业版的bug！

**Comment by hjqcn** [comment]
> > 1、docker compose 方式本地部署dify 1.0版本 模型的api key 添加不上 2、安装模型插件时打开代理安装的很快，但不开代理安装不上，下载模型插件到本地，从本地安装，不成功
> 
> 周末，等他们上班吧，估计在处理商业版的bug！

啊？，商业片还有很多BUG吗？这次1.0.0真的有点急躁和草率啊。

**Comment by FerretAngel** [comment]
+1

**Comment by qzzq2002** [comment]
me too

**Comment by LanYu4qz** [comment]
me too

**Comment by wubucheng** [comment]
点击安装插件提示成功，实际上是出于安装过程中，去插件管理看了一下，安装过程很慢，而且容易安装失败

**Comment by caixiaomao** [comment]
一样的问题，停止、重启也还是一样的问题

**Comment by HeartIsBeat** [comment]
+1

**Comment by crazywoola** [comment]
Try https://github.com/langgenius/dify/issues/14736#issuecomment-2693905382 & https://github.com/langgenius/dify/issues/14682#issuecomment-2694019566

**Comment by yangshuo-1004** [comment]
> 大家都遇到模型秘钥不可以配置的问题了吗

遇到了，解决不了啊

**Comment by forachange** [comment]
mark，看看啥时候有解决方案

**Comment by dcxs** [comment]
+1

**Comment by hunkwang** [comment]
1. Check if /dify/docker/.env exists - it does
2. Restart
docker compose stop
docker compose up -d
3. Uninstall the plugin and reinstall it
4. The Tongyi Qianwen plugin still reports an error, downgrade to version 0.4 and continue installation
5. Success

**Comment by leadroy** [comment]
This 1.0 release is very disappointing and I hope to complete the fix soon. It was originally planned to go online, but now it seems that it will have to wait, and it is very unstable.

**Comment by huangsijun17** [comment]
查阅Docker下插件相关容器日志`docker logs docker-plugin_daemon-1`，若存在大量近期日志，切分部存在初始化错误，则大概率为插件初始化问题。等待若干小时，有概率初始化成功。对应插件初始化成功后即可导入秘钥。
---

个人怀疑，插件初始化时需要下载文件，网络问题导致初始化超时？插件初始化状态不在插件列表显示，导致误以为“安装成功“？

**Comment by sevck** [comment]
+1 
I have a question, why do I need to request “Marketplaces.dify.ai” when I add AI model keys
==================

`requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='marketplace.dify.ai', port=443): Max retries exceeded with url: /api/v1/plugins/batch (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f457e784f20>, 'Connection to marketplace.dify.ai timed out. (connect timeout=None)'))
2025-03-06 10:45:29.325 ERROR [Dummy-4] [app.py:875] - Exception on /console/api/workspaces/current/model-providers/langgenius/azure_openai/azure_openai/models [POST]
Traceback (most recent call last):
  File "/app/api/.venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/.venv/lib/python3.12/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/controllers/console/wraps.py", line 147, in decorated
    return view(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/libs/login.py", line 94, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/controllers/console/wraps.py", line 27, in decorated
    return view(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/controllers/console/workspace/models.py", line 154, in post
    model_provider_service.save_model_credentials(
  File "/app/api/services/model_provider_service.py", line 237, in save_model_credentials
    provider_configuration.add_or_update_custom_model_credentials(
  File "/app/api/core/entities/provider_configuration.py", line 406, in add_or_update_custom_model_credentials
    provider_model_record, credentials = self.custom_model_credentials_validate(model_type, model, credentials)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/entities/provider_configuration.py", line 386, in custom_model_credentials_validate
    credentials = model_provider_factory.model_credentials_validate(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/model_runtime/model_providers/model_provider_factory.py", line 190, in model_credentials_validate
    self.plugin_model_manager.validate_model_credentials(
  File "/app/api/core/plugin/manager/model.py", line 137, in validate_model_credentials
    for resp in response:
                ^^^^^^^^
  File "/app/api/core/plugin/manager/base.py", line 189, in _request_with_plugin_daemon_response_stream
    self._handle_plugin_daemon_error(error.error_type, error.message)
  File "/app/api/core/plugin/manager/base.py", line 223, in _handle_plugin_daemon_error
    raise PluginDaemonInternalServerError(description=message)
core.plugin.manager.exc.PluginDaemonInternalServerError: PluginDaemonInternalServerError: killed by timeout`

**Comment by dofospider** [comment]
官方对于windows的docker部署推荐在wsl2的子系统内建立docker 容器，这样建立后的文件都在wsl的内部，大家尝试一下，可以解决很多问题。

**Comment by cleverdouble** [comment]
![Image](https://github.com/user-attachments/assets/c237a432-0619-468a-b5c3-27ae0fd9c52e)

**Comment by jackyzzy** [comment]
同样的问题，想退回到0.15.3，发现还退回不了。

**Comment by sevck** [comment]
我解决了，插件的docker配置http/https代理，配置一下pip的源环境变量就可以了

**Comment by shiliu2023** [comment]
还没好吗？！1.0.1也还是不行！

**Comment by sevck** [comment]
in version 1.0.1:
```
 # plugin daemon
  plugin_daemon:
    image: langgenius/dify-plugin-daemon:07d13bfb59acc422afa06436c7fdc5f3bc7e6554-local
    restart: always
    environment:
      # Use the shared environment variables.
      <<: *shared-api-worker-env
      PIP_INDEX_URL: 'https://mirrors.aliyun.com/pypi/simple/'
      DB_DATABASE: ${DB_PLUGIN_DATABASE:-dify_plugin}
      SERVER_PORT: ${PLUGIN_DAEMON_PORT:-5002}
      SERVER_KEY: ${PLUGIN_DAEMON_KEY:-lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi}
      MAX_PLUGIN_PACKAGE_SIZE: ${PLUGIN_MAX_PACKAGE_SIZE:-52428800}
      PPROF_ENABLED: ${PLUGIN_PPROF_ENABLED:-false}
      DIFY_INNER_API_URL: ${PLUGIN_DIFY_INNER_API_URL:-http://api:5001}
      DIFY_INNER_API_KEY: ${PLUGIN_DIFY_INNER_API_KEY:-QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1}
      PLUGIN_REMOTE_INSTALLING_HOST: ${PLUGIN_DEBUGGING_HOST:-0.0.0.0}
      PLUGIN_REMOTE_INSTALLING_PORT: ${PLUGIN_DEBUGGING_PORT:-5003}
      PLUGIN_WORKING_PATH: ${PLUGIN_WORKING_PATH:-/app/storage/cwd}
      FORCE_VERIFYING_SIGNATURE: ${FORCE_VERIFYING_SIGNATURE:-true}
      PYTHON_ENV_INIT_TIMEOUT: ${PLUGIN_PYTHON_ENV_INIT_TIMEOUT:-120}
      PLUGIN_MAX_EXECUTION_TIMEOUT: ${PLUGIN_MAX_EXECUTION_TIMEOUT:-600}
      PIP_MIRROR_URL: ${PIP_MIRROR_URL:-}
      http_proxy: 1xxxxx5:6666
      https_proxy: 1xxx.xxx.xx.x:6666
    ports:
      - "${EXPOSE_PLUGIN_DEBUGGING_PORT:-5003}:${PLUGIN_DEBUGGING_PORT:-5003}"
    volumes:
      - ./volumes/plugin_daemon:/app/storage
    depends_on:
      - db

```
