### ISSUE TITLE
Can not Setting Ollama Model

### ISSUE THREAD

**Issue by xyweiii** [langgenius/dify#14978]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

v1.0.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

when I start settingup  ollama model, I setting the  Model Name and.,Model Url, Then  Click the   Save Button, but it not effect

<img width="1102" alt="Image" src="https://github.com/user-attachments/assets/fb9ea5ad-b129-4d2c-a766-d35b26582040" />

### ✔️ Expected Behavior

when I start settingup  ollama model, I setting the  Model Name and.,Model Url, Then  Click the   Save Button, but it not effect

<img width="1102" alt="Image" src="https://github.com/user-attachments/assets/9e31404f-c414-4503-a2e1-1440dbc68660" />

**Comment by crazywoola** [comment]
What is `Model Url` in your screenshot?

**Comment by IEEE1394-KKND** [comment]
![Image](https://github.com/user-attachments/assets/f331e1b2-e71b-4f0d-a469-a046524eb9ee)

**Comment by crazywoola** [comment]
This seems a network issue to me, I can not reproduce this after a fresh install.

**Comment by myavier** [comment]
Hi,I got the same issue, install by using docker in Windows . I try to use curl  in the docker container and get a normal reponse. I guess it's not a problem of nework addr , I found no exception log  in the API & WEB service.

![Image](https://github.com/user-attachments/assets/2afedb9b-f47b-4609-bdd4-4ce643caf45c)

**Comment by myavier** [comment]
Hi I have the same problem, and I try to curl ollama api url in the container, can get a normal response from the interface, I guess the network is fine. No exception log was found in the API&WEB service.

![Image](https://github.com/user-attachments/assets/f3c2cb9c-d114-46ef-9f5f-9c05b2e70735)

**Comment by xyweiii** [comment]
> 您的屏幕截图里有什么`Model Url`？
This model was deployed on my local machine
<img width="646" alt="Image" src="https://github.com/user-attachments/assets/657715ec-7925-400c-b03c-edccd481c8ec" />

**Comment by xyweiii** [comment]
> What is `Model Url` in your screenshot?

This model was deployed on my local machine

<img width="715" alt="Image" src="https://github.com/user-attachments/assets/0bff3d35-3822-4273-86a6-879d712f77a1" />

**Comment by xyweiii** [comment]
> [@xyweiii](https://github.com/xyweiii)您好！我在这里帮助您解决任何错误、问题或贡献。让我们一起解决您的问题。
> 
> 我发现了一些可能与您的问题相关的类似讨论：
> 
> 1. [添加 ollama 模型时出错](https://github.com/langgenius/dify/discussions/14104)- 此讨论仍然开放，可能会提供对类似问题的见解。
> 2. [保存模型时请求超时的原因是什么？](https://github.com/langgenius/dify/discussions/14017) - 这是另一个可能与您的问题相关的开放式讨论。
> 3. [无法添加 Ollama 模型](https://github.com/langgenius/dify/discussions/12336)- 此讨论也是开放的，可能包含有用的信息。
> 
> 要在 Dify 中设置 Ollama 模型，请确保您已遵循以下步骤：
> 
> 1. **下载并运行 Ollama**：确保 Ollama 客户端正在运行并可在本地端口 11434 上访问。
> 2. **配置 Dify** : 在 Dify 的设置中，输入正确的模型名称和基本 URL。如果使用 Docker，请替换`localhost`为`host.docker.internal`。
> 3. **网络配置**：确保`OLLAMA_HOST`环境变量设置为`0.0.0.0`允许从其他机器访问，并且防火墙设置中端口 11434 已打开。
> 
> 如果“保存”按钮未应用更改，则可能是由于网络配置问题或模型配置界面中的设置不正确。请仔细检查模型名称和 URL 字段的准确性，并确保网络设置配置正确[[1] ](https://github.com/langgenius/dify/issues/14330)[[2]](https://github.com/langgenius/dify-docs/blob/main/en/development/models-integration/ollama.md)。
> 
> _要继续与[Dosu](https://dosu.dev)交谈，请提及[@dosu](https://github.com/dosu)。_
> 
> 帮助 Dosu 学习！提供反馈：[很好的回应](https://app.dosu.dev/response-feedback/f0778617-51d1-4271-80a9-74f46cc56a75?feedback_type=great_response)|[不相关的答案](https://app.dosu.dev/response-feedback/f0778617-51d1-4271-80a9-74f46cc56a75?feedback_type=irrelevant_answer)|[不正确的来源](https://app.dosu.dev/response-feedback/f0778617-51d1-4271-80a9-74f46cc56a75?feedback_type=incorrect_sources)|[太冗长](https://app.dosu.dev/response-feedback/f0778617-51d1-4271-80a9-74f46cc56a75?feedback_type=too_verbose)|[幻觉](https://app.dosu.dev/response-feedback/f0778617-51d1-4271-80a9-74f46cc56a75?feedback_type=hallucination)|[错误报告](https://app.dosu.dev/response-feedback/f0778617-51d1-4271-80a9-74f46cc56a75?feedback_type=bug_report)|[其他](https://app.dosu.dev/response-feedback/f0778617-51d1-4271-80a9-74f46cc56a75?feedback_type=other)


I  confirm the port  11434 is open , and when the version V0.15.3 is Ok .

**Comment by Dmitry-Diordychuk** [comment]
```yaml
docker-compose.yaml
...
...
...
# plugin daemon
plugin_daemon:
  image: langgenius/dify-plugin-daemon:0.0.3-local
  restart: always
  environment:
    # Use the shared environment variables.
    <<: *shared-api-worker-env
    DB_DATABASE: ${DB_PLUGIN_DATABASE:-dify_plugin}
    SERVER_PORT: ${PLUGIN_DAEMON_PORT:-5002}
    SERVER_KEY: ${PLUGIN_DAEMON_KEY:-lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi}
    MAX_PLUGIN_PACKAGE_SIZE: ${PLUGIN_MAX_PACKAGE_SIZE:-52428800}
    PPROF_ENABLED: ${PLUGIN_PPROF_ENABLED:-false}
    DIFY_INNER_API_URL: ${PLUGIN_DIFY_INNER_API_URL:-http://api:5001}
    DIFY_INNER_API_KEY: ${INNER_API_KEY_FOR_PLUGIN:-QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1}
    PLUGIN_REMOTE_INSTALLING_HOST: ${EXPOSE_PLUGIN_DEBUGGING_HOST:-localhost}
    PLUGIN_REMOTE_INSTALLING_PORT: ${EXPOSE_PLUGIN_DEBUGGING_PORT:-5003}
    PLUGIN_WORKING_PATH: ${PLUGIN_WORKING_PATH:-/app/storage/cwd}
    PLUGIN_MAX_EXECUTION_TIMEOUT: 2400 <--------------------------------------------------------------------------------------------------------------------------------
    FORCE_VERIFYING_SIGNATURE: ${FORCE_VERIFYING_SIGNATURE:-true}
  ports:
    - "${EXPOSE_PLUGIN_DEBUGGING_PORT:-5003}:${PLUGIN_DEBUGGING_PORT:-5003}"
  volumes:
    - ./volumes/plugin_daemon:/app/storage
...
...
...
```
