### ISSUE TITLE
Failed to invoke tool: Failed to invoke tool: Output variable `result[0]` must be a string

### ISSUE THREAD

**Issue by rainvstar** [langgenius/dify#15227]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.0.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/92935626-fc9b-4d1f-a9aa-c33130a37c54)
I hava a workflow, the output is Array[Object]。I publish this workflow as a tool。
when I use this tool in another workflow ,it goes wrong.

![Image](https://github.com/user-attachments/assets/86b41fb8-dce0-44d7-bab5-2b0e13d7f1e4)
Failed to invoke tool: Failed to invoke tool: Output variable `result[0]` must be a string

I don't understand how to deliever the output。

**Comment by rainvstar** [comment]
> Hello, [@rainvstar](https://github.com/rainvstar)! I'm here to help you with your bug report and answer any questions you may have. Let's work together to resolve the issue you're facing.
> 
> To resolve the issue where the output variable `result[0]` must be a string, you need to transform the `Array[Object]` output into a text format. This is necessary because the Dify workflow output panel only supports text or file outputs directly.
> 
> You can achieve this transformation by using a template node or a code node. Here's an example of how you can use a code node to convert the array into a string:
> 
> def main(result: list):
>     # Assuming result is a list of objects, convert each object to a string representation
>     return {
>         "result": "\n".join([str(item) for item in result])
>     }
> This script takes each object in the array, converts it to a string, and joins them with newline characters. Alternatively, you can use a template node to achieve a similar transformation [[1]](https://github.com/langgenius/dify/issues/12682).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention [@dosu](https://github.com/dosu)._
> 
> Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/12710ebb-75f3-4983-a18b-fcf883a67720?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/12710ebb-75f3-4983-a18b-fcf883a67720?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/12710ebb-75f3-4983-a18b-fcf883a67720?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/12710ebb-75f3-4983-a18b-fcf883a67720?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/12710ebb-75f3-4983-a18b-fcf883a67720?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/12710ebb-75f3-4983-a18b-fcf883a67720?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/12710ebb-75f3-4983-a18b-fcf883a67720?feedback_type=other)



I return as string, but it still not work。

![Image](https://github.com/user-attachments/assets/9974b546-02a3-4170-97ca-8e7e14b7dcb6)
![Image](https://github.com/user-attachments/assets/9ffdf08d-9528-4bbd-8b96-098630a78b25)
![Image](https://github.com/user-attachments/assets/d8e5f23a-5aa0-42b2-b324-a1ba89ecd472)

**Comment by rainvstar** [comment]
@dosubot @crazywoola 
my python code:
```
import requests
import json

def main(sql: str) -> dict:
    url = 'http://host.docker.internal:5000/query'
    headers = {'Content-Type': 'application/json'}
    data = {'sql': sql}
    print('开始执行查询')
    response = requests.post(url, headers=headers, data=json.dumps(data))
    res = response.json()
    print(res)
    return {
        'result': "\n".join([str(item) for item in res])
    }
    # return {'result':sql}

```
result
`{
  "result": "{'group_id': 'group_001', 'group_name': '中美关系深度探讨群', 'group_nickname': '群主-张建国', 'join_time': 'Thu, 06 Mar 2025 16:00:01 GMT', 'wechat_id': 'user001'}\n{'group_id': 'group_001', 'group_name': '中美关系深度探讨群', 'group_nickname': '群员-李华', 'join_time': 'Thu, 06 Mar `2025` 16:00:01 GMT', 'wechat_id': 'user002'}\n{'group_id': 'group_001', 'group_name': '中美关系深度探讨群', 'group_nickname': '群员-王芳', 'join_time': 'Thu, 06 Mar 2025 16:00:01 GMT', 'wechat_id': 'user003'}\n{'group_id': 'group_001', 'group_name': '中美关系深度探讨群', 'group_nickname': '群员-陈刚', 'join_time': 'Thu, 06 Mar 2025 16:00:01 GMT', 'wechat_id': 'user004'}\n{'group_id': 'group_001', 'group_name': '中美关系深度探讨群', 'group_nickname': '群员-孙阳', 'join_time': 'Thu, 06 Mar 2025 16:00:01 GMT', 'wechat_id': 'user100'}"
}`

I had convert the array into a string, but it still not work when i use this workflow as tool in another workflow.

**Comment by rainvstar** [comment]
@dosubot @crazywoola 
this is my work flow, the definition of the output result type is string. I can' find where is the problem.
```
app:
  description: 输入sql，返回查询结果
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: Sql查询
  use_icon_as_answer_icon: false
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: code
        targetType: end
      id: 1741254243163-source-1741593203734-target
      source: '1741254243163'
      sourceHandle: source
      target: '1741593203734'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1741250705858-source-1741254243163-target
      source: '1741250705858'
      sourceHandle: source
      target: '1741254243163'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - label: sql
          max_length: 256
          options: []
          required: true
          type: text-input
          variable: sql
      height: 89
      id: '1741250705858'
      position:
        x: 304.49464086611715
        y: 328.84912107878586
      positionAbsolute:
        x: 304.49464086611715
        y: 328.84912107878586
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        code: "import requests\nimport json\n\ndef main(sql: str) -> dict:\n    url\
          \ = 'http://host.docker.internal:5000/query'\n    headers = {'Content-Type':\
          \ 'application/json'}\n    data = {'sql': sql}\n    print('开始执行查询')\n  \
          \  response = requests.post(url, headers=headers, data=json.dumps(data))\n\
          \    res = response.json()\n    print(res)\n    return {\n        'result':\
          \ \"\\n\".join([str(item) for item in res])\n    }\n    # return {'result':sql}\n\
          \    "
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 代码执行
        type: code
        variables:
        - value_selector:
          - '1741250705858'
          - sql
          variable: sql
      height: 53
      id: '1741254243163'
      position:
        x: 677.6039921567362
        y: 356.07478520348894
      positionAbsolute:
        x: 677.6039921567362
        y: 356.07478520348894
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1741254243163'
          - result
          variable: result
        selected: false
        title: 结束
        type: end
      height: 89
      id: '1741593203734'
      position:
        x: 1088.2198683789743
        y: 356.07478520348894
      positionAbsolute:
        x: 1088.2198683789743
        y: 356.07478520348894
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    viewport:
      x: -271.54428042654354
      y: -151.83071563197592
      zoom: 1.1486983549970362

```

another workflow where to use the above tool
```
app:
  description: '23232'
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: test
  use_icon_as_answer_icon: false
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: tool
      id: 1741335806041-source-1741590655895-target
      source: '1741335806041'
      sourceHandle: source
      target: '1741590655895'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: tool
        targetType: code
      id: 1741590655895--1741590681337-target
      source: '1741590655895'
      sourceHandle: source
      target: '1741590681337'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: end
      id: 1741590681337-source-1741590743086-target
      source: '1741590681337'
      sourceHandle: source
      target: '1741590743086'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - label: sql
          max_length: 200
          options: []
          required: true
          type: paragraph
          variable: sql
      height: 89
      id: '1741335806041'
      position:
        x: 142
        y: 168
      positionAbsolute:
        x: 142
        y: 168
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        desc: ''
        provider_id: 46de781a-dafd-4093-bb10-59e15510980f
        provider_name: Sql查询服务
        provider_type: workflow
        selected: false
        title: Sql查询服务
        tool_configurations: {}
        tool_label: Sql查询服务
        tool_name: sqlQuery
        tool_parameters:
          sql:
            type: mixed
            value: '{{#1741335806041.sql#}}'
        type: tool
      height: 53
      id: '1741590655895'
      position:
        x: 441.96856686697913
        y: 168
      positionAbsolute:
        x: 441.96856686697913
        y: 168
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        code: "\ndef main(text: str) -> dict:\n    return {\n        \"result\": text,\n\
          \    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: true
        title: 代码执行
        type: code
        variables:
        - value_selector:
          - '1741590655895'
          - text
          variable: text
      height: 53
      id: '1741590681337'
      position:
        x: 748
        y: 168
      positionAbsolute:
        x: 748
        y: 168
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1741590655895'
          - text
          variable: text
        selected: false
        title: 结束
        type: end
      height: 89
      id: '1741590743086'
      position:
        x: 1051
        y: 168
      positionAbsolute:
        x: 1051
        y: 168
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    viewport:
      x: 82.24938427357768
      y: 199.67785567733603
      zoom: 0.6597539553864472
```
