### ISSUE TITLE
Workflow exception capture fails

### ISSUE THREAD

**Issue by auxpd** [langgenius/dify#15252]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.0.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

As shown in the figure, set up a workflow that handles branches when there is an exception

<img width="599" alt="Image" src="https://github.com/user-attachments/assets/757f8646-498c-40af-a1d4-87b83b23ae5b" />

### ✔️ Expected Behavior

When the node is abnormal, it can correctly enter the abnormal branch for processing

### ❌ Actual Behavior

An error is reported for the entire workflow

<img width="601" alt="Image" src="https://github.com/user-attachments/assets/860ca75f-4b10-4164-adb5-611d620a16be" />

**Comment by auxpd** [comment]
In versions before 1.0.0, exceptions are normally caught and entered into the exception branch, and an error is reported in 1.0.0, and the entire workflow is terminated directly

**Comment by QuantumGhost** [comment]
@auxpd Hi there,

To better assist with troubleshooting this issue, could you please create a minimal reproducible workflow and export it using the "Export DSL" feature?

You can find detailed instructions on how to export DSL in our documentation:
[Exporting Application](https://docs.dify.ai/guides/management/app-management#exporting-application)

This will help us investigate the workflow behavior more effectively.

**Comment by auxpd** [comment]
```
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: test_workflow
  use_icon_as_answer_icon: false
dependencies: []
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 40
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: tool
      id: 1741772703514-source-1741772709537-target
      source: '1741772703514'
      sourceHandle: source
      target: '1741772709537'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: tool
        targetType: end
      id: 1741772709537-source-1741772714273-target
      source: '1741772709537'
      sourceHandle: source
      target: '1741772714273'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: tool
        targetType: code
      id: 1741772709537-fail-branch-1741772720383-target
      source: '1741772709537'
      sourceHandle: fail-branch
      target: '1741772720383'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: code
        targetType: end
      id: 1741772720383-source-1741772714273-target
      source: '1741772720383'
      sourceHandle: source
      target: '1741772714273'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables: []
      height: 54
      id: '1741772703514'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        error_strategy: fail-branch
        is_team_authorization: true
        output_schema: null
        paramSchemas: []
        params: {}
        provider_id: 46abc33c-a194-4aaf-a123-d85ee64b6850
        provider_name: test_tool_workflow
        provider_type: workflow
        selected: false
        title: test_tool_workflow
        tool_configurations: {}
        tool_label: test_tool_workflow
        tool_name: test_tool_workflow
        tool_parameters: {}
        type: tool
      height: 90
      id: '1741772709537'
      position:
        x: 384
        y: 282
      positionAbsolute:
        x: 384
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs: []
        selected: false
        title: 结束
        type: end
      height: 54
      id: '1741772714273'
      position:
        x: 1229
        y: 292
      positionAbsolute:
        x: 1229
        y: 292
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main() -> dict:\n    return {\n        \"result\": “”,\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: true
        title: 异常出现后处理节点
        type: code
        variables: []
      height: 54
      id: '1741772720383'
      position:
        x: 675
        y: 434
      positionAbsolute:
        x: 675
        y: 434
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -114
      y: 1
      zoom: 1
```
