### ISSUE TITLE
http/https proxy cannot be configured in a private docker environment

### ISSUE THREAD

**Issue by sevck** [langgenius/dify#15600]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.0.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

My environment: docker
Usage version: 1.0.1

Background: My docker environment does not have direct access to the Internet, but can use proxies. I configured http in the.env file:
<img width="628" alt="Image" src="https://github.com/user-attachments/assets/6478ee8d-2b79-4e4f-a8dc-538b1d878b2a" />
But there's a hint.

![Image](https://github.com/user-attachments/assets/5fc4aed3-03b7-4b0b-aca9-7f9b1518b0b9)

How to use proxies correctly
The agent cannot access dify.ai, I can choose to upload and install the plugin locally,
But it seems that some pip dependencies need to be installed, and that adding an Azure OpenAI Service Model requires access to my docker is configured with a proxy

I have seen many issues, including the official document: https://docs.dify.ai/zh-hans/getting-started/install-self-hosted/environments
And part of the configuration of squid, are not successful, how to use correctly

### ✔️ Expected Behavior

Want to be able to install plug-in dependencies
Expect the plug-in to use the proxy normally

### ❌ Actual Behavior

docker-plugin_daemon-1  has a prompt:
```
[ERROR]init environment failed: failed to install dependencies: exit status 2, output: error: unexpected argument '--proxy' found

  tip: a similar argument exists: '--prefix'

Usage: uv pip install --prefix <PREFIX> <PACKAGE|--requirements <REQUIREMENTS>|--editable <EDITABLE>>

For more information, try '--help'.
, retry in 30s

```

**Comment by sevck** [comment]
In 1.0.0, I was able to modify the environment variables, but in 1.0.1 I can't use them anymore:
docker-compose.yaml
```
  # plugin daemon
  plugin_daemon:
    image: langgenius/dify-plugin-daemon:0.0.4-local
    restart: always
    environment:
      # Use the shared environment variables.
      <<: *shared-api-worker-env
      HTTP_PROXY: my_proxy_host:my_proxy_port
      HTTPS_PROXY: my_proxy_host:my_proxy_port
      PIP_INDEX_URL: 'https://mirrors.aliyun.com/pypi/simple/'
      DB_DATABASE: ${DB_PLUGIN_DATABASE:-dify_plugin}
      SERVER_PORT: ${PLUGIN_DAEMON_PORT:-5002}
      SERVER_KEY: ${PLUGIN_DAEMON_KEY:-lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi}
      MAX_PLUGIN_PACKAGE_SIZE: ${PLUGIN_MAX_PACKAGE_SIZE:-52428800}
      PPROF_ENABLED: ${PLUGIN_PPROF_ENABLED:-false}
      DIFY_INNER_API_URL: ${PLUGIN_DIFY_INNER_API_URL:-http://api:5001}
      DIFY_INNER_API_KEY: ${PLUGIN_DIFY_INNER_API_KEY:-QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1}
      PLUGIN_REMOTE_INSTALLING_HOST: ${PLUGIN_DEBUGGING_HOST:-0.0.0.0}
      PLUGIN_REMOTE_INSTALLING_PORT: ${PLUGIN_DEBUGGING_PORT:-5003}
      PLUGIN_WORKING_PATH: ${PLUGIN_WORKING_PATH:-/app/storage/cwd}
      FORCE_VERIFYING_SIGNATURE: ${FORCE_VERIFYING_SIGNATURE:-true}
      PYTHON_ENV_INIT_TIMEOUT: ${PLUGIN_PYTHON_ENV_INIT_TIMEOUT:-120}
      PLUGIN_MAX_EXECUTION_TIMEOUT: ${PLUGIN_MAX_EXECUTION_TIMEOUT:-600}
      PIP_MIRROR_URL: ${PIP_MIRROR_URL:-}
      HTTP_PROXY: http://10.10.6.15:6666
      HTTPS_PROXY: http://10.10.6.15:6666
    ports:
      - "${EXPOSE_PLUGIN_DEBUGGING_PORT:-5003}:${PLUGIN_DEBUGGING_PORT:-5003}"
    volumes:
      - ./volumes/plugin_daemon:/app/storage
    depends_on:
      - db

```

**Comment by Yeuoly** [comment]
It has been fixed https://github.com/langgenius/dify-plugin-daemon/pull/99, replacing tag of plugin_daemon to 07d13bfb59acc422afa06436c7fdc5f3bc7e6554-local should solve this

**Comment by sevck** [comment]
I used the image and configured the proxy for the image
```
  # plugin daemon
  plugin_daemon:
    image: langgenius/dify-plugin-daemon:07d13bfb59acc422afa06436c7fdc5f3bc7e6554-local
    restart: always
    environment:
      # Use the shared environment variables.
      <<: *shared-api-worker-env
      PIP_INDEX_URL: 'https://mirrors.aliyun.com/pypi/simple/'
      DB_DATABASE: ${DB_PLUGIN_DATABASE:-dify_plugin}
      SERVER_PORT: ${PLUGIN_DAEMON_PORT:-5002}
      SERVER_KEY: ${PLUGIN_DAEMON_KEY:-lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi}
      MAX_PLUGIN_PACKAGE_SIZE: ${PLUGIN_MAX_PACKAGE_SIZE:-52428800}
      PPROF_ENABLED: ${PLUGIN_PPROF_ENABLED:-false}
      DIFY_INNER_API_URL: ${PLUGIN_DIFY_INNER_API_URL:-http://api:5001}
      DIFY_INNER_API_KEY: ${PLUGIN_DIFY_INNER_API_KEY:-QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1}
      PLUGIN_REMOTE_INSTALLING_HOST: ${PLUGIN_DEBUGGING_HOST:-0.0.0.0}
      PLUGIN_REMOTE_INSTALLING_PORT: ${PLUGIN_DEBUGGING_PORT:-5003}
      PLUGIN_WORKING_PATH: ${PLUGIN_WORKING_PATH:-/app/storage/cwd}
      FORCE_VERIFYING_SIGNATURE: ${FORCE_VERIFYING_SIGNATURE:-true}
      PYTHON_ENV_INIT_TIMEOUT: ${PLUGIN_PYTHON_ENV_INIT_TIMEOUT:-120}
      PLUGIN_MAX_EXECUTION_TIMEOUT: ${PLUGIN_MAX_EXECUTION_TIMEOUT:-600}
      PIP_MIRROR_URL: ${PIP_MIRROR_URL:-}
      HTTP_PROXY: 10.10.6.15:6666
      HTTPS_PROXY: 10.10.6.15:6666
    ports:
      - "${EXPOSE_PLUGIN_DEBUGGING_PORT:-5003}:${PLUGIN_DEBUGGING_PORT:-5003}"
    volumes:
      - ./volumes/plugin_daemon:/app/storage
    depends_on:
      - db

```


error info:
```
2025/03/12 08:51:23 runtime_lifetime.go:76: [ERROR]init environment failed: failed to install dependencies: exit status 2, output: error: Failed to fetch: `https://mirrors.aliyun.com/pypi/simple/numpy/`
  Caused by: Request failed after 3 retries
  Caused by: error sending request for url (https://mirrors.aliyun.com/pypi/simple/numpy/)
  Caused by: operation timed out
, retry in 30s
2025/03/12 08:51:53 runtime_lifetime.go:70: [INFO]init environment for plugin langgenius/azure_openai:0.0.8
2025/03/12 08:53:56 runtime_lifetime.go:76: [ERROR]init environment failed: failed to install dependencies: exit status 2, output: error: Failed to fetch: `https://mirrors.aliyun.com/pypi/simple/tiktoken/`
  Caused by: Request failed after 3 retries
  Caused by: error sending request for url (https://mirrors.aliyun.com/pypi/simple/tiktoken/)
  Caused by: operation timed out
, retry in 30s
2025/03/12 08:54:26 runtime_lifetime.go:70: [INFO]init environment for plugin langgenius/azure_openai:0.0.8
2025/03/12 08:56:28 runtime_lifetime.go:76: [ERROR]init environment failed: failed to install dependencies: exit status 2, output: error: Failed to fetch: `https://mirrors.aliyun.com/pypi/simple/dify-plugin/`
  Caused by: Request failed after 3 retries
  Caused by: error sending request for url (https://mirrors.aliyun.com/pypi/simple/dify-plugin/)
  Caused by: operation timed out
, retry in 30s
2025/03/12 08:56:58 runtime_lifetime.go:70: [INFO]init environment for plugin langgenius/azure_openai:0.0.8
2025/03/12 08:56:58 watcher.go:85: [ERROR]plugin launch error: init environment for plugin langgenius/azure_openai:0.0.8 failed too many times, you should consider the package is corrupted or your network is unstable
2025/03/12 08:57:32 factory.go:28: [ERROR]PluginDaemonInternalServerError: killed by timeout
goroutine 53 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/langgenius/dify-plugin-daemon/internal/types/exception.InternalServerError({0x18112a0, 0xc00020f1b0})
        /app/internal/types/exception/factory.go:27 +0x27
github.com/langgenius/dify-plugin-daemon/internal/service.baseSSEService[...](0xc00060f0a0, 0x15fbb1c, 0x258?)
        /app/internal/service/base_sse.go:81 +0x4e6
github.com/langgenius/dify-plugin-daemon/internal/service.ValidateModelCredentials(0xc00016ea00, 0xc000810d00, 0x258)
        /app/internal/service/invoke_model.go:237 +0x198
github.com/langgenius/dify-plugin-daemon/internal/server.(*App).pluginDispatchGroup.ValidateModelCredentials.func18.1({{{0xc00054423d, 0x24}, {0xc0001fdb80, 0x7}}, {{0x0, 0x0}}, {0xc0001cc900, 0x5e}, 0x0, 0x0, ...})
        /app/internal/server/controllers/model.go:111 +0x91
github.com/langgenius/dify-plugin-daemon/internal/server/controllers.BindPluginDispatchRequest[...].func1()
        /app/internal/server/controllers/base.go:53 +0xb5
github.com/langgenius/dify-plugin-daemon/internal/server/controllers.BindRequest[...](0xc000810d00, 0xc00060f328)
        /app/internal/server/controllers/base.go:31 +0x276
github.com/langgenius/dify-plugin-daemon/internal/server/controllers.BindPluginDispatchRequest[...](0x1608938?, 0xa?)
        /app/internal/server/controllers/base.go:37 +0x45
github.com/langgenius/dify-plugin-daemon/internal/server.(*App).pluginDispatchGroup.ValidateModelCredentials.func18(0xc000810d00)
        /app/internal/server/controllers/model.go:108 +0x74
github.com/gin-gonic/gin.(*Context).Next(0xc000810d00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
github.com/langgenius/dify-plugin-daemon/internal/server.(*App).pluginDispatchGroup.(*App).InitClusterID.func3(0xc000810d00)
        /app/internal/server/middleware.go:170 +0x54
github.com/gin-gonic/gin.(*Context).Next(0xc000810d00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
github.com/langgenius/dify-plugin-daemon/internal/server.(*App).pluginDispatchGroup.(*App).RedirectPluginInvoke.func2(0xc000810d00)
        /app/internal/server/middleware.go:97 +0x74
github.com/gin-gonic/gin.(*Context).Next(0xc000810d00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
github.com/langgenius/dify-plugin-daemon/internal/server.(*App).pluginDispatchGroup.(*App).FetchPluginInstallation.func1(0xc000810d00)
        /app/internal/server/middleware.go:66 +0x2f2
github.com/gin-gonic/gin.(*Context).Next(0xc000810d00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
github.com/langgenius/dify-plugin-daemon/internal/server.(*App).pluginGroup.CheckingKey.func1(0xc000810d00)
        /app/internal/server/middleware.go:24 +0x95
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0xc000810d00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102 +0x7a
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc000810d00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249 +0xe5
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0006f6b60, 0xc000810d00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633 +0x892
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0006f6b60, {0x1823720, 0xc0003920e0}, 0xc0003a7440)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589 +0x1b2
net/http.serverHandler.ServeHTTP({0x18194c8?}, {0x1823720?, 0xc0003920e0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc0003a2630, {0x1825ed0, 0xc0000fc960})
        /usr/local/go/src/net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 40
        /usr/local/go/src/net/http/server.go:3290 +0x4b4

```
