### ISSUE TITLE
Model Parameter Validation Error in Tool-Type Plugin When Using Model-Selector

### ISSUE THREAD

**Issue by jaguarliuu** [langgenius/dify#15631]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.0.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After adding a model parameter of type model-selector to my tool-type plugin, the Dify interface throws a "Model cannot be empty" error even after the user selects a model. The parameter configuration appears correct, but the validation fails unexpectedly.

1. define a tool plugin with a model-selector parameter in tools/tool.yaml:
```yaml
parameters:
  - name: model
    type: model-selector
    scope: llm
    required: true
    label:
      en_US: Model
    # ... other fields ...
    form: llm  # <— Suspected issue
  - name: query
    type: string
    required: true
    # ... ...
```
2. Load the plugin in Dify and navigate to the tool configuration page.
3. Select a model from the dropdown.
4. Observe the validation error: "Model cannot be empty".
Did I make a mistake in the configuration, or is this a system bug?

my tool repo：https://github.com/jaguarliuu/rookie_text2data
