### ISSUE TITLE
tool selector with empty tools raise error

### ISSUE THREAD

**Issue by hjlarry** [langgenius/dify#15825]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.0.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. config plugin params to tool,  here I develop a agent plugin
```
  - name: tools
    type: array[tools]
    # change to false when fix issue
    required: false
    label:
      en_US: Tools list
      zh_Hans: 工具列表
      pt_BR: Tools list
```

2. don't select any tools
3. draft run this node, raise `The tools selector must be a list.`
