### ISSUE TITLE
Custom plugin tool with `output_schema` error

### ISSUE THREAD

**Issue by majinkai** [langgenius/dify#16150]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.0.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

```yaml
output_schema:
  type: object
  properties:
    text:
      type: string
```

### ✔️ Expected Behavior

 python -m main
{"event": "log", "data": {"level": "INFO", "message": "Installed tool: union-id", "timestamp": 1742346828.017111}}

### ❌ Actual Behavior

python -m main

```
An error occurred while parsing the data: b"tools register failed, invalid tools declaration: Key: 'ToolProviderDeclaration.Tools[0].OutputSchema' Error:Field validation for 'OutputSchema' failed on the 'json_schema' tag"
Traceback (most recent call last):
  File "/Users/majinkai/Desktop/dify-build/union-id/venv/lib/python3.12/site-packages/dify_plugin/core/server/tcp/request_reader.py", line 147, in _read_stream
    data = loads(line)
           ^^^^^^^^^^^
```

**Comment by majinkai** [comment]
How should I operate if I want to override default structure(`TOOL-OUTPUT-STRUCT`) and only output one variable @dosu

**Comment by majinkai** [comment]
I don't want to change any source code, I just want to constrain the return of only one variable through settings. @dosu

**Comment by dar0xt** [comment]
@dosu
It is necessary to include not only variables but also a description in i18n format.

**Comment by majinkai** [comment]
```yml
output_schema:
  type: object
  properties:
    dataset_id:
      type: string
      label:
        en_US: Dataset Id
        zh_Hans: 知识库ID
      human_description:
        en_US: Dataset Id
        zh_Hans: 知识库ID
```

![Image](https://github.com/user-attachments/assets/1939e2e3-f20f-46df-a418-fd04854d5e0b)

Can I hide variables other than dataset_id. Additionally, dataset_id failed to internationalize.
