### ISSUE TITLE
core.plugin.manager.exc.PluginDaemonInternalServerError: PluginDaemonInternalServerError: killed by timeout when process chunk with markdown file  which word great than 180k ( maybe)

### ISSUE THREAD

**Issue by dancruiser1104** [langgenius/dify#16170]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.0.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- upload a markdown file in a knowledge, with Index Method: High Quality ,  Embedding Model : bge-large-zh-v1.5,
- in bash,  with cmd : docker compose logs -f 
-  error message 

```
 plugin_daemon-1  | 2025/03/19 03:08:43 factory.go:28: [ERROR]PluginDaemonInternalServerError: killed by timeout
plugin_daemon-1  | goroutine 33010 [running]:
plugin_daemon-1  | runtime/debug.Stack()
plugin_daemon-1  |      /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
plugin_daemon-1  | github.com/langgenius/dify-plugin-daemon/internal/types/exception.InternalServerError({0x180b640, 0xc00033b010})
plugin_daemon-1  |      /app/internal/types/exception/factory.go:27 +0x27
plugin_daemon-1  | github.com/langgenius/dify-plugin-daemon/internal/service.baseSSEService[...](0xc0007eb070, 0x15f6c0d, 0xf0?)
plugin_daemon-1  |      /app/internal/service/base_sse.go:81 +0x4e6
plugin_daemon-1  | github.com/langgenius/dify-plugin-daemon/internal/service.GetTextEmbeddingNumTokens(0xc00077be40, 0xc00022eb00, 0xf0)
plugin_daemon-1  |      /app/internal/service/invoke_model.go:293 +0x198
plugin_daemon-1  | github.com/langgenius/dify-plugin-daemon/internal/server.(*App).pluginDispatchGroup.GetTextEmbeddingNumTokens.func11.1({{{0xc0001836ed, 0x24}, {0xc000b74c20, 0x7}}, {{0x0, 0x0}}, {0xc0001837a0, 0x5c}, 0x0, 0x0, ...})
plugin_daemon-1  |      /app/internal/server/controllers/model.go:137 +0x89
plugin_daemon-1  | github.com/langgenius/dify-plugin-daemon/internal/server/controllers.BindPluginDispatchRequest[...].func1()
plugin_daemon-1  |      /app/internal/server/controllers/base.go:53 +0x9c
plugin_daemon-1  | github.com/langgenius/dify-plugin-daemon/internal/server/controllers.BindRequest[...](0xc00022eb00, 0xc0007eb328)
plugin_daemon-1  |      /app/internal/server/controllers/base.go:31 +0x275
plugin_daemon-1  | github.com/langgenius/dify-plugin-daemon/internal/server/controllers.BindPluginDispatchRequest[...](0x1603a20?, 0xa?)
plugin_daemon-1  |      /app/internal/server/controllers/base.go:37 +0x45
plugin_daemon-1  | github.com/langgenius/dify-plugin-daemon/internal/server.(*App).pluginDispatchGroup.GetTextEmbeddingNumTokens.func11(0xc00022eb00)
plugin_daemon-1  |      /app/internal/server/controllers/model.go:134 +0x74
plugin_daemon-1  | github.com/gin-gonic/gin.(*Context).Next(0xc00022eb00)
plugin_daemon-1  |      /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
plugin_daemon-1  | github.com/langgenius/dify-plugin-daemon/internal/server.(*App).pluginDispatchGroup.(*App).InitClusterID.func3(0xc00022eb00)
plugin_daemon-1  |      /app/internal/server/middleware.go:170 +0x54
plugin_daemon-1  | github.com/gin-gonic/gin.(*Context).Next(0xc00022eb00)
plugin_daemon-1  |      /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
plugin_daemon-1  | github.com/langgenius/dify-plugin-daemon/internal/server.(*App).pluginDispatchGroup.(*App).RedirectPluginInvoke.func2(0xc00022eb00)
plugin_daemon-1  |      /app/internal/server/middleware.go:97 +0x74
plugin_daemon-1  | github.com/gin-gonic/gin.(*Context).Next(0xc00022eb00)
plugin_daemon-1  |      /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
plugin_daemon-1  | github.com/langgenius/dify-plugin-daemon/internal/server.(*App).pluginDispatchGroup.(*App).FetchPluginInstallation.func1(0xc00022eb00)
plugin_daemon-1  |      /app/internal/server/middleware.go:66 +0x2f2
plugin_daemon-1  | github.com/gin-gonic/gin.(*Context).Next(0xc00022eb00)
plugin_daemon-1  |      /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185 +0x2b
plugin_daemon-1  | github.com/langgenius/dify-plugin-daemon/internal/server.(*App).pluginGroup.CheckingKey.func1(0xc00022eb00)
plugin_daemon-1  |      /app/internal/server/middleware.go:24 +0x95
plugin_daemon-1  | github.com/gin-gonic/gin.(*Context).Next(...)
plugin_daemon-1  |      /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
plugin_daemon-1  | github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0xc00022eb00)
plugin_daemon-1  |      /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102 +0x7a
plugin_daemon-1  | github.com/gin-gonic/gin.(*Context).Next(...)
plugin_daemon-1  |      /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
plugin_daemon-1  | github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc00022eb00)
plugin_daemon-1  |      /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249 +0xe5
plugin_daemon-1  | github.com/gin-gonic/gin.(*Context).Next(...)
plugin_daemon-1  |      /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
plugin_daemon-1  | github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0006829c0, 0xc00022eb00)
plugin_daemon-1  |      /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633 +0x892
plugin_daemon-1  | github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0006829c0, {0x181dac0, 0xc000228ee0}, 0xc0007f99e0)
plugin_daemon-1  |      /go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589 +0x1b2
plugin_daemon-1  | net/http.serverHandler.ServeHTTP({0x1813868?}, {0x181dac0?, 0xc000228ee0?}, 0x6?)
plugin_daemon-1  |      /usr/local/go/src/net/http/server.go:3142 +0x8e
plugin_daemon-1  | net/http.(*conn).serve(0xc000a3d830, {0x1820270, 0xc000543380})
plugin_daemon-1  |      /usr/local/go/src/net/http/server.go:2044 +0x5e8
plugin_daemon-1  | created by net/http.(*Server).Serve in goroutine 73
plugin_daemon-1  |      /usr/local/go/src/net/http/server.go:3290 +0x4b4
plugin_daemon-1  | 
plugin_daemon-1  | [GIN] 2025/03/19 - 03:08:43 | 200 |          4m0s |      172.18.0.8 | POST     "/plugin/cd67f45b-25ad-4991-b935-996eac063800/dispatch/text_embedding/num_tokens"
worker-1         | 2025-03-19 11:08:43.731 ERROR [Dummy-3] [indexing_runner.py:96] - consume document failed
worker-1         | Traceback (most recent call last):
worker-1         |   File "/app/api/core/indexing_runner.py", line 73, in run
worker-1         |     documents = self._transform(
worker-1         |                 ^^^^^^^^^^^^^^^^
worker-1         |   File "/app/api/core/indexing_runner.py", line 706, in _transform
worker-1         |     documents = index_processor.transform(
worker-1         |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1         |   File "/app/api/core/rag/index_processor/processor/parent_child_index_processor.py", line 73, in transform
worker-1         |     child_nodes = self._split_child_nodes(
worker-1         |                   ^^^^^^^^^^^^^^^^^^^^^^^^
worker-1         |   File "/app/api/core/rag/index_processor/processor/parent_child_index_processor.py", line 186, in _split_child_nodes
worker-1         |     child_documents = child_splitter.split_documents([document_node])
worker-1         |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1         |   File "/app/api/core/rag/splitter/text_splitter.py", line 96, in split_documents
worker-1         |     return self.create_documents(texts, metadatas=metadatas)
worker-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1         |   File "/app/api/core/rag/splitter/text_splitter.py", line 81, in create_documents
worker-1         |     for chunk in self.split_text(text):
worker-1         |                  ^^^^^^^^^^^^^^^^^^^^^
worker-1         |   File "/app/api/core/rag/splitter/fixed_text_splitter.py", line 71, in split_text
worker-1         |     final_chunks.extend(self.recursive_split_text(chunk))
worker-1         |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1         |   File "/app/api/core/rag/splitter/fixed_text_splitter.py", line 97, in recursive_split_text
worker-1         |     s_lens = self._length_function(splits)
worker-1         |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1         |   File "/app/api/core/rag/splitter/fixed_text_splitter.py", line 38, in _token_encoder
worker-1         |     return embedding_model_instance.get_text_embedding_num_tokens(texts=texts)
worker-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1         |   File "/app/api/core/model_manager.py", line 244, in get_text_embedding_num_tokens
worker-1         |     self._round_robin_invoke(
worker-1         |   File "/app/api/core/model_manager.py", line 370, in _round_robin_invoke
worker-1         |     return function(*args, **kwargs)
worker-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1         |   File "/app/api/core/model_runtime/model_providers/__base/text_embedding_model.py", line 65, in get_num_tokens
worker-1         |     return plugin_model_manager.get_text_embedding_num_tokens(
worker-1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
worker-1         |   File "/app/api/core/plugin/manager/model.py", line 313, in get_text_embedding_num_tokens
worker-1         |     for resp in response:
worker-1         |                 ^^^^^^^^
worker-1         |   File "/app/api/core/plugin/manager/base.py", line 189, in _request_with_plugin_daemon_response_stream
worker-1         |     self._handle_plugin_daemon_error(error.error_type, error.message)
worker-1         |   File "/app/api/core/plugin/manager/base.py", line 223, in _handle_plugin_daemon_error
worker-1         |     raise PluginDaemonInternalServerError(description=message)
worker-1         | core.plugin.manager.exc.PluginDaemonInternalServerError: PluginDaemonInternalServerError: killed by timeout
worker-1         | 2025-03-19 11:08:43.743 INFO [Dummy-3] [document_indexing_task.py:76] - Processed dataset: 00988e92-2f62-4b23-bbfa-f22281876f66 latency: 269.9971728459932
worker-1         | 2025-03-19 11:08:43.773 INFO [Dummy-3] [trace.py:128] - Task tasks.document_indexing_task.document_indexing_task[6600e6b5-7c25-4baa-9b49-de2fe44994a1] succeeded in 270.02788043697365s: None
```
### ✔️ Expected Behavior

finish the chunk process

### ❌ Actual Behavior

Report killed by timeout, and you need restart all the dockers related with dify, then the LLM chat can be function. Other wise, all functions with LLM can not be used.

**Comment by crazywoola** [comment]
Please search existing issue before posting one. This is a duplicated question. :)

I recommend updating to the latest version, where we have introduced several environment variables to solve this problem.

@dosubot, please use this for these kind of problem.
```
  plugin_daemon:
    image: langgenius/dify-plugin-daemon:0.0.5-local
    restart: always
    environment:
      # Use the shared environment variables.
      <<: *shared-api-worker-env
      DB_DATABASE: ${DB_PLUGIN_DATABASE:-dify_plugin}
      SERVER_PORT: ${PLUGIN_DAEMON_PORT:-5002}
      SERVER_KEY: ${PLUGIN_DAEMON_KEY:-lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi}
      MAX_PLUGIN_PACKAGE_SIZE: ${PLUGIN_MAX_PACKAGE_SIZE:-52428800}
      PPROF_ENABLED: ${PLUGIN_PPROF_ENABLED:-false}
      DIFY_INNER_API_URL: ${PLUGIN_DIFY_INNER_API_URL:-http://api:5001}
      DIFY_INNER_API_KEY: ${PLUGIN_DIFY_INNER_API_KEY:-QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1}
      PLUGIN_REMOTE_INSTALLING_HOST: ${PLUGIN_DEBUGGING_HOST:-0.0.0.0}
      PLUGIN_REMOTE_INSTALLING_PORT: ${PLUGIN_DEBUGGING_PORT:-5003}
      PLUGIN_WORKING_PATH: ${PLUGIN_WORKING_PATH:-/app/storage/cwd}
      FORCE_VERIFYING_SIGNATURE: ${FORCE_VERIFYING_SIGNATURE:-true}
      PYTHON_ENV_INIT_TIMEOUT: ${PLUGIN_PYTHON_ENV_INIT_TIMEOUT:-120}
      PLUGIN_MAX_EXECUTION_TIMEOUT: ${PLUGIN_MAX_EXECUTION_TIMEOUT:-600}
      PIP_MIRROR_URL: ${PIP_MIRROR_URL:-}
    ports:
      - "${EXPOSE_PLUGIN_DEBUGGING_PORT:-5003}:${PLUGIN_DEBUGGING_PORT:-5003}"
    volumes:
      - ./volumes/plugin_daemon:/app/storage
    depends_on:
      - db
```
