### ISSUE TITLE
tool-plugin secret-input display unexpected

### ISSUE THREAD

**Issue by bionexit** [langgenius/dify#16494]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.1.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I'm working on a tool-plugin development, when I set a parameter to a specific input element with `secret-input` type, unfortunately the front end doesn't show * marked the content. 

please kindly help.

./tools/connector.yaml
```
parameters:
  - name: mysql_password
    type: secret-input
    required: true
    label:
      en_US: MySQL Password
      zh_Hans:  MySQL 密码
    human_description:
      en_US: Please input your MySQL password
      zh_Hans: 请输入你的 MySQL 密码
    form: form 
```

 

### ✔️ Expected Behavior

![Image](https://github.com/user-attachments/assets/a1045556-a7f5-447d-a92c-4d183e50234e)

the password section should be covered with *

### ❌ Actual Behavior

![Image](https://github.com/user-attachments/assets/856e5a8d-bd3e-4c32-943a-dafe391c9a8b)
