### ISSUE TITLE
Time zone setting is invalid, interface displays time issue

### ISSUE THREAD

**Issue by AlexKuai** [langgenius/dify#16547]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.1.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- My configuration

    - docker-compose.yaml

    ```yaml
    api:
        environment:
          TZ: Asia/Shanghai
        volumes:
          - /etc/localtime:/etc/localtime:ro   # Mount local host time
    worker:
        environment:
          TZ: Asia/Shanghai
        volumes:
          - /etc/localtime:/etc/localtime:ro  # Mount local host time
    web:
        environment:
          TZ: Asia/Shanghai
        volumes:
          - /etc/localtime:/etc/localtime:ro  # Mount local host time
    ```

    - .env

    ```ini
    LOG_TZ=Asia/Shanghai
    ```

- problem

Through the above configuration, the display time on my interface is still 8 hours ahead of the current local time. The following is a screenshot of what was displayed after I just logged in.

![Image](https://github.com/user-attachments/assets/ef3b99c3-99a9-4940-8a9c-7279fa3ab41d)

But the logs and time entering the container are consistent with the local host time.

![Image](https://github.com/user-attachments/assets/5a327193-803c-4212-90a9-df54af8704ce)

![Image](https://github.com/user-attachments/assets/1a7bdac2-a347-4e09-8093-bd991772a7a8)

### ✔️ Expected Behavior

Display the correct time zone and time

### ❌ Actual Behavior

The time is not in the current time zone
