### ISSUE TITLE
Number Parameter Not Visible and Secret Input Lacks Masking

### ISSUE THREAD

**Issue by jaguarliuu** [langgenius/dify#16715]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.1.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When developing my Dify plugin, I defined two parameters:
- A number type parameter
- A secret-input type parameter

Here is config yaml: 
```yaml
 - name: port
    type: number
    required: true
    form: form
    min: 1
    max: 65535
    label:
      en_US: Database port
      zh_Hans: 数据库端口
      pt_BR: Database port
    human_description:
  - name: password
    type: secret-input
    required: true
    form: form
    label:
      en_US: Password
      zh_Hans: 密码
      pt_BR: Password
    human_description:
      en_US: Password
```

However, during plugin usage I'm observing two issues:

- The number type parameter is not being displayed in the UI
- The secret-input parameter isn't masked (no *** protection) when entered

![Image](https://github.com/user-attachments/assets/caeed95f-44c1-482e-a61d-92bd0857ba0d)
