### ISSUE TITLE
plugin_daemon can not init environment failed: failed to create virtual environment: exit status 101

### ISSUE THREAD

**Issue by geosmart** [langgenius/dify#16802]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.1.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

```yaml
  # plugin daemon
  plugin_daemon:
    image: harbor.dc.servyou-it.com/jrsyb-ops/mirrors/langgenius/dify-plugin-daemon:0.0.6-local
    restart: always
    environment:
      # Use the shared environment variables.
      <<: *shared-api-worker-env
      DB_DATABASE: ${DB_PLUGIN_DATABASE:-dify_plugin}
      SERVER_PORT: ${PLUGIN_DAEMON_PORT:-5002}
      SERVER_KEY: ${PLUGIN_DAEMON_KEY:-lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi}
      MAX_PLUGIN_PACKAGE_SIZE: ${PLUGIN_MAX_PACKAGE_SIZE:-52428800}
      PPROF_ENABLED: ${PLUGIN_PPROF_ENABLED:-false}
      DIFY_INNER_API_URL: ${PLUGIN_DIFY_INNER_API_URL:-http://api:5001}
      DIFY_INNER_API_KEY: ${PLUGIN_DIFY_INNER_API_KEY:-QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1}
      PLUGIN_REMOTE_INSTALLING_HOST: ${PLUGIN_DEBUGGING_HOST:-0.0.0.0}
      PLUGIN_REMOTE_INSTALLING_PORT: ${PLUGIN_DEBUGGING_PORT:-5003}
      PLUGIN_WORKING_PATH: ${PLUGIN_WORKING_PATH:-/app/storage/cwd}
      FORCE_VERIFYING_SIGNATURE: ${FORCE_VERIFYING_SIGNATURE:-true}
      PLUGIN_MAX_EXECUTION_TIMEOUT: ${PLUGIN_MAX_EXECUTION_TIMEOUT:-600}
      # 设置超时时间为 300 秒
      PYTHON_ENV_INIT_TIMEOUT: ${PYTHON_ENV_INIT_TIMEOUT:-300}
      PIP_MIRROR_URL: ${PIP_MIRROR_URL:-https://pypi.tuna.tsinghua.edu.cn/simple}
      RUST_BACKTRACE: full
    ports:
      - "${EXPOSE_PLUGIN_DEBUGGING_PORT:-5003}:${PLUGIN_DEBUGGING_PORT:-5003}"
    volumes:
      - **./volumes/plugin_daemon:/app/storage**
```

error log
```c
[GIN] 2025/03/26 - 03:46:36 | 200 |   88.833035ms |     172.23.0.10 | GET      "/plugin/8c80eea5-47c3-4b96-b769-c0a9de5bac93/management/models?page=1&page_size=256"
2025/03/26 03:46:58 runtime_lifetime.go:70: [INFO]init environment for plugin langgenius/deepseek:0.0.5
2025/03/26 03:46:58 runtime_lifetime.go:76: [ERROR]init environment failed: failed to create virtual environment: exit status 101, output: 
thread 'main' panicked at /home/runner/work/uv/uv/crates/uv/src/lib.rs:2017:10:
Tokio executor failed, was there a panic?: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }
stack backtrace:
   0:     0x55bb437a2d7b - <unknown>
   1:     0x55bb43412ef3 - <unknown>
   2:     0x55bb437a25f2 - <unknown>
   3:     0x55bb437a2bb3 - <unknown>
   4:     0x55bb437a2403 - <unknown>
   5:     0x55bb437e6688 - <unknown>
   6:     0x55bb437e65e9 - <unknown>
   7:     0x55bb437e917c - <unknown>
   8:     0x55bb430c6c8f - <unknown>
   9:     0x55bb430c7005 - <unknown>
  10:     0x55bb43eeace9 - <unknown>
  11:     0x55bb442bf943 - <unknown>
  12:     0x55bb43ee9ae4 - <unknown>
  13:     0x7f6c3e8541ca - <unknown>
  14:     0x7f6c3e85428b - __libc_start_main
```
  15:     0x55bb43136459 - <unknown>
  16:                0x0 - <unknown>
, retry in 30s

### ✔️ Expected Behavior

add deepseek plugin ,success save the  api key

### ❌ Actual Behavior

stuck at  save the deepseek  api key. thro 499.

10.249.1.86 - - [26/Mar/2025:03:48:16 +0000] "POST /console/api/workspaces/current/model-providers/langgenius/deepseek/deepseek HTTP/1.1" 499 0 "http://10.199.140.152/tools" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36" "-"

and the  error exist in plugin_daemon
