### ISSUE TITLE
Agent is not find tool name

### ISSUE THREAD

**Issue by yj11** [langgenius/dify#16913]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

v1.1.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I create dify workflow tool. When I use Agent and tool, Agent is not find tool
![Image](https://github.com/user-attachments/assets/0fd4bb84-5114-4824-bc74-904cc4f59d18
![Image](https://github.com/user-attachments/assets/feccc370-1faf-4d2b-bf39-9f0629ecb1e9)

### ✔️ Expected Behavior

use tool, get result 

### ❌ Actual Behavior

![Image](https://github.com/user-attachments/assets/0fd4bb84-5114-4824-bc74-904cc4f59d18)

**Comment by crazywoola** [comment]
<img width="1422" alt="Image" src="https://github.com/user-attachments/assets/8db1cf77-65d6-43b9-8dee-de9013f03fb1" />

Can not reproduce.

**Comment by apoollo** [comment]
> <img alt="Image" width="1422" src="https://private-user-images.githubusercontent.com/100913391/427379120-8db1cf77-65d6-43b9-8dee-de9013f03fb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMwNTgzOTAsIm5iZiI6MTc0MzA1ODA5MCwicGF0aCI6Ii8xMDA5MTMzOTEvNDI3Mzc5MTIwLThkYjFjZjc3LTY1ZDYtNDNiOS04ZGVlLWRlOTAxM2YwM2ZiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDMyN1QwNjQ4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzQ4MjMyM2E4ZmUyZTZlZjQ5ZTBjZjBmNTk1OTgyNTc5Yzc1ZTk4NjM3MDVjYzZlYzVhOTIwNTY5Zjg2OWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.RkI0F4pLc6k4Q8LTHXL4okVgMxqYt2s5TqV1RC8Fy4M">
> Can not reproduce.

what is version ？

**Comment by yj11** [comment]
Use your own workflow tools

**Comment by yj11** [comment]
Use your own workflow tools

**Comment by yj11** [comment]
v1.1.1

**Comment by apoollo** [comment]
what's LLM ?

**Comment by yj11** [comment]
```
app:
  description: ktp_recognize
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: ktp_recognize
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/openai:0.0.12@604c1a752a92633a354dc7eea717248314f23bab66a9ce48d33b1c57a0f9463e
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: llm
      id: 1742889359068-source-1742889362780-target
      source: '1742889359068'
      sourceHandle: source
      target: '1742889362780'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: llm
        targetType: end
      id: 1742889362780-source-1742889365418-target
      source: '1742889362780'
      sourceHandle: source
      target: '1742889365418'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables: []
      height: 54
      id: '1742889359068'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: gpt-4o-mini
          provider: langgenius/openai/openai
        prompt_template:
        - id: 3bfcd8a4-234d-4372-9936-c628d1dd97fa
          role: system
          text: 回复你好
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 90
      id: '1742889362780'
      position:
        x: 384
        y: 282
      positionAbsolute:
        x: 384
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1742889362780'
          - text
          variable: res
        selected: false
        title: 结束
        type: end
      height: 90
      id: '1742889365418'
      position:
        x: 688
        y: 282
      positionAbsolute:
        x: 688
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -97
      y: 149
      zoom: 1
```
you use this DSL publish tool. Then Agent is used.

**Comment by yj11** [comment]
```
app:
  description: 'checkpoint for verifying the correctness of the KTP.

    sub-point：

    1.it''s a KTP  2.expiration date  3.structure of NIK'
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: Material - KTP
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/gemini:0.0.8@420e755f870062b3da528617d2c0439a599ce1cbbb00645492c3bdb2b360afb6
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: iteration
      id: 1742289355685-source-1742461539107-target
      source: '1742289355685'
      sourceHandle: source
      target: '1742461539107'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: true
        isInLoop: false
        iteration_id: '1742461539107'
        sourceType: iteration-start
        targetType: llm
      id: 1742461539107start-source-1742461592701-target
      source: 1742461539107start
      sourceHandle: source
      target: '1742461592701'
      targetHandle: target
      type: custom
      zIndex: 1002
    - data:
        isInIteration: true
        isInLoop: false
        iteration_id: '1742461539107'
        sourceType: llm
        targetType: code
      id: 1742461592701--1742461676348-target
      source: '1742461592701'
      sourceHandle: source
      target: '1742461676348'
      targetHandle: target
      type: custom
      zIndex: 1002
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: iteration
      id: 1742289355685-source-1742888860671-target
      source: '1742289355685'
      sourceHandle: source
      target: '1742888860671'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: true
        isInLoop: false
        iteration_id: '1742888860671'
        sourceType: iteration-start
        targetType: tool
      id: 1742888860671start-source-1742889002707-target
      source: 1742888860671start
      sourceHandle: source
      target: '1742889002707'
      targetHandle: target
      type: custom
      zIndex: 1002
    - data:
        isInIteration: true
        isInLoop: false
        iteration_id: '1742888860671'
        sourceType: tool
        targetType: code
      id: 1742889002707--1742889017670-target
      source: '1742889002707'
      sourceHandle: source
      target: '1742889017670'
      targetHandle: target
      type: custom
      zIndex: 1002
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: iteration
        targetType: code
      id: 1742888860671-source-1742889121031-target
      source: '1742888860671'
      sourceHandle: source
      target: '1742889121031'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: iteration
        targetType: code
      id: 1742461539107-source-1742889121031-target
      source: '1742461539107'
      sourceHandle: source
      target: '1742889121031'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: code
        targetType: end
      id: 1742889121031-source-1742461753448-target
      source: '1742889121031'
      sourceHandle: source
      target: '1742461753448'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables:
        - allowed_file_extensions: []
          allowed_file_types:
          - image
          - document
          - video
          allowed_file_upload_methods:
          - local_file
          - remote_url
          label: files
          max_length: 5
          options: []
          required: true
          type: file-list
          variable: files
      height: 90
      id: '1742289355685'
      position:
        x: 50.18627996123871
        y: 450.4475182190014
      positionAbsolute:
        x: 50.18627996123871
        y: 450.4475182190014
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        error_handle_mode: terminated
        height: 178
        is_parallel: true
        iterator_selector:
        - '1742289355685'
        - files
        output_selector:
        - '1742461676348'
        - result
        output_type: array[object]
        parallel_nums: 10
        selected: false
        start_node_id: 1742461539107start
        title: CORRECT
        type: iteration
        width: 692
      height: 178
      id: '1742461539107'
      position:
        x: 384.745343000969
        y: 394.54679314632386
      positionAbsolute:
        x: 384.745343000969
        y: 394.54679314632386
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 692
      zIndex: 1
    - data:
        desc: ''
        isInIteration: true
        selected: false
        title: ''
        type: iteration-start
      draggable: false
      height: 48
      id: 1742461539107start
      parentId: '1742461539107'
      position:
        x: 24
        y: 68
      positionAbsolute:
        x: 408.745343000969
        y: 462.54679314632386
      selectable: false
      sourcePosition: right
      targetPosition: left
      type: custom-iteration-start
      width: 44
      zIndex: 1002
    - data:
        context:
          enabled: true
          variable_selector:
          - '1742461539107'
          - item
        desc: ''
        isInIteration: true
        isInLoop: false
        iteration_id: '1742461539107'
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: gemini-2.0-flash
          provider: langgenius/gemini/google
        prompt_template:
        - id: 0c30dd7e-021a-4a59-9d4b-5e0b39b27597
          role: system
          text: ''
        - id: e3efdb08-ed76-4b8d-9534-7918a8151e9e
          role: user
          text: "## Role\n你是一个证件识别机器人。\n\n## Initialization\n1.从以下图像{{#1742461539107.item#}}中提取信息。\n\
            2.判断图像是否为KTP，将结果is_KTP和判断依据is_KTP_reason追加至提取信息JSON中。\n\n## Example：\n\
            {\n    \"NIK\": \"JL SELAMET PERUMAHAN RANCABALI NO. 40\",\n    “is_KTP”:\
            \ “yes”,\n    “is_KTP_reason”: ””\n}\n\n## Workflow\n请根据提供的示例理解每个字段的含义，不要将示例作为最终输出。\n\
            \n1.验证NIK是否有效，有效则返回yes，并将NIK Valid字段添加到最终输出JSON中。\n2.在JSON中提取字段名为\"Berlaku\
            \ Hingga\"的值，忽略任何非印尼文的字段，然后将结果Valid Util追加至输出JSON中。\n3.通过Valid Until的值，判断当前NIK是否在有效期内。\n\
            比如：Valid Until等于SEUMUR HIDUP，则Within Valid Until字段值为yes；Valid Until等于28-12-2018，则Within\
            \ Valid Until字段值为no；Valid Until为空字符串，则Within Valid Until字段值为no；\n将Within\
            \ Valid Util追加至输出JSON中。\n\n## Constraints\n从原始文档中提取用于输出的每条文本只能使用一次。请尽量将它们放在最合适的字段中。\n\
            输出为JSON字符串，不添加Markdown格式。\n空字符串返回\"\"。\n\nNO COMMENTS. NO ACKNOWLEDGEMENTS"
        selected: false
        title: LLM 2
        type: llm
        variables: []
        vision:
          configs:
            detail: high
            variable_selector:
            - '1742461539107'
            - item
          enabled: true
      height: 90
      id: '1742461592701'
      parentId: '1742461539107'
      position:
        x: 146.63357502422582
        y: 65
      positionAbsolute:
        x: 531.3789180251948
        y: 459.54679314632386
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        code: "import re\ndef main(json_str: str) -> dict:\n    # 替换中文引号为英文引号\n  \
          \  cleaned_string = json_str.replace('\"', '\"').replace('\"', '\"')\n\n\
          \    # 提取JSON部分，去掉多余的标记\n    start_index = cleaned_string.find('{')\n  \
          \  end_index = cleaned_string.rfind('}') + 1\n    json_string = cleaned_string[start_index:end_index]\n\
          \n    # 尝试解析JSON字符串\n    try:\n        data = json.loads(json_string)\n\
          \        is_KTP = data.get('is_KTP', '')\n        is_KTP_reason = data.get('is_KTP_reason',\
          \ '')\n        NIK = data.get('NIK', '')\n        # NIK_valid = data.get('NIK\
          \ Valid', '')\n        valid_until = data.get('Valid Until', '')\n     \
          \   within_valid_until = data.get('Within Valid Until', '')\n    except\
          \ json.JSONDecodeError as e:\n        return {\n            \"result\":\
          \ {\n                \"result\": False,\n                \"reasons\": {\n\
          \                    \"is_KTP\": {\n                        \"result\":\
          \ False,\n                        \"reason\": \"Failed to parse JSON, {}\"\
          .format(json_str)\n                    },\n                    \"NIK_valid\"\
          : {\n                        \"result\": False,\n                      \
          \  \"reason\": \"Failed to parse JSON, {}\".format(json_str)\n         \
          \           },\n                    \"Berlaku_Hingga_valid\": {\n      \
          \                  \"result\": False,\n                        \"reason\"\
          : \"Failed to parse JSON, {}\".format(json_str)\n                    }\n\
          \                }\n            },\n        }\n\n    is_KTP_bool = True\
          \ if is_KTP == 'yes' else False\n    # NIK_valid_bool = True if NIK_valid\
          \ == 'yes' else False\n    within_valid_until_bool = True if within_valid_until\
          \ == 'yes' else False\n\n    # NIK正则表达式\n    pattern = r'^((1[1-9])|(21)|([37][1-6])|(5[1-4])|(6[1-5])|([8-9][1-2]))[0-9]{4}(([0-6][0-9])|(7[0-1]))((0[1-9])|(1[0-2]))[0-9]{5,6}$'\n\
          \    # 是否匹配\n    if NIK == '':\n        NIK_valid_bool = False\n    else:\n\
          \        if re.match(pattern, NIK):\n            NIK_valid_bool = True\n\
          \        else:\n            NIK_valid_bool = False\n\n    return {\n   \
          \     \"result\": {\n            \"result\": is_KTP_bool and NIK_valid_bool\
          \ and within_valid_until_bool,\n            \"reasons\": {\n           \
          \     \"is_KTP\": {\n                    \"result\": is_KTP_bool,\n    \
          \                \"reason\": is_KTP_reason\n                },\n       \
          \         \"NIK_valid\": {\n                    \"result\": NIK_valid_bool,\n\
          \                    \"reason\": NIK\n                },\n             \
          \   \"Berlaku_Hingga_valid\": {\n                    \"result\": within_valid_until_bool,\n\
          \                    \"reason\": valid_until\n                }\n      \
          \      }\n        },\n    }\n"
        code_language: python3
        desc: ''
        isInIteration: true
        isInLoop: false
        iteration_id: '1742461539107'
        outputs:
          result:
            children: null
            type: object
        selected: false
        title: Correct Logic
        type: code
        variables:
        - value_selector:
          - '1742461592701'
          - text
          variable: json_str
      height: 54
      id: '1742461676348'
      parentId: '1742461539107'
      position:
        x: 432
        y: 68
      positionAbsolute:
        x: 816.745343000969
        y: 462.54679314632386
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1742889121031'
          - is_correct
          variable: is_correct
        - value_selector:
          - '1742889121031'
          - is_clear
          variable: is_clear
        selected: false
        title: End
        type: end
      height: 116
      id: '1742461753448'
      position:
        x: 1453.1687040069946
        y: 450.4475182190014
      positionAbsolute:
        x: 1453.1687040069946
        y: 450.4475182190014
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        error_handle_mode: terminated
        is_parallel: true
        iterator_selector:
        - '1742289355685'
        - files
        output_selector:
        - '1742889017670'
        - value
        output_type: array[object]
        parallel_nums: 10
        selected: false
        start_node_id: 1742888860671start
        title: Clear
        type: iteration
        width: 692
      height: 148
      id: '1742888860671'
      position:
        x: 384.745343000969
        y: 611.5467931463238
      positionAbsolute:
        x: 384.745343000969
        y: 611.5467931463238
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 692
      zIndex: 1
    - data:
        desc: ''
        isInIteration: true
        selected: false
        title: ''
        type: iteration-start
      draggable: false
      height: 48
      id: 1742888860671start
      parentId: '1742888860671'
      position:
        x: 24
        y: 68
      positionAbsolute:
        x: 408.745343000969
        y: 679.5467931463238
      selectable: false
      sourcePosition: right
      targetPosition: left
      type: custom-iteration-start
      width: 44
      zIndex: 1002
    - data:
        desc: ''
        isInIteration: true
        isInLoop: false
        is_team_authorization: true
        iteration_id: '1742888860671'
        output_schema: null
        paramSchemas:
        - auto_generate: null
          default: null
          form: llm
          human_description:
            en_US: ''
            ja_JP: ''
            pt_BR: ''
            zh_Hans: ''
          label:
            en_US: input_file
            ja_JP: input_file
            pt_BR: input_file
            zh_Hans: input_file
          llm_description: ''
          max: null
          min: null
          name: input_file
          options: []
          placeholder:
            en_US: ''
            ja_JP: ''
            pt_BR: ''
            zh_Hans: ''
          precision: null
          required: true
          scope: null
          template: null
          type: file
        params:
          input_file: ''
        provider_id: 4ea4af5c-5d1c-41f6-bee8-2ea493d21ec8
        provider_name: Material - Common Tool For File Clear Check
        provider_type: workflow
        selected: false
        title: Material - Common Tool For File Clear Check
        tool_configurations: {}
        tool_label: Material - Common Tool For File Clear Check
        tool_name: file_clear_check
        tool_parameters:
          input_file:
            type: variable
            value:
            - '1742888860671'
            - item
        type: tool
      height: 54
      id: '1742889002707'
      parentId: '1742888860671'
      position:
        x: 128
        y: 68
      positionAbsolute:
        x: 512.745343000969
        y: 679.5467931463238
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        code: "\nfunction main({ result_clear_list }) {\n    if (result_clear_list.length\
          \ && result_clear_list.length > 0) {\n        const result_clear = result_clear_list[0].is_clear;\n\
          \        return {\n            value: result_clear,\n        };\n    } \n\
          \    return {\n        value: {},\n    }\n}\n"
        code_language: javascript
        desc: ''
        isInIteration: true
        isInLoop: false
        iteration_id: '1742888860671'
        outputs:
          value:
            children: null
            type: object
        selected: false
        title: Clear Logic
        type: code
        variables:
        - value_selector:
          - '1742889002707'
          - json
          variable: result_clear_list
      height: 54
      id: '1742889017670'
      parentId: '1742888860671'
      position:
        x: 432
        y: 68
      positionAbsolute:
        x: 816.745343000969
        y: 679.5467931463238
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        code: "function main({ is_correct_value_list, is_clear_value_list }) {\n\n\
          \    let is_correct = is_correct_value_list.find(item => {\n        return\
          \ item.result;\n    });\n\n    let is_clear = is_clear_value_list.find(item\
          \ => {\n        return item.result;\n    });\n\n    is_correct = is_correct\
          \ || is_correct_value_list[0];\n    is_clear = is_clear || is_clear_value_list[0];\n\
          \n    return {\n        is_correct,\n        is_clear,\n    };\n}"
        code_language: javascript
        desc: ''
        outputs:
          is_clear:
            children: null
            type: object
          is_correct:
            children: null
            type: object
        selected: false
        title: Aggregator
        type: code
        variables:
        - value_selector:
          - '1742461539107'
          - output
          variable: is_correct_value_list
        - value_selector:
          - '1742888860671'
          - output
          variable: is_clear_value_list
      height: 54
      id: '1742889121031'
      position:
        x: 1163.0358424630456
        y: 475.03843055477273
      positionAbsolute:
        x: 1163.0358424630456
        y: 475.03843055477273
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -1185.7637223384709
      y: -163.32937731035076
      zoom: 0.9889504015511178
```
You use this DSL publish tool. Then Agent is used.

**Comment by yj11** [comment]
```
app:
  description: ktp_recognize
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: ktp_recognize
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/gemini:0.0.8@420e755f870062b3da528617d2c0439a599ce1cbbb00645492c3bdb2b360afb6
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: llm
      id: 1742889359068-source-1742889362780-target
      source: '1742889359068'
      sourceHandle: source
      target: '1742889362780'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: llm
        targetType: end
      id: 1742889362780-source-1742889365418-target
      source: '1742889362780'
      sourceHandle: source
      target: '1742889365418'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - allowed_file_extensions: []
          allowed_file_types:
          - image
          allowed_file_upload_methods:
          - local_file
          - remote_url
          label: image
          max_length: 48
          options: []
          required: true
          type: file
          variable: image
      height: 90
      id: '1742889359068'
      position:
        x: 79
        y: 282
      positionAbsolute:
        x: 79
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        model:
          completion_params: {}
          mode: chat
          name: gemini-2.0-flash
          provider: langgenius/gemini/google
        prompt_template:
        - id: 3bfcd8a4-234d-4372-9936-c628d1dd97fa
          role: system
          text: 'Please help me recognize the Indonesian KTP (Kartu Tanda Penduduk)
            card and find some critical information. And return it to me in json format. 

            Here is the critical information: \"ktp_number\", \"full_name\", \"province\",
            \"date_of_birth\", and \"gender\". The keys in json must be these words.
            The value of each field is a string and must be extracted from the image
            and be precisely the same as in the picture.

            Please answer JSON data concisely.

            Notice:

            - \"province\" in [''DKI Jakarta'', ''Banten'', ''Jawa Barat'', ''Jawa
            Tengah'', ''Jawa Timur'', ''DI Yogyakarta'', ''Bali'', ''Sumatera Utara'',
            ''Sumatera Selatan'', ''Sumatera Barat'', ''Riau'', ''Jambi'', ''Aceh'',
            ''Lampung'', ''Bengkulu'', ''Kepulauan Bangka Belitung'', ''Kepulauan
            Riau'', ''Kalimantan Barat'', ''Kalimantan Tengah'', ''Kalimantan Selatan'',
            ''Kalimantan Timur'', ''Kalimantan Utara'', ''Sulawesi Barat'', ''Sulawesi
            Utara'', ''Sulawesi Tengah'', ''Sulawesi Selatan'', ''Sulawesi Tenggara'',
            ''Gorontalo'', ''Maluku'', ''Maluku Utara'', ''Nusa Tenggara Barat'',
            ''Nusa Tenggara Timur'', ''Papua'', ''Papua Barat'']

            - \"date_of_birth\" format is dd-mm-yyyy'
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          configs:
            detail: high
            variable_selector:
            - '1742889359068'
            - image
          enabled: true
      height: 90
      id: '1742889362780'
      position:
        x: 384
        y: 282
      positionAbsolute:
        x: 384
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1742889362780'
          - text
          variable: res
        selected: false
        title: 结束
        type: end
      height: 90
      id: '1742889365418'
      position:
        x: 688
        y: 282
      positionAbsolute:
        x: 688
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -173
      y: 151
      zoom: 1

```
Use this DSL.
