### ISSUE TITLE
Looking for Dify DSL Specification

### ISSUE THREAD

**Issue by poppop0911** [langgenius/dify#16979]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I'm currently exploring Dify and specifically looking for documentation or specifications regarding its DSL (Domain Specific Language) that can be used for LLM output generation. However, I haven't been able to locate any comprehensive documentation about this.

Could someone please point me to:
- The official DSL specification documentation
- Any examples of using Dify DSL with LLMs
- Best practices for implementing DSL generation with Dify

This information would be extremely helpful for implementing structured output generation in my project.

Thank you in advance for any guidance or resources you can provide!

**Comment by poppop0911** [comment]
# Dify DSL 配置说明

## 基础结构
```yaml
kind: app # 应用类型声明
version: "0.1.5" # DSL 版本号
app: # 应用基础配置
name: string # 应用名称
description: string # 应用描述
mode: string # 应用模式
enable_site: boolean # 是否启用网站访问
enable_api: boolean # 是否启用 API 访问
```

## 应用模式（mode）支持类型
1. `workflow`: 工作流模式
- 适用于需要定义复杂流程的应用
- 只需要基础的 app 配置

2. `completion`: 补全模式
- 适用于简单的文本生成应用
- 需要配置 model_config
- 支持自定义输入表单

3. `chat`: 对话模式
- 适用于基础对话应用
- 需要配置 model_config
- 支持基本的对话功能

4. `advanced-chat`: 高级对话模式
- 适用于复杂对话应用
- 支持自定义工作流程图
- 可以配置多个节点和边

5. `agent-chat`: 智能代理模式
- 适用于需要调用外部工具的应用
- 需要配置 model_config
- 支持工具集成

## 模型配置示例
```yaml
model_config:
model:
provider: "openai" # 模型提供商
name: "gpt-4o" # 模型名称
mode: "chat" # 模型模式
completion_params: {} # 补全参数

user_input_form: | # 用户输入表单（JSON 格式）
[
{
"paragraph": {
"label": "查询",
"variable": "query",
"required": true
}
}
]

pre_prompt: "{{query}}" # 预设提示语
```

## 工作流配置示例
```yaml
workflow:
conversation_variables: [] # 对话变量
environment_variables: [] # 环境变量

features: # 功能特性配置
file_upload:
enabled: boolean
speech_to_text:
enabled: boolean
text_to_speech:
enabled: boolean

graph: # 工作流程图
nodes: # 节点配置
- id: string
type: string
data: object
edges: # 边配置
- source: string
target: string
type: string
```

## 特性说明
1. `enable_site` 和 `enable_api`: 控制应用访问方式
2. `model_config`: 定义模型行为和参数
3. `workflow`: 定义复杂的处理流程
4. `features`: 配置额外功能特性
5. `graph`: 定义节点间的连接关系

## 最佳实践
1. 根据应用需求选择合适的模式
2. 合理配置模型参数
3. 正确设置节点间的连接关系
4. 根据需要启用相应的特性
5. 确保配置格式正确，特别是 JSON 字符串

这个配置框架支持从简单的对话应用到复杂的工作流应用，可以根据具体需求选择合适的模式和配置。
