### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information)

### ISSUE THREAD

**Issue by tashua314** [langgenius/dify#17424]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.1.3

### Cloud or Self Hosted

Cloud

## console error
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' data: mediastream: blob: filesystem: 'nonce-MzI5YWM4OTItM2RjMS00ODk5LWIxYzMtNDNiZjkwM2IxNWMw' *.dify.dev *.dify.ai *.udify.app udify.app *.r2.cloudflarestorage.com *.sentry.io http://localhost:* http://127.0.0.1:* https://analytics.google.com googletagmanager.com *.googletagmanager.com https://www.google-analytics.com https://api.github.com". Either the 'unsafe-inline' keyword, a hash ('sha256-h3DaRvfRtfr797lCBaD0t7VVe2c8eUvGzaJPsh1g3D8='), or a nonce ('nonce-...') is required to enable inline execution.

<img width="471" alt="Image" src="https://github.com/user-attachments/assets/be3332cf-75cd-460c-8377-150f0929c305" />

## DSL
```
app:
  description: 恋愛コミュニケーションのスキルをロールプレイングを通じて向上させるアプリです
  icon: heart_eyes
  icon_background: '#FBE8FF'
  mode: advanced-chat
  name: Koi-Tre AI v1.2
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/openai:0.0.11@390c87cc0f17370a70d3b214cd71a8de81fe9d6b52e6a38287acde034138b672
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - remote_url
      - local_file
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - remote_url
        - local_file
      number_limits: 3
    opening_statement: 'ようこそ！

      ここでは、ロールプレイを通じて恋愛力を向上させるトレーニングができます。

      上記の初期設定情報を元にシチュエーションを設定します。


      まず、「始める」と入力してください😄

      それに対してあなたがどのように反応するかを考え、セリフを答えてもらいます。

      それに対して評価とアドバイスを行います。


      一緒に恋愛シーンのセリフを学びましょう⭐


      まず「始める」と入力しましょう😄'
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      configs: []
      enabled: false
      type: ''
    speech_to_text:
      enabled: false
    suggested_questions:
    - 始める
    - Start（English ver.）
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        sourceType: code
        targetType: if-else
      id: 1714977608816-1714977531946
      source: '1714977608816'
      sourceHandle: source
      target: '1714977531946'
      targetHandle: target
      type: custom
    - data:
        sourceType: if-else
        targetType: answer
      id: 1714977531946-1714977798446
      source: '1714977531946'
      sourceHandle: 'false'
      target: '1714977798446'
      targetHandle: target
      type: custom
    - data:
        sourceType: start
        targetType: http-request
      id: start-1714980617122
      source: start
      sourceHandle: source
      target: '1714980617122'
      targetHandle: target
      type: custom
    - data:
        sourceType: http-request
        targetType: code
      id: 1714980617122-1714977608816
      source: '1714980617122'
      sourceHandle: source
      target: '1714977608816'
      targetHandle: target
      type: custom
    - data:
        sourceType: if-else
        targetType: llm
      id: 1714977531946-llm
      source: '1714977531946'
      sourceHandle: 'true'
      target: llm
      targetHandle: target
      type: custom
    - data:
        sourceType: question-classifier
        targetType: answer
      id: 1715740914219-answer
      source: '1715740914219'
      sourceHandle: '1'
      target: answer
      targetHandle: target
      type: custom
    - data:
        sourceType: question-classifier
        targetType: answer
      id: 1715740914219-1715741038536
      source: '1715740914219'
      sourceHandle: '2'
      target: '1715741038536'
      targetHandle: target
      type: custom
    - data:
        sourceType: llm
        targetType: question-classifier
      id: llm-1715740914219
      source: llm
      sourceHandle: source
      target: '1715740914219'
      targetHandle: target
      type: custom
    - data:
        sourceType: question-classifier
        targetType: code
      id: 1715740914219-1715761161876
      source: '1715740914219'
      sourceHandle: '1715740978305'
      target: '1715761161876'
      targetHandle: target
      type: custom
    - data:
        sourceType: code
        targetType: http-request
      id: 1715761161876-1715767438133
      source: '1715761161876'
      sourceHandle: source
      target: '1715767438133'
      targetHandle: target
      type: custom
    - data:
        sourceType: http-request
        targetType: answer
      id: 1715767438133-1715754492577
      source: '1715767438133'
      sourceHandle: source
      target: '1715754492577'
      targetHandle: target
      type: custom
    nodes:
    - data:
        selected: false
        title: START
        type: start
        variables:
        - default: ''
          description: null
          hint: null
          label: あなたの名前
          max_length: 48
          options: null
          required: true
          type: text-input
          variable: your_name
        - default: ''
          description: null
          hint: null
          label: あなたの性別
          max_length: null
          options:
          - 男性
          - 女性
          required: true
          type: select
          variable: your_sex
        - default: ''
          description: null
          hint: null
          label: あなたの年齢
          max_length: 48
          options: null
          required: true
          type: text-input
          variable: your_age
        - default: ''
          description: null
          hint: null
          label: ' お相手の年齢'
          max_length: 48
          options: null
          required: false
          type: text-input
          variable: partner_age
        - default: ''
          description: null
          hint: null
          label: お相手の性別
          max_length: null
          options:
          - 男性
          - 女性
          required: false
          type: select
          variable: partner_sex
        - default: ''
          description: null
          hint: null
          label: 会話の難易度
          max_length: null
          options:
          - 簡単
          - 普通
          - 難しい
          required: true
          type: select
          variable: level
        - default: ''
          description: null
          hint: null
          label: 会話の方法
          max_length: null
          options:
          - 対面
          - チャット
          required: true
          type: select
          variable: method
        - default: ''
          description: null
          hint: null
          label: その他希望があれば（職業・関係性・シチュエーションなど）
          max_length: null
          options: null
          required: false
          type: paragraph
          variable: other
        - label: あなたのID（画面下部に記載）
          max_length: 48
          options: []
          required: true
          type: text-input
          variable: uid
      height: 298
      id: start
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: false
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: null
        memory:
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: false
        model:
          completion_params:
            stop: []
            temperature: 1
          mode: chat
          name: gpt-4o
          provider: langgenius/openai/openai
        prompt_template:
        - id: 49bf103a-1e7d-48db-bd9b-4d9381974c4f
          role: system
          text: "# 概要\n会話が開始されたらまず最初に、このプロンプトでは何ができるかを８０文字程度で説明します。\n入力いただいた設定をベースにロープレを開始します。\n\
            恋愛シーンのあるシチュエーションを提示します。\nそのシチュエーションにおいて、あなたならどんなセリフを言うかを回答してもらいます。\nそのシチュエーションにおいて回答頂いたセリフを採点します。\n\
            採点結果として、「評価点」と「アドバイス」を出力します。\n※ 回答をもらうメッセージの最後に次の行を記述してください。\n   - もしどうしてもセリフが思い浮かばなかった場合、「ヒント」と入力してくださいね！\n\
            \n\n# 「評価点」のルール\n- 10点満点で採点\n- シチュエーションにおいて適切かどうかを評価\n- フォーマット：{点数} /\
            \ 10 点\n\n# 「アドバイス」のルール\n- 一つは褒める\n- シチュエーションにおいてより効果的な表現や改善点を伝える\n- 応援メッセージを含める\n\
            - 最後に、下記から進め方を選ばせる\n   - 1. このまま会話を進める\n   - 2. 同じシチュエーションをやり直す\n   -\
            \ 3. シチュエーションをリセット\n   - 4. 初期設定からリセット\n\n# 初期設定\n- あなたのお名前: {{#start.your_name#}}\n\
            \n- あなたの性別: {{#start.your_sex#}}\n\n- あなたの年齢: {{#start.your_age#}}\n\n\
            - お相手の年齢（未設定はランダム）: {{#start.partner_age#}}\n- お相手の性別: {{#start.partner_sex#}}\n\
            \n- 会話の難易度: {{#start.level#}}\n\n- 会話の方法: {{{#start.method#}}\n\n- その他希望があれば:\
            \ {{#start.other#}}\n\n# 「シチュエーション」のルール\n- 相手の名前・年齢・職業の提示\n   - 初期設定に指定が無ければランダムで設定（ランダム性は最大）\n\
            - 場所の提示\n- 二人の関係性の提示\n- 会話の流れの提示\n- 初期設定を元にランダムで作成する\n- シーンをイメージする画像を表示する\n\
            - 「このあと、どんなセリフを伝えますか？」と提示する\n\n# 会話のきっかけに関して\n「Start」と入力された場合は、内容を全て英語で記述してください。\n\
            同様に、もし他の言語でスタートされた場合はその言語に合わせて内容を記述してください。\nカタカナ・ひらがなで入力された場合は日本語で内容を記述してください。\n"
        selected: false
        title: LLM
        type: llm
        vision:
          configs:
            detail: high
          enabled: false
      height: 98
      id: llm
      position:
        x: 975.8459540839585
        y: 282
      positionAbsolute:
        x: 975.8459540839585
        y: 282
      selected: false
      type: custom
      width: 244
    - data:
        answer: '{{#llm.text#}}'
        selected: false
        title: ANSWER
        type: answer
      height: 103
      id: answer
      position:
        x: 1944.197300583185
        y: 282
      positionAbsolute:
        x: 1944.197300583185
        y: 282
      selected: false
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: is
            id: '1714977538276'
            value: 'True'
            variable_selector:
            - '1714977608816'
            - result
          logical_operator: and
        conditions:
        - comparison_operator: is
          id: '1714977538276'
          value: 'True'
          variable_selector:
          - '1714977608816'
          - result
        desc: ''
        logical_operator: and
        selected: false
        title: IF/ELSE
        type: if-else
      height: 126
      id: '1714977531946'
      position:
        x: 688.9284367573073
        y: 282
      positionAbsolute:
        x: 688.9284367573073
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "import json\n\ndef main(body: str) -> dict:\n    if check_record_exists(body):\n\
          \        return {\n            \"result\": \"True\",\n        }\n    else:\n\
          \        return {\n            \"result\": \"False\",\n        }\n\ndef\
          \ check_record_exists(json_body: str) -> bool:\n    \"\"\"\n    JSONレスポンスからレコードの存在をチェックする。\n\
          \    \n    :param json_body: JSON形式の文字列\n    :return: レコードが存在する場合はTrue、そうでない場合はFalse\n\
          \    \"\"\"\n    # JSONデータを辞書型に変換\n    body = json.loads(json_body)\n\n\
          \    # レコードが存在するかチェック（リストの長さが0より大きいか）\n    return len(body)"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: auth uid
        type: code
        variables:
        - value_selector:
          - '1714980617122'
          - body
          variable: body
      height: 54
      id: '1714977608816'
      position:
        x: 536.4822428537354
        y: 486.0512737597052
      positionAbsolute:
        x: 536.4822428537354
        y: 486.0512737597052
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: 'すみませんが、そのIDでは本サービスを使用できません。

          画面を読み込み直し、再度IDを確認して入力してください。'
        desc: ''
        selected: false
        title: 認証失敗
        type: answer
        variables: []
      height: 148
      id: '1714977798446'
      position:
        x: 975.8459540839585
        y: 452.2160099910112
      positionAbsolute:
        x: 975.8459540839585
        y: 452.2160099910112
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        authorization:
          type: no-auth
        body:
          type: none
        desc: ''
        headers: apikey:<TODO: apikey>
        method: get
        params: 'select:firebase_uid

          firebase_uid:eq.{{#start.uid#}}'
        retry_config:
          max_retries: 3
          retry_enabled: true
          retry_interval: 100
        selected: true
        timeout:
          connect: 10
          max_connect_timeout: 300
          max_read_timeout: 600
          max_write_timeout: 600
          read: 60
          write: 20
        title: supabaseにuidがあるか確認webhook
        type: http-request
        url: https://bnnhlqlmlqolrwpkkdxp.supabase.co/rest/v1/users
        variables: []
      height: 135
      id: '1714980617122'
      position:
        x: 340.54136863543704
        y: 321.2334845809437
      positionAbsolute:
        x: 340.54136863543704
        y: 321.2334845809437
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        classes:
        - id: '1'
          name: "進め方を選ぶ時\n\n# 大体の場合の選択肢\n   - 1. このまま会話を進める\n   - 2. 同じシチュエーションをやり直す\n\
            \   - 3. シチュエーションをリセット\n   - 4. 初期設定からリセット"
        - id: '2'
          name: ロールプレイを始める表現
        - id: '1715740978305'
          name: 'シチュエーションに即したセリフを言った時、もしくはヒントをもらう時

            （セリフは言わずに選ぶ場合もある）'
        desc: ''
        instruction: '今は恋愛ロールプレイの実施中、もしくは始める所です。

          大まかな流れとしては、

          - シチュエーションを設定する

          - ロールプレイを始める

          - シチュエーションに即したセリフを言うもしくは選択する

          - ヒントが欲しい時は「ヒント」（もしくは類する言葉）と言う

          - 次の行動選択する


          という流れです。


          質問がどの工程なのかを出力してください。'
        instructions: ''
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: gpt-4o
          provider: langgenius/openai/openai
        query_variable_selector:
        - sys
        - query
        selected: false
        title: 質問分類器
        topics: []
        type: question-classifier
      height: 308
      id: '1715740914219'
      position:
        x: 1333.5510167500129
        y: 282
      positionAbsolute:
        x: 1333.5510167500129
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#llm.text#}}'
        desc: ''
        selected: false
        title: ANSWER
        type: answer
        variables: []
      height: 103
      id: '1715741038536'
      position:
        x: 1944.197300583185
        y: 402.2583203745579
      positionAbsolute:
        x: 1944.197300583185
        y: 402.2583203745579
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#llm.text#}}'
        desc: ''
        selected: false
        title: ANSWER
        type: answer
        variables: []
      height: 103
      id: '1715754492577'
      position:
        x: 2272.0228611918205
        y: 560.4037691097429
      positionAbsolute:
        x: 2272.0228611918205
        y: 560.4037691097429
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "def main(res: str, query: str) -> dict:\n    return {\n        \"result\"\
          : res.replace('\\n', '\\\\n'),\n        \"query\": query.replace('\\n',\
          \ '\\\\n')\n    }"
        code_language: python3
        dependencies: []
        desc: ''
        outputs:
          query:
            children: null
            type: string
          result:
            children: null
            type: string
        selected: false
        title: 改行記号エスケープ
        type: code
        variables:
        - value_selector:
          - llm
          - text
          variable: res
        - value_selector:
          - sys
          - query
          variable: query
      height: 54
      id: '1715761161876'
      position:
        x: 1636.0902079409836
        y: 538.4900272392333
      positionAbsolute:
        x: 1636.0902079409836
        y: 538.4900272392333
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        authorization:
          config:
            api_key: <TODO: apikey>
            type: bearer
          type: api-key
        body:
          data: "  { \"uid\": \"{{#start.uid#}}\", \"conversation_id\": \"{{#sys.conversation_id#}}\"\
            , \"llm_text\": \"{{#1715761161876.result#}}\", \"query\": \"{{#1715761161876.query#}}\"\
            \ } \n"
          type: json
        desc: ''
        headers: 'apikey:<TODO: apikey>

          Content-Type:application/json

          Prefer:return=minimal'
        method: post
        params: ''
        retry_config:
          max_retries: 3
          retry_enabled: true
          retry_interval: 100
        selected: false
        timeout:
          connect: 10
          max_connect_timeout: 300
          max_read_timeout: 600
          max_write_timeout: 600
          read: 60
          write: 20
        title: 履歴保存
        type: http-request
        url: https://oj17qn5325.execute-api.ap-northeast-1.amazonaws.com/koi-tre/operations
        variables: []
      height: 151
      id: '1715767438133'
      position:
        x: 1944.197300583185
        y: 560.4037691097429
      positionAbsolute:
        x: 1944.197300583185
        y: 560.4037691097429
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -56.097524661471766
      y: -147.7762941155363
      zoom: 0.9432157975562474

```

### ✔️ Expected Behavior

open the app page

### ❌ Actual Behavior

Application error: a client-side exception has occurred (see the browser console for more information)
