### ISSUE TITLE
A simple image understanding workflow runs out of time

### ISSUE THREAD

**Issue by AnoyiX** [langgenius/dify#17673]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.1.3

### Cloud or Self Hosted

Cloud

## Bug Description

I wrote a workflow to get image info, when I upload a 2.9 MB image file, it runs more then 2 hours and hasn't finished now.

<img width="1458" alt="Image" src="https://github.com/user-attachments/assets/d3005966-cf74-48de-ac22-ef8dd0342d31" />

but if I upload a 240 KB image file, it's fast to get the result, only 32s.

<img width="1459" alt="Image" src="https://github.com/user-attachments/assets/b5e6f800-dbab-4d8f-9e3b-14d45ea11426" />

and I tried this workflow in dify v0.15.x, upload the same 2.9 MB image file, it's fast to get the result too.

### 1. Import this DSL

```yaml
cat Vision.yml 
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: Vision
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/volcengine_maas:0.0.10@ba0a7fc3151e89bf8645cd3abb3ccff971ee59e5b1127efca50b092dbb93bf80
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: llm
        targetType: end
      id: 1732269851607-source-1732248953168-target
      source: '1732269851607'
      sourceHandle: source
      target: '1732248953168'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: start
        targetType: llm
      id: 1732095090452-source-1732269851607-target
      source: '1732095090452'
      sourceHandle: source
      target: '1732269851607'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - allowed_file_extensions: []
          allowed_file_types:
          - image
          allowed_file_upload_methods:
          - local_file
          - remote_url
          label: image
          max_length: 48
          options: []
          required: false
          type: file
          variable: image
      height: 90
      id: '1732095090452'
      position:
        x: 262.5686389829273
        y: 561.5650822501483
      positionAbsolute:
        x: 262.5686389829273
        y: 561.5650822501483
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1732269851607'
          - text
          variable: result
        selected: false
        title: 结束
        type: end
      height: 90
      id: '1732248953168'
      position:
        x: 881.1955611797839
        y: 561.5650822501483
      positionAbsolute:
        x: 881.1955611797839
        y: 561.5650822501483
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        model:
          completion_params: {}
          mode: chat
          name: Doubao-1-5-Vision-Pro-32k
          provider: langgenius/volcengine_maas/volcengine_maas
        prompt_template:
        - id: 98954070-0fbd-4835-a9fd-49f27af5f07f
          role: system
          text: 描述图片信息
        - id: 351aaac1-9e48-45ce-a371-01a7dc6add75
          role: user
          text: ''
        selected: true
        title: LLM
        type: llm
        variables: []
        vision:
          configs:
            detail: low
            variable_selector:
            - '1732095090452'
            - image
          enabled: true
      height: 90
      id: '1732269851607'
      position:
        x: 571.8986719047097
        y: 561.5650822501483
      positionAbsolute:
        x: 571.8986719047097
        y: 561.5650822501483
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 170.55657787011023
      y: -89.59598942773005
      zoom: 1.1467788202501001
```
you can use other vision llm model

### 2. Upload a image file

image file size >= 2.5 MB

### ✔️ Expected Behavior

output the llm result as fast as API response, not only fast when upload a small image file.

### ❌ Actual Behavior

When uploading a large image file, the system freezes
