### ISSUE TITLE
Is it normal for the total token to be 0

### ISSUE THREAD

**Issue by CAICCU** [langgenius/dify#17764]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.2.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/2f7f9569-5512-4355-af97-cb6ea3c5ef96)

I connected to the locally deployed VLLM API and ran the demo, find that the consumed token was always 0, but the model can work normally. Is this normal？

**Comment by CAICCU** [comment]
this my vllm command:
```
    environment:
      - CUDA_VISIBLE_DEVICES=6,7
      - VLLM_WORKER_MULTIPROC_METHOD=spawn
      - NCCL_P2P_DISABLE=1
    command: ["--model", "/models/DeepSeek-R1-Distill-Qwen-32B",  "--served-model-name", "deepseek-r1-32b",  "--dtype", "float16", "--gpu-memory-utilization", "0.9", "--tensor_parallel_size", "2", "--max-model-len", "32768", "--enforce-eager", "--enable-reasoning", "--reasoning-parser", "deepseek_r1"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

```
