### ISSUE TITLE
Add Proxy in Alibaba Cloud Dify: 'Expecting value' Error on Page and X Installation Failure in Model Providers

### ISSUE THREAD

**Issue by zyfhg** [langgenius/dify#18108]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.2.0

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Hello, I launched Dify on Alibaba Cloud. In order to use the Grok API on it, I made the following modifications to the docker-compose.yaml file, hoping to use the proxy on the host machine. Here are the modifications I made: I added proxy configurations to four services, namely api, worker, web, and plugin_daemon.
After the modification, I conducted a test and was able to successfully use curl to access Google within the api Docker container. However, after accessing the Dify startup page, the page kept showing the error "Expecting value: line 1 column 1 (char 0)". Could you tell me what might be the cause of this issue?
Moreover, I found that I'm unable to install X in the model providers section. Can you help me troubleshoot this problem?
`
x-proxy-env: &proxy-env #new
  HTTP_PROXY:  http://172.17.0.1:7890
  HTTPS_PROXY: http://172.17.0.1:7890
  # Avoid re-routing internal traffic to proxies
  NO_PROXY: localhost,127.0.0.1,::1,db,redis,nginx,ssrf_proxy,sandbox

x-shared-env: &shared-api-worker-env
.....
services:
  # API service
  api:
    image: langgenius/dify-api:1.2.0
    restart: always
    dns:  #new addition
      - 8.8.8.8
      - 8.8.4.4
    environment:
      # Use the shared environment variables.
      <<: [*shared-api-worker-env, *proxy-env]  #new addition
      # Startup mode, 'api' starts the API server.
      MODE: api
....
  worker:
    image: langgenius/dify-api:1.2.0
    restart: always
    dns:  #new addition
      - 8.8.8.8
      - 8.8.4.4
    environment:
      # Use the shared environment variables.
      <<: [*shared-api-worker-env, *proxy-env]  #new addition
      # Startup mode, 'worker' starts the Celery worker for processing the queue.
      MODE: worker
....
  web:
    image: langgenius/dify-web:1.2.0
    restart: always
    dns:  #new addition
      - 8.8.8.8
      - 8.8.4.4
    environment:
      <<: *proxy-env  #new addition
      CONSOLE_API_URL: ${CONSOLE_API_URL:-}
  # plugin daemon
  plugin_daemon:
    image: langgenius/dify-plugin-daemon:0.0.7-local
    dns:   #new addition
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    environment:
      # Use the shared environment variables.   
      <<: [*shared-api-worker-env, *proxy-env]    #new addition
      DB_DATABASE: ${DB_PLUGIN_DATABASE:-dify_plugin}
      SERVER_PORT: ${PLUGIN_DAEMON_PORT:-5002}
....

`

**Comment by Sakura4036** [comment]
I added HTTP PROXY env for sanbox and plugin_daemon in middleware docker yaml, like you implemented, but I did not modify the dns, and also since I was started from source code, I also added HTTP PROXY at startup env. Currently, Google Gemini Model Provider is correctly used.

```yaml
x-proxy-env: &proxy-env
  HTTP_PROXY:  http://192.168.1.5:7890
  HTTPS_PROXY: http://192.168.1.5:7890
  NO_PROXY: localhost,127.0.0.1,::1,db,redis,ssrf_proxy,sandbox, 192.168.0.1/16

services:
  sandbox:
    image: langgenius/dify-sandbox:0.2.11
    restart: always
    env_file:
      - ./middleware.env
    environment:
      <<: *proxy-env
      ...

  plugin_daemon:
    image: langgenius/dify-plugin-daemon:0.0.7-local
    restart: always
    env_file:
      - ./middleware.env
    environment:
      <<: *proxy-env
...
```
