### ISSUE TITLE
When Ollama and Dify containers are started separately under Docker on the same host machine, Dify cannot access Ollama using the Ollama container name.

### ISSUE THREAD

**Issue by solan30003** [langgenius/dify#18165]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.1.3, 1.2.0

### Cloud or Self Hosted

Self Hosted (Docker)

### I. Background:
On the same host machine (192.168.110.201, firewall already disabled), two docker-compose.yaml files are used to start Ollama and Dify (api, work, etc.) containers separately. They share a bridge network named ollama-dify-net.
Both can start normally, and http://192.168.0.201:11434 can be accessed normally. Dify can also access and install the Ollama model plugin without issues.
Using the command "docker inspect ollama-dify-net", the obtained container IPs are: Ollama container: 172.21.0.2, docker-api-1 container: 172.21.0.4.
```json
"Containers": {
            "3693b2e12e089c2fc268a18cecf6f5e17cd5ba6b2d08c7eac8824079ceffe562": {
                "Name": "docker-api-1",
                "EndpointID": "3e86ec6cfc3992bd239d7bd80429e6b271a0ee0490ba46a4789006bbcab1fef5",
                "MacAddress": "02:42:ac:15:00:04",
                "IPv4Address": "172.21.0.4/16",
                "IPv6Address": ""
            },
            "3caa5eb4f4400bd03867461553357b080d4b9b319aefe8656bc035a0a2e87648": {
                "Name": "docker-sandbox-1",
                "EndpointID": "5cfd438ae23028584a1fa05334da0f89db9f10ce2866151d48c4abf9d2ef6045",
                "MacAddress": "02:42:ac:15:00:03",
                "IPv4Address": "172.21.0.3/16",
                "IPv6Address": ""
            },
            "77c66a480b9d4db0d968470d39555349e137aa68e8ca0bade2b7ed538b163b9d": {
                "Name": "docker-nginx-1",
                "EndpointID": "c00dc3cd786206aa517532ba8566a610c02db9c93a583f2c7b2a28d17fb9d49f",
                "MacAddress": "02:42:ac:15:00:06",
                "IPv4Address": "172.21.0.6/16",
                "IPv6Address": ""
            },
            "8c26240de7087c70323875a34166787f140d82e939d80dfc81ed1db5fabeaf46": {
                "Name": "docker-worker-1",
                "EndpointID": "bafa4a240107d5811aeda7aee8f2e771213bf25333dc944d4f2ce110654269ca",
                "MacAddress": "02:42:ac:15:00:05",
                "IPv4Address": "172.21.0.5/16",
                "IPv6Address": ""
            },
            "954728dd0b211fe721e747ea8cd1b69530a7750b0f50d195e387495189817d9a": {
                "Name": "ollama",
                "EndpointID": "46fda917e84f114e0312c76b46152821ba7a5eae899566e33158af40381242a1",
                "MacAddress": "02:42:ac:15:00:02",
                "IPv4Address": "172.21.0.2/16",
                "IPv6Address": ""
            }
        },
```

**II. Network Debugging:**
(1) Accessing from the host machine:
Successful: curl http://192.168.110.201:11434 returns: Ollama is running
(2) Inside the docker-api-1 container (172.21.0.4), network debugging as follows:
Successful: ping ollama
Successful: ping 172.21.0.2
Successful (Ollama is running): curl http://ollama:11434
Successful (Ollama is running): curl http://172.21.0.2:11434
Failed: curl http://192.168.110.201:11434

Such as:
```
root@3693b2e12e08:/app/api# curl http://ollama:11434
Ollama is running
root@3693b2e12e08:/app/api# curl http://172.21.0.2:11434
Ollama is running
root@3693b2e12e08:/app/api# curl http://192.168.110.201:11434
curl: (7) Failed to connect to 192.168.110.201 port 11434 after 1 ms: Couldn't connect to server
```
Based on the above description, the Ollama and Dify (api) containers are successfully sharing the network, and the api container can access the Ollama service using the Ollama container name from within.

### III. Execution and Error:
On the Dify settings page - model provider, when configuring the Ollama plugin with the model service provided by the Ollama container, an error occurs with the message: Failed to resolve 'ollama' ([Errno -2] Name or service not known).

**The browser's HTTP request and response are as follows:**
**POST:**
http://192.168.110.211/console/api/workspaces/current/model-providers/langgenius/ollama/ollama/models
**REQUEST BODY:**
```json
{"model":"deepseek-r1:1.5b","model_type":"llm","credentials":{"mode":"chat","context_size":"4096","max_tokens":"4096","vision_support":"false","function_call_support":"false","base_url":"http://ollama:11434"},"load_balancing":{"enabled":false,"configs":[]}}
```
**RESPONSE:**
```json
{
    "code": "invalid_param",
    "message": "An error occurred during credentials validation: HTTPConnectionPool(host='ollama', port=11434): Max retries exceeded with url: /api/chat (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7fdcb36f65a0>: Failed to resolve 'ollama' ([Errno -2] Name or service not known)\"))",
    "status": 400
}
```

If BaseUrl: http://172.21.0.2:11434, error:
```json
{
    "code": "invalid_param",
    "message": "An error occurred during credentials validation: HTTPConnectionPool(host='172.21.0.2', port=11434): Max retries exceeded with url: /api/chat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdcb373d520>, 'Connection to 172.21.0.2 timed out. (connect timeout=10)'))",
    "status": 400
}
```
If BaseUrl: http://192.168.110.211:11434, error:
```json
{
    "code": "invalid_param",
    "message": "An error occurred during credentials validation: HTTPConnectionPool(host='192.168.110.211', port=11434): Max retries exceeded with url: /api/chat (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fdcb36f5c10>, 'Connection to 192.168.110.211 timed out. (connect timeout=10)'))",
    "status": 400
}

```

![Image](https://github.com/user-attachments/assets/b8f853f0-b57d-43ad-87bd-9a67dee3baa1)
![Image](https://github.com/user-attachments/assets/41b4f1f0-3df4-40f6-9ea4-7ecfddd844aa)

 ### IV. Configuration Files

**ollama's docker-compose.yaml：**
```yaml
services:       # 定义服务
  ollama:          # 服务名称
    image: ollama/ollama  # 使用的镜像
    container_name: ollama
    ports:
      - "11434:11434"  # 映射端口
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    volumes:
      - /opt/data/ollama:/root/.ollama  # 挂载卷
      #- ollama_data:/root/.ollama
    networks:
      #- mynet  # 使用的网络
      #- default
      - ollama-dify-net

networks:
  ollama-dify-net:
    external: true
```
**dify's docker-compose.yaml：**
```yaml
services:
  # API service
  api:
    image: langgenius/dify-api:1.1.3
    ...other settings...
    networks:
      - ssrf_proxy_network
      - default
      - ollama-dify-net
  worker:
    image: langgenius/dify-api:1.1.3
    ...other settings...
    networks:
      - ssrf_proxy_network
      - default
      - ollama-dify-net
  sandbox:
    image: langgenius/dify-sandbox:0.2.11

  ...other settings...
    networks:
      - ssrf_proxy_network
      - ollama-dify-net

networks:
  ollama-dify-net:
    external: true
  ssrf_proxy_network:
    driver: bridge
    internal: true
  milvus:
    driver: bridge
  opensearch-net:
    driver: bridge
    internal: true
```

### ✔️ Expected Behavior

In a shared network environment, Dify can correctly access Ollama's service using the Ollama container name.
**Please** do not use http://host.docker.internal:11434. I want to use Ollama's container name to access it within the shared network environment. In fact, **_host.docker.internal_** is also inaccessible.

### ❌ Actual Behavior

Dify cannot access Ollama using the Ollama container name
```json
{
    "code": "invalid_param",
    "message": "An error occurred during credentials validation: HTTPConnectionPool(host='ollama', port=11434): Max retries exceeded with url: /api/chat (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7fdcb36f65a0>: Failed to resolve 'ollama' ([Errno -2] Name or service not known)\"))",
    "status": 400
}
```

**Comment by kenwoodjw** [comment]
@solan30003 You need to add network to plugin_daemon
```
plugin_daemon:
    image: langgenius/dify-plugin-daemon:0.0.7-local
  ...other settings...
    networks:
      - default
      - ollama-dify-net
```
