### ISSUE TITLE
### Delimiter unsupported by chuncking md file?

### ISSUE THREAD

**Issue by pandabearambat** [langgenius/dify#18626]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.3.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

# GitLab CI Action: CCA SBOM Generic Job

## Description

Generic action for SBOM generation for Code Clearance. This job scans the specified location for package dependencies and generates a Software Bill of Materials (SBOM) in compliance with the Standard BOM v2 format.

## Stage

This job is executed in the `analysis` stage of the CI/CD pipeline.

### Required Variables

- `SCAN_LOCATION`: Location of package dependencies you want to scan (relative to the repository root). Defaults to `"."`.
- `RUN_MODE`: Defines the mode of operation. Allowed values are:
  - `scan`: Perform a standard scan.
  - `convert`: Convert existing data.
  - `deep-scan`: Perform a deep scan. Defaults to `"scan"`.

### Optional Variables

- `SBOM_V2`: Transforms output to Standard BOM v2 format if set to `"true"`. Defaults to `"true"`.

## How to use

To use this job in your GitLab CI pipeline, include the following snippet in your `.gitlab-ci.yml` file:

```yaml
stages:
- analysis

include:
- project: dm/devops-coe/sasops/actions/common-actions
  file: catalog.yml
  ref: main

cca-sbom-generic-job:
  stage: analysis
  extends:
    - .common-actions.jobs.cca-sbom-generic-job
  variables:
    SCAN_LOCATION: "artifacts/tests/testdata/npm/node_modules/"
  needs:
    - job: build-generic-job
      artifacts: true
```

for example this md file , im able to use chunk settings of (?<=\n{2}|\n#{1,6} |\n- ) delmiter and 500 Maximum chunk length and 50 chunk overlap 

![Image](https://github.com/user-attachments/assets/233cb102-20b8-453c-a691-649b2f2cb3e7)

everything is fine related to # and ## chunck but for example on ## variables and sub of it ### i expect to have all in one chunk, tried to change related delimiter but no clue 
only if i remove the section of ### (for required variables and optional) as per example:
## Variables

   Required Variables
- `SCAN_LOCATION`: Location of package dependencies you want to scan (relative to the repository root). Defaults to `"."`.
- `RUN_MODE`: Defines the mode of operation. Allowed values are:
  - `scan`: Perform a standard scan.
  - `convert`: Convert existing data.
  - `deep-scan`: Perform a deep scan. Defaults to `"scan"`.
  Optional Variables
- `SBOM_V2`: Transforms output to Standard BOM v2 format if set to `"true"`. Defaults to `"true"`.

 under ##variables it makes it all in one chunk:
 
is there is something that I missed here please ?

### ✔️ Expected Behavior

have varaibles example in one chunk and not separted ## and sub of it ###

### ❌ Actual Behavior

separated chunks of variable section
