### ISSUE TITLE
structured_output of LLM node can not used to assignment node

### ISSUE THREAD

**Issue by Sakura4036** [langgenius/dify#18670]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

v1.3.0

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

1. create a chatflow and add a Session variable named `target`
2. add a llm node, configure structured_output Including `message` field
3. add assignment node， assign Session variable `target` with structured_output value `message`

![Image](https://github.com/user-attachments/assets/3eff70f9-78cd-4b18-92ba-4e37483fc933)

![Image](https://github.com/user-attachments/assets/1980349c-1cee-4171-b1cd-02808eb24edd)

![Image](https://github.com/user-attachments/assets/6d344204-7f29-4175-a264-37a2b6abda57)

### ✔️ Expected Behavior

 variable `target` assigned successfully

### ❌ Actual Behavior

Run failed: Invalid input value ['17454578199050', 'structured_output', 'message']

![Image](https://github.com/user-attachments/assets/3573c530-f743-47ff-8097-302a99c48e09)

**Comment by Sakura4036** [comment]
```yaml
app:
  description: 判断意图，生成调研方向和大纲
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: test_llm_output
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: package
  value:
    plugin_unique_identifier: langgenius/volcengine_maas:0.0.10@ba0a7fc3151e89bf8645cd3abb3ccff971ee59e5b1127efca50b092dbb93bf80
kind: app
version: 0.2.0
workflow:
  conversation_variables:
  - description: 调研方向
    id: ea7376a1-68dc-4082-b2c7-1182bb321cc7
    name: research_direction
    selector:
    - conversation
    - research_direction
    value: ''
    value_type: string
  - description: 调研阶段
    id: 3e13e453-9fb6-4626-900a-6e9e2e3614c4
    name: stage_research
    selector:
    - conversation
    - stage_research
    value: research
    value_type: string
  - description: 确认调研方向
    id: 4756ed27-c2a7-4f35-bd77-2e6cfd204af3
    name: stage_direction
    selector:
    - conversation
    - stage_direction
    value: direction
    value_type: string
  - description: 意图识别阶段
    id: a6b62837-a157-4808-bc0b-0e70d2953314
    name: stage_query
    selector:
    - conversation
    - stage_query
    value: query
    value_type: string
  - description: 用户目标
    id: d8cad58f-5886-4f5b-9444-3b6c6ea65abb
    name: user_target
    selector:
    - conversation
    - user_target
    value: ''
    value_type: string
  - description: 当前运行阶段
    id: aa3e0ad7-22b1-492b-9f8b-6e6eeef0caf9
    name: stage
    selector:
    - conversation
    - stage
    value: query
    value_type: string
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 500
        batch_count_limit: 50
        file_size_limit: 150
        image_file_size_limit: 20
        video_file_size_limit: 1000
        workflow_file_upload_limit: 100
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: answer
        targetType: assigner
      id: answer-source-1744963982943-target
      selected: false
      source: answer
      sourceHandle: source
      target: '1744963982943'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: if-else
        targetType: answer
      id: 1744963729446-true-answer-target
      selected: false
      source: '1744963729446'
      sourceHandle: 'true'
      target: answer
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: if-else
        targetType: assigner
      id: 1744963729446-false-1744964071679-target
      selected: false
      source: '1744963729446'
      sourceHandle: 'false'
      target: '1744964071679'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: assigner
        targetType: answer
      id: 1744964071679-source-1744964039703-target
      selected: false
      source: '1744964071679'
      sourceHandle: source
      target: '1744964039703'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: if-else
      id: 1744962850876-source-1744965447400-target
      selected: false
      source: '1744962850876'
      sourceHandle: source
      target: '1744965447400'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: answer
        targetType: llm
      id: 1744964039703-source-1744965593584-target
      selected: false
      source: '1744964039703'
      sourceHandle: source
      target: '1744965593584'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: assigner
        targetType: answer
      id: 1744966755777-source-1744966533657-target
      selected: false
      source: '1744966755777'
      sourceHandle: source
      target: '1744966533657'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: if-else
        targetType: llm
      id: 1744965447400-true-17454578199050-target
      selected: false
      source: '1744965447400'
      sourceHandle: 'true'
      target: '17454578199050'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: llm
        targetType: if-else
      id: 17454578199050-source-1744963729446-target
      selected: false
      source: '17454578199050'
      sourceHandle: source
      target: '1744963729446'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: llm
        targetType: assigner
      id: 1744965593584-source-1744966755777-target
      selected: false
      source: '1744965593584'
      sourceHandle: source
      target: '1744966755777'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: if-else
        targetType: answer
      id: 1744965447400-false-1745546009830-target
      source: '1744965447400'
      sourceHandle: 'false'
      target: '1745546009830'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - label: additional_info
          max_length: 48000
          options: []
          required: false
          type: paragraph
          variable: additional_info
      height: 89
      id: '1744962850876'
      position:
        x: -56.944694793544954
        y: 505.89007484392687
      positionAbsolute:
        x: -56.944694793544954
        y: 505.89007484392687
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#17454578199050.structured_output.message#}}'
        desc: ''
        selected: false
        title: 继续询问
        type: answer
        variables: []
      height: 104
      id: answer
      position:
        x: 1246
        y: 347.5
      positionAbsolute:
        x: 1246
        y: 347.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: is
            id: 13800553-ff35-4243-b0c6-0b4d9e3ad65e
            value: 'no'
            varType: object
            variable_selector:
            - '17454578199050'
            - structured_output
            - clear
          id: 'true'
          logical_operator: and
        desc: ''
        selected: false
        title: 条件分支 2
        type: if-else
      height: 125
      id: '1744963729446'
      position:
        x: 942
        y: 347.5
      positionAbsolute:
        x: 942
        y: 347.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        items:
        - input_type: variable
          operation: over-write
          value:
          - conversation
          - stage_query
          variable_selector:
          - conversation
          - stage
          write_mode: over-write
        selected: false
        title: 变量赋值 2
        type: assigner
        version: '2'
      height: 87
      id: '1744963982943'
      position:
        x: 1550
        y: 347.5
      positionAbsolute:
        x: 1550
        y: 347.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '好的，目前明确您的任务目标: {{#conversation.user_target#}}

          正在生成调研方向...'
        desc: ''
        selected: false
        title: 目标确定
        type: answer
        variables: []
      height: 120
      id: '1744964039703'
      position:
        x: 1550
        y: 469.90135343037355
      positionAbsolute:
        x: 1550
        y: 469.90135343037355
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        items:
        - input_type: constant
          operation: over-write
          value:
          - '17454578199050'
          - structured_output
          - message
          variable_selector:
          - conversation
          - user_target
          write_mode: over-write
        - input_type: variable
          operation: over-write
          value:
          - conversation
          - stage_direction
          variable_selector:
          - conversation
          - stage
          write_mode: over-write
        selected: false
        title: 变量赋值 2
        type: assigner
        version: '2'
      height: 115
      id: '1744964071679'
      position:
        x: 1252.2996052494743
        y: 486.2006767151868
      positionAbsolute:
        x: 1252.2996052494743
        y: 486.2006767151868
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: empty
            id: 13832cf0-4bce-41fa-aeed-ec7d05cf7a64
            value: ''
            varType: string
            variable_selector:
            - conversation
            - stage
          - comparison_operator: is
            id: c75cfae9-d8e2-4ecc-8240-9ec0719d6b74
            value: '{{#conversation.stage_query#}}'
            varType: string
            variable_selector:
            - conversation
            - stage
          id: 'true'
          logical_operator: or
        desc: ''
        selected: false
        title: 条件分支 3
        type: if-else
      height: 151
      id: '1744965447400'
      position:
        x: 315.1011842515769
        y: 505.89007484392687
      positionAbsolute:
        x: 315.1011842515769
        y: 505.89007484392687
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: DeepSeek-V3
          provider: langgenius/volcengine_maas/volcengine_maas
        prompt_template:
        - id: 3a75dcf1-b752-40e8-a1f6-bc3b8ea5982c
          role: system
          text: "<instruction>\n调研专家，根据用户任务分析调研方向并以换行符分割返回。以下是详细的步骤和示例，确保输出清晰且不含任何XML标签。\n\
            \n<instructions>\n1. 仔细阅读用户提供的任务描述，明确调研的核心目标和需求。\n2. 根据任务描述，拆解出可能的调研方向或关键问题，确保每个方向与任务目标高度相关。\n\
            3. 将分析出的调研方向用换行符分隔，每个方向应简洁明了，避免冗长。\n4. 确保输出不包含任何XML标签或其他格式标记，仅以纯文本形式返回。\n\
            5. 如果任务描述模糊或信息不足，可适当补充合理的调研方向，但需标注为“推测方向”。\n</instructions>\n\n<examples>\n\
            <example>\n输入：分析新能源汽车市场的增长潜力  \n输出：  \n新能源汽车技术发展趋势  \n消费者对新能源汽车的接受度  \n\
            政策支持与补贴的影响  \n充电基础设施的完善程度  \n竞争对手的市场份额分析  \n</example>\n\n<example>\n\
            输入：研究远程办公对员工生产力的影响  \n输出：  \n远程办公工具的使用效率  \n员工工作满意度与生产力的关系  \n远程团队沟通协作的挑战\
            \  \n家庭环境对工作效率的影响  \n长期远程办公的心理健康影响  \n</example>\n\n<example>\n输入：探索智能家居产品的用户需求\
            \  \n输出：  \n智能家居产品的核心功能需求  \n用户对隐私安全的关注点  \n价格敏感度与购买意愿  \n不同年龄段用户的使用偏好\
            \  \n智能家居与其他设备的兼容性需求  \n</example>\n</examples>\n\n<notes>\n1. 每个调研方向应独立成行，避免重复或重叠内容。\
            \  \n2. 如果任务涉及多个细分领域，可适当分组或分层次列出方向。  \n3. 输出时无需编号或添加标题，仅用换行符分隔即可。  \n\
            4. 若用户任务描述过于宽泛，可优先列出最相关的3-5个方向。  \n</notes>\n</instruction>"
        - id: fb78317d-1105-40b5-b207-05f75289b95a
          role: user
          text: 'target:{{#conversation.user_target#}} {{#conversation.user_target#}}


            addtional_info: {{#1744962850876.additional_info#}}'
        retry_config:
          max_retries: 3
          retry_enabled: false
          retry_interval: 1000
        selected: false
        structured_output:
          schema:
            additionalProperties: false
            properties:
              research_directions:
                description: 调研方向字符串列表
                items:
                  type: string
                type: array
            required:
            - research_directions
            type: object
        structured_output_enabled: false
        title: 调研方向
        type: llm
        variables: []
        vision:
          enabled: false
      height: 89
      id: '1744965593584'
      position:
        x: 1855.7998872141357
        y: 491.5
      positionAbsolute:
        x: 1855.7998872141357
        y: 491.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '调研方向如下，如需修改请详细描述：

          {{#1744965593584.structured_output.research_directions#}}'
        desc: ''
        selected: false
        title: 直接回复 3
        type: answer
        variables: []
      height: 120
      id: '1744966533657'
      position:
        x: 2522.1152824846354
        y: 491.5
      positionAbsolute:
        x: 2522.1152824846354
        y: 491.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        items:
        - input_type: variable
          operation: over-write
          value:
          - '1744965593584'
          - text
          variable_selector:
          - conversation
          - research_direction
          write_mode: over-write
        - input_type: variable
          operation: over-write
          value:
          - conversation
          - stage_outline
          variable_selector:
          - conversation
          - stage
          write_mode: over-write
        selected: false
        title: 变量赋值 3
        type: assigner
        version: '2'
      height: 115
      id: '1744966755777'
      position:
        x: 2185.7173126301955
        y: 491.5
      positionAbsolute:
        x: 2185.7173126301955
        y: 491.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        isInIteration: false
        isInLoop: true
        loop_id: '1745456837401'
        memory:
          query_prompt_template: '{{#sys.query#}}'
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: false
            size: 48
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: DeepSeek-V3
          provider: langgenius/volcengine_maas/volcengine_maas
        prompt_template:
        - id: c814bf32-1123-4591-8964-2909ed7d71f0
          role: system
          text: "<instruction>\n你是一个智能助手，你的任务是分析用户问题，帮助用户完成调研任务。你需要通过对话明确用户的意图和需求。以下是你的工作流程：\n\
            \n1. **分析用户输入**：仔细阅读用户的问题或描述，判断其目标是否清晰。\n2. **判断清晰度**：\n   - 如果用户描述模糊或信息不足，回复{\"\
            clear\":\"no\", \"message\":\"你的引导问题\"}，通过提问帮助用户明确目标。\n   - 如果用户目标明确，回复{\"\
            clear\":\"yes\", \"message\":\"用户的具体任务描述\"}。\n3. **输出格式**：确保输出为纯JSON格式，不包含任何XML标签或其他标记语言。\n\
            4. **对话引导**：若用户目标不明确，提出开放式问题或提供选项，帮助用户聚焦需求。\n5. **任务确认**：当用户目标明确后，总结任务描述并确认。\n\
            \n注意：所有输出必须为JSON格式，且不包含额外标记或解释。不要包含**```**标记。\n</instruction>\n\n<examples>\n\
            以下是输入和输出的示例：\n\n<example>\n输入：\"我想了解市场趋势。\"\n输出：{\"clear\":\"no\", \"\
            message\":\"您想了解哪个行业或产品的市场趋势？是否有具体的时间范围或地区？\"}\n</example>\n\n<example>\n\
            输入：\"我需要2023年中国新能源汽车市场的销售数据和竞争分析。\"\n输出：{\"clear\":\"yes\", \"message\"\
            :\"用户需要2023年中国新能源汽车市场的销售数据和竞争分析。\"}\n</example>\n\n<example>\n输入：\"帮我找一些资料。\"\
            \n输出：{\"clear\":\"no\", \"message\":\"您需要什么主题的资料？是学术研究、行业报告还是其他类型？请提供更多细节。\"\
            }\n</example>\n</examples>\n\n<additional_guidance>\n- 避免假设用户意图，始终通过提问确认模糊描述。\n\
            - 若用户多次未能明确目标，逐步缩小范围（如提供选项：\"您是想要A、B还是C？\"）。\n- 对于明确任务，需在message中精确复述用户需求，不可简化或改写。\n\
            - 所有交互需保持专业和友好，避免机械式回复。\n</additional_guidance>\n\n</instruction>"
        retry_config:
          max_retries: 3
          retry_enabled: true
          retry_interval: 1000
        selected: false
        structured_output:
          schema:
            additionalProperties: false
            properties:
              clear:
                enum:
                - 'yes'
                - 'no'
                type: string
              message:
                type: string
            required:
            - clear
            - message
            type: object
        structured_output_enabled: true
        title: 意图识别
        type: llm
        variables: []
        vision:
          enabled: false
      height: 119
      id: '17454578199050'
      position:
        x: 638
        y: 347.5
      positionAbsolute:
        x: 638
        y: 347.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        answer: test {{#conversation.stage#}}
        desc: ''
        selected: false
        title: 直接回复 4
        type: answer
        variables: []
      height: 104
      id: '1745546009830'
      position:
        x: 638
        y: 505.5
      positionAbsolute:
        x: 638
        y: 505.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 108.78772097894648
      y: 61.53016024218414
      zoom: 0.8165703277032814
```

**Comment by Sakura4036** [comment]
![Image](https://github.com/user-attachments/assets/45b02538-ce72-434f-9081-2cb701be7527)

**Comment by Sakura4036** [comment]
remove the variable and add it again, it works.

**Comment by Sakura4036** [comment]
but why this session variable's input_type is being set to constant?

**Comment by Sakura4036** [comment]
> > but why this session variable's input_type is being set to constant?
> 
> Are all of your operations performed on the page? If so, we will continue to investigate the cause of this issue.

yes, on the page. 

Is it possible that it is due to version issues? This Workflow app and session variables are created in `v.1.2.0`, and llm structured_output is only supported in `v1.3.0`.

**Comment by Sakura4036** [comment]
No, I shouldn't have set any numeric session variables, they are all string variables.

**Comment by Sakura4036** [comment]
@Nov1c444  right, i encountered this problem again, and this time, even if I delete and then add the session variable again, it still doesn't work!  And this time, the input_type is `variable` instead of `constant`.

![Image](https://github.com/user-attachments/assets/e47c7307-6ff7-492a-8769-a7ac8907c3e7)

![Image](https://github.com/user-attachments/assets/d29505d0-f53e-4334-8470-e075604d9606)

![Image](https://github.com/user-attachments/assets/a612be50-8d11-4236-a57f-db18524e81f2)

```yml
- data:
        desc: ''
        items:
        - input_type: variable
          operation: over-write
          value:
          - conversation
          - stage_research
          variable_selector:
          - conversation
          - stage
          write_mode: over-write
        - input_type: variable
          operation: over-write
          value:
          - conversation
          - plan
          variable_selector:
          - conversation
          - plan
          write_mode: over-write
        - input_type: variable
          operation: over-write
          value:
          - '1745747199389'
          - structured_output
          - market_task
          variable_selector:
          - conversation
          - market_task
          write_mode: over-write
        - input_type: variable
          operation: over-write
          value:
          - '1745747199389'
          - structured_output
          - academy_task
          variable_selector:
          - conversation
          - academy_task
          write_mode: over-write
        - input_type: variable
          operation: over-write
          value:
          - '1745747199389'
          - structured_output
          - patent_task
          variable_selector:
          - conversation
          - patent_task
          write_mode: over-write
        selected: true
        title: 变量赋值 2
        type: assigner
        version: '2'
```
