### ISSUE TITLE
Variable Block can not read conversation variables

### ISSUE THREAD

**Issue by jamesljl** [langgenius/dify#18929]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.3.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Variable Block can not read conversation variables even conversation variables already exists

![Image](https://github.com/user-attachments/assets/be514ec0-be28-40ae-9be0-5b959aaa44dc)

**Comment by QuantumGhost** [comment]
Thank you for reporting this issue. However, I was unable to reproduce the behavior you described on my side. The variable selector appears to function correctly and is assigning values to conversation variables as expected.

<img width="916" alt="Image" src="https://github.com/user-attachments/assets/d94d80ef-5240-4377-8285-1b6e83ae9c52" />

I suspect the issue might be related to your deployment setup.

To assist with troubleshooting, I’ve exported the workflow DSL from my environment where the issue is not present. You can copy it  and import it into your deployment to verify. Let me know if the issue persists after testing.

```yml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: convvar
  use_icon_as_answer_icon: false
dependencies: []
kind: app
version: 0.2.0
workflow:
  conversation_variables:
  - description: test variable
    id: 0d45c2cf-5b2e-4eee-bc55-0e717ddd0168
    name: testConvVar01
    selector:
    - conversation
    - testConvVar01
    value: '"a"'
    value_type: string
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInLoop: false
        sourceType: start
        targetType: answer
      id: 1745769614409-source-1745769620734-target
      source: '1745769614409'
      sourceHandle: source
      target: '1745769620734'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: assigner
        targetType: answer
      id: 1745769834853-source-answer-target
      source: '1745769834853'
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: answer
        targetType: assigner
      id: 1745769620734-source-1745769834853-target
      source: '1745769620734'
      sourceHandle: source
      target: '1745769834853'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables: []
      height: 54
      id: '1745769614409'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: 'Before: {{#conversation.testConvVar01#}}


          '
        desc: ''
        selected: false
        title: Answer 2
        type: answer
        variables: []
      height: 105
      id: '1745769620734'
      position:
        x: 380
        y: 282
      positionAbsolute:
        x: 380
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: 'After: {{#conversation.testConvVar01#}}


          '
        desc: ''
        selected: false
        title: Answer
        type: answer
        variables: []
      height: 105
      id: answer
      position:
        x: 980
        y: 282
      positionAbsolute:
        x: 980
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        items:
        - input_type: variable
          operation: over-write
          value:
          - sys
          - conversation_id
          variable_selector:
          - conversation
          - testConvVar01
          write_mode: over-write
        selected: true
        title: Variable Assigner
        type: assigner
        version: '2'
      height: 88
      id: '1745769834853'
      position:
        x: 680
        y: 282
      positionAbsolute:
        x: 680
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -458
      y: 49
      zoom: 1
```
