### ISSUE TITLE
getting 'Uncaught TypeError: s.filter is not a function' console error in workflow

### ISSUE THREAD

**Issue by mendybraun** [langgenius/dify#19200]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.3.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

It works perfectly in earlier versions (I tested the same yaml file in version **1.1.3** and it worked without any error but in version **1.3.1** it's showing this error):

![Image](https://github.com/user-attachments/assets/03a1c2d5-dbfa-42b2-9b66-f42440b3956d)

![Image](https://github.com/user-attachments/assets/c6c94fa5-b655-425a-b2bf-7a94d277991c)

![Image](https://github.com/user-attachments/assets/459e5efb-bdfc-4463-9be4-508aa69d735b)

**this is the workflow yaml file:**

```yaml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: text replace
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: package
  value:
    plugin_unique_identifier: mendybraun/mendys_tools:0.0.26@145161a226a97388aa1a65248ecb83c39373d3537ab6b1817b515bdf746d16f2
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 100
        batch_count_limit: 20
        file_size_limit: 25
        image_file_size_limit: 25
        video_file_size_limit: 100
        workflow_file_upload_limit: 85
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: tool
      id: 1746158380788-source-1746158389071-target
      source: '1746158380788'
      sourceHandle: source
      target: '1746158389071'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: tool
        targetType: template-transform
      id: 1746158389071-source-1746158432539-target
      source: '1746158389071'
      sourceHandle: source
      target: '1746158432539'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: template-transform
        targetType: end
      id: 1746158432539-source-1746158426181-target
      source: '1746158432539'
      sourceHandle: source
      target: '1746158426181'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables:
        - label: original
          max_length: 1000000
          options: []
          required: true
          type: paragraph
          variable: original
        - label: replacments
          max_length: 1000000
          options: []
          required: true
          type: paragraph
          variable: replacments
      height: 115
      id: '1746158380788'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        desc: ''
        is_team_authorization: true
        output_schema:
          properties:
            diff:
              description: Markdown formatted diff showing changes
              type: string
            new_text:
              description: The text after all replacements have been applied
              type: string
            report:
              description: Detailed report of all replacements made
              type: object
          type: object
        paramSchemas:
        - auto_generate: null
          default: null
          form: llm
          human_description:
            en_US: The original text content to be modified.
            ja_JP: The original text content to be modified.
            pt_BR: The original text content to be modified.
            zh_Hans: The original text content to be modified.
          label:
            en_US: Original Text
            ja_JP: Original Text
            pt_BR: Original Text
            zh_Hans: 原始文本
          llm_description: The original text content that will have replacements applied
            to it.
          max: null
          min: null
          name: content
          options: []
          placeholder: null
          precision: null
          required: true
          scope: null
          template: null
          type: string
        - auto_generate: null
          default: null
          form: llm
          human_description:
            en_US: Array of replacement sets in format "original|||replacement" or
              with prefix "regex:" or "literal:".
            ja_JP: Array of replacement sets in format "original|||replacement" or
              with prefix "regex:" or "literal:".
            pt_BR: Array of replacement sets in format "original|||replacement" or
              with prefix "regex:" or "literal:".
            zh_Hans: Array of replacement sets in format "original|||replacement"
              or with prefix "regex:" or "literal:".
          label:
            en_US: Replacement Sets
            ja_JP: Replacement Sets
            pt_BR: Replacement Sets
            zh_Hans: 替换集
          llm_description: An array of replacement sets.
          max: null
          min: null
          name: replacement_sets
          options: []
          placeholder: null
          precision: null
          required: true
          scope: null
          template: null
          type: string
        params:
          content: ''
          replacement_sets: ''
        provider_id: mendybraun/mendys_tools/mendys_tools
        provider_name: mendybraun/mendys_tools/mendys_tools
        provider_type: builtin
        selected: false
        title: Smart Text Replacer
        tool_configurations: {}
        tool_description: A tool for replacing text content using an array of replacement
          rules, with automatic regex detection and detailed change reporting.
        tool_label: Smart Text Replacer
        tool_name: smart_text_replacer
        tool_parameters:
          content:
            type: mixed
            value: '{{#1746158380788.original#}}'
          replacement_sets:
            type: mixed
            value: '{{#1746158380788.replacments#}}'
        type: tool
      height: 53
      id: '1746158389071'
      position:
        x: 383
        y: 282
      positionAbsolute:
        x: 383
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1746158432539'
          - output
          variable: output
        selected: false
        title: End
        type: end
      height: 89
      id: '1746158426181'
      position:
        x: 986
        y: 282
      positionAbsolute:
        x: 986
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        desc: ''
        selected: false
        template: "```python\r\n{{ new_text }}\r\n```\r\n{{ diff }}\r\n"
        title: Template
        type: template-transform
        variables:
        - value_selector:
          - '1746158389071'
          - new_text
          variable: new_text
        - value_selector:
          - '1746158389071'
          - diff
          variable: diff
      height: 53
      id: '1746158432539'
      position:
        x: 686
        y: 282
      positionAbsolute:
        x: 686
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    viewport:
      x: -171.1848894305066
      y: 221.95068496698838
      zoom: 0.8010698775896221
```
