### ISSUE TITLE
I have a problem. When I create a workflow, I cannot reference the output variable of the previous module.

### ISSUE THREAD

**Issue by KangXin4J** [langgenius/dify#19844]
### Self Checks

- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

I have a problem. When I create a workflow, I cannot reference the output variable of the previous module.

![Image](https://github.com/user-attachments/assets/f73b6c82-b5d0-4a98-a8a9-bbb25d971c4f)

![Image](https://github.com/user-attachments/assets/578457a3-41fb-4763-9a5a-4cd836890951)

**Comment by KangXin4J** [comment]
help me ，thanks ，run is success，but has warning，i can‘t publish

**Comment by KangXin4J** [comment]
The iterated item cannot be referenced during iteration. Mine is the latest version.

**Comment by KangXin4J** [comment]
The iterated item cannot be referenced during iteration. Mine is the latest version. @dosu

**Comment by laipz8200** [comment]
<img width="1529" alt="Image" src="https://github.com/user-attachments/assets/61b9948a-28bb-4f44-b42f-9c2cf433ef64" />

I can't reproduce this issue. Please don't modify our bug report template, and include your version in the report.

**Comment by KangXin4J** [comment]
This is my dsl
```yml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: 自动生成公告
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/deepseek:0.0.5@fd6efd37c2a931911de8ab9ca3ba2da303bef146d45ee87ad896b04b36d09403
kind: app
version: 0.3.0
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInLoop: false
        sourceType: start
        targetType: http-request
      id: 1747404775998-source-1747406003854-target
      source: '1747404775998'
      sourceHandle: source
      target: '1747406003854'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: http-request
        targetType: code
      id: 1747406003854-source-1747408057843-target
      source: '1747406003854'
      sourceHandle: source
      target: '1747408057843'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: code
        targetType: iteration
      id: 1747408057843-source-1747408862372-target
      source: '1747408057843'
      sourceHandle: source
      target: '1747408862372'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: true
        isInLoop: false
        iteration_id: '1747408862372'
        sourceType: iteration-start
        targetType: llm
      id: 1747408862372start-source-1747409009161-target
      source: 1747408862372start
      sourceHandle: source
      target: '1747409009161'
      targetHandle: target
      type: custom
      zIndex: 1002
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: iteration
        targetType: code
      id: 1747408862372-source-1747413779343-target
      source: '1747408862372'
      sourceHandle: source
      target: '1747413779343'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: code
        targetType: iteration
      id: 1747413779343-source-1747415437871-target
      source: '1747413779343'
      sourceHandle: source
      target: '1747415437871'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: true
        isInLoop: false
        iteration_id: '1747415437871'
        sourceType: iteration-start
        targetType: code
      id: 1747415437871start-source-1747416144516-target
      source: 1747415437871start
      sourceHandle: source
      target: '1747416144516'
      targetHandle: target
      type: custom
      zIndex: 1002
    - data:
        isInIteration: true
        isInLoop: false
        iteration_id: '1747415437871'
        sourceType: code
        targetType: http-request
      id: 1747416144516-source-1747416190961-target
      source: '1747416144516'
      sourceHandle: source
      target: '1747416190961'
      targetHandle: target
      type: custom
      zIndex: 1002
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: iteration
        targetType: iteration
      id: 1747415437871-source-1747416233801-target
      source: '1747415437871'
      sourceHandle: source
      target: '1747416233801'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: true
        isInLoop: false
        iteration_id: '1747416233801'
        sourceType: iteration-start
        targetType: llm
      id: 1747416233801start-source-1747416241825-target
      source: 1747416233801start
      sourceHandle: source
      target: '1747416241825'
      targetHandle: target
      type: custom
      zIndex: 1002
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: iteration
        targetType: iteration
      id: 1747416233801-source-1747416549492-target
      source: '1747416233801'
      sourceHandle: source
      target: '1747416549492'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: true
        isInLoop: false
        iteration_id: '1747416549492'
        sourceType: iteration-start
        targetType: code
      id: 1747416549492start-source-1747416583384-target
      source: 1747416549492start
      sourceHandle: source
      target: '1747416583384'
      targetHandle: target
      type: custom
      zIndex: 1002
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: iteration
        targetType: code
      id: 1747416549492-source-1747416782174-target
      source: '1747416549492'
      sourceHandle: source
      target: '1747416782174'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: code
        targetType: end
      id: 1747416782174-source-1747416347384-target
      selected: false
      source: '1747416782174'
      sourceHandle: source
      target: '1747416347384'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: code
        targetType: http-request
      id: 1747416782174-source-1747461806631-target
      source: '1747416782174'
      sourceHandle: source
      target: '1747461806631'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - label: list_url
          max_length: 256
          options: []
          required: true
          type: text-input
          variable: list_url
        - label: detail_url
          max_length: 256
          options: []
          required: true
          type: text-input
          variable: detail_url
        - label: body
          max_length: 1000
          options: []
          required: false
          type: paragraph
          variable: body
        - label: platform
          max_length: 100
          options: []
          required: true
          type: text-input
          variable: platform
      height: 168
      id: '1747404775998'
      position:
        x: 30
        y: 305
      positionAbsolute:
        x: 30
        y: 305
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        authorization:
          config: null
          type: no-auth
        body:
          data:
          - id: key-value-732
            key: ''
            type: text
            value: '{{#1747404775998.body#}}'
          type: json
        desc: ''
        headers: ''
        method: post
        params: ''
        retry_config:
          max_retries: 3
          retry_enabled: true
          retry_interval: 100
        selected: false
        ssl_verify: true
        timeout:
          max_connect_timeout: 0
          max_read_timeout: 0
          max_write_timeout: 0
        title: '请求 '
        type: http-request
        url: '{{#1747404775998.list_url#}}'
        variables: []
      height: 127
      id: '1747406003854'
      position:
        x: 333.25720320298126
        y: 305
      positionAbsolute:
        x: 333.25720320298126
        y: 305
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\nfunction main({content}) {\n    try{\n        let arr = findFirstArray(safeParseJson(content));\n\
          \        return {\n          result: JSON.parse(JSON.stringify(arr?.slice(0,\
          \ 3) || content))\n        }\n    }catch{\n      return {\n        result:\
          \ content\n      }\n    }\n}\nfunction safeParseJson(jsonString) {\n  if\
          \ (!jsonString || typeof jsonString !== 'string') {\n    console.warn(\"\
          Input is not a valid string or is empty.\");\n    return null; // 或者返回一个特定的错误对象或空对象/数组\n\
          \  }\n\n  let cleanJsonString = jsonString.trim();\n\n  // 尝试从Markdown代码块中提取（如果模型经常这样返回）\n\
          \  const codeBlockMatch = cleanJsonString.match(/```json\\s*([\\s\\S]*?)\\\
          s*```/);\n  if (codeBlockMatch && codeBlockMatch[1]) {\n    cleanJsonString\
          \ = codeBlockMatch[1].trim();\n  } else {\n    // 另一种启发式方法：如果字符串以 '{' 或\
          \ '[' 开头，并以 '}' 或 ']' 结尾\n    // 这只是一个简单的检查，可能不完美\n    const firstChar =\
          \ cleanJsonString.charAt(0);\n    const lastChar = cleanJsonString.charAt(cleanJsonString.length\
          \ - 1);\n    if (!((firstChar === '{' && lastChar === '}') || (firstChar\
          \ === '[' && lastChar === ']'))) {\n        // 尝试查找第一个 { 或 [ 和最后一个 } 或 ]\n\
          \        const firstBrace = cleanJsonString.indexOf('{');\n        const\
          \ firstBracket = cleanJsonString.indexOf('[');\n        let startIndex =\
          \ -1;\n\n        if (firstBrace !== -1 && (firstBracket === -1 || firstBrace\
          \ < firstBracket)) {\n            startIndex = firstBrace;\n        } else\
          \ if (firstBracket !== -1) {\n            startIndex = firstBracket;\n \
          \       }\n\n        if (startIndex !== -1) {\n            const lastBrace\
          \ = cleanJsonString.lastIndexOf('}');\n            const lastBracket = cleanJsonString.lastIndexOf(']');\n\
          \            let endIndex = -1;\n\n            if (lastBrace !== -1 && (lastBracket\
          \ === -1 || lastBrace > lastBracket) && cleanJsonString.charAt(startIndex)\
          \ === '{') {\n                endIndex = lastBrace;\n            } else\
          \ if (lastBracket !== -1 && cleanJsonString.charAt(startIndex) === '[')\
          \ {\n                endIndex = lastBracket;\n            }\n          \
          \  \n            if (endIndex !== -1 && endIndex > startIndex) {\n     \
          \           cleanJsonString = cleanJsonString.substring(startIndex, endIndex\
          \ + 1);\n            } else {\n                 // console.warn(\"Could\
          \ not reliably find JSON start/end in a dirty string.\");\n            \
          \     // 不做改变，尝试直接解析原始的 cleanJsonString\n            }\n        }\n    }\n\
          \  }\n\n\n  try {\n    const jsonData = JSON.parse(cleanJsonString);\n \
          \   return jsonData;\n  } catch (error) {\n    console.error(\"Failed to\
          \ parse JSON string:\", error.message);\n    console.error(\"Attempted to\
          \ parse (after cleaning):\", cleanJsonString);\n    console.error(\"Original\
          \ string was:\", jsonString);\n    return null; // 或者根据需要抛出错误或返回特定错误对象\n\
          \  }\n}\n\n\n\nfunction findFirstArray(obj, visited = new WeakSet()) {\n\
          \  // 如果当前值是数组，直接返回\n  if (Array.isArray(obj)) {\n    return obj;\n  }\n\
          \n  // 如果不是对象或为null，返回null\n  if (typeof obj !== 'object' || obj === null)\
          \ {\n    return null;\n  }\n\n  // 检查循环引用，避免重复处理\n  if (visited.has(obj))\
          \ {\n    return null;\n  }\n  visited.add(obj);\n\n  // 遍历对象的所有自身属性\n  for\
          \ (const key in obj) {\n    if (Object.prototype.hasOwnProperty.call(obj,\
          \ key)) {\n      const value = obj[key];\n      // 递归检查属性值\n      const\
          \ result = findFirstArray(value, visited);\n      if (result) {\n      \
          \  return result;\n      }\n    }\n  }\n  // 未找到数组\n  return null;\n}"
        code_language: javascript
        desc: ''
        outputs:
          result:
            children: null
            type: array[object]
        selected: false
        title: 代码执行
        type: code
        variables:
        - value_selector:
          - '1747406003854'
          - body
          variable: content
      height: 54
      id: '1747408057843'
      position:
        x: 636.5144064059625
        y: 305
      positionAbsolute:
        x: 636.5144064059625
        y: 305
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        error_handle_mode: terminated
        height: 210
        is_parallel: false
        iterator_selector:
        - '1747408057843'
        - result
        output_selector:
        - '1747409009161'
        - text
        output_type: array[string]
        parallel_nums: 10
        selected: false
        start_node_id: 1747408862372start
        title: 迭代
        type: iteration
        width: 1028
      height: 210
      id: '1747408862372'
      position:
        x: 973.9402622718062
        y: 305
      positionAbsolute:
        x: 973.9402622718062
        y: 305
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 1028
      zIndex: 1
    - data:
        desc: ''
        isInIteration: true
        selected: false
        title: ''
        type: iteration-start
      draggable: false
      height: 48
      id: 1747408862372start
      parentId: '1747408862372'
      position:
        x: 60
        y: 81
      positionAbsolute:
        x: 1033.9402622718062
        y: 386
      selectable: false
      sourcePosition: right
      targetPosition: left
      type: custom-iteration-start
      width: 44
      zIndex: 1002
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        isInIteration: true
        isInLoop: false
        iteration_id: '1747408862372'
        model:
          completion_params: {}
          mode: chat
          name: deepseek-chat
          provider: langgenius/deepseek/deepseek
        prompt_config:
          jinja2_variables:
          - value_selector:
            - '1747408862372'
            - item
            variable: item
          - value_selector:
            - '1747404775998'
            - detail_url
            variable: detail_url
        prompt_template:
        - edition_type: jinja2
          id: 56093c95-0ca9-467f-a568-345b6e7d8589
          jinja2_text: '----

            {{ item }}这个数据是数字藏品平台活动的数据，帮我整理一下，给出活动公告内容的主要数据，生成一个指导字段的json内容。

            ----

            主要字段：

            标题->title、时间->time、id、平台名称->platform，公告详详情地址->detail等主要信息，你可以适当加入其他字段，让数据更加完整

            ------

            {{ detail_url }}这个是详情请求实例，希望对你有用：参考格式生成详情地址detail

            -------

            输出格式：直接输出json信息，不要有其他内容，json内容使用```json ```块，请直接提供答案，无需解释思考过程。'
          role: system
          text: '----

            这个数据是数字藏品平台活动的数据，帮我整理一下，给出每一个活动内容的主要数据，生成一个json列表内容。

            ----

            主要字段：

            标题->title、时间->time、id、平台名称->platform，公告详详情地址->detail等主要信息，你可以适当加入其他字段，让数据更加完整，

            ------

            这个是详情请求实例，希望对你有用：参考格式生成详情地址detail，数据中有详情内容的话生成详情内容detailInfo

            -------

            输出格式：直接输出json信息，不要有其他内容，json内容使用```json ```块，json是数组，请直接提供答案，无需解释思考过程。'
        - edition_type: jinja2
          id: 56392edd-ce3f-4c62-87bb-0d0d5daa4357
          jinja2_text: '----

            {{ item }}这个数据是数字藏品平台活动的数据，帮我整理一下，给出活动公告内容的主要数据，生成一个指导字段的json内容。

            ----

            主要字段：

            标题->title、时间->time、id、平台名称->platform，公告详详情地址->detail等主要信息，你可以适当加入其他字段，让数据更加完整

            ------

            {{ detail_url }}这个是详情请求实例，希望对你有用：参考格式生成详情地址detail

            -------

            输出格式：直接输出json信息，不要有其他内容，json内容使用```json ```块,请直接提供答案，无需解释思考过程。'
          role: user
          text: ''
        selected: false
        structured_output_enabled: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 90
      id: '1747409009161'
      parentId: '1747408862372'
      position:
        x: 201.7716096089439
        y: 77.08432633143127
      positionAbsolute:
        x: 1175.71187188075
        y: 382.08432633143127
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        code: "\nfunction main({arr}) {\n    let result = []\n    for(let i = 0;i\
          \ < arr.length;i++) {\n      result.push(safeParseJson(arr[i]))\n    }\n\
          \    return {\n        result: result\n    }\n}\n\nfunction safeParseJson(jsonString)\
          \ {\n  if (!jsonString || typeof jsonString !== 'string') {\n    console.warn(\"\
          Input is not a valid string or is empty.\");\n    return null; // 或者返回一个特定的错误对象或空对象/数组\n\
          \  }\n\n  let cleanJsonString = jsonString.trim();\n\n  // 尝试从Markdown代码块中提取（如果模型经常这样返回）\n\
          \  const codeBlockMatch = cleanJsonString.match(/```json\\s*([\\s\\S]*?)\\\
          s*```/);\n  if (codeBlockMatch && codeBlockMatch[1]) {\n    cleanJsonString\
          \ = codeBlockMatch[1].trim();\n  } else {\n    // 另一种启发式方法：如果字符串以 '{' 或\
          \ '[' 开头，并以 '}' 或 ']' 结尾\n    // 这只是一个简单的检查，可能不完美\n    const firstChar =\
          \ cleanJsonString.charAt(0);\n    const lastChar = cleanJsonString.charAt(cleanJsonString.length\
          \ - 1);\n    if (!((firstChar === '{' && lastChar === '}') || (firstChar\
          \ === '[' && lastChar === ']'))) {\n        // 尝试查找第一个 { 或 [ 和最后一个 } 或 ]\n\
          \        const firstBrace = cleanJsonString.indexOf('{');\n        const\
          \ firstBracket = cleanJsonString.indexOf('[');\n        let startIndex =\
          \ -1;\n\n        if (firstBrace !== -1 && (firstBracket === -1 || firstBrace\
          \ < firstBracket)) {\n            startIndex = firstBrace;\n        } else\
          \ if (firstBracket !== -1) {\n            startIndex = firstBracket;\n \
          \       }\n\n        if (startIndex !== -1) {\n            const lastBrace\
          \ = cleanJsonString.lastIndexOf('}');\n            const lastBracket = cleanJsonString.lastIndexOf(']');\n\
          \            let endIndex = -1;\n\n            if (lastBrace !== -1 && (lastBracket\
          \ === -1 || lastBrace > lastBracket) && cleanJsonString.charAt(startIndex)\
          \ === '{') {\n                endIndex = lastBrace;\n            } else\
          \ if (lastBracket !== -1 && cleanJsonString.charAt(startIndex) === '[')\
          \ {\n                endIndex = lastBracket;\n            }\n          \
          \  \n            if (endIndex !== -1 && endIndex > startIndex) {\n     \
          \           cleanJsonString = cleanJsonString.substring(startIndex, endIndex\
          \ + 1);\n            } else {\n                 // console.warn(\"Could\
          \ not reliably find JSON start/end in a dirty string.\");\n            \
          \     // 不做改变，尝试直接解析原始的 cleanJsonString\n            }\n        }\n    }\n\
          \  }\n\n\n  try {\n    const jsonData = JSON.parse(cleanJsonString);\n \
          \   return jsonData;\n  } catch (error) {\n    console.error(\"Failed to\
          \ parse JSON string:\", error.message);\n    console.error(\"Attempted to\
          \ parse (after cleaning):\", cleanJsonString);\n    console.error(\"Original\
          \ string was:\", jsonString);\n    return null; // 或者根据需要抛出错误或返回特定错误对象\n\
          \  }\n}\n"
        code_language: javascript
        desc: ''
        outputs:
          result:
            children: null
            type: array[object]
        selected: false
        title: 代码执行 2
        type: code
        variables:
        - value_selector:
          - '1747408862372'
          - output
          variable: arr
      height: 54
      id: '1747413779343'
      position:
        x: 2028.5144064059627
        y: 305
      positionAbsolute:
        x: 2028.5144064059627
        y: 305
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        error_handle_mode: terminated
        height: 209.77160960894372
        is_parallel: false
        iterator_selector:
        - '1747413779343'
        - result
        output_selector:
        - '1747416190961'
        - body
        output_type: array[string]
        parallel_nums: 10
        selected: false
        start_node_id: 1747415437871start
        title: 迭代 2
        type: iteration
        width: 967.0309249162692
      height: 210
      id: '1747415437871'
      position:
        x: 2380.0534014151635
        y: 305
      positionAbsolute:
        x: 2380.0534014151635
        y: 305
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 967
      zIndex: 1
    - data:
        desc: ''
        isInIteration: true
        selected: false
        title: ''
        type: iteration-start
      draggable: false
      height: 48
      id: 1747415437871start
      parentId: '1747415437871'
      position:
        x: 24
        y: 68
      positionAbsolute:
        x: 2404.0534014151635
        y: 373
      selectable: false
      sourcePosition: right
      targetPosition: left
      type: custom-iteration-start
      width: 44
      zIndex: 1002
    - data:
        code: "\nfunction main({item}) {\n    return {\n        result: item['detail']\n\
          \    }\n}\n"
        code_language: javascript
        desc: ''
        isInIteration: true
        isInLoop: false
        iteration_id: '1747415437871'
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 代码执行 3
        type: code
        variables:
        - value_selector:
          - '1747415437871'
          - item
          variable: item
      height: 54
      id: '1747416144516'
      parentId: '1747415437871'
      position:
        x: 109.43008007453136
        y: 65.77160960894372
      positionAbsolute:
        x: 2489.483481489695
        y: 370.7716096089437
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        authorization:
          config: null
          type: no-auth
        body:
          data: []
          type: none
        desc: ''
        headers: ''
        isInIteration: true
        isInLoop: false
        iteration_id: '1747415437871'
        method: get
        params: ''
        retry_config:
          max_retries: 3
          retry_enabled: true
          retry_interval: 100
        selected: false
        ssl_verify: true
        timeout:
          max_connect_timeout: 0
          max_read_timeout: 0
          max_write_timeout: 0
        title: HTTP 请求 2
        type: http-request
        url: '{{#1747416144516.result#}}'
        variables: []
      height: 127
      id: '1747416190961'
      parentId: '1747415437871'
      position:
        x: 440.1707647672065
        y: 63
      positionAbsolute:
        x: 2820.22416618237
        y: 368
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        desc: ''
        error_handle_mode: terminated
        height: 175.02881281192498
        is_parallel: false
        iterator_selector:
        - '1747415437871'
        - output
        output_selector:
        - '1747416241825'
        - text
        output_type: array[string]
        parallel_nums: 10
        selected: false
        start_node_id: 1747416233801start
        title: 迭代 3
        type: iteration
        width: 388
      height: 175
      id: '1747416233801'
      position:
        x: 3487.473519774544
        y: 305
      positionAbsolute:
        x: 3487.473519774544
        y: 305
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 388
      zIndex: 1
    - data:
        desc: ''
        isInIteration: true
        selected: false
        title: ''
        type: iteration-start
      draggable: false
      height: 48
      id: 1747416233801start
      parentId: '1747416233801'
      position:
        x: 24
        y: 68
      positionAbsolute:
        x: 3511.473519774544
        y: 373
      selectable: false
      sourcePosition: right
      targetPosition: left
      type: custom-iteration-start
      width: 44
      zIndex: 1002
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        isInIteration: true
        isInLoop: false
        iteration_id: '1747416233801'
        model:
          completion_params: {}
          mode: chat
          name: deepseek-chat
          provider: langgenius/deepseek/deepseek
        prompt_config:
          jinja2_variables:
          - value_selector:
            - '1747416233801'
            - item
            variable: item
        prompt_template:
        - edition_type: jinja2
          id: 9d46e254-207f-43f6-be68-c26e17a6ac8c
          jinja2_text: '{{ item }}这个是活动的详情信息，请求提取有效的信息，生成html，无需整个页面，父标签是div就行了，方便javascript通过innerHtml的方式展示，可以适配多端，注意样式，让页面友好,不要有多余的其他信息，直接输出html,输出的html使用```html
            ```包含起来。去除风险提示和提醒的相关内容，去掉<img>标签，字体颜色不能是白色

            ----

            请直接提供答案，无需解释思考过程。'
          role: system
          text: '这个是活动的详情信息，请求提取有效的信息，生成html，无需整个页面，父标签是div就行了，方便javascript通过innerHtml的方式展示，可以适配多端，注意样式，让页面友好,不要有多余的其他信息，直接输出html,输出的html使用```html
            ```包含起来。去除风险提示和提醒的相关内容，去掉<img>标签，字体颜色不能是白色

            ----

            请直接提供答案，无需解释思考过程。'
        selected: false
        title: LLM 2
        type: llm
        variables: []
        vision:
          enabled: false
      height: 90
      id: '1747416241825'
      parentId: '1747416233801'
      position:
        x: 121.31482882683122
        y: 65.02881281192498
      positionAbsolute:
        x: 3608.788348601375
        y: 370.028812811925
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1747416782174'
          - result
          variable: r
        selected: false
        title: 结束
        type: end
      height: 90
      id: '1747416347384'
      position:
        x: 4832.029253776175
        y: 310.19957757913124
      positionAbsolute:
        x: 4832.029253776175
        y: 310.19957757913124
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        error_handle_mode: terminated
        is_parallel: false
        iterator_selector:
        - '1747416233801'
        - output
        output_selector:
        - '1747416583384'
        - result
        output_type: array[string]
        parallel_nums: 10
        selected: false
        start_node_id: 1747416549492start
        title: 迭代 4
        type: iteration
        width: 388
      height: 148
      id: '1747416549492'
      position:
        x: 3988.212092362875
        y: 305
      positionAbsolute:
        x: 3988.212092362875
        y: 305
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 388
      zIndex: 1
    - data:
        desc: ''
        isInIteration: true
        selected: false
        title: ''
        type: iteration-start
      draggable: false
      height: 48
      id: 1747416549492start
      parentId: '1747416549492'
      position:
        x: 24
        y: 68
      positionAbsolute:
        x: 4012.212092362875
        y: 373
      selectable: false
      sourcePosition: right
      targetPosition: left
      type: custom-iteration-start
      width: 44
      zIndex: 1002
    - data:
        code: "\nfunction main({item}) {\n    return {\n        result: processHtmlContent(item)\n\
          \    }\n}\n\nfunction processHtmlContent(content) {\n  // 提取```html```块的内容\n\
          \  const htmlMatch = content.match(/```html\\n([\\s\\S]*?)\\n```/);\n  if\
          \ (!htmlMatch) return null;\n\n  const htmlString = htmlMatch[1];\n  //\
          \ 处理转义字符，确保HTML格式正确\n  const processedString = htmlString\n    .replace(/\\\
          \\n/g, '')     // 换行符\n    .replace(/\\\\t/g, '')     // 制表符\n    .replace(/\\\
          \\r/g, '')     // 回车符\n    .replace(/\\\\f/g, '')     // 换页符\n    .replace(/\\\
          \\b/g, '')     // 退格符\n    .replace(/\\\\\\\"/g, '\"')     // 转义双引号\n  \
          \  .replace(/\\\\/g, '');   // 转义反斜杠\n\n  return processedString;\n}\n"
        code_language: javascript
        desc: ''
        isInIteration: true
        isInLoop: false
        iteration_id: '1747416549492'
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 代码执行 4
        type: code
        variables:
        - value_selector:
          - '1747416549492'
          - item
          variable: item
      height: 54
      id: '1747416583384'
      parentId: '1747416549492'
      position:
        x: 128
        y: 65
      positionAbsolute:
        x: 4116.212092362875
        y: 370
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        code: "\nfunction main({arr,infoList,platform}) {\n    let r = []\n    for(let\
          \ i = 0;i < arr.length;i++) {\n        let obj = {\n            \"title\"\
          : infoList[i].title,\n            \"time\": infoList[i].time,\n        \
          \    \"content\": arr[i],\n            \"platform\": platform\n        };\n\
          \        r.push(obj)\n    }\n    return {\n        result: JSON.stringify(r)\n\
          \    }\n}\n"
        code_language: javascript
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 代码执行 5
        type: code
        variables:
        - value_selector:
          - '1747416549492'
          - output
          variable: arr
        - value_selector:
          - '1747413779343'
          - result
          variable: infoList
        - value_selector:
          - '1747404775998'
          - platform
          variable: platform
      height: 54
      id: '1747416782174'
      position:
        x: 4433.2409051748
        y: 305
      positionAbsolute:
        x: 4433.2409051748
        y: 305
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        authorization:
          config:
            api_key: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJRUy1hdXRvLXNlcnZpY2UiLCJzdWIiOiJrYW5neGluIiwiaWF0IjoxNzQ3Mzg4NzE3LCJleHAiOjg2NTc0NzM4ODcxNywidXNlcm5hbWUiOiJrYW5neGluIn0.btXuL9trRJusPFkDmEkQKYj83GrsqEsMNfCkoHmlRxk
            header: Authorization
            type: custom
          type: api-key
        body:
          data:
          - id: key-value-208
            key: ''
            type: text
            value: '{{#1747416782174.result#}}'
          type: json
        desc: ''
        headers: ''
        method: post
        params: ''
        retry_config:
          max_retries: 3
          retry_enabled: true
          retry_interval: 100
        selected: false
        ssl_verify: true
        timeout:
          max_connect_timeout: 0
          max_read_timeout: 0
          max_write_timeout: 0
        title: HTTP 请求 3
        type: http-request
        url: http://192.168.31.38:8080/auto/common/api/push
        variables: []
      height: 140
      id: '1747461806631'
      position:
        x: 4832.029253776175
        y: 532.0491772064751
      positionAbsolute:
        x: 4832.029253776175
        y: 532.0491772064751
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -2519.4273234071616
      y: 23.483342385389903
      zoom: 1.3462632095527973

```
docker images version

![Image](https://github.com/user-attachments/assets/2cfa814a-fa0a-4e3b-8499-2dd823a44652)
