### ISSUE TITLE
plugin error：node id not found in workflow graph

### ISSUE THREAD

**Issue by hz20091942** [langgenius/dify#20135]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.4.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

**I developed an HTTP request tool plugin myself. After initializing the project with dify init, the modified code is as follows:**
```yaml
identity:
  name: dify-plugin-http-interface
  author: hz
  label:
    en_US: dify-plugin-http-interface
    zh_Hans: dify-plugin-http-interface
    pt_BR: dify-plugin-http-interface
description:
  human:
    en_US: http interface
    zh_Hans: http interface
    pt_BR: http interface
  llm: http interface
parameters:
  - name: url
    type: string
    required: true
    label:
      en_US: URL
      zh_Hans: URL
    human_description:
      en_US: The URL to make the HTTP request to
      zh_Hans: 要发送HTTP请求的URL
      pt_BR: O URL para fazer a requisição HTTP
    form: llm
  - name: method
    type: select
    options:
      - label:
          en_US: GET
          zh_Hans: GET
        value: get
      - label:
          en_US: POST
          zh_Hans: POST
        value: post
    required: true
    label:
      en_US: POST/GET
      zh_Hans: POST/GET
    form: form
    human_description:
      en_US: The HTTP method to use
      zh_Hans: 要使用的HTTP方法
  - name: headers
    type: string
    required: false
    label:
      en_US: Custom request headers JSON string
      zh_Hans: 自定义Headers请求头(json字符串)
    form: llm
    human_description:
      en_US: Custom request header JSON string
      zh_Hans: 自定义Headers请求头(json字符串)
  - name: bodyType
    type: select
    requested: false
    options:
      - label:
          en_US: JSON
          zh_Hans: JSON
        value: json
      - label:
          en_US: FORM
          zh_Hans: FORM
        value: form-data
      - label:
          en_US: x-www-form-urlencoded
          zh_Hans: x-www-form-urlencoded
        value: x-www-form-urlencoded
    label:
      en_US: Request Body Type
      zh_Hans: 请求体类型 Body Type
    form: form
    human_description:
      en_US: The type of the request body
      zh_Hans: 请求体的类型 Body Type
  - name: params
    type: string
    required: false
    label:
      en_US: Params
      zh_Hans: 请求参数 Params
    form: llm
    human_description:
      en_US: The parameters of the request
      zh_Hans: 请求的参数 Params
extra:
  python:
    source: tools/dify-plugin-http-interface.py
```
```phton
from collections.abc import Generator
from typing import Any
import requests
import json

from dify_plugin import Tool
from dify_plugin.entities.tool import ToolInvokeMessage

class DifyPluginHttpInterfaceTool(Tool):
    def _invoke(self, tool_parameters: dict[str, Any]) -> Generator[ToolInvokeMessage]:
        headers_param = tool_parameters.get("headers", "")
        headers = None

        if headers_param:
            headers = json.loads(headers_param)

        params = None
        data = None
        data_result = {}
        params_param = tool_parameters.get("params", "")
        bodyType_param = tool_parameters.get("bodyType", "")
        if params_param:
            if bodyType_param:
                if bodyType_param == "json":
                    params = json.loads(params_param)
                elif bodyType_param == "form-data" or bodyType_param == "x-www-form-urlencoded":
                    data = json.loads(params_param)
                    for key, value in data.items():
                        if isinstance(value, dict):
                            data_result[key] = json.dumps(value)
                        else:
                            data_result[key] = value
            else:
                params = json.loads(params_param)
        
        method = tool_parameters.get("method", "").lower()
        response = None
        try:
            if method == "get":
                response = requests.get(
                    url=tool_parameters.get("url", ""),
                    headers=headers,
                    params=params,
                    timeout=60000
                )
            elif method == "post":
                response = requests.post(
                    url=tool_parameters.get("url", ""),
                    headers=headers,
                    data=data_result,
                    json=params,
                    timeout=60000
                )
            else:
                raise ValueError(f"Unsupported HTTP method: {method}")
        
            response.encoding = 'utf-8'
            response.raise_for_status()
            valuable_res = response.json()
            yield self.create_json_message(valuable_res)
        except requests.exceptions.HTTPError as http_err:
            yield self.create_text_message(f"HTTP 错误: {http_err}")
            yield self.create_text_message(f"响应内容: {response.content.decode('utf-8')}")
        except json.JSONDecodeError as json_err:
            yield self.create_text_message(f"JSON 解析失败: {json_err}")
        except requests.exceptions.RequestException as req_err:
            yield self.create_text_message(f"请求错误: {req_err}")
```
**After completing the plugin development, I entered the debug mode for the plugin, and the plugin has been loaded normally.** 

**I created two ChatFlows, both of which use the newly created plugin.** 

**The first ChatFlow works successfully. The plugin tests successfullyon its own, and the ChatFlow works successfully. The screenshot is as follows:**
![Image](https://github.com/user-attachments/assets/fa4be9df-027f-4133-b2ec-0b30781c2926)

**The issue is with the second ChatFlow. The screenshot is as follows:**

![Image](https://github.com/user-attachments/assets/8c4bdabe-57dc-47a7-a0dc-afc6f4b5d036)

**The problem phenomenon includes the following:**

**1. After inserting the newly developed plugin, the browser console reports an error:**
POST http://xxxx/console/api/apps/e1df3753-f2d6-4c36-9e7f-517f4e253ae8/workflows/draft net::ERR_CONNECTION_RESET
**2. When testing the new plugin separately, a popup error occurs：node id not found in workflow graph**

![Image](https://github.com/user-attachments/assets/0a73f117-a300-4d64-8b1b-e6a50c538d28)

**3. When exiting the current ChatFlow and re-entering it, the newly inserted plugin disappears.**

**I hope to get an explanation for why this happens.**
