### ISSUE TITLE
Agent FunctionCalling call_tool 401 Unauthorized

### ISSUE THREAD

**Issue by lework** [langgenius/dify#20340]
### Dify version

1.4.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Agent FunctionCalling  Log

```json
{
  "output": {
    "tool_call_id": "getCozeITQA",
    "tool_call_input": {
      "query": "vpn安装",
      "question": "vpn安装"
    },
    "tool_call_name": "getCozeITQA",
    "tool_response": "tool invoke error: read tool response failed: request failed: 401 Unauthorized: Invalid Authorization token."
  }
}
```

getCozeITQA dsl

![Image](https://github.com/user-attachments/assets/b227e8ea-9559-4a57-9bb4-2ec827a64a84)

### ✔️ Expected Behavior

```json
{
  "output": {
    "tool_call_id": "getCozeITQA",
    "tool_call_input": {
      "query": "vpn安装",
      "question": "vpn安装"
    },
    "tool_call_name": "getCozeITQA",
    "tool_response": "vpn安装"
  }
}
```

### ❌ Actual Behavior

```json
{
  "output": {
    "tool_call_id": "getCozeITQA",
    "tool_call_input": {
      "query": "vpn安装",
      "question": "vpn安装"
    },
    "tool_call_name": "getCozeITQA",
    "tool_response": "tool invoke error: read tool response failed: request failed: 401 Unauthorized: Invalid Authorization token."
  }
}
```

**Comment by lework** [comment]
This tool has no credentials configuration, just simple inputs and outputs

**Comment by lework** [comment]
chatflow

```yml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: agent call
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/tongyi:0.0.25@325423749d5e71f8b4681af1b2ed46d7686cb1947e443a86ba5d14ac45ff85a4
kind: app
version: 0.3.0
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 20
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 20
        video_file_size_limit: 100
        workflow_file_upload_limit: 20
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: question-classifier
      id: 1748399159930-source-1748399186826-target
      source: '1748399159930'
      sourceHandle: source
      target: '1748399186826'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: agent
        targetType: answer
      id: 1748399221528-source-1748399328017-target
      source: '1748399221528'
      sourceHandle: source
      target: '1748399328017'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: question-classifier
        targetType: agent
      id: 1748399186826-2-1748399221528-target
      source: '1748399186826'
      sourceHandle: '2'
      target: '1748399221528'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables: []
      height: 54
      id: '1748399159930'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        classes:
        - id: '2'
          name: 其他
        desc: ''
        instructions: ''
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: qwen-max
          provider: langgenius/tongyi/tongyi
        query_variable_selector:
        - '1748399159930'
        - sys.query
        selected: false
        title: 问题分类器
        topics: []
        type: question-classifier
        vision:
          enabled: false
      height: 134
      id: '1748399186826'
      position:
        x: 380
        y: 282
      positionAbsolute:
        x: 380
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        agent_parameters:
          instruction:
            type: constant
            value: '```xml

              <instruction>

              根据用户的问题，你需要执行以下步骤：

              1. 先调用getCozeITQA工具，根据工具的返回回答问题。如果知识库回答中有相关信息，使用该信息回答问题，并在答案的结尾标注答案来源于知识库。在这种情况下，答案最后标记答案来源于知识库"。

              2. 如果你不能推导出答案，需要调用工具创建百事通工单。在这种情况下，你的回答应该是 "无法推导出答案，已创建百事通工单"。


              请注意，你的输出不应包含任何XML标签。

              </instruction>


              <example>

              例如，如果用户的问题是 "如何重置密码？"，并且知识库中有相关信息，你的回答应该是 "要重置密码，你需要访问设置页面，然后点击''重置密码''选项
              \n（ps：答案来源于知识库）"。

              如果你不能推导出答案，你的回答应该是 "无法推导出答案"。

              </example>

              ```'
          model:
            type: constant
            value:
              completion_params: {}
              mode: chat
              model: qwen-max
              model_type: llm
              provider: langgenius/tongyi/tongyi
              type: model-selector
          query:
            type: constant
            value: '{{#sys.query#}}'
          tools:
            type: constant
            value:
            - enabled: true
              extra:
                description: IT知识库
              parameters: {}
              provider_name: 0aad80b6-260f-4ac7-9b1b-a8403103e4a8
              schemas:
              - auto_generate: null
                default: null
                form: form
                human_description:
                  en_US: 用户问题
                  ja_JP: 用户问题
                  pt_BR: 用户问题
                  zh_Hans: 用户问题
                label:
                  en_US: query
                  ja_JP: query
                  pt_BR: query
                  zh_Hans: query
                llm_description: 用户问题
                max: null
                min: null
                name: query
                options: []
                placeholder:
                  en_US: ''
                  ja_JP: ''
                  pt_BR: ''
                  zh_Hans: ''
                precision: null
                required: true
                scope: null
                template: null
                type: string
              settings:
                query:
                  value: '1222334'
              tool_description: IT知识库
              tool_label: 测试
              tool_name: getCozeITQA
              type: workflow
        agent_strategy_label: FunctionCalling
        agent_strategy_name: function_calling
        agent_strategy_provider_name: langgenius/agent/agent
        desc: ''
        output_schema: null
        plugin_unique_identifier: langgenius/agent:0.0.15@3cb96179914f8c4025282bcb1cc2fd5a951f6be0877567b02daee01e28ca4bf3
        selected: false
        title: Agent
        type: agent
      height: 198
      id: '1748399221528'
      position:
        x: 726
        y: 197
      positionAbsolute:
        x: 726
        y: 197
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#1748399221528.text#}}'
        desc: ''
        selected: false
        title: 直接回复 2
        type: answer
        variables: []
      height: 104
      id: '1748399328017'
      position:
        x: 1030
        y: 197
      positionAbsolute:
        x: 1030
        y: 197
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -56.381722312295096
      y: 155.94745141726457
      zoom: 1.0000000000000002
```

tool workflow

```yml
app:
  description: 测试1
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: 测试
  use_icon_as_answer_icon: false
dependencies: []
kind: app
version: 0.3.0
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 20
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 20
        video_file_size_limit: 100
        workflow_file_upload_limit: 20
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: end
      id: 1748401019368-source-1748401027443-target
      source: '1748401019368'
      sourceHandle: source
      target: '1748401027443'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: true
        title: 开始
        type: start
        variables:
        - label: query
          max_length: 256
          options: []
          required: true
          type: text-input
          variable: query
      height: 90
      id: '1748401019368'
      position:
        x: 79
        y: 282
      positionAbsolute:
        x: 79
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1748401019368'
          - query
          variable: result
        selected: false
        title: 结束
        type: end
      height: 90
      id: '1748401027443'
      position:
        x: 384
        y: 282
      positionAbsolute:
        x: 384
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 304
      y: 51.5
      zoom: 1
```
