### ISSUE TITLE
the workflow running has parallel bug when integrate TEMPLATE with CODE

### ISSUE THREAD

**Issue by sontallive** [langgenius/dify#20356]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.4.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

If I only have two parallel template node with a code, it works fine.

<img width="1343" alt="Image" src="https://github.com/user-attachments/assets/f696dad8-1224-4906-9c4c-43969bfeabae" />

But when i have two parallel template node with a code, and an extra template parallel with the code, it have bug

<img width="1534" alt="Image" src="https://github.com/user-attachments/assets/a492e730-ae7b-4455-abbc-52f388d4578d" />

The code relies on the template and template2, so it failed, because it run code twice but only have one dependency every run.

Extra info:
the config of the code:

<img width="1153" alt="Image" src="https://github.com/user-attachments/assets/57902030-fc30-42ce-bdbd-80d7196726e9" />

the dsl of the workflow:
```yaml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: test_bug
  use_icon_as_answer_icon: false
dependencies: []
kind: app
version: 0.3.0
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: template-transform
      id: 1748420363419-source-1748420383832-target
      source: '1748420363419'
      sourceHandle: source
      target: '1748420383832'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: template-transform
      id: 1748420363419-source-1748420387199-target
      source: '1748420363419'
      sourceHandle: source
      target: '1748420387199'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: template-transform
        targetType: code
      id: 1748420383832-source-1748420409186-target
      source: '1748420383832'
      sourceHandle: source
      target: '1748420409186'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: template-transform
        targetType: code
      id: 1748420387199-source-1748420409186-target
      source: '1748420387199'
      sourceHandle: source
      target: '1748420409186'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: code
        targetType: end
      id: 1748420409186-source-1748420573290-target
      source: '1748420409186'
      sourceHandle: source
      target: '1748420573290'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: start
        targetType: template-transform
      id: 1748420363419-source-1748421429085-target
      source: '1748420363419'
      sourceHandle: source
      target: '1748421429085'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: template-transform
        targetType: end
      id: 1748421429085-source-1748420573290-target
      source: '1748421429085'
      sourceHandle: source
      target: '1748420573290'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables: []
      height: 54
      id: '1748420363419'
      position:
        x: 30
        y: 245
      positionAbsolute:
        x: 30
        y: 245
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        selected: false
        template: '123'
        title: Template
        type: template-transform
        variables: []
      height: 54
      id: '1748420383832'
      position:
        x: 334
        y: 245
      positionAbsolute:
        x: 334
        y: 245
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        selected: false
        template: '456'
        title: Template 2
        type: template-transform
        variables: []
      height: 54
      id: '1748420387199'
      position:
        x: 334
        y: 339
      positionAbsolute:
        x: 334
        y: 339
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "import hashlib\nimport random\nimport time\n\ndef main(a: str, b: str)\
          \ -> dict:\n    current_time = str(int(time.time() // 60))\n    combined_seed\
          \ = a + b + current_time\n    seed_value = int(hashlib.md5(combined_seed.encode()).hexdigest()[:8],\
          \ 16)\n    random.seed(seed_value)\n    \n    # Generate random percentage\n\
          \    percentage = random.randint(1, 100)\n    \n    if percentage < 75:\n\
          \        x= a\n    else:\n        x = b\n    \n    return {\n        'result':\
          \ x\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: Code
        type: code
        variables:
        - value_selector:
          - '1748420383832'
          - output
          variable: a
        - value_selector:
          - '1748420387199'
          - output
          variable: b
      height: 54
      id: '1748420409186'
      position:
        x: 638
        y: 245
      positionAbsolute:
        x: 638
        y: 245
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1748420409186'
          - result
          variable: result
        selected: false
        title: End
        type: end
      height: 90
      id: '1748420573290'
      position:
        x: 942
        y: 245
      positionAbsolute:
        x: 942
        y: 245
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        selected: false
        template: '111'
        title: Template 3
        type: template-transform
        variables: []
      height: 54
      id: '1748421429085'
      position:
        x: 638
        y: 396
      positionAbsolute:
        x: 638
        y: 396
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 305.00000000000006
      y: 156.60000000000002
      zoom: 0.7
```

### ✔️ Expected Behavior

The code should run once and the two templates run parallel

### ❌ Actual Behavior

the code run twice with two tempaltes in specific workflow
