### ISSUE TITLE
API service attempts to connect to localhost:5002 for plugin tasks, ignoring PLUGIN_DAEMON_API_URL (Dify API 1.4.1 / Plugin Daemon 0.1.1-local)

### ISSUE THREAD

**Issue by 50ethan** [langgenius/dify#20595]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.4.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Hi Dify Team,

I am seeking assistance with a persistent issue I'm encountering while setting up a self-hosted Dify instance using Docker Compose. I can access the Dify UI via HTTPS (https://sora-chat.shop) and log in successfully. However, when I attempt to install any model provider (e.g., OpenAI, Claude), I receive a "500 Internal Server Error" in the UI.

Dify Versions Used:

API Image: langgenius/dify-api:1.4.1
Web Image: langgenius/dify-web:1.4.1
Plugin Daemon Image: langgenius/dify-plugin-daemon:0.1.1-local
Database: PostgreSQL 15 Alpine (via Docker)
Redis: Redis 6 Alpine (via Docker)
Problem Description / Actual Behavior:
The core issue appears to be that the api service is attempting to connect to localhost:5002 when fetching plugin-related tasks, instead of using the PLUGIN_DAEMON_API_URL defined in its environment. This leads to a connection refused error.

Here is the relevant error snippet from the api container logs when the 500 error occurs in the UI:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5002): Max retries exceeded with url: /plugin/c22a1a81-3bda-4ffa-ac25-b72b1fd4e624/management/install/tasks?page=1&page_size=100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe4ac9df4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:
...
Traceback (most recent call last):
  File "/app/api/core/plugin/impl/base.py", line 64, in _request
    response = requests.request( ... )
  File "/app/api/.venv/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5002): Max retries exceeded with url: /plugin/c22a1a81-3bda-4ffa-ac25-b72b1fd4e624/management/install/tasks?page=1&page_size=100 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe4ac9df4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:
...
  File "/app/api/core/plugin/impl/base.py", line 69, in _request
    raise PluginDaemonInnerError(code=-500, message="Request to Plugin Daemon Service failed")
core.plugin.entities.plugin_daemon.PluginDaemonInnerError
This error occurs consistently when the UI tries to load model provider information or when I attempt an installation.
```
Expected Behavior:

The api service should use the environment variable PLUGIN_DAEMON_API_URL (which is set to http://plugin_daemon:5003/v1) to communicate with the plugin_daemon service.
I should be able to install model providers without encountering 500 errors.
The plugin_daemon service should run stably. (Currently, docker compose ps shows it as "Up", and its logs indicate it becomes "master of the cluster" after an initial DB connection retry, though it logs a non-fatal [ERROR]start remote plugin server failed: gnet: invalid network address related to PLUGIN_REMOTE_INSTALLING_HOST).
Relevant docker-compose.yml sections:
(My full docker-compose.yml matches the last version you helped me construct, which includes all previously discussed environment variables for all services, including the keys and paths for plugin_daemon.)

api service:

YAML
```
  api:
    image: langgenius/dify-api:1.4.1
    ports:
      - "5001:5001"
    depends_on:
      - db
      - redis
      - plugin_daemon
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: difyuser
      DB_PASSWORD: difypassword # Using actual password
      DB_DATABASE: dify
      MIGRATION_ENABLED: "true"
      STORAGE_TYPE: local
      STORAGE_LOCAL_PATH: storage
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      PLUGIN_DAEMON_API_URL: http://plugin_daemon:5003/v1 # Correct URL is set here
    volumes:
      - ./storage:/app/api/storage
    restart: unless-stopped
plugin_daemon service:
```

YAML
```
  plugin_daemon:
    image: langgenius/dify-plugin-daemon:0.1.1-local
    ports:
      - "5003:5003"
    depends_on:
      - db
      - redis
    environment:
      SERVER_KEY: "c8e21edfd034e332ffd4a41811f509a9" # My actual key
      DIFY_INNER_API_URL: http://api:5001
      DIFY_INNER_API_KEY: "c8e21edfd034e332ffd4a41811f509a9" # Using the same as SERVER_KEY
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      DB_USERNAME: difyuser
      DB_PASSWORD: difypassword # Using actual password
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: dify
      PLUGIN_REMOTE_INSTALLING_HOST: "sora-chat.shop" # Tried with and without https://
      PLUGIN_REMOTE_INSTALLING_PORT: "443"
      PLUGIN_STORAGE_TYPE: "local"
      PLUGIN_STORAGE_LOCAL_PATH: "/app/plugins"
      PLUGIN_WORKING_PATH: "/app/storage/cwd"
    volumes:
      - ./storage/plugins:/app/plugins
      - ./plugin_daemon_work_storage:/app/storage
    restart: unless-stopped
```
(All host directories for volumes have been created, e.g., mkdir -p ~/dify/docker/storage/plugins and mkdir -p ~/dify/docker/plugin_daemon_work_storage/cwd.)

Troubleshooting Steps Taken:

Numerous iterations of correcting docker-compose.yml for all services (api, plugin_daemon, etc.) based on official examples and community advice.
Ensured all required environment variables (DB credentials, Redis credentials, various Dify-specific keys and URLs, storage paths) are set for both api and plugin_daemon.
Corrected depends_on to avoid circular dependencies.
Used docker compose down -v --remove-orphans and docker compose up -d --force-recreate extensively after each change.
Nginx is configured for HTTPS and general Dify UI access/login works.
Specific Questions:

Why is the api service attempting to connect to localhost:5002 for /plugin/... tasks, despite PLUGIN_DAEMON_API_URL being set to http://plugin_daemon:5003/v1?
Is there another environment variable or internal configuration that might be causing the api service to use localhost:5002 as a fallback or default for these specific plugin-related calls?
Could this be an issue specific to the combination of langgenius/dify-api:1.4.1 and langgenius/dify-plugin-daemon:0.1.1-local?
How can I ensure the api service correctly uses http://plugin_daemon:5003/v1 for all communications with the plugin_daemon service?
Any guidance on how to resolve this would be greatly appreciated. I'm happy to provide more logs or try further diagnostic steps.

Thank you for your time and help!
