### ISSUE TITLE
Unexpected behaviour of Variable Aggregator on different branches

### ISSUE THREAD

**Issue by kirakiseki** [langgenius/dify#20606]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.4.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I found a strange behaviour in my chatflow. I want to search different knowledge base depends on different event types and use Variable Aggregator to aggregate corresponding knowledge. But the Variable Aggregator are skipped like this:

<img width="1729" alt="Image" src="https://github.com/user-attachments/assets/74517446-5d90-4746-9ccd-6a49a8fe6c30" />

I made a minimal reproduction chatflow like this:

<img width="1353" alt="Image" src="https://github.com/user-attachments/assets/e233079b-e166-4561-93b8-2f049d86b696" />

The Conditional Branch node would go into different branches depending on user's input from choices [1,2,3].
The Code Execution nodes 1A, 1B, 2A, 2B are used to generate its corresponding strings like "1a", "1b", "2a" and "2b".
The Variable Aggregator nodes A and B where the bug lies aim to aggregate the results with postfix "a" and "b".
The Answer node would output the results from the both Variable Aggregator nodes directly.

Here is the minium reproduction DSL for debugging:
<details>

<summary>DSL content</summary>

```yaml
app:/
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: bugtest-并行
  use_icon_as_answer_icon: false
dependencies: []
kind: app
version: 0.3.0
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInLoop: false
        sourceType: start
        targetType: if-else
      id: 1748962309200-source-1748962316650-target
      selected: false
      source: '1748962309200'
      sourceHandle: source
      target: '1748962316650'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: if-else
        targetType: code
      id: 1748962316650-true-1748962370039-target
      selected: false
      source: '1748962316650'
      sourceHandle: 'true'
      target: '1748962370039'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: variable-aggregator
        targetType: answer
      id: 1748962354160-source-1748962443930-target
      selected: false
      source: '1748962354160'
      sourceHandle: source
      target: '1748962443930'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: if-else
        targetType: code
      id: 1748962316650-true-17489624177180-target
      selected: false
      source: '1748962316650'
      sourceHandle: 'true'
      target: '17489624177180'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: if-else
        targetType: code
      id: 1748962316650-f7644790-79ca-4c3f-b690-b85450789c77-17489625222390-target
      selected: false
      source: '1748962316650'
      sourceHandle: f7644790-79ca-4c3f-b690-b85450789c77
      target: '17489625222390'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: if-else
        targetType: code
      id: 1748962316650-f7644790-79ca-4c3f-b690-b85450789c77-17489625325210-target
      selected: false
      source: '1748962316650'
      sourceHandle: f7644790-79ca-4c3f-b690-b85450789c77
      target: '17489625325210'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: code
        targetType: variable-aggregator
      id: 1748962370039-source-1748962354160-target
      selected: false
      source: '1748962370039'
      sourceHandle: source
      target: '1748962354160'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: code
        targetType: variable-aggregator
      id: 17489625222390-source-1748962354160-target
      selected: false
      source: '17489625222390'
      sourceHandle: source
      target: '1748962354160'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: code
        targetType: variable-aggregator
      id: 17489624177180-source-17489625685610-target
      selected: false
      source: '17489624177180'
      sourceHandle: source
      target: '17489625685610'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: code
        targetType: variable-aggregator
      id: 17489625325210-source-17489625685610-target
      selected: false
      source: '17489625325210'
      sourceHandle: source
      target: '17489625685610'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: variable-aggregator
        targetType: answer
      id: 17489625685610-source-1748962443930-target
      selected: false
      source: '17489625685610'
      sourceHandle: source
      target: '1748962443930'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables: []
      height: 54
      id: '1748962309200'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: is
            id: 5ddebef1-e5cf-4043-8101-1dd0b9c7a472
            value: '1'
            varType: string
            variable_selector:
            - sys
            - query
          id: 'true'
          logical_operator: and
        - case_id: f7644790-79ca-4c3f-b690-b85450789c77
          conditions:
          - comparison_operator: is
            id: 274c03d5-ffec-471b-a11d-9c14c5c8593d
            value: '2'
            varType: string
            variable_selector:
            - sys
            - query
          id: f7644790-79ca-4c3f-b690-b85450789c77
          logical_operator: and
        - case_id: ea89f090-bd49-467e-980c-943312d36439
          conditions:
          - comparison_operator: is
            id: 73e44731-75c7-4a38-ae73-29bacfa247e8
            value: '3'
            varType: string
            variable_selector:
            - sys
            - query
          id: ea89f090-bd49-467e-980c-943312d36439
          logical_operator: and
        desc: ''
        selected: false
        title: 条件分支
        type: if-else
      height: 222
      id: '1748962316650'
      position:
        x: 386
        y: 282
      positionAbsolute:
        x: 386
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        output_type: string
        selected: false
        title: a
        type: variable-aggregator
        variables:
        - - '1748962370039'
          - result
        - - '17489625222390'
          - result
      height: 131
      id: '1748962354160'
      position:
        x: 1238
        y: 203
      positionAbsolute:
        x: 1238
        y: 203
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(arg1: str) -> dict:\n    return {\n        \"result\": \"\
          1a\",\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: true
        title: 1a
        type: code
        variables:
        - value_selector:
          - sys
          - query
          variable: arg1
      height: 54
      id: '1748962370039'
      position:
        x: 729
        y: 175
      positionAbsolute:
        x: 729
        y: 175
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(arg1: str) -> dict:\n    return {\n        \"result\": \"\
          1b\",\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 1b
        type: code
        variables:
        - value_selector:
          - sys
          - query
          variable: arg1
      height: 54
      id: '17489624177180'
      position:
        x: 729
        y: 267
      positionAbsolute:
        x: 729
        y: 267
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: 'This is Answer Node


          {{#1748962354160.output#}}

          {{#17489625685610.output#}}'
        desc: ''
        selected: false
        title: 直接回复
        type: answer
        variables: []
      height: 121
      id: '1748962443930'
      position:
        x: 1625.9925571196463
        y: 310.910308834967
      positionAbsolute:
        x: 1625.9925571196463
        y: 310.910308834967
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(arg1: str) -> dict:\n    return {\n        \"result\": \"\
          2a\",\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 2a
        type: code
        variables:
        - value_selector:
          - sys
          - query
          variable: arg1
      height: 54
      id: '17489625222390'
      position:
        x: 729
        y: 396.5
      positionAbsolute:
        x: 729
        y: 396.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(arg1: str) -> dict:\n    return {\n        \"result\": \"\
          2b\",\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 2b
        type: code
        variables:
        - value_selector:
          - sys
          - query
          variable: arg1
      height: 54
      id: '17489625325210'
      position:
        x: 729
        y: 481.5
      positionAbsolute:
        x: 729
        y: 481.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        output_type: string
        selected: false
        title: b
        type: variable-aggregator
        variables:
        - - '17489624177180'
          - result
        - - '17489625325210'
          - result
      height: 131
      id: '17489625685610'
      position:
        x: 1238
        y: 396.5
      positionAbsolute:
        x: 1238
        y: 396.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -189.64043824692612
      y: 15.075408994011923
      zoom: 0.7453551933994609

```
</details>

### ✔️ Expected Behavior

For CASE 1 branch of Conditional Branch node, triggers Code Execution node 1A and 1B, and Variable Aggregator node A takes the first None value that is "1a", while Variable Aggregator node B outputs "1b", then the result in the Answer node should be  "1a 1b".

So does the CASE 2 branch, the result of Variable Aggregator node A is "2a", node B is "2b", final answer should be  "2a2b".

### ❌ Actual Behavior

When it goes into CASE 1 branch, after the execution of 1A and 1B, Variable Aggregator A and B are both skipped, it just slipped into the final Answer Node with no expected output "1a1b".
<img width="2005" alt="Image" src="https://github.com/user-attachments/assets/9eb5f435-85a2-4e03-8436-21182a88ea37" />

But it's weird when it's in CASE 2, everything runs well as my expection, the answer is "2a2b" normally.

<img width="2227" alt="Image" src="https://github.com/user-attachments/assets/4b05c7ea-b9e4-4a97-9bc7-8232ad5ff324" />

If I add an other node like Code Execution node A+B which is used to concat the output from Variable Aggregator nodes A and B, it would throw an unexpected keyword argument error.

<img width="2228" alt="Image" src="https://github.com/user-attachments/assets/77f51a0d-1ef1-4c30-8ccd-3bba5f43edca" />
