### ISSUE TITLE
Application error: a client-side exception has occurred while loading localhost (see the browser console for more information).

### ISSUE THREAD

**Issue by GCPD123** [langgenius/dify#20818]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.4.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

```
/console/api/apps/5e08f199-d862-4792-bb39-2f51f66f9056:1 
            
            
            Failed to load resource: the server responded with a status of 404 (NOT FOUND)
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
api.github.com/repos/langgenius/dify:1 
            
            
            Failed to load resource: the server responded with a status of 403 ()
api.github.com/repos/langgenius/dify:1 
            
            
            Failed to load resource: the server responded with a status of 403 ()
/console/api/apps/5876cee3-7efa-4a87-82c5-f211168b8df1/workflows/draft:1 
            
            
            Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
/console/api/installed-apps/741a6105-a1ee-4b39-998a-ad927b78a917/parameters:1 
            
            
            Failed to load resource: the server responded with a status of 400 (BAD REQUEST)
074ffed0-57257aaa72a30406.js:1  Uncaught TypeError: Cannot read properties of undefined (reading 'x')
    at 074ffed0-57257aaa72a30406.js:1:27271
    at Array.forEach (<anonymous>)
    at td (074ffed0-57257aaa72a30406.js:1:27158)
    at setNodes (074ffed0-57257aaa72a30406.js:1:73029)
    at 074ffed0-57257aaa72a30406.js:1:22085
    at ob (7aa3e4eb-df755cd629be1b60.js:1:80066)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95812)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95849)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95849)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95849)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95849)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95849)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95849)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95849)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95849)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95849)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95849)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95849)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
    at oG (7aa3e4eb-df755cd629be1b60.js:1:95792)
    at oX (7aa3e4eb-df755cd629be1b60.js:1:95696)
/console/api/apps?page=1&limit=30&name=:1 
            
            
            Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED)
/console/api/account/profile:1 
            
            
            Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED)
/console/api/workspaces/current?:1 
            
            
            Failed to load resource: the server responded with a status of 401 (UNAUTHORIZED)
3374-688e9970e8eca026.js:1  Uncaught TypeError: Cannot read properties of undefined (reading 'checkValid')
    at 3374-688e9970e8eca026.js:1:406165
    at Object.ai [as useMemo] (7aa3e4eb-df755cd629be1b60.js:1:47842)
    at 7088-1d6cae86cb82768c.js:1:167177
    at F (3374-688e9970e8eca026.js:1:405268)
    at page-8857d9238676d978.js:1:118891
    at lS (7aa3e4eb-df755cd629be1b60.js:1:39325)
    at ot (7aa3e4eb-df755cd629be1b60.js:1:64573)
    at a9 (7aa3e4eb-df755cd629be1b60.js:1:63435)
    at ov (7aa3e4eb-df755cd629be1b60.js:1:79275)
    at ic (7aa3e4eb-df755cd629be1b60.js:1:112360)
    at 7aa3e4eb-df755cd629be1b60.js:1:112205
    at is (7aa3e4eb-df755cd629be1b60.js:1:112213)
    at u9 (7aa3e4eb-df755cd629be1b60.js:1:109424)
    at iQ (7aa3e4eb-df755cd629be1b60.js:1:130771)
    at iI (7aa3e4eb-df755cd629be1b60.js:1:129010)
    at ib (7aa3e4eb-df755cd629be1b60.js:1:125930)
    at ig (7aa3e4eb-df755cd629be1b60.js:1:123682)
    at u7 (7aa3e4eb-df755cd629be1b60.js:1:110614)
    at u9 (7aa3e4eb-df755cd629be1b60.js:1:109967)
    at iH (7aa3e4eb-df755cd629be1b60.js:1:130650)
    at MessagePort.w (7088-1d6cae86cb82768c.js:1:4842)
3374-688e9970e8eca026.js:1  Uncaught TypeError: Cannot read properties of undefined (reading 'checkValid')
    at 3374-688e9970e8eca026.js:1:406165
    at Object.ai [as useMemo] (7aa3e4eb-df755cd629be1b60.js:1:47842)
    at 7088-1d6cae86cb82768c.js:1:167177
    at F (3374-688e9970e8eca026.js:1:405268)
    at page-8857d9238676d978.js:1:118891
    at lS (7aa3e4eb-df755cd629be1b60.js:1:39325)
    at ot (7aa3e4eb-df755cd629be1b60.js:1:64573)
    at a9 (7aa3e4eb-df755cd629be1b60.js:1:63435)
    at ov (7aa3e4eb-df755cd629be1b60.js:1:79275)
    at ic (7aa3e4eb-df755cd629be1b60.js:1:112360)
    at 7aa3e4eb-df755cd629be1b60.js:1:112205
    at is (7aa3e4eb-df755cd629be1b60.js:1:112213)
    at u9 (7aa3e4eb-df755cd629be1b60.js:1:109424)
    at iQ (7aa3e4eb-df755cd629be1b60.js:1:130771)
    at iI (7aa3e4eb-df755cd629be1b60.js:1:129010)
    at ib (7aa3e4eb-df755cd629be1b60.js:1:125930)
    at ig (7aa3e4eb-df755cd629be1b60.js:1:123682)
    at u7 (7aa3e4eb-df755cd629be1b60.js:1:110614)
    at u9 (7aa3e4eb-df755cd629be1b60.js:1:109967)
    at iH (7aa3e4eb-df755cd629be1b60.js:1:130650)
    at MessagePort.w (7088-1d6cae86cb82768c.js:1:4842)
```

### ✔️ Expected Behavior

When I imported this DSL file into Dify, this error occurred.
The detailed DSL file being imported is as follows:
```
app:
  description: ''
  icon: 6287692b-d96e-4556-a480-43296ecd1781
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: 1588时间同步故障处理助手
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/tongyi:0.0.25@325423749d5e71f8b4681af1b2ed46d7686cb1947e443a86ba5d14ac45ff85a4
kind: app
version: 0.3.0
workflow:
  conversation_variables: []
  environment_variables:
  - description: ''
    id: 3bfe16e6-33dd-4b7d-b034-9a493cdbe7ec
    name: img_service
    selector:
    - env
    - img_service
    value: https://test-askbigmodel.fiberhome.work/imgs/olt_pics/
    value_type: string
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 1
    opening_statement: 可输入 1588 时间同步相关的产品型号、单盘名称、软件版本等信息。 
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: if-else
      id: edge-start-to-1588-fault-type
      selected: false
      source: start-node
      sourceHandle: source
      target: 1588-fault-type-check
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: answer
      id: edge-1588-fault-type-to-clock-sync-failure
      selected: false
      source: 1588-fault-type-check
      sourceHandle: clock-sync-failure
      target: clock-sync-failure-check
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: answer
        targetType: llm
      id: edge-clock-sync-failure-to-llm
      selected: false
      source: clock-sync-failure-check
      sourceHandle: source
      target: clock-sync-failure-llm
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: llm
        targetType: answer
      id: edge-llm-to-1588-solution
      selected: false
      source: clock-sync-failure-llm
      sourceHandle: source
      target: 1588-solution-node
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: 1588 时间同步故障排查起始节点
        selected: false
        title: 开始
        type: start
        variables:
        - label: 1588 时间同步故障类型
          max_length: 48
          options:
          - 时钟同步失败
          - 时钟精度偏差过大
          - 时钟丢失
          - 时钟抖动异常
          - 时钟频率偏移
          required: true
          type: select
          variable: 1588_fault_type
          id: 1588-fault-type-select
          name: 1588-fault-type-select
      height: 89
      id: start-node
      position:
        x: -58.14
        y: 522.91
      positionAbsolute:
        x: -58.14
        y: 522.91
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: clock-sync-failure
          conditions:
          - comparison_operator: is
            id: cond-1588-clock-sync-failure
            value: 时钟同步失败
            varType: string
            variable_selector:
            - start-node
            - 1588_fault_type
          logical_operator: and
        desc: 1588 时间同步故障类型判断
        selected: false
        title: 1588 故障类型判断
        type: if-else
      height: 221
      id: 1588-fault-type-check
      position:
        x: 332.68
        y: 522.91
      positionAbsolute:
        x: 332.68
        y: 522.91
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: 正在分析时钟同步失败原因...
        desc: 时钟同步失败分析节点
        selected: false
        title: 时钟同步失败分析
        type: answer
        variables: []
      height: 101
      id: clock-sync-failure-check
      position:
        x: 741.77
        y: 851.77
      positionAbsolute:
        x: 741.77
        y: 851.77
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - sys
          - query
        desc: 1588 时间同步故障处理大语言模型节点
        memory:
          query_prompt_template: ''
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: false
            size: 50
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: qwen-max-latest
          provider: langgenius/tongyi/tongyi
        prompt_template:
        - id: 1588-system-prompt
          role: system
          text: "# 角色：你是一名 1588 时间同步专家\n\n# 任务：\n你的任务是基于技能指导用户排查并最终确定 1588 时间同步的故障原因。\n\
            - 按照技能中所列出的步骤，用对话的方式，一步一步引导用户进行操作，通过向用户询问上一步操作的结果，决定如何引导用户的下一步操作，直到帮助用户解决故障或结束流程。\n\
            - 按照技能描述的步骤进行，不要假设在技能故障排查描述中没有的命令行，也不能改变技能步骤的结构。\n- 当技能步骤中出现输出：\"![ ](***)\
            \"的图片加载语句时，必须在回答中引用此图片加载语句的原文。\n- 如果用户的回答不清晰，可能有多种理解，提醒用户重新详细回答。\n-\
            如果用户回答不懂、不知道、不清楚，或者无法查看等，请直跳到下一个步骤或子步骤。\n- 在对话过程中，只需要讲述步骤内容，不要提及步骤编号。\n\
            \n# 技能：故障排查步骤如下：\n## 步骤 1：检查 1588 设备的时钟源配置是否正确。\n- 配置正确：跳到步骤 2。\n- 配置错误：重新配置时钟源，跳到步骤 1.1。\n\
            ### 步骤 1.1：重新配置后，检查 1588 时间同步是否恢复正常。\n- 是：流程结束。\n- 否：跳到步骤 2。\n## 步骤 2：检查网络链路是否正常。\n\
            - 链路正常：跳到步骤 3。\n- 链路异常：修复网络链路，跳到步骤 2.1。\n### 步骤 2.1：修复后，检查 1588 时间同步是否恢复正常。\n\
            - 是：流程结束。\n- 否：跳到步骤 3。\n## 步骤 3：检查 1588 设备的硬件是否正常。\n- 硬件正常：跳到步骤 4。\n- 硬件异常：更换故障硬件，跳到步骤 3.1。\n\
            ### 步骤 3.1：更换后，检查 1588 时间同步是否恢复正常。\n- 是：流程结束。\n- 否：跳到步骤 4。\n## 步骤 4：检查 1588 设备的软件版本是否兼容。\n\
            - 版本兼容：跳到步骤 5。\n- 版本不兼容：升级或降级软件版本，跳到步骤 4.1。\n### 步骤 4.1：升级或降级后，检查 1588 时间同步是否恢复正常。\n\
            - 是：流程结束。\n- 否：跳到步骤 5。\n## 步骤 5：如果以上步骤都没有解决故障，请你将用户在每个步骤的回答信息进行汇总，将汇总结果列成清单，并要求用户联系 1588 时间同步专家。不要向用户提出其他要求。\n\
            ## 如果在以上任何一步，用户回答故障已解决，即终止流程。"
        - id: 1588-assistant-prompt
          role: assistant
          text: 如果出现“你可能想问”的问题列表内容，删掉这部分内容。
      height: 300
      id: clock-sync-failure-llm
      position:
        x: 1100
        y: 851.77
      positionAbsolute:
        x: 1100
        y: 851.77
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 300
    - data:
        answer: "根据分析结果，1588 时间同步故障的可能原因及解决方案如下：\n{{#LLM_OUTPUT#}}"
        desc: 1588 时间同步故障解决方案节点
        selected: false
        title: 1588 解决方案
        type: answer
        variables: []
      height: 101
      id: 1588-solution-node
      position:
        x: 1400
        y: 851.77
      positionAbsolute:
        x: 1400
        y: 851.77
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
```
