### ISSUE TITLE
Importing a chatflow DSL does not import its conversion variables.

### ISSUE THREAD

**Issue by QuantumGhost** [langgenius/dify#21039]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

v1.4.2

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Import the `DSL import test (before import)` DSL into your workspace.
2. Open the conversation variable panel. Verify that there's a conversation variable named `before_import`.
   
   ![Conversation variable panel showing before_import variable](https://github.com/user-attachments/assets/efdc6f19-4f14-41a4-bc0a-b10fda977637)
3. Use the "Import DSL" feature to import the `DSL import test (imported)` DSL.
   
   ![Import DSL dialog](https://github.com/user-attachments/assets/b6024ee7-dc32-4317-a975-068b3b930561)
4. Wait for the import to succeed, then refresh the page.
5. Open the conversation variable panel again.

DSLs:

<details>

<summary>DSL import test (before import)</summary>

This DSL contains a conversation variable named `before_import`.

```yaml
app:
  description: 'This is a chatflow used to test conversation variable handling while
    import DSL.


    This chatflow has a conversation variable named `before_import`.'
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: DSL import test (before import)
  use_icon_as_answer_icon: false
dependencies: []
kind: app
version: 0.3.0
workflow:
  conversation_variables:
  - description: Test conversation variable
    id: a12bf36c-3c29-44b4-b749-9a9b403a7f67
    name: before_import
    selector:
    - conversation
    - before_import
    value: before import default value.
    value_type: string
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInLoop: false
        sourceType: start
        targetType: answer
      id: 1750043990949-source-answer-target
      source: '1750043990949'
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables: []
      height: 54
      id: '1750043990949'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#conversation.before_import#}}'
        desc: ''
        selected: false
        title: Answer
        type: answer
        variables: []
      height: 105
      id: answer
      position:
        x: 438
        y: 282
      positionAbsolute:
        x: 438
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -150
      y: 121.5
      zoom: 1
```
</details>

<details>

<summary>DSL import test (imported)</summary>

This DSL contains a conversation variable named `imported`.

```yaml
app:
  description: 'This is a chatflow used to test conversation variable handling while
    import DSL.



    This chatflow has a conversation variable named `imported`.'
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: DSL import test (imported)
  use_icon_as_answer_icon: false
dependencies: []
kind: app
version: 0.3.0
workflow:
  conversation_variables:
  - description: Test conversation variable.
    id: 5fcb91bf-5b28-4395-8c74-ae67b8dcef2d
    name: imported
    selector:
    - conversation
    - imported
    value: imported default value
    value_type: string
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInLoop: false
        sourceType: start
        targetType: answer
      id: 1750044115373-source-answer-target
      source: '1750044115373'
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables: []
      height: 54
      id: '1750044115373'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#conversation.imported#}}'
        desc: ''
        selected: false
        title: Answer
        type: answer
        variables: []
      height: 105
      id: answer
      position:
        x: 473
        y: 282
      positionAbsolute:
        x: 473
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 0
      y: 0
      zoom: 1
```

</details>

### ✔️ Expected Behavior

The importing process should:

1. Remove the `before_import` conversation variable from the original chatflow.
2. Add the new `imported` conversation variable from the imported DSL.

### ❌ Actual Behavior

1. The `before_import`  conversation variable is not removed.
2. The new `imported` conversation variable is not added.
