### ISSUE TITLE
In Dify’s Code node (JavaScript), using JSON.parse() throws a ‘list index out of range’ error when handling numbers that exceed the precision limit

### ISSUE THREAD

**Issue by tortorse** [langgenius/dify#21200]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.4.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. Provide a JSON input to the Code node. The JSON contains a field whose value is a decimal number less than 0.00001.
2. Execute the node

<img width="1064" alt="Image" src="https://github.com/user-attachments/assets/9d524756-37f3-4cb0-854b-ae80ac3740e1" />

<img width="1065" alt="Image" src="https://github.com/user-attachments/assets/10f26076-19a4-4718-9bd0-2d654ca6b7a9" />

<img width="1064" alt="Image" src="https://github.com/user-attachments/assets/a042892d-cdc0-41e4-9608-596e79965045" />

The DSL:

```yaml
app:
  description: Reproduce JSON parsing error
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: Code Node JSON Parse Error
  use_icon_as_answer_icon: false
dependencies: []
kind: app
version: 0.3.0
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        isInLoop: false
        sourceType: code
        targetType: end
      id: 1750255178451-source-1750255217435-target
      source: '1750255178451'
      sourceHandle: source
      target: '1750255217435'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: start
        targetType: code
      id: 1750254940522-source-1750255178451-target
      source: '1750254940522'
      sourceHandle: source
      target: '1750255178451'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - label: JSON
          max_length: 120
          options: []
          required: true
          type: paragraph
          variable: JSON
      height: 90
      id: '1750254940522'
      position:
        x: 30
        y: 245
      positionAbsolute:
        x: 30
        y: 245
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\nfunction main({input}) {\n    return {\n        result: JSON.parse(input)\n\
          \    }\n}\n"
        code_language: javascript
        desc: ''
        outputs:
          result:
            children: null
            type: object
        selected: false
        title: 代码执行
        type: code
        variables:
        - value_selector:
          - '1750254940522'
          - JSON
          variable: input
      height: 54
      id: '1750255178451'
      position:
        x: 334
        y: 245
      positionAbsolute:
        x: 334
        y: 245
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1750255178451'
          - result
          variable: output
        selected: false
        title: 结束
        type: end
      height: 90
      id: '1750255217435'
      position:
        x: 638
        y: 245
      positionAbsolute:
        x: 638
        y: 245
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 162
      y: 14
      zoom: 0.7
```

### ✔️ Expected Behavior

The JSON is parsed successfully.

### ❌ Actual Behavior

Error message: list index out of range.
