### ISSUE TITLE
how to add https server for dify; dify怎么设置https访问

### ISSUE THREAD

**Issue by deepblue-star** [langgenius/dify#3083]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of the help you need

我在我的云虚拟机上部署了docker dify，但是我需要通过https访问dify，而不是原来的http，这应该怎么设置呢

**Comment by liduang** [comment]
我按照这个配置完后，访问https，报404，请问什么原因哈

**Comment by dididixu** [comment]
花了2小时踩了无数坑搞定了
1. docker/nginx/ssl下放你的.crt和.key
2. 修改docker/nginx/conf.d/default.conf，把443那部分注释取消，更换crt和key的名称
3. 修改docker/docker-compose.yaml nginx部分直接看示例
```
# The nginx reverse proxy.
  # used for reverse proxying the API service and Web service.
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl
    depends_on:
      - api
      - web
    ports:
      #- "80:80"
      - "443:443"
```
