### ISSUE TITLE
404 found on initial login dify

### ISSUE THREAD

**Issue by hanxuanliang** [langgenius/dify#3131]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

v0.5.11-fix1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. first login dify
<img width="1792" alt="image" src="https://github.com/langgenius/dify/assets/29874640/5e3c6186-108e-4250-8447-f5a65ffd97de">

2. then I reset my email and password
<img width="886" alt="image" src="https://github.com/langgenius/dify/assets/29874640/2086b03c-c0e2-4834-8a53-ee410d22afe4">

3. update docker-compose.yaml
    - expose port: api & web & db
    - add `COOKIE_HTTPONLY` config
    - update `CONSOLE_WEB_URL` and `CONSOLE_API_URL` config
    ```yaml
    CONSOLE_WEB_URL: 'http://127.0.0.1:3000'
      # Password for admin user initialization.
      # If left unset, admin user will not be prompted for a password when creating the initial admin account.
      INIT_PASSWORD: ''
      # The base URL of console application api server, refers to the Console base URL of WEB service if console domain is
      # different from api or web app domain.
      # example: http://cloud.dify.ai
      CONSOLE_API_URL: 'http://127.0.0.1:5001'
      # The URL prefix for Service API endpoints, refers to the base URL of the current API service if api domain is
      # different from console domain.
      # example: http://api.dify.ai
      SERVICE_API_URL: 'http://127.0.0.1:5001'
      # The URL prefix for Web APP frontend, refers to the Web App base URL of WEB service if web app domain is different from
      # console or api domain.
      # example: http://udify.app
      APP_WEB_URL: 'http://127.0.0.1:3000'
      ...
      COOKIE_HTTPONLY: 'true'
      COOKIE_SAMESITE: 'Lax'
      COOKIE_SECURE: 'true'
      ...
      ```

### ✔️ Expected Behavior

I've gone through almost all the documentation and issues and still haven't found the right solution. This issue seems to appear many times in issues, why not provide a default docker-compose.dafult.yaml for the convenience of standalone deployment users to experience?

### ❌ Actual Behavior

<img width="1792" alt="image" src="https://github.com/langgenius/dify/assets/29874640/e140db62-67aa-449f-a2c5-cfee8e305a3a">
