### ISSUE TITLE
Sandbox cannot import datetime module

### ISSUE THREAD

**Issue by jamesliu668** [langgenius/dify#3566]
### Self Checks

- [X] This is only for bug report, if you would like to ask a quesion, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Dify version

0.6.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I created a flow with code node. If I put the python code like below, it will work.
`
def main() -> dict:

    return {
        "result": "2024/4/17 17:35:42"
    }
`

But if I put code like this:
`
from datetime import datetime
def main() -> dict:

    return {
        "result": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
`

The node will give out an error:

> Traceback (most recent call last): File "<string>", line 40, in <module> File "<string>", line 2, in <module> ModuleNotFoundError: No module named 'datetime' error: exit status 255

### ✔️ Expected Behavior

Print the datetime result

### ❌ Actual Behavior

No module named 'datetime' error

**Comment by takatost** [comment]
Have you write `importe datetime`?

**Comment by crazywoola** [comment]
Duplicated https://github.com/langgenius/dify/issues/3331

**Comment by jamesliu668** [comment]
A little bit different. I am using `docker-compose.yaml` to setup the dify env. The sandbox part is below (I am using the original setting without any change)

```
  # The DifySandbox
  sandbox:
    image: langgenius/dify-sandbox:latest
    restart: always
    cap_add:
    # Why is sys_admin permission needed?
    # https://docs.dify.ai/getting-started/install-self-hosted/install-faq#id-16.-why-is-sys_admin-permission-needed
      - SYS_ADMIN
    environment:
      # The DifySandbox configurations
      API_KEY: dify-sandbox
      GIN_MODE: release
      WORKER_TIMEOUT: 15
```

The code I am using is below:
```
from datetime import datetime
def main() -> dict:

    return {
        "result": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }
```

I don't find the `dify-sandbox` souce code, so I don't know where to check the problem.

Thanks
