### ISSUE TITLE
 How to modify the upload file size to 100MB in the local deployment version of docker? Want to know the specific steps

### ISSUE THREAD

**Issue by ryanwong2023** [langgenius/dify#3865]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Pleas do not modify this template :) and fill in all the required fields.

### Provide a description of requested docs changes

 How to modify the upload file size to 100MB in the local deployment version of docker? Want to know the specific steps

**Comment by FarVision2** [comment]
Find the env example file under 
_dify/api /.env.example_

in there, you are looking for
_Upload configuration_

edit to what you wish and rename the file to _.env_

copy the .env file to
\dify\docker

The docker-compose.yaml file needs to have the environment variable entry added.

```
version: '3'
services:
  # API service
  api:
    image: langgenius/dify-api:x.x.x
    restart: always
    env_file:
      - .env
    environment:
      # Startup mode, 'api' starts the API server.
      MODE: api
      # The log level for the application. Supported values are `DEBUG`, `INFO`, `WARNING`, `ERROR`, `CRITICAL`
      LOG_LEVEL: INFO
```
run your _docker-compose up -d_ like usual.

After that, all your configuration scripts will built off that. You should do not have to manually edit any other files

one thing to watch out for is making the limits too large and your embedding API will time out, and the token estimate generator may not return in time and also time out.

A general rule of thumb I like to keep is if you are loading many small files is not a problem but if you are loading larger files do one or two at a time, do not load the entire thing up as much as possible because things start timing out and you'll have to delete the partial entry and redo it again anyway
