### ISSUE TITLE
Nginx still not work on Mac M1

### ISSUE THREAD

**Issue by red-wu5** [langgenius/dify#4399]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.6

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I am directly cloning the latest code from Dify, and run docker-compose (using colima) up -d --build in docker folder, but still get error 
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/usr/local/project/dify/docker/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": mount /usr/local/project/dify/docker/nginx/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`
I see many people have raised this issue, but there are still many who have not solved it ! 
This is my docker-compose.yaml
```
  nginx:
    image: nginx:latest
    restart: always
    privileged: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      #- ./nginx/ssl:/etc/ssl
    depends_on:
      - api
      - web
    ports:
      - "80:80"
      #- "443:443"
```
and I'm sure nginx.conf is not a directory

### ✔️ Expected Behavior

up nginx container successful

### ❌ Actual Behavior

got error
`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/usr/local/project/dify/docker/nginx/nginx.conf" to rootfs at "/etc/nginx/nginx.conf": mount /usr/local/project/dify/docker/nginx/nginx.conf:/etc/nginx/nginx.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`
