### ISSUE TITLE
RuntimeError: missing networks: default

### ISSUE THREAD

**Issue by elviswf** [langgenius/dify#4773]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Docker deploy:

`sudo podman-compose -f ./docker-compose.yaml up`

### ✔️ Expected Behavior

Docker deployed normally.

### ❌ Actual Behavior

podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.6.1
Traceback (most recent call last):
  File "/bin/podman-compose", line 11, in <module>
    load_entry_point('podman-compose==1.0.6', 'console_scripts', 'podman-compose')()
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 2940, in main
    podman_compose.run()
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 1420, in run
    self._parse_compose_file()
  File "/usr/lib/python3.6/site-packages/podman_compose.py", line 1567, in _parse_compose_file
    raise RuntimeError(f"missing networks: {missing_nets_str}")
RuntimeError: missing networks: default

**Comment by elviswf** [comment]
Adding the default networks solved my problem.
`docker-compose.yaml`: line 478-485 changed to this:

```
networks:
  # create a network between sandbox, api and ssrf_proxy, and can not access outside.
  ssrf_proxy_network:
    driver: bridge
    internal: true
  default:
    driver: bridge
    internal: true
```

**Comment by elviswf** [comment]
I found another issue in podman deployment process:
 `socket.gaierror: [Errno -3] Temporary failure in name resolution`

It says the sandbox is not in the networks.

When I add default to the sandbox config, the error is solved.  `docker-compose.yaml`: line 406-407

```
  sandbox:
    image: langgenius/dify-sandbox:0.2.0
    restart: always
    environment:
      # The DifySandbox configurations
      # Make sure you are changing this key for your deployment with a strong key.
      # You can generate a strong key using `openssl rand -base64 42`.
      API_KEY: dify-sandbox
      GIN_MODE: 'release'
      WORKER_TIMEOUT: 15
      ENABLE_NETWORK: 'true'
      HTTP_PROXY: 'http://ssrf_proxy:3128'
      HTTPS_PROXY: 'http://ssrf_proxy:3128'
    volumes:
      - ./volumes/sandbox/dependencies:/dependencies:z
    networks:
      - ssrf_proxy_network
      - default
```
