### ISSUE TITLE
Output files from iterasion node gives TypeError.

### ISSUE THREAD

**Issue by AndyMik90** [langgenius/dify#4873]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.9

### Cloud or Self Hosted

Cloud, Self Hosted (Docker), Self Hosted (Source)

### Steps to reproduce

1. When using tools that can ouput files in iteration node it gives TypeError: Object of type FileVar is not JSON serializable.
2. Also the output from iteration node don't recognize an Array of files.
![CleanShot 2024-06-02 at 21 30 53](https://github.com/langgenius/dify/assets/119136210/5727f90a-41b6-4063-850b-d1f0e5851359)
![CleanShot 2024-06-02 at 21 36 52](https://github.com/langgenius/dify/assets/119136210/5d49c039-8eb4-48c0-9388-fc7235a826a1)

DSL to reproduce:
```
app:
  description: ''
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: workflow
  name: Iteration File test
workflow:
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1717356703710-source-1717356707855-target
      source: '1717356703710'
      sourceHandle: source
      target: '1717356707855'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: iteration
      id: 1717356707855-source-1717356937099-target
      source: '1717356707855'
      sourceHandle: source
      target: '1717356937099'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: iteration
        targetType: end
      id: 1717356937099-source-1717356952635-target
      source: '1717356937099'
      sourceHandle: source
      target: '1717356952635'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables:
        - label: image1
          max_length: 48
          options: []
          required: true
          type: text-input
          variable: image1
        - label: image2
          max_length: 48
          options: []
          required: true
          type: text-input
          variable: image2
      height: 116
      id: '1717356703710'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "def main(arg1: str, arg2: str) -> dict:\n    return {\n        \"result\"\
          : [arg1, arg2],\n    }"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: array[string]
        selected: false
        title: Code
        type: code
        variables:
        - value_selector:
          - '1717356703710'
          - image1
          variable: arg1
        - value_selector:
          - '1717356703710'
          - image2
          variable: arg2
      height: 54
      id: '1717356707855'
      position:
        x: 384
        y: 282
      positionAbsolute:
        x: 384
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        height: 324
        iterator_selector:
        - '1717356707855'
        - result
        output_selector:
        - '1717356940480'
        - files
        output_type: array[string]
        selected: false
        startNodeType: tool
        start_node_id: '1717356940480'
        title: Iteration
        type: iteration
        width: 485
      height: 324
      id: '1717356937099'
      position:
        x: 688
        y: 282
      positionAbsolute:
        x: 688
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 485
      zIndex: 1
    - data:
        desc: ''
        isInIteration: true
        isIterationStart: true
        iteration_id: '1717356937099'
        provider_id: dalle
        provider_name: dalle
        provider_type: builtin
        selected: false
        title: DALL-E 3
        tool_configurations:
          n: 1
          quality: standard
          size: square
          style: vivid
        tool_label: DALL-E 3
        tool_name: dalle3
        tool_parameters:
          prompt:
            type: mixed
            value: '{{#1717356937099.item#}}'
        type: tool
      extent: parent
      height: 168
      id: '1717356940480'
      parentId: '1717356937099'
      position:
        x: 117
        y: 85
      positionAbsolute:
        x: 805
        y: 367
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1001
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1717356937099'
          - output
          variable: output
        selected: false
        title: End
        type: end
      height: 90
      id: '1717356952635'
      position:
        x: 1233
        y: 282
      positionAbsolute:
        x: 1233
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 2.365291011755289
      y: 200.59946916062177
      zoom: 0.9125654885434517

``` 

### ✔️ Expected Behavior

Output the files in an array so multiple files can be outputted in the end node.

### ❌ Actual Behavior

TypeError: Object of type FileVar is not JSON serializable and wrong Array.
