### ISSUE TITLE
If HTTP-PROXY is configured, it will cause errors in the code execution module

### ISSUE THREAD

**Issue by sunk926** [langgenius/dify#5058]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.10

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Perhaps there is a conflict below

HTTP_PROXY: 'http://192.168.8.6:10809'
HTTPS_PROXY: 'http://192.168.8.6:10809'

...

SSRF_PROXY_HTTP_URL: 'http://ssrf_proxy:3128'
SSRF_PROXY_HTTPS_URL: 'http://ssrf_proxy:3128'

**Comment by sunk926** [comment]
> Hello @sunk926 👋, I'm here to help you with any issues you're experiencing with the Dify software. I can assist with bug fixes, answer questions, and guide you on how to contribute. Let me know how I can assist you!
> 
> To resolve errors in the code execution module when HTTP-PROXY is configured in Dify version 0.6.10 on a self-hosted Docker environment, you can use the following Nginx proxy configuration:...


I saw the following information in the Hysteria output log...
```
2024-06-10T10:59:37Z    ERROR   HTTP error      {"addr": "172.31.0.7:59124", "reqURL": "http://sandbox:8194/v1/sandbox/dependencies?language=python3", "error": "Get \"http://sandbox:8194/v1/sandbox/dependencies?language=python3\": dial error: resolve error: lookup sandbox on 8.8.8.8:53: no such host"}
2024-06-10T10:59:40Z    ERROR   HTTP error      {"addr": "172.31.0.7:59126", "reqURL": "http://sandbox:8194/v1/sandbox/run", "error": "Post \"http://sandbox:8194/v1/sandbox/run\": dial error: resolve error: lookup sandbox on 8.8.8.8:53: no such host"}
```
I believe that the configuration of "HTTP_PROXY" might be causing the local URL http://sandbox/ to be proxied by "HTTP_PROXY". However, my hysteria client is unable to handle this issue. Could you please suggest any other methods to resolve this problem?
```
version: '3'
services:
  # API service
  api:
    image: langgenius/dify-api:0.6.10
    restart: always
    environment:
      HTTP_PROXY: 'http://192.168.8.6:10809'
      HTTPS_PROXY: 'http://192.168.8.6:10809'
      # Startup mode, 'api' starts the API server.
      MODE: api
      ...
```
