### ISSUE TITLE
[Enhancement] Optimization of the docker-compose.yaml file

### ISSUE THREAD

**Issue by breakstring** [langgenius/dify#5249]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing?

When I tried to deploy using docker-compose, modifying environment variables in the complex YAML file was a painful task, and it also faced merge issues after git updates.

### 2. Describe the feature you'd like to see

1. Please move the variable values from the YAML file to a .env file. You can provide a .env.template file that contains default values, so we can copy it to create our own .env file. This way, when the repository is updated, we will only pull the .env.template file, and our local deployment won't conflict with its changes.
2. In the same docker-compose.yaml file, try to reduce configuration errors by reusing anchors to minimize repetitive configurations (especially for the current API and worker services, which share many identical variables). [Reference](https://docs.docker.com/compose/compose-file/11-extension/).
```yaml
x-shared-env: &default-env
  environment:
    ENV2: common_value_2
    ENV3: common_value_3

services:
  service_api:
    image: some_image:latest
    environment:
      <<: *default-env
      MODE: api

  service_worker:
    image: some_image:latest
    environment:
      <<: *default-env
      MODE: worker
```
3. In the current deployment architecture, some pre-configured content (such as the nginx configuration and the contents of the two pre-set volumes) needs to be directly operated on the server. Firstly, it's inconvenient to git clone/pull the code on the server. Secondly, it makes it difficult to deploy using container management tools (such as Portainer). I hope these parts can be optimized through some mechanism.

### 3. How will this feature improve your workflow or experience?

Deployment and maintenance should both become more convenient.

### 5. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.
