### ISSUE TITLE
After setting the CONSOLE_API_URL, the page cannot be accessed and remains in a loading state.

### ISSUE THREAD

**Issue by lvjiajjjlzy** [langgenius/dify#5737]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I tried to set CONSOLE_API_URL to a domain name, loopback address, and *, but the loading failed. After deleting it, it loaded successfully, but then I tried to connect to cloud.dify.ai and received a 401 error.
After redeploying the project, the problem still exists
![image](https://github.com/langgenius/dify/assets/103650510/1ce5ec6a-e618-4fe9-bbe1-6b7d03d6a1bc)

**Comment by crazywoola** [comment]
Please attach the screenshot of the web console. The blank screenshot doesn't helpful at all.

**Comment by lvjiajjjlzy** [comment]
> Please attach the screenshot of the web console. The blank screenshot doesn't helpful at all.

![image](https://github.com/langgenius/dify/assets/103650510/d9e3573c-3f0e-42c7-8d31-35b0675c2ee2)

**Comment by crazywoola** [comment]
https://docs.dify.ai/getting-started/install-self-hosted/environments

See the environments. 

You are requesting `https://mingpixel.site` from `https://dify.mingpixel.site`, so you will get a cors error, because you are not in the same domain.

As the bots suggests

```
# Example docker-compose.yml configuration
services:
  web:
    environment:
      - CONSOLE_API_URL=https://new-domain.com/api # see this line 
      - CONSOLE_WEB_URL=https://new-domain.com # and this line
      - SERVICE_API_URL=https://new-domain.com/service
      - APP_API_URL=https://new-domain.com/app-api
      - APP_WEB_URL=https://new-domain.com/app
 ```
They should be the same.
Please do not use bug template to fire an issue of env setup. Please go to discussion instead. https://github.com/langgenius/dify/discussions Thank you very much.
