### ISSUE TITLE
LLM error occurred on Azure GPT-4o

### ISSUE THREAD

**Issue by k3ntar0** [langgenius/dify#5790]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1
This issue does not occur in version 0.6.11 or earlier on my environment.

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I have implemented a workflow using Azure OpenAI GPT-4o to generate responses. The initial part of the text generation process, where the text is streamed, runs without any issues. However, during the streaming, I encounter an interruption in the generation process with the following error, causing the processing at the LLM node to halt: 

[azure_openai] Error: 'NoneType' object has no attribute 'tool_calls'

### ✔️ Expected Behavior

The generation by the LLM should complete and proceed to the next node in the workflow.

### ❌ Actual Behavior

The generation by the LLM is interrupted, and the workflow stops.

**Comment by laipz8200** [comment]
Could you provide us with a minimal DSL that would cause this exception?

**Comment by k3ntar0** [comment]
@laipz8200 
Thank you for addressing the issue.
This is a minimal workflow.

```yaml
app:
  description: ''
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: workflow
  name: Buggy Workflow
workflow:
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: llm
      id: 1719829040418-source-1719829045310-target
      source: '1719829040418'
      sourceHandle: source
      target: '1719829045310'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: llm
        targetType: end
      id: 1719829045310-source-1719829102839-target
      source: '1719829045310'
      sourceHandle: source
      target: '1719829102839'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables:
        - label: text
          max_length: 48
          options: []
          required: true
          type: text-input
          variable: text
      height: 90
      id: '1719829040418'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - '1719829040418'
          - text
        desc: ''
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: gpt-4o
          provider: azure_openai
        prompt_template:
        - id: 2676b1db-c839-44a9-b0eb-7589e741d8ad
          role: system
          text: '{{#context#}}'
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          configs:
            detail: high
          enabled: true
      height: 98
      id: '1719829045310'
      position:
        x: 384
        y: 282
      positionAbsolute:
        x: 384
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs: []
        selected: false
        title: End
        type: end
      height: 54
      id: '1719829102839'
      position:
        x: 688
        y: 282
      positionAbsolute:
        x: 688
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -63
      y: 51.5
      zoom: 1
```

<img width="1334" alt="Screenshot 2024-07-01 at 19 21 29" src="https://github.com/langgenius/dify/assets/11198599/24c3fc5b-6891-4c07-8d60-e1c5cc6077fc">

This issue occurred not only on the remote server but also locally.
