### ISSUE TITLE
the input field of tool panel not worked as expected

### ISSUE THREAD

**Issue by hjlarry** [langgenius/dify#6002]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.12-fix1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

when you develop a tool, add this config in the yaml file:
```
parameters:
  - name: test_select
    type: select
    options:
      - value: 0
        label:
          en_US: value_is_0
    required: true
    label:
      en_US: Test Select
    human_description:
      en_US: Test Select
    form: form
  - name: test_secret_input
    type: secret-input
    required: true
    label:
      en_US: Test Secret Input
    human_description:
      en_US: Test Secret Input
    form: form
  - name: test_number
    type: number
    required: true
    label:
      en_US: Test Number
    human_description:
      en_US: Test Number
    form: form
  - name: test_boolean
    type: boolean
    required: true
    label:
      en_US: Test Boolean
    human_description:
      en_US: Test Boolean
    form: form
```

you will get some input fields like this:
![image](https://github.com/langgenius/dify/assets/25834719/8a403649-2fd1-4fd2-b7c2-25654acd137a)

the problem is:

- secret input field,  it is not mask the input text
- number input field, you can't enter a `0`, it will not display; if you enter the `0.23`, it will display `.23`
- number input field, if the default value is 0,  when you run this node, it will raise `tool parameter test_number not found in tool config`
- select field, when you choose an option run once, and then click the clear btn run once again, it will submit the first time's value
- boolean field, it is not display the required star
- boolean field, there is no default value, but the `False` is selected in the page. when you click run btn, it will raise `Test Boolean 不能为空`
- boolean field, when you click again to choose `False`, it will raise `tool parameter test_boolean not found in tool config`
