### ISSUE TITLE
tool params not work as expected when develop a tool

### ISSUE THREAD

**Issue by hjlarry** [langgenius/dify#6549]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

use following params to config a tool:
```
  - name: test_number
    type: number
    required: false
    label:
      en_US: Test Number
    min: 5
    placeholder:
      en_US: Please input a number between 5 and 10
      zh_Hans: 请输入一个介于 5 和 10 之间的数字
    form: llm
  - name: type
    type: select
    required: false
    label:
      en_US: search type
    form: llm
    placeholder:
      en_US: Please choose an option
    options:
      - value: sports
        label:
          en_US: sports
      - value: games
        label:
          en_US: games
```
simply because the form type is `llm`,  it is all display as text.

### ✔️ Expected Behavior

![7b637a5c491bb2fe5ea28981cb95069](https://github.com/user-attachments/assets/167cecfb-b624-4425-a1bf-fff209d25cf6)

### ❌ Actual Behavior

![10bf577a88e613f33973976cf155dc0](https://github.com/user-attachments/assets/b8ac33d3-0566-48ab-8034-86b437693f79)
