### ISSUE TITLE
Run failed: Node Code Execution run failed: Failed to parse result

### ISSUE THREAD

**Issue by majestichou** [langgenius/dify#6871]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I started dify version 0.6.15 with docker. I set the environment variable for the code node.  Run the following command to check the environment variables of the sanbox container:
```
[root@cturf165 docker]# docker exec -it docker-sandbox-1 env
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=831f3c73466a
TERM=xterm
SANDBOX_PORT=8194
CODE_MAX_NUMBER_ARRAY_LENGTH=10000000
TEMPLATE_TRANSFORM_MAX_LENGTH=80000000
CODE_MAX_STRING_LENGTH=80000000
HTTPS_PROXY=http://ssrf_proxy:3128
CODE_MAX_NUMBER=922337203685477580700
CODE_MAX_STRING_ARRAY_LENGTH=300000
ENABLE_NETWORK=true
CODE_MAX_OBJECT_ARRAY_LENGTH=300000
CODE_MIN_NUMBER=-922337203685477580800
WORKER_TIMEOUT=15
API_KEY=dify-sandbox
GIN_MODE=release
HTTP_PROXY=http://ssrf_proxy:3128
LANG=C.UTF-8
GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D
PYTHON_VERSION=3.10.14
PYTHON_PIP_VERSION=23.0.1
PYTHON_SETUPTOOLS_VERSION=65.5.1
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/e03e1607ad60522cf34a92e834138eb89f57667c/public/get-pip.py
PYTHON_GET_PIP_SHA256=ee09098395e42eb1f82ef4acb231a767a6ae85504a9cf9983223df0a7cbd35d7
HOME=/root
```

I built an app using chatflow and the content of its DSL file named "test.yml" is as follows:

```
app:
  description: ''
  icon: "\U0001F916"
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: test
kind: app
version: 0.1.0
workflow:
  environment_variables: []
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: code
        targetType: iteration
      id: 1722480460067-source-1722488343394-target
      source: '1722480460067'
      sourceHandle: source
      target: '1722488343394'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: true
        iteration_id: '1722488343394'
        sourceType: code
        targetType: answer
      id: 1722488455130-source-1722488502069-target
      source: '1722488455130'
      sourceHandle: source
      target: '1722488502069'
      targetHandle: target
      type: custom
      zIndex: 1002
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1722480438479-source-1722480460067-target
      source: '1722480438479'
      sourceHandle: source
      target: '1722480460067'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: "\u5F00\u59CB"
        type: start
        variables: []
      height: 54
      id: '1722480438479'
      position:
        x: 282
        y: 282
      positionAbsolute:
        x: 282
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "def main() -> dict:\n    original_strings_with_empty = [\"apple\",\
          \ \"\", \"cherry\", \"date\", \"\", \"fig\", \"grape\", \"honeydew\", \"\
          kiwi\", \"\", \"mango\", \"nectarine\", \"orange\", \"papaya\", \"quince\"\
          , \"raspberry\", \"strawberry\", \"tangerine\", \"ugli fruit\", \"vanilla\
          \ bean\", \"watermelon\", \"xigua\", \"yellow passionfruit\", \"zucchini\"\
          ] * 5\n\n    # \u6269\u5C55\u6BCF\u4E2A\u5B57\u7B26\u4E32\u52303000\u4E2A\
          \u5B57\u7B26\uFF0C\u901A\u8FC7\u91CD\u590D\u539F\u59CB\u5B57\u7B26\u4E32\
          \u7684\u5B57\u7B26\n    extended_strings = []\n\n    for s in original_strings_with_empty:\n\
          \        if s:  # \u68C0\u67E5\u5B57\u7B26\u4E32\u662F\u5426\u975E\u7A7A\
          \n            # \u8BA1\u7B97\u9700\u8981\u91CD\u590D\u7684\u6B21\u6570\uFF0C\
          \u4F7F\u7528ceil\u51FD\u6570\u786E\u4FDD\u957F\u5EA6\u81F3\u5C11\u4E3A3000\n\
          \            repeat_times = 600\n            # \u91CD\u590D\u5B57\u7B26\u4E32\
          \u5E76\u5207\u7247\u4EE5\u786E\u4FDD\u957F\u5EA6\u6B63\u597D\u4E3A3000\n\
          \            extended_s = (s * repeat_times)[:2000]\n            extended_strings.append(extended_s)\n\
          \        else:\n            # \u5982\u679C\u5B57\u7B26\u4E32\u4E3A\u7A7A\
          \uFF0C\u8FD9\u91CC\u5047\u8BBE\u4E0D\u5904\u7406\u7A7A\u5B57\u7B26\u4E32\
          \uFF0C\u76F4\u63A5\u4FDD\u6301\u4E3A\u7A7A\n            extended_strings.append(s)\
          \ \n    \n    return {\n        \"result\": extended_strings,\n    }"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: array[string]
        selected: false
        title: "\u4EE3\u7801\u6267\u884C"
        type: code
        variables: []
      height: 54
      id: '1722480460067'
      position:
        x: 680
        y: 282
      positionAbsolute:
        x: 680
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        height: 209
        iterator_selector:
        - '1722480460067'
        - result
        output_selector:
        - '1722488455130'
        - result
        output_type: array[string]
        selected: false
        startNodeType: code
        start_node_id: '1722488455130'
        title: "\u8FED\u4EE3"
        type: iteration
        width: 681
      height: 209
      id: '1722488343394'
      position:
        x: 962
        y: 282
      positionAbsolute:
        x: 962
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 681
      zIndex: 1
    - data:
        code: "\ndef main(arg1: str) -> dict:\n    return {\n        \"result\": arg1,\n\
          \    }\n"
        code_language: python3
        desc: ''
        isInIteration: true
        isIterationStart: true
        iteration_id: '1722488343394'
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: "\u4EE3\u7801\u6267\u884C 2"
        type: code
        variables:
        - value_selector:
          - '1722488343394'
          - item
          variable: arg1
      extent: parent
      height: 54
      id: '1722488455130'
      parentId: '1722488343394'
      position:
        x: 117
        y: 85
      positionAbsolute:
        x: 1079
        y: 367
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1001
    - data:
        answer: '

          {{#1722488455130.result#}}'
        desc: ''
        isInIteration: true
        iteration_id: '1722488343394'
        selected: false
        title: "\u76F4\u63A5\u56DE\u590D"
        type: answer
        variables: []
      extent: parent
      height: 107
      id: '1722488502069'
      parentId: '1722488343394'
      position:
        x: 421
        y: 85
      positionAbsolute:
        x: 1383
        y: 367
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    viewport:
      x: -650.5
      y: 62
      zoom: 1
```

**The code of Code Execution Node 1 is as follows:**

```
def main() -> dict:
    original_strings_with_empty = ["apple", "", "cherry", "date", "", "fig", "grape", "honeydew", "kiwi", "", "mango", "nectarine", "orange", "papaya", "quince", "raspberry", "strawberry", "tangerine", "ugli fruit", "vanilla bean", "watermelon", "xigua", "yellow passionfruit", "zucchini"] * 5


    extended_strings = []

    for s in original_strings_with_empty:
        if s: 
            repeat_times = 600
            extended_s = (s * repeat_times)[:3000]
            extended_strings.append(extended_s)
        else:
            extended_strings.append(s) 
    
    return {
        "result": extended_strings,
    }
```
And then I run the app. The app crashes. The error message is as follows:

**`Run failed: Node Code Execution run failed: Failed to parse result`**

Then I change the code of Code Execution Node 1 to set the character length to 2000.

```
def main() -> dict:
    original_strings_with_empty = ["apple", "", "cherry", "date", "", "fig", "grape", "honeydew", "kiwi", "", "mango", "nectarine", "orange", "papaya", "quince", "raspberry", "strawberry", "tangerine", "ugli fruit", "vanilla bean", "watermelon", "xigua", "yellow passionfruit", "zucchini"] * 5


    extended_strings = []

    for s in original_strings_with_empty:
        if s:  
            repeat_times = 600

            extended_s = (s * repeat_times)[:2000]
            extended_strings.append(extended_s)
        else:

            extended_strings.append(s) 
    
    return {
        "result": extended_strings,
    }
```

The application is running properly. 

Then I change the code of Code Execution Node 1 to make the original_strings_with_empty have less elements.

```
def main() -> list:
    original_strings_with_empty = ["apple", "", "cherry", "date", "", "fig", "grape", "honeydew", "kiwi", "", "mango", "nectarine", "orange", "papaya"] * 5

    extended_strings = []

    for s in original_strings_with_empty:
        if s:  
            repeat_times = 600
            extended_s = (s * repeat_times)[:3000]
            extended_strings.append(extended_s)
        else:
            extended_strings.append(s) 
    
    return {
        "result": extended_strings,
    }
```
The application is also running properly. 

**According to my understanding, I have configured the environment variables correctly, but the application still reports an error. It cannot handle a string array with  more than 3000 elements per string.**

### ✔️ Expected Behavior

The application is running properly.

### ❌ Actual Behavior

Run failed: Node Code Execution run failed: Failed to parse result
