### ISSUE TITLE
The tool parameter of number type not support float value

### ISSUE THREAD

**Issue by hjlarry** [langgenius/dify#7643]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Source)

### Steps to reproduce

In a tool's config file, set the params like this:
```
  - name: guidance_scale
    type: number
    required: true
    default: 7.5
    min: 0
    max: 100
    label:
      en_US: Guidance Scale
      zh_Hans: 与提示词紧密性
    form: form
```

### ❌ Actual Behavior

raise Exception:

```
{
    "code": "invalid_param",
    "message": "2 validation errors for StableDiffusionTool\nparameters.5.default.int\n  Input should be a valid integer, got a number with a fractional part [type=int_from_float, input_value=7.5, input_type=float]\n    For further information visit https://errors.pydantic.dev/2.8/v/int_from_float\nparameters.5.default.str\n  Input should be a valid string [type=string_type, input_value=7.5, input_type=float]\n    For further information visit https://errors.pydantic.dev/2.8/v/string_type",
    "status": 400
}
```
