### ISSUE TITLE
Forgot to expose Milvus standalone port in yaml

### ISSUE THREAD

**Issue by winsonwhe** [langgenius/dify#7653]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

Follow the steps of [Deploy with Docker Compose](https://docs.dify.ai/getting-started/install-self-hosted/docker-compose) to setup Dify and **Milvus**, in docker compose yaml and Milvus part, it is lack of expose Milvus require port, leading to fail to connect with Milvus.

### ✔️ Expected Behavior

Correct yaml should refer https://github.com/milvus-io/milvus/blob/master/deployments/docker/standalone/docker-compose.yml

```
  milvus-standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.1
    profiles:
      - milvus
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_ENDPOINTS: ${ETCD_ENDPOINTS:-etcd:2379}
      MINIO_ADDRESS: ${MINIO_ADDRESS:-minio:9000}
      common.security.authorizationEnabled: ${MILVUS_AUTHORIZATION_ENABLED:-true}
    volumes:
      - ./volumes/milvus/milvus:/var/lib/milvus
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    **ports:
      - "19530:19530"
      - "9091:9091"**
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - milvus

```
