### ISSUE TITLE
In the output, the order of 'ta' is sometimes reversed as 'at'.

### ISSUE THREAD

**Issue by wsbao** [langgenius/dify#8015]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.3

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

- Use an open-source model like Qwen2-70B-Instruct
- Apply agent framework in ReAct mode
Then, in the output, the order of 'ta' is sometimes reversed as 'at'.
![image](https://github.com/user-attachments/assets/7277bcbc-b571-4cc1-9726-45f9e216362b)
![image](https://github.com/user-attachments/assets/5858bd98-90e0-4588-a326-31bc6fdf21d5)

### ✔️ Expected Behavior

Correct order of the output alpabets, especially for 'a' and 't'.

### ❌ Actual Behavior

The order of 'ta' is sometimes reversed as 'at'.
![image](https://github.com/user-attachments/assets/7277bcbc-b571-4cc1-9726-45f9e216362b)
![image](https://github.com/user-attachments/assets/5858bd98-90e0-4588-a326-31bc6fdf21d5)

**Comment by wsbao** [comment]
I created a YAML DSL for this App to reproduce this bug. I used [LM Studio](https://lmstudio.ai/) to host [Qwen2-7B-Instruct-q2_k.gguf](https://huggingface.co/Qwen/Qwen2-7B-Instruct-GGUF/resolve/main/qwen2-7b-instruct-q2_k.gguf) locally with CPU only.

```yaml
app:
  description: ''
  icon: speaking_head_in_silhouette
  icon_background: '#E0EAFF'
  mode: agent-chat
  name: Gossip
  use_icon_as_answer_icon: false
kind: app
model_config:
  agent_mode:
    enabled: true
    max_iteration: 5
    prompt: null
    strategy: react
    tools: []
  annotation_reply:
    enabled: false
  chat_prompt_config: {}
  completion_prompt_config: {}
  dataset_configs:
    datasets:
      datasets: []
    retrieval_model: multiple
  dataset_query_variable: ''
  external_data_tools: []
  file_upload:
    image:
      detail: high
      enabled: false
      number_limits: 3
      transfer_methods:
      - remote_url
      - local_file
  model:
    completion_params:
      max_tokens: 4096
      stop: []
      temperature: 0
    mode: chat
    name: Qwen2-7B-Instruct-q2_k.gguf
    provider: openai_api_compatible
  more_like_this:
    enabled: false
  opening_statement: ''
  pre_prompt: ''
  prompt_type: simple
  retriever_resource:
    enabled: true
  sensitive_word_avoidance:
    configs: []
    enabled: false
    type: ''
  speech_to_text:
    enabled: false
  suggested_questions: []
  suggested_questions_after_answer:
    enabled: false
  text_to_speech:
    enabled: false
    language: ''
    voice: ''
  user_input_form: []
version: 0.1.2
```
When we ask "What are ISO standard and stable diffusion?", the "rather" in the front-end output is mis-spelt as "athn".

![image](https://github.com/user-attachments/assets/cd632c61-16aa-40d2-b88b-e59b4a338610)

However, if we use same JSON payload

```json
{
    "model": "Qwen2-7B-Instruct-q2_k.gguf",
    // "stream": true,
    "temperature": 0,
    "max_tokens": 4096,
    "messages": [
        {
            "role": "system",
            "content": "Respond to the human as helpfully and accurately as possible. \n\n\n\nYou have access to the following tools:\n\n[]\n\nUse a json blob to specify a tool by providing an action key (tool name) and an action_input key (tool input).\nValid \"action\" values: \"Final Answer\" or \n\nProvide only ONE action per $JSON_BLOB, as shown:\n\n```\n{\n  \"action\": $TOOL_NAME,\n  \"action_input\": $ACTION_INPUT\n}\n```\n\nFollow this format:\n\nQuestion: input question to answer\nThought: consider previous and subsequent steps\nAction:\n```\n$JSON_BLOB\n```\nObservation: action result\n... (repeat Thought/Action/Observation N times)\nThought: I know what to respond\nAction:\n```\n{\n  \"action\": \"Final Answer\",\n  \"action_input\": \"Final response to human\"\n}\n```\n\nBegin! Reminder to ALWAYS respond with a valid json blob of a single action. Use tools if necessary. Respond directly if appropriate. Format is Action:```$JSON_BLOB```then Observation:.\n"
        },
        {
            "role": "user",
            "content": "What are ISO standard and stable diffusion?"
        }
    ],
    "stop": [
        "Observation"
    ]
}
```

to query this model API, and the result is correct:
```json
{
    "id": "chatcmpl-***h",
    "object": "chat.completion",
    "created": 17***01,
    "model": "Qwen2-7B-Instruct/Repository/qwen2-7b-instruct-q2_k.gguf",
    "choices": [
        {
            "index": 0,
            "message": {
                "role": "assistant",
                "content": "Thought: The user wants information about ISO standards and stable diffusion processes separately rather than asking for their relationship or comparison.\n\nAction:\n```\n{\n  \"action\": \"Final Answer\",\n  \"action_input\": {\n    \"ISO Standards\": \"ISO standards refer to International Organization for Standardization guidelines that provide specifications for products, services, systems, processes, etc., ensuring quality assurance.\",\n    \"Stable Diffusion Processes\": \"Stable diffusion refers to the process where substances move from areas of higher concentration to lower concentration until equilibrium is reached.\"\n}\n}\n```\n\n"
            },
            "logprobs": null,
            "finish_reason": "stop"
        }
    ],
    "usage": {
        "prompt_tokens": 242,
        "completion_tokens": 112,
        "total_tokens": 354
    },
    "system_fingerprint": "Qwen2-7B-Instruct/***/qwen2-7b-instruct-q2_k.gguf"
}
```
