### ISSUE TITLE
Debug and preview run error in parallel workflow

### ISSUE THREAD

**Issue by zhijianma** [langgenius/dify#8708]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

![image](https://github.com/user-attachments/assets/60cd01a0-80ac-4216-9a84-4a32133113ba)

The following is the workflow config

代码执行（Code）
arg1:  sys.query
```python
def main(arg1: str) -> dict:
    return {
        "result": arg1
    }
```
代码执行2 （Code2）
arg1:  sys.query
```python
def main(arg1: str) -> dict:
    import time
    time.sleep(10)
    return {
        "result": arg1,
    }
```

代码执行3（Code3）
arg1:  sys.query
```python

def main(arg1: str) -> dict:
    import time
    time.sleep(5)
    return {
        "result": arg1,
    }
```

代码执行4（Code4）
arg1:  代码执行2.result
arg2:  代码执行3.result
```python
def main(arg1: str, arg2: str) -> dict:
    import time
    time.sleep(5)
    return {
        "result": arg1 + arg2,
    }

```

代码执行5（Code5）
arg1:  代码执行.result
arg2:  代码执行4.result
```python
def main(arg1: str, arg2: str) -> dict:
    return {
        "result": arg1 + arg2,
    }
```

### ✔️ Expected Behavior

Node `代码执行4` needs to wait for its predecessor nodes to complete before executing.

### ❌ Actual Behavior

Node `代码执行4`  gets  a `None` value from args1.

Traceback (most recent call last): File "/var/sandbox/sandbox-python/tmp/df08b01c_e944_4b0b_9424_e7c2745ced23.py", line 48, in <module> File "<string>", line 19, in <module> File "<string>", line 8, in main TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' error: exit status 255

**Comment by crazywoola** [comment]
Please attach the DSL.

**Comment by zhijianma** [comment]
> Please attach the DSL. And I am not sure why do you need to code like this, I think a single code node is enough for the whole task and it won't generate errors.
In this case, I just use `Code` to simulate a parallel mode for a multi-input scenario.
And the DSL file as follows:

```yaml
app:
  description: ffd
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: test_workflow
  use_icon_as_answer_icon: false
kind: app
version: 0.1.2
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1725590432628-source-1727072856489-target
      selected: false
      source: '1725590432628'
      sourceHandle: source
      target: '1727072856489'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1725590432628-source-1727147018481-target
      selected: false
      source: '1725590432628'
      sourceHandle: source
      target: '1727147018481'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: start
        targetType: code
      id: 1725590432628-source-1727147052531-target
      selected: false
      source: '1725590432628'
      sourceHandle: source
      target: '1727147052531'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: code
      id: 1727147018481-source-1727147066015-target
      selected: false
      source: '1727147018481'
      sourceHandle: source
      target: '1727147066015'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: code
      id: 1727147052531-source-1727147066015-target
      selected: false
      source: '1727147052531'
      sourceHandle: source
      target: '1727147066015'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: code
      id: 1727072856489-source-1727147079381-target
      selected: false
      source: '1727072856489'
      sourceHandle: source
      target: '1727147079381'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: code
        targetType: code
      id: 1727147066015-source-1727147079381-target
      selected: false
      source: '1727147066015'
      sourceHandle: source
      target: '1727147079381'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - label: query
          max_length: 48
          options: []
          required: true
          type: text-input
          variable: query
      height: 90
      id: '1725590432628'
      position:
        x: 38.56889643898978
        y: 313.8700796623155
      positionAbsolute:
        x: 38.56889643898978
        y: 313.8700796623155
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(arg1: str) -> dict:\n    return {\n        \"result\": arg1\n\
          \    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 代码执行
        type: code
        variables:
        - value_selector:
          - '1725590432628'
          - query
          variable: arg1
      height: 54
      id: '1727072856489'
      position:
        x: 348.94291237145285
        y: 328.2116155103575
      positionAbsolute:
        x: 348.94291237145285
        y: 328.2116155103575
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(arg1: str) -> dict:\n    import time\n    time.sleep(10)\n\
          \    return {\n        \"result\": arg1,\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 代码执行 2
        type: code
        variables:
        - value_selector:
          - '1725590432628'
          - query
          variable: arg1
      height: 54
      id: '1727147018481'
      position:
        x: 348.94291237145285
        y: 481.764766868757
      positionAbsolute:
        x: 348.94291237145285
        y: 481.764766868757
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(arg1: str) -> dict:\n    import time\n    time.sleep(5)\n\
          \    return {\n        \"result\": arg1,\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 代码执行 3
        type: code
        variables:
        - value_selector:
          - '1725590432628'
          - query
          variable: arg1
      height: 54
      id: '1727147052531'
      position:
        x: 348.94291237145285
        y: 574.7647668687571
      positionAbsolute:
        x: 348.94291237145285
        y: 574.7647668687571
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(arg1: str, arg2: str) -> dict:\n    import time\n    time.sleep(5)\n\
          \    return {\n        \"result\": arg1 + arg2,\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 代码执行 4
        type: code
        variables:
        - value_selector:
          - '1727147018481'
          - result
          variable: arg1
        - value_selector:
          - '1727147052531'
          - result
          variable: arg2
      height: 54
      id: '1727147066015'
      position:
        x: 694.374015932463
        y: 516.8218544973042
      positionAbsolute:
        x: 694.374015932463
        y: 516.8218544973042
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        code: "\ndef main(arg1: str, arg2: str) -> dict:\n    return {\n        \"\
          result\": arg1 + arg2,\n    }\n"
        code_language: python3
        desc: ''
        outputs:
          result:
            children: null
            type: string
        selected: false
        title: 代码执行 5
        type: code
        variables:
        - value_selector:
          - '1727072856489'
          - result
          variable: arg1
        - value_selector:
          - '1727147066015'
          - result
          variable: arg2
      height: 54
      id: '1727147079381'
      position:
        x: 949.3561132228729
        y: 328.2116155103575
      positionAbsolute:
        x: 949.3561132228729
        y: 328.2116155103575
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 640.8622190234412
      y: 215.12657776416864
      zoom: 0.5109640591636222

```
