### ISSUE TITLE
Firecrawl started throwing the error: 'Failed to invoke tool: unhashable type: 'dict'.'

### ISSUE THREAD

**Issue by ugyuji** [langgenius/dify#8792]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

1. Create a new "Workflow"
2. Add Firecrawl's "Crawl" tool
3. Set a "Start URL" variable to "https://dify.ai/"
4. Run the workflow

### ❌ Actual Behavior

<img width="236" alt="35b2061a9ead09d037198315f3bd573a" src="https://github.com/user-attachments/assets/5fca200a-d8df-4fee-af25-53a66bb87a46">

**Comment by hjlarry** [comment]
I can't reproduce.  Can you upload your workflow DSL?

**Comment by Halflifefa** [comment]
The same question, the process used is the official template <Interview Preparation (Conditional Parallel)>
Key obtained from https://www.firecrawl.dev/app/api-keys

**Comment by hjlarry** [comment]
now I reproduce it in the cloud version,  
but in my local newest branch, it works, maybe some PR already fix this

**Comment by ugyuji** [comment]
Here's the DSL content:

```yaml
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: workflow
  name: Test Workflow
  use_icon_as_answer_icon: false
kind: app
version: 0.1.2
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: tool
      id: 1712630129285-source-1727334022276-target
      source: '1712630129285'
      sourceHandle: source
      target: '1727334022276'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: tool
        targetType: end
      id: 1727334022276-source-1713020453724-target
      source: '1727334022276'
      sourceHandle: source
      target: '1713020453724'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables:
        - label: url
          max_length: 256
          options: []
          required: true
          type: text-input
          variable: url
      height: 90
      id: '1712630129285'
      position:
        x: 30
        y: 427
      positionAbsolute:
        x: 30
        y: 427
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        outputs:
        - value_selector:
          - '1727334022276'
          - text
          variable: output
        selected: false
        title: End
        type: end
      height: 90
      id: '1713020453724'
      position:
        x: 638
        y: 427
      positionAbsolute:
        x: 638
        y: 427
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        provider_id: firecrawl
        provider_name: firecrawl
        provider_type: builtin
        selected: false
        title: Crawl
        tool_configurations:
          allowBackwardLinks: 0
          allowExternalLinks: 0
          excludePaths: null
          excludeTags: null
          formats: null
          headers: null
          ignoreSitemap: 1
          includePaths: null
          includeTags: null
          limit: 5
          maxDepth: 2
          onlyMainContent: 0
          waitFor: null
          wait_for_results: 1
          webhook: null
        tool_label: Crawl
        tool_name: crawl
        tool_parameters:
          url:
            type: mixed
            value: '{{#1712630129285.url#}}'
        type: tool
      height: 454
      id: '1727334022276'
      position:
        x: 334
        y: 427
      positionAbsolute:
        x: 334
        y: 427
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 307.80000000000007
      y: -8.799999999999955
      zoom: 0.7
```

The same error can be seen in both local and cloud environments.
