### ISSUE TITLE
The latest version of dify cannot properly render the formula of the markdown file.

### ISSUE THREAD

**Issue by majestichou** [langgenius/dify#9206]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Create app from importing DSL file and the content of DSL file is as follows:
```
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: test-md-formula
  use_icon_as_answer_icon: false
kind: app
version: 0.1.2
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        sourceType: start
        targetType: llm
      id: 1728613407510-llm
      source: '1728613407510'
      sourceHandle: source
      target: llm
      targetHandle: target
      type: custom
    - data:
        sourceType: llm
        targetType: answer
      id: llm-answer
      source: llm
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables: []
      height: 54
      id: '1728613407510'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        model:
          completion_params:
            max_tokens: 2000
            temperature: 0.1
            top_p: 0.3
          mode: chat
          name: qwen-turbo
          provider: tongyi
        prompt_template:
        - id: ba35722b-0880-4899-b4e2-c624e21370d9
          role: system
          text: 你的职责是根据用户的提示词完成用户指定的任务，或者回答用户的问题。
        - id: df10b603-a554-4829-8df6-fa135fe8c468
          role: user
          text: '{{#sys.query#}}'
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 98
      id: llm
      position:
        x: 380
        y: 282
      positionAbsolute:
        x: 380
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#llm.text#}}'
        desc: ''
        selected: false
        title: 直接回复
        type: answer
        variables: []
      height: 107
      id: answer
      position:
        x: 680
        y: 282
      positionAbsolute:
        x: 680
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: -150
      y: 113
      zoom: 1
```
2. Enter the following information in the chat text box of the app:

```
What's the following formula?
$$1.5 , \text{m} \leq h_{UE} \leq 13.5 , \text{m}$$ 和 $$15 , \text{m} \leq h_{BS} \leq 35 , \text{m}$$
```
3. The answer of the app is as follows:
```
The formulas you've provided define the range of acceptable heights for two entities, likely referring to an "UE" (User Equipment) and a "BS" (Base Station), in meters.

Specifically:

For the UE (User Equipment): The height $$h_{UE}$$ must be within the range from 1.5 meters to 13.5 meters.
For the BS (Base Station): The height $$h_{BS}$$ must be within the range from 15 meters to 35 meters.
These constraints could be relevant in scenarios such as wireless communication systems where the height of devices can affect signal strength and coverage.
```
![image](https://github.com/user-attachments/assets/1bf8f335-1143-41ae-bb86-2bf73088b33e)

In addition, I tried the 0.7.0 version of dify, deployed with docker.

![image](https://github.com/user-attachments/assets/ccba6603-0fff-48b6-a424-9ad45e385557)

As can be seen from the test above, the latest version of dify cannot properly render the formula of the markdown file.

### ✔️ Expected Behavior

The latest version of dify can properly render the formula of the markdown file.

### ❌ Actual Behavior

The latest version of dify cannot properly render the formula of the markdown file.
