### ISSUE TITLE
Bedrock ValidationException: Conversation Alternation Error

### ISSUE THREAD

**Issue by torinkwok** [langgenius/dify#9294]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1-fix1

### Cloud or Self Hosted

Cloud

## Problem Description

After the first successful question-answer round in each conversation, subsequent questions consistently fail due to a Bedrock `ValidationException` error:

> ValidationException: A conversation must alternate between user and assistant roles. Make sure the conversation alternates between user and assistant roles and try again.

![Screenshot of ValidationException error](https://github.com/user-attachments/assets/3e8f2e07-7fd9-4a67-8982-6079e8bc5ee1)

## Reproduction Steps

1. Start a new conversation
2. Ask the first question (✅ succeeds)
3. Ask a second question (❌ fails)

## Configuration

The app uses a near-vanilla configuration:

`[START]` => `[LLM (Amazon Bedrock Claude 3.5 Sonnet)]` => `[ANSWER]`

![Screenshot of app configuration](https://github.com/user-attachments/assets/a3ede8fe-91ab-43d7-8acc-3a28ebcde655)

## Additional Information

The DSL YAML of the Dify Cloud app is available here:

```yml
app:
  description: Claude Sonnet 3.5
  icon: mechanical_leg
  icon_background: '#EFF1F5'
  mode: advanced-chat
  name: Assistant
  use_icon_as_answer_icon: false
kind: app
version: 0.1.2
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: llm
      id: 1727761029738-source-1728790041675-target
      source: '1727761029738'
      sourceHandle: source
      target: '1728790041675'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: llm
        targetType: answer
      id: 1728790041675-source-answer-target
      source: '1728790041675'
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables: []
      height: 52
      id: '1727761029738'
      position:
        x: 30
        y: 252.5
      positionAbsolute:
        x: 30
        y: 252.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        answer: '{{#1728790041675.text#}}'
        desc: ''
        selected: false
        title: Answer
        type: answer
        variables: []
      height: 105
      id: answer
      position:
        x: 636
        y: 252.5
      positionAbsolute:
        x: 636
        y: 252.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        memory:
          query_prompt_template: '{{#sys.query#}}'
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: true
            size: 20
        model:
          completion_params:
            temperature: 0.7
          mode: chat
          name: anthropic.claude-3-5-sonnet-20240620-v1:0
          provider: bedrock
        prompt_template:
        - edition_type: basic
          id: f3e0d271-3342-46ec-9fd0-7a9ebce054eb
          role: system
          text: ''
        selected: true
        title: LLM
        type: llm
        variables: []
        vision:
          configs:
            detail: high
          enabled: true
      height: 96
      id: '1728790041675'
      position:
        x: 333
        y: 252.5
      positionAbsolute:
        x: 333
        y: 252.5
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 243
    viewport:
      x: -6.8880313885315445
      y: 80.43180777220238
      zoom: 0.8423025465083342
```

Until recently, this app config worked perfectly. Then this error started occurring.

### ✔️ Expected Behavior

The conversation should proceed normally, with the LLM responding to each user query in turn. The `PROCESS DATA` section within the `Logs & Ann. → Conversation Log → LLM` should show an alternating pattern of user and assistant roles.

### ❌ Actual Behavior

The second user query is duplicated in the conversation log, disrupting the expected role alternation. The `PROCESS DATA` section shows:

```json
{
  "model_mode": "chat",
  "prompts": [
    {
      "role": "user",
      "text": "Etherium?",
      "files": []
    },
    {
      "role": "assistant",
      "text": "Ethereum is a decentralized, open-source blockchain platform...",
      "files": []
    },
    {
      "role": "user",
      "text": "Is it a risk-on asset?",
      "files": []
    },
    {
      "role": "user", // 💥 Duplicated
      "text": "Is it a risk-on asset?",
      "files": []
    }
  ],
  "model_provider": "bedrock",
  "model_name": "anthropic.claude-3-5-sonnet-20240620-v1:0"
}
```

The same second question is fired twice behind the scenes, causing the Bedrock `ValidationException`. This disrupts the expected alternation between user and assistant roles.
