### ISSUE TITLE
I asked multiple questions to a file upload workflow application and it reported an error：answer-placeholder-1729784995710 is not a valid uuid

### ISSUE THREAD

**Issue by majestichou** [langgenius/dify#9815]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Cloud, Self Hosted (Docker)

### Steps to reproduce

1. Using the following DSL to create a file upload workflow application
```
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: File Reader
  use_icon_as_answer_icon: false
kind: app
version: 0.1.2
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - document
      allowed_file_upload_methods:
      - local_file
      enabled: true
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 1
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: document-extractor
      id: 1729783247377-source-1729783260965-target
      source: '1729783247377'
      sourceHandle: source
      target: '1729783260965'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: document-extractor
        targetType: iteration
      id: 1729783260965-source-1729783291108-target
      source: '1729783260965'
      sourceHandle: source
      target: '1729783291108'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: true
        iteration_id: '1729783291108'
        sourceType: iteration-start
        targetType: llm
      id: 1729783291108start-source-1729783331892-target
      source: 1729783291108start
      sourceHandle: source
      target: '1729783331892'
      targetHandle: target
      type: custom
      zIndex: 1002
    - data:
        isInIteration: true
        iteration_id: '1729783291108'
        sourceType: llm
        targetType: answer
      id: 1729783331892-source-1729783335740-target
      source: '1729783331892'
      sourceHandle: source
      target: '1729783335740'
      targetHandle: target
      type: custom
      zIndex: 1002
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables: []
      height: 53
      id: '1729783247377'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        is_array_file: true
        selected: false
        title: Doc Extractor
        type: document-extractor
        variable_selector:
        - sys
        - files
      height: 93
      id: '1729783260965'
      position:
        x: 380
        y: 282
      positionAbsolute:
        x: 380
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        height: 185
        iterator_selector:
        - '1729783260965'
        - text
        output_selector:
        - '1729783331892'
        - text
        output_type: array[string]
        selected: false
        start_node_id: 1729783291108start
        title: Iteration
        type: iteration
        width: 692
      height: 185
      id: '1729783291108'
      position:
        x: 684
        y: 282
      positionAbsolute:
        x: 684
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 692
      zIndex: 1
    - data:
        desc: ''
        isInIteration: true
        selected: false
        title: ''
        type: iteration-start
      draggable: false
      height: 48
      id: 1729783291108start
      parentId: '1729783291108'
      position:
        x: 24
        y: 68
      positionAbsolute:
        x: 708
        y: 350
      selectable: false
      sourcePosition: right
      targetPosition: left
      type: custom-iteration-start
      width: 44
      zIndex: 1002
    - data:
        context:
          enabled: false
          variable_selector: []
        desc: ''
        isInIteration: true
        iteration_id: '1729783291108'
        memory:
          query_prompt_template: 'The document is as follows：

            {{#1729783291108.item#}}

            The user''s question is as follow:

            {{#sys.query#}}'
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: false
            size: 50
        model:
          completion_params:
            temperature: 0.7
            top_p: 0.8
          mode: chat
          name: qwen-max-latest
          provider: tongyi
        prompt_template:
        - id: 7ded19d8-74e2-421a-b2ba-b20f81292845
          role: system
          text: You are a document reader, and your job is to read the document and
            answer the user's questions.
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 97
      id: '1729783331892'
      parentId: '1729783291108'
      position:
        x: 128
        y: 68
      positionAbsolute:
        x: 812
        y: 350
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    - data:
        answer: '{{#1729783331892.text#}}'
        desc: ''
        isInIteration: true
        iteration_id: '1729783291108'
        selected: false
        title: Answer
        type: answer
        variables: []
      height: 102
      id: '1729783335740'
      parentId: '1729783291108'
      position:
        x: 432
        y: 68
      positionAbsolute:
        x: 1116
        y: 350
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
      zIndex: 1002
    viewport:
      x: -90
      y: 39
      zoom: 1
```
2. I uploaded a PDF file, the file content is as follows:
<img width="874" alt="image" src="https://github.com/user-attachments/assets/a66d9f2a-dfae-46d1-9d36-79858ca5516a">
And I asked the first question, and everything was fine. Although there are slight problems with formula rendering, this is not the key (I mentioned this at the issue: [issue](https://github.com/langgenius/dify/issues/9206), and it did not be solved right now). 
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/088b89c8-c358-4dd9-b83c-939a65af0b8d">

4. I asked the question a second time, but the workflow did not respond or report an error.
<img width="675" alt="image" src="https://github.com/user-attachments/assets/3cb90da1-a7ca-4c5e-9c72-fd66c95aafc6">

5. I asked the question for the 3rd and 4th time, but errors were reported when running.
<img width="675" alt="image" src="https://github.com/user-attachments/assets/c32eb79f-67e6-437a-a93f-35c74c42bc58">

### ✔️ Expected Behavior

no error

### ❌ Actual Behavior

I asked multiple questions to a file upload workflow application that has no memory and reported an error：answer-placeholder-1729784995710 is not a valid uuid
