### ISSUE TITLE
"BOOL" type is not supported

### ISSUE THREAD

**Issue by Jalen-Zhong** [langgenius/dify#9856]
### Self Checks

- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### 1. Is this request related to a challenge you're experiencing? Tell me about your story.

Thanks for you nice works! 
I got a issuse about input type:
I define myself's tools with Schema like:
```
        content:
          application/json:
            schema:
              type: object
              properties:
                fs:
                  type: integer
                  description: Sample rate of the audio file
                wav:
                  type: array
                  items:
                    type: number
                  description: Audio samples as a list of numbers
                language:
                  type: string
                  description: Language type of the speech
                show_emo:
                  type: boolean
                  description: Whether to display emotion information
                show_event:
                  type: boolean
                  description: Whether to display event information
```
When I use this self-define tool in my workflow. I found input type of the dify given is not support bool type.

### 2. Additional context or comments

How can I define bool type as input?
or
Could you consider this issuse?

### 3. Can you help us with this feature?

- [ ] I am interested in contributing to this feature.
