### ISSUE TITLE
Run failed: Failed to extract text fromPPTX: <urlopen error [Errno -3] Temporary failure in name resolution>

### ISSUE THREAD

**Issue by majestichou** [langgenius/dify#9995]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

1. `cp .env.example .env`, then change the parameters in .env
`ETL_TYPE=Unstructured`
`UNSTRUCTURED_API_URL=http://unstructured:8000/general/v0/general`
2. Run the following command to start the dify service:
`docker compose --profile unstructured up -d`
3. Create an application based on the following YAML file:
```
app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: test-pptx
  use_icon_as_answer_icon: false
kind: app
version: 0.1.2
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInIteration: false
        sourceType: start
        targetType: document-extractor
      id: 1730188656653-source-1730188681288-target
      source: '1730188656653'
      sourceHandle: source
      target: '1730188681288'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: document-extractor
        targetType: answer
      id: 1730188681288-source-answer-target
      source: '1730188681288'
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: 开始
        type: start
        variables:
        - allowed_file_extensions: []
          allowed_file_types:
          - document
          allowed_file_upload_methods:
          - local_file
          label: pptx
          max_length: 48
          options: []
          required: false
          type: file
          variable: pptx
      height: 90
      id: '1730188656653'
      position:
        x: 80
        y: 282
      positionAbsolute:
        x: 80
        y: 282
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#llm.text#}}'
        desc: ''
        selected: false
        title: 直接回复
        type: answer
        variables: []
      height: 103
      id: answer
      position:
        x: 680
        y: 282
      positionAbsolute:
        x: 680
        y: 282
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        desc: ''
        is_array_file: false
        selected: false
        title: 文档提取器
        type: document-extractor
        variable_selector:
        - '1730188656653'
        - pptx
      height: 94
      id: '1730188681288'
      position:
        x: 384
        y: 282
      positionAbsolute:
        x: 384
        y: 282
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 226
      y: 119.5
      zoom: 1
```
4. Upload a pptx file named "test.pptx" and ask "What is the content of the document?"
the content of this pptx file is as follows:
![image](https://github.com/user-attachments/assets/a7d3ac7a-ac5b-411e-9e04-0a0429b32d17)

5. The application fails to run, and the following error message is displayed:
`Run failed: Failed to extract text from PPTX: <urlopen error [Errno -3] Temporary failure in name resolution>`

**One more word, I used the 0.10.1 dify docker image, repeated the above process, and everything was fine. However, version 0.10.2 fails to run.**

### ✔️ Expected Behavior

Correctly parse the .docx file.

### ❌ Actual Behavior

Run failed: Failed to extract text fromPPTX: <urlopen error [Errno -3] Temporary failure in name resolution>
